###############################################################
#  Generated by:      Cadence Innovus 21.35-s114_1
#  OS:                Linux x86_64(Host ID pc231.ee.hacettepe.edu.tr)
#  Generated on:      Thu Dec 18 16:23:10 2025
#  Design:            custom_riscv_core
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Pin offsets inferred from set_clock_latency assertions:
set_ccopt_property insertion_delay -pin {instruction_reg[14]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[15]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[16]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[17]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[18]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[19]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[20]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[21]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[22]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[23]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[24]/CLK} 0.300
set_ccopt_property insertion_delay -pin {instruction_reg[6]/CLK} 0.300

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   sys_clk (period 10.000ns) in timing_config FUNC_MODE([../constraints/basic_timing.sdc])
create_ccopt_clock_tree -name sys_clk -source clk -no_skew_group
# Clock period setting for source pin of sys_clk
set_ccopt_property clock_period -pin clk 10

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:sys_clk in timing_config:FUNC_MODE (sdc ../constraints/basic_timing.sdc)
create_ccopt_skew_group -name sys_clk/FUNC_MODE -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group sys_clk/FUNC_MODE true
set_ccopt_property extracted_from_clock_name -skew_group sys_clk/FUNC_MODE sys_clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group sys_clk/FUNC_MODE FUNC_MODE
set_ccopt_property extracted_from_delay_corners -skew_group sys_clk/FUNC_MODE SINGLE_CORNER


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

