/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module alu(operand_a, operand_b, alu_op, result, zero);
  wire [31:0] _00_;
  wire [31:0] _01_;
  wire _02_;
  wire _03_;
  wire [31:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [31:0] _15_;
  wire [31:0] _16_;
  wire [31:0] _17_;
  wire [31:0] _18_;
  wire [31:0] _19_;
  wire [31:0] _20_;
  wire [31:0] _21_;
  input [3:0] alu_op;
  wire [3:0] alu_op;
  input [31:0] operand_a;
  wire [31:0] operand_a;
  input [31:0] operand_b;
  wire [31:0] operand_b;
  output [31:0] result;
  wire [31:0] result;
  output zero;
  wire zero;
  assign _00_ = operand_a + operand_b;
  assign _01_ = operand_a & operand_b;
  assign zero = ! result;
  assign _02_ = $signed(operand_a) < $signed(operand_b);
  assign _03_ = operand_a < operand_b;
  assign _04_ = operand_a | operand_b;
  function [31:0] _28_;
    input [31:0] a;
    input [319:0] b;
    input [9:0] s;
    casez (s) // synopsys parallel_case
      10'b?????????1:
        _28_ = b[31:0];
      10'b????????1?:
        _28_ = b[63:32];
      10'b???????1??:
        _28_ = b[95:64];
      10'b??????1???:
        _28_ = b[127:96];
      10'b?????1????:
        _28_ = b[159:128];
      10'b????1?????:
        _28_ = b[191:160];
      10'b???1??????:
        _28_ = b[223:192];
      10'b??1???????:
        _28_ = b[255:224];
      10'b?1????????:
        _28_ = b[287:256];
      10'b1?????????:
        _28_ = b[319:288];
      default:
        _28_ = a;
    endcase
  endfunction
  assign result = _28_(32'hxxxxxxxx, { _00_, _18_, _01_, _04_, _21_, _15_, _16_, _17_, _19_, _20_ }, { _14_, _13_, _12_, _11_, _10_, _09_, _08_, _07_, _06_, _05_ });
  assign _05_ = alu_op == 4'h9;
  assign _06_ = alu_op == 4'h8;
  assign _07_ = alu_op == 4'h7;
  assign _08_ = alu_op == 4'h6;
  assign _09_ = alu_op == 4'h5;
  assign _10_ = alu_op == 4'h4;
  assign _11_ = alu_op == 4'h3;
  assign _12_ = alu_op == 4'h2;
  assign _13_ = alu_op == 4'h1;
  assign _14_ = ! alu_op;
  assign _15_ = operand_a << operand_b[4:0];
  assign _16_ = operand_a >> operand_b[4:0];
  assign _17_ = $signed(operand_a) >>> operand_b[4:0];
  assign _18_ = operand_a - operand_b;
  assign _19_ = _02_ ? 32'd1 : 32'd0;
  assign _20_ = _03_ ? 32'd1 : 32'd0;
  assign _21_ = operand_a ^ operand_b;
endmodule

module csr_unit(clk, rst_n, csr_addr, csr_wdata, csr_op, csr_rdata, csr_valid, trap_entry, trap_return, trap_pc, trap_cause, trap_val, trap_vector, epc_out, interrupts_i, interrupt_pending, interrupt_enabled, interrupt_cause, instr_retired);
  wire [31:0] _000_;
  wire [63:0] _001_;
  wire [31:0] _002_;
  wire [63:0] _003_;
  wire [31:0] _004_;
  wire [31:0] _005_;
  wire [31:0] _006_;
  wire [31:0] _007_;
  wire [31:0] _008_;
  wire [31:0] _009_;
  wire [31:0] _010_;
  wire [31:0] _011_;
  wire [31:0] _012_;
  wire [31:0] _013_;
  wire [31:0] _014_;
  wire [31:0] _015_;
  wire [31:0] _016_;
  wire [31:0] _017_;
  wire [31:0] _018_;
  wire [31:0] _019_;
  wire [31:0] _020_;
  wire [31:0] _021_;
  wire [31:0] _022_;
  wire [31:0] _023_;
  wire [31:0] _024_;
  wire [31:0] _025_;
  wire [31:0] _026_;
  wire [31:0] _027_;
  wire [31:0] _028_;
  wire [31:0] _029_;
  wire [31:0] _030_;
  wire [31:0] _031_;
  wire [31:0] _032_;
  wire [31:0] _033_;
  wire [31:0] _034_;
  wire [31:0] _035_;
  wire [31:0] _036_;
  wire [31:0] _037_;
  wire [32:0] _038_;
  wire [63:0] _039_;
  wire [63:0] _040_;
  wire [31:0] _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire [31:0] _064_;
  wire [31:0] _065_;
  wire [31:0] _066_;
  wire [31:0] _067_;
  wire _068_;
  wire [31:0] _069_;
  wire [31:0] _070_;
  wire [31:0] _071_;
  wire [31:0] _072_;
  wire _073_;
  wire [31:0] _074_;
  wire [31:0] _075_;
  wire [31:0] _076_;
  wire _077_;
  wire [31:0] _078_;
  wire [31:0] _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire [1:0] _084_;
  wire [1:0] _085_;
  wire [1:0] _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [31:0] _090_;
  wire _091_;
  wire [31:0] _092_;
  wire [31:0] _093_;
  wire [31:0] _094_;
  wire _095_;
  wire [31:0] _096_;
  wire [31:0] _097_;
  wire [31:0] _098_;
  wire _099_;
  wire [31:0] _100_;
  wire [31:0] _101_;
  wire [31:0] _102_;
  wire _103_;
  wire [31:0] _104_;
  wire [31:0] _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  input clk;
  wire clk;
  input [11:0] csr_addr;
  wire [11:0] csr_addr;
  input [2:0] csr_op;
  wire [2:0] csr_op;
  output [31:0] csr_rdata;
  wire [31:0] csr_rdata;
  output csr_valid;
  wire csr_valid;
  input [31:0] csr_wdata;
  wire [31:0] csr_wdata;
  wire [31:0] csr_wdata_final;
  wire csr_write;
  output [31:0] epc_out;
  wire [31:0] epc_out;
  wire [31:0] i;
  input instr_retired;
  wire instr_retired;
  output [31:0] interrupt_cause;
  wire [31:0] interrupt_cause;
  output interrupt_enabled;
  wire interrupt_enabled;
  output interrupt_pending;
  wire interrupt_pending;
  input [31:0] interrupts_i;
  wire [31:0] interrupts_i;
  reg [31:0] mcause;
  reg [63:0] mcycle;
  reg [31:0] mepc;
  reg [31:0] mie;
  wire mie_bit;
  reg [63:0] minstret;
  reg [31:0] mip;
  wire mpie_bit;
  reg [31:0] mscratch;
  wire [31:0] mstatus;
  reg [31:0] mtval;
  reg [31:0] mtvec;
  wire [31:0] mtvec_base;
  wire [1:0] mtvec_mode;
  wire [31:0] pending_and_enabled;
  input rst_n;
  wire rst_n;
  input [31:0] trap_cause;
  wire [31:0] trap_cause;
  input trap_entry;
  wire trap_entry;
  input [31:0] trap_pc;
  wire [31:0] trap_pc;
  input trap_return;
  wire trap_return;
  input [31:0] trap_val;
  wire [31:0] trap_val;
  output [31:0] trap_vector;
  wire [31:0] trap_vector;
  wire valid;
  assign _038_ = { mtvec[31:2], 2'h0 } + { trap_cause[30:0], 2'h0 };
  assign _039_ = mcycle + 64'h0000000000000001;
  assign _040_ = minstret + 64'h0000000000000001;
  assign pending_and_enabled = mip & mie;
  assign _041_ = csr_rdata & _064_;
  reg [3:0] _128_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) _128_ <= 4'h0;
    else if (_048_) _128_ <= { _004_[12:11], _004_[7], _004_[3] };
  assign { mstatus[12:11], mstatus[7], mstatus[3] } = _128_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mie <= 32'd0;
    else if (_049_) mie <= csr_wdata_final;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mtvec <= 32'd0;
    else if (_050_) mtvec <= csr_wdata_final;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mscratch <= 32'd0;
    else if (_051_) mscratch <= csr_wdata_final;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mepc <= 32'd0;
    else if (_052_) mepc <= _002_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mcause <= 32'd0;
    else if (_053_) mcause <= _000_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mtval <= 32'd0;
    else if (_054_) mtval <= _005_;
  assign _042_ = | { _063_, trap_return, trap_entry };
  assign _043_ = { _080_, _063_, trap_return, trap_entry } != 4'h4;
  assign _044_ = { _103_, _063_, trap_return, trap_entry } != 4'h4;
  assign _045_ = { trap_return, trap_entry } != 2'h2;
  assign _046_ = { _099_, _063_, trap_return, trap_entry } != 4'h4;
  assign _047_ = { _095_, _063_, trap_return, trap_entry } != 4'h4;
  assign _060_ = ~ trap_return;
  assign _061_ = ~ trap_entry;
  assign _048_ = & { _043_, _042_ };
  assign _049_ = & { _061_, _060_, _108_, _063_ };
  assign _050_ = & { _061_, _060_, _107_, _063_ };
  assign _051_ = & { _061_, _060_, _106_, _063_ };
  assign _052_ = & { _045_, _044_, _042_ };
  assign _053_ = & { _046_, _045_, _042_ };
  assign _054_ = & { _047_, _045_, _042_ };
  assign _055_ = | { _121_, _120_, _119_, _118_, _117_, _116_, _115_, _114_, _113_, _112_, _108_, _107_, _106_, _103_, _099_, _095_, _091_, _080_, _077_, _073_, _068_ };
  assign _056_ = | { _112_, _068_ };
  assign _057_ = | { _113_, _073_ };
  assign _058_ = | { _114_, _091_ };
  assign _059_ = | { _115_, _077_ };
  assign _062_ = ! mtvec[1:0];
  assign interrupt_pending = _122_ && mstatus[3];
  assign _063_ = csr_write && valid;
  assign csr_write = | csr_op;
  assign _064_ = ~ csr_wdata;
  assign _065_ = csr_rdata | csr_wdata;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mcycle <= 64'h0000000000000000;
    else mcycle <= _001_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) minstret <= 64'h0000000000000000;
    else minstret <= _003_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mip <= 32'd0;
    else mip <= interrupts_i;
  assign _066_ = instr_retired ? _040_[63:32] : minstret[63:32];
  assign _067_ = _068_ ? csr_wdata_final : _066_;
  assign _069_ = _063_ ? _067_ : _066_;
  assign _070_ = trap_return ? _066_ : _069_;
  assign _003_[63:32] = trap_entry ? _066_ : _070_;
  assign _071_ = instr_retired ? _040_[31:0] : minstret[31:0];
  assign _072_ = _073_ ? csr_wdata_final : _071_;
  assign _074_ = _063_ ? _072_ : _071_;
  assign _075_ = trap_return ? _071_ : _074_;
  assign _003_[31:0] = trap_entry ? _071_ : _075_;
  assign _076_ = _077_ ? csr_wdata_final : _039_[31:0];
  assign _078_ = _063_ ? _076_ : _039_[31:0];
  assign _079_ = trap_return ? _039_[31:0] : _078_;
  assign _001_[31:0] = trap_entry ? _039_[31:0] : _079_;
  assign _081_ = _080_ ? csr_wdata_final[7] : 1'hx;
  assign _082_ = _063_ ? _081_ : 1'hx;
  assign _083_ = trap_return ? 1'h1 : _082_;
  assign _004_[7] = trap_entry ? mstatus[3] : _083_;
  assign _084_ = _080_ ? csr_wdata_final[12:11] : 2'hx;
  assign _085_ = _063_ ? _084_ : 2'hx;
  assign _086_ = trap_return ? 2'h3 : _085_;
  assign _004_[12:11] = trap_entry ? 2'h3 : _086_;
  assign _087_ = _080_ ? csr_wdata_final[3] : 1'hx;
  assign _088_ = _063_ ? _087_ : 1'hx;
  assign _089_ = trap_return ? mstatus[7] : _088_;
  assign _004_[3] = trap_entry ? 1'h0 : _089_;
  assign _090_ = _091_ ? csr_wdata_final : _039_[63:32];
  assign _092_ = _063_ ? _090_ : _039_[63:32];
  assign _093_ = trap_return ? _039_[63:32] : _092_;
  assign _001_[63:32] = trap_entry ? _039_[63:32] : _093_;
  assign _094_ = _095_ ? csr_wdata_final : 32'hxxxxxxxx;
  assign _096_ = _063_ ? _094_ : 32'hxxxxxxxx;
  assign _097_ = trap_return ? 32'hxxxxxxxx : _096_;
  assign _005_ = trap_entry ? trap_val : _097_;
  assign _098_ = _099_ ? csr_wdata_final : 32'hxxxxxxxx;
  assign _100_ = _063_ ? _098_ : 32'hxxxxxxxx;
  assign _101_ = trap_return ? 32'hxxxxxxxx : _100_;
  assign _000_ = trap_entry ? trap_cause : _101_;
  assign _102_ = _103_ ? { csr_wdata_final[31:1], 1'h0 } : 32'hxxxxxxxx;
  assign _104_ = _063_ ? _102_ : 32'hxxxxxxxx;
  assign _105_ = trap_return ? 32'hxxxxxxxx : _104_;
  assign _002_ = trap_entry ? trap_pc : _105_;
  function [31:0] _206_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _206_ = b[31:0];
      3'b?1?:
        _206_ = b[63:32];
      3'b1??:
        _206_ = b[95:64];
      default:
        _206_ = a;
    endcase
  endfunction
  assign csr_wdata_final = _206_(32'd0, { csr_wdata, _065_, _041_ }, { _111_, _110_, _109_ });
  assign _109_ = csr_op[1:0] == 2'h3;
  assign _110_ = csr_op[1:0] == 2'h2;
  assign _111_ = csr_op[1:0] == 2'h1;
  function [31:0] _210_;
    input [31:0] a;
    input [447:0] b;
    input [13:0] s;
    casez (s) // synopsys parallel_case
      14'b?????????????1:
        _210_ = b[31:0];
      14'b????????????1?:
        _210_ = b[63:32];
      14'b???????????1??:
        _210_ = b[95:64];
      14'b??????????1???:
        _210_ = b[127:96];
      14'b?????????1????:
        _210_ = b[159:128];
      14'b????????1?????:
        _210_ = b[191:160];
      14'b???????1??????:
        _210_ = b[223:192];
      14'b??????1???????:
        _210_ = b[255:224];
      14'b?????1????????:
        _210_ = b[287:256];
      14'b????1?????????:
        _210_ = b[319:288];
      14'b???1??????????:
        _210_ = b[351:320];
      14'b??1???????????:
        _210_ = b[383:352];
      14'b?1????????????:
        _210_ = b[415:384];
      14'b1?????????????:
        _210_ = b[447:416];
      default:
        _210_ = a;
    endcase
  endfunction
  assign csr_rdata = _210_(32'd0, { 51'h0000000080000, mstatus[12:11], 3'h0, mstatus[7], 3'h0, mstatus[3], 35'h040000100, mie, mtvec, mscratch, mepc, mcause, mtval, mip, mcycle[31:0], mcycle[63:32], minstret[31:0], minstret[63:32] }, { _118_, _080_, _117_, _108_, _107_, _106_, _103_, _099_, _095_, _116_, _059_, _058_, _057_, _056_ });
  assign valid = _055_ ? 1'h1 : 1'h0;
  assign _112_ = csr_addr == 12'hc82;
  assign _113_ = csr_addr == 12'hc02;
  assign _114_ = csr_addr == 12'hc80;
  assign _115_ = csr_addr == 12'hc00;
  assign _068_ = csr_addr == 12'hb82;
  assign _073_ = csr_addr == 12'hb02;
  assign _091_ = csr_addr == 12'hb80;
  assign _077_ = csr_addr == 12'hb00;
  assign _116_ = csr_addr == 12'h344;
  assign _095_ = csr_addr == 12'h343;
  assign _099_ = csr_addr == 12'h342;
  assign _103_ = csr_addr == 12'h341;
  assign _106_ = csr_addr == 12'h340;
  assign _107_ = csr_addr == 12'h305;
  assign _108_ = csr_addr == 12'h304;
  assign _117_ = csr_addr == 12'h301;
  assign _080_ = csr_addr == 12'h300;
  assign _119_ = csr_addr == 12'hf14;
  assign _118_ = csr_addr == 12'hf13;
  assign _120_ = csr_addr == 12'hf12;
  assign _121_ = csr_addr == 12'hf11;
  assign _028_ = trap_cause[31] ? _038_[31:0] : { mtvec[31:2], 2'h0 };
  assign trap_vector = _062_ ? { mtvec[31:2], 2'h0 } : _028_;
  assign interrupt_cause = pending_and_enabled[0] ? 32'd2147483648 : _030_;
  assign _030_ = pending_and_enabled[1] ? 32'd2147483649 : _029_;
  assign _029_ = pending_and_enabled[2] ? 32'd2147483650 : _026_;
  assign _026_ = pending_and_enabled[3] ? 32'd2147483651 : _025_;
  assign _025_ = pending_and_enabled[4] ? 32'd2147483652 : _024_;
  assign _024_ = pending_and_enabled[5] ? 32'd2147483653 : _023_;
  assign _023_ = pending_and_enabled[6] ? 32'd2147483654 : _022_;
  assign _022_ = pending_and_enabled[7] ? 32'd2147483655 : _021_;
  assign _021_ = pending_and_enabled[8] ? 32'd2147483656 : _020_;
  assign _020_ = pending_and_enabled[9] ? 32'd2147483657 : _019_;
  assign _019_ = pending_and_enabled[10] ? 32'd2147483658 : _018_;
  assign _018_ = pending_and_enabled[11] ? 32'd2147483659 : _017_;
  assign _017_ = pending_and_enabled[12] ? 32'd2147483660 : _015_;
  assign _015_ = pending_and_enabled[13] ? 32'd2147483661 : _014_;
  assign _014_ = pending_and_enabled[14] ? 32'd2147483662 : _013_;
  assign _013_ = pending_and_enabled[15] ? 32'd2147483663 : _012_;
  assign _012_ = pending_and_enabled[16] ? 32'd2147483664 : _011_;
  assign _011_ = pending_and_enabled[17] ? 32'd2147483665 : _010_;
  assign _010_ = pending_and_enabled[18] ? 32'd2147483666 : _009_;
  assign _009_ = pending_and_enabled[19] ? 32'd2147483667 : _008_;
  assign _008_ = pending_and_enabled[20] ? 32'd2147483668 : _007_;
  assign _007_ = pending_and_enabled[21] ? 32'd2147483669 : _006_;
  assign _006_ = pending_and_enabled[22] ? 32'd2147483670 : _037_;
  assign _037_ = pending_and_enabled[23] ? 32'd2147483671 : _036_;
  assign _036_ = pending_and_enabled[24] ? 32'd2147483672 : _035_;
  assign _035_ = pending_and_enabled[25] ? 32'd2147483673 : _034_;
  assign _034_ = pending_and_enabled[26] ? 32'd2147483674 : _033_;
  assign _033_ = pending_and_enabled[27] ? 32'd2147483675 : _032_;
  assign _032_ = pending_and_enabled[28] ? 32'd2147483676 : _031_;
  assign _031_ = pending_and_enabled[29] ? 32'd2147483677 : _027_;
  assign _027_ = pending_and_enabled[30] ? 32'd2147483678 : _016_;
  assign _016_ = pending_and_enabled[31] ? 32'd2147483679 : 32'd0;
  assign _122_ = | pending_and_enabled;
  assign csr_valid = valid;
  assign epc_out = mepc;
  assign i = 32'd4294967295;
  assign interrupt_enabled = mstatus[3];
  assign mie_bit = mstatus[3];
  assign mpie_bit = mstatus[7];
  assign { mstatus[31:13], mstatus[10:8], mstatus[6:4], mstatus[2:0] } = 28'h0000000;
  assign mtvec_base = { mtvec[31:2], 2'h0 };
  assign mtvec_mode = mtvec[1:0];
endmodule

module custom_riscv_core(clk, rst_n, iwb_adr_o, iwb_dat_i, iwb_cyc_o, iwb_stb_o, iwb_ack_i, dwb_adr_o, dwb_dat_o, dwb_dat_i, dwb_we_o, dwb_sel_o, dwb_cyc_o, dwb_stb_o, dwb_ack_i, dwb_err_i, interrupts);
  wire [31:0] _000_;
  wire _001_;
  wire [1:0] _002_;
  wire _003_;
  wire [31:0] _004_;
  wire [2:0] _005_;
  wire [31:0] _006_;
  wire _007_;
  wire [31:0] _008_;
  wire _009_;
  wire [31:0] _010_;
  wire [31:0] _011_;
  wire [31:0] _012_;
  wire [31:0] _013_;
  wire [31:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire [3:0] _093_;
  wire _094_;
  wire [31:0] _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire [1:0] _100_;
  wire [1:0] _101_;
  wire [1:0] _102_;
  wire [1:0] _103_;
  wire [1:0] _104_;
  wire [1:0] _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire [31:0] _112_;
  wire [31:0] _113_;
  wire [31:0] _114_;
  wire [31:0] _115_;
  wire [31:0] _116_;
  wire [31:0] _117_;
  wire [31:0] _118_;
  wire [31:0] _119_;
  wire _120_;
  wire [31:0] _121_;
  wire _122_;
  wire [31:0] _123_;
  wire [31:0] _124_;
  wire [31:0] _125_;
  wire [31:0] _126_;
  wire [31:0] _127_;
  wire [31:0] _128_;
  wire [31:0] _129_;
  wire _130_;
  wire [31:0] _131_;
  wire [31:0] _132_;
  wire [31:0] _133_;
  wire [31:0] _134_;
  wire [31:0] _135_;
  wire [31:0] _136_;
  wire [31:0] _137_;
  wire [31:0] _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire [2:0] _143_;
  wire [2:0] _144_;
  wire [2:0] _145_;
  wire [2:0] _146_;
  wire [2:0] _147_;
  wire [2:0] _148_;
  wire [2:0] _149_;
  wire [2:0] _150_;
  wire [2:0] _151_;
  wire [2:0] _152_;
  wire [2:0] _153_;
  wire _154_;
  wire [2:0] _155_;
  wire [2:0] _156_;
  wire [3:0] _157_;
  wire [3:0] _158_;
  wire [31:0] _159_;
  wire [7:0] _160_;
  wire [7:0] _161_;
  wire [15:0] _162_;
  wire [31:0] _163_;
  wire [31:0] _164_;
  wire [31:0] _165_;
  wire [31:0] _166_;
  wire [31:0] _167_;
  wire [3:0] alu_op;
  wire [31:0] alu_operand_a;
  wire [31:0] alu_operand_b;
  wire [31:0] alu_result;
  reg [31:0] alu_result_reg;
  wire alu_src_imm;
  wire alu_zero;
  input clk;
  wire clk;
  wire [11:0] csr_addr;
  wire [2:0] csr_op;
  wire [31:0] csr_rdata;
  wire csr_valid;
  wire [31:0] csr_wdata;
  input dwb_ack_i;
  wire dwb_ack_i;
  output [31:0] dwb_adr_o;
  wire [31:0] dwb_adr_o;
  reg [31:0] dwb_adr_reg;
  output dwb_cyc_o;
  wire dwb_cyc_o;
  reg dwb_cyc_reg;
  input [31:0] dwb_dat_i;
  wire [31:0] dwb_dat_i;
  output [31:0] dwb_dat_o;
  wire [31:0] dwb_dat_o;
  reg [31:0] dwb_dat_reg;
  input dwb_err_i;
  wire dwb_err_i;
  output [3:0] dwb_sel_o;
  wire [3:0] dwb_sel_o;
  reg [3:0] dwb_sel_reg;
  output dwb_stb_o;
  wire dwb_stb_o;
  wire dwb_stb_reg;
  output dwb_we_o;
  wire dwb_we_o;
  reg dwb_we_reg;
  wire [31:0] epc_out;
  wire [31:0] exception_cause;
  wire exception_taken;
  wire [31:0] exception_val;
  wire [2:0] funct3;
  wire [6:0] funct7;
  wire illegal_instr;
  wire [31:0] immediate;
  wire instr_retired;
  reg [31:0] instruction;
  wire [31:0] interrupt_cause;
  wire interrupt_enabled;
  wire interrupt_pending;
  wire interrupt_req;
  input [31:0] interrupts;
  wire [31:0] interrupts;
  wire is_branch;
  wire is_ebreak;
  wire is_ecall;
  wire is_jump;
  wire is_m;
  wire is_mret;
  wire is_system;
  wire is_zpec;
  input iwb_ack_i;
  wire iwb_ack_i;
  output [31:0] iwb_adr_o;
  wire [31:0] iwb_adr_o;
  output iwb_cyc_o;
  wire iwb_cyc_o;
  reg iwb_cyc_reg;
  input [31:0] iwb_dat_i;
  wire [31:0] iwb_dat_i;
  output iwb_stb_o;
  wire iwb_stb_o;
  wire iwb_stb_reg;
  wire [1:0] load_addr_offset;
  wire [7:0] load_byte;
  wire [31:0] load_data_processed;
  wire [15:0] load_halfword;
  wire load_sign_bit;
  reg mdu_ack;
  wire mdu_busy;
  wire mdu_done;
  reg [2:0] mdu_funct3;
  reg [1:0] mdu_pending;
  wire [63:0] mdu_product;
  wire [31:0] mdu_quotient;
  wire [31:0] mdu_remainder;
  reg [31:0] mdu_result_reg;
  reg mdu_start;
  reg [31:0] mem_data_reg;
  wire mem_read;
  wire mem_write;
  wire [6:0] opcode;
  reg [31:0] pc;
  wire [4:0] rd_addr;
  wire [31:0] rd_data;
  wire rd_wen;
  wire reg_write;
  wire [4:0] rs1_addr;
  wire [31:0] rs1_data;
  wire [4:0] rs2_addr;
  wire [31:0] rs2_data;
  input rst_n;
  wire rst_n;
  wire stall;
  reg [2:0] state;
  reg [31:0] trap_cause;
  reg trap_entry;
  reg [31:0] trap_pc;
  reg trap_return;
  reg [31:0] trap_val;
  wire [31:0] trap_vector;
  assign _014_ = rs1_data + immediate;
  assign _013_ = pc + immediate;
  assign _012_ = pc + 32'd4;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dwb_cyc_reg <= 1'h0;
    else if (_033_) dwb_cyc_reg <= _096_;
  always @(posedge clk)
    if (_034_) dwb_adr_reg <= alu_result_reg;
  always @(posedge clk)
    if (_034_)
      if (!mem_write) dwb_sel_reg <= 4'hf;
      else dwb_sel_reg <= _093_;
  always @(posedge clk)
    if (_035_) dwb_dat_reg <= _095_;
  always @(posedge clk)
    if (_034_) dwb_we_reg <= mem_write;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) iwb_cyc_reg <= 1'h0;
    else if (_036_) iwb_cyc_reg <= _097_;
  always @(posedge clk)
    if (_037_) instruction <= iwb_dat_i;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state <= 3'h0;
    else if (_038_) state <= _005_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) trap_entry <= 1'h0;
    else if (_039_) trap_entry <= _007_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) trap_return <= 1'h0;
    else if (_040_) trap_return <= _009_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) trap_pc <= 32'd0;
    else if (_041_) trap_pc <= _008_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) trap_cause <= 32'd0;
    else if (_041_) trap_cause <= _006_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) trap_val <= 32'd0;
    else if (_041_) trap_val <= _010_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pc <= 32'd0;
    else if (_042_) pc <= _004_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mem_data_reg <= 32'd0;
    else if (_043_) mem_data_reg <= dwb_dat_i;
  always @(posedge clk)
    if (_044_) alu_result_reg <= _000_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mdu_start <= 1'h0;
    else if (_045_) mdu_start <= _003_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mdu_ack <= 1'h0;
    else if (_046_) mdu_ack <= _001_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mdu_result_reg <= 32'd0;
    else if (_047_) mdu_result_reg <= _011_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mdu_pending <= 2'h0;
    else if (_048_) mdu_pending <= _002_;
  always @(posedge clk)
    if (_049_) mdu_funct3 <= funct3;
  assign _015_ = { _098_, iwb_ack_i, interrupt_pending } != 3'h4;
  assign _016_ = { _094_, _082_, dwb_ack_i } != 3'h6;
  assign _017_ = | { _053_, _098_, _154_, _099_, _092_, _094_ };
  assign _018_ = { _098_, interrupt_pending } != 2'h2;
  assign _019_ = { _099_, exception_taken } != 2'h2;
  assign _020_ = | { _098_, _099_, _130_ };
  assign _021_ = { _099_, exception_taken, is_mret } != 3'h4;
  assign _022_ = { _099_, exception_taken } != 2'h3;
  assign _023_ = | { _098_, _099_ };
  assign _024_ = | { _099_, _130_, instr_retired };
  assign _025_ = { _099_, exception_taken, is_mret, is_m } != 4'h9;
  assign _026_ = { _099_, exception_taken, is_mret } != 3'h5;
  assign _027_ = { _092_, _070_, _069_, _077_ } != 4'h8;
  assign _028_ = { _092_, _069_, _077_ } != 3'h6;
  assign _029_ = { _092_, _077_ } != 2'h3;
  assign _030_ = | { _099_, _092_ };
  assign _031_ = { _099_, exception_taken, is_mret, is_m } != 4'h8;
  assign _032_ = | { _092_, instr_retired };
  assign _054_ = ~ interrupt_pending;
  assign _055_ = ~ _077_;
  assign _056_ = ~ is_mret;
  assign _057_ = ~ exception_taken;
  assign _033_ = & { _094_, _082_ };
  assign _034_ = & { _094_, _082_, rst_n };
  assign _035_ = & { _094_, _082_, rst_n, mem_write };
  assign _036_ = & { _054_, _098_ };
  assign _037_ = & { _054_, _098_, iwb_ack_i, rst_n };
  assign _038_ = & { _017_, _016_, _015_ };
  assign _039_ = & { _020_, _019_, _018_ };
  assign _040_ = & { _023_, _022_, _021_ };
  assign _041_ = & { _023_, _019_, _018_ };
  assign _042_ = & { _024_, _022_, _021_ };
  assign _043_ = & { _094_, _082_, dwb_ack_i, mem_read };
  assign _044_ = & { _030_, _029_, _028_, _027_, _026_, _025_, _022_, rst_n };
  assign _045_ = & { _031_, _030_, _026_, _022_ };
  assign _046_ = & { _032_, _029_, _028_, _027_ };
  assign _047_ = & { _055_, _092_, _069_ };
  assign _048_ = & { _031_, _030_, _027_, _026_, _022_ };
  assign _049_ = & { _057_, _056_, _099_, rst_n, is_m };
  assign _050_ = | { _084_, _085_ };
  assign _051_ = | { _086_, _087_ };
  assign _052_ = | { _089_, _088_, _090_ };
  assign _053_ = | { _130_, instr_retired };
  assign _058_ = opcode == 7'h17;
  assign _059_ = opcode == 7'h37;
  assign _062_ = alu_result_reg[1:0] == 2'h2;
  assign _060_ = ! alu_result_reg[1:0];
  assign _061_ = alu_result_reg[1:0] == 2'h1;
  assign _067_ = opcode == 7'h0f;
  assign _068_ = ! mdu_pending;
  assign _069_ = mdu_pending == 2'h1;
  assign _070_ = mdu_pending == 2'h2;
  assign _071_ = opcode == 7'h6f;
  assign _072_ = rs1_data >= rs2_data;
  assign _073_ = reg_write && instr_retired;
  assign rd_wen = _073_ && _078_;
  assign _074_ = is_system && _079_;
  assign _075_ = _074_ && _080_;
  assign _076_ = _075_ && _081_;
  assign _077_ = mdu_done && _068_;
  assign _078_ = ! is_branch;
  assign _079_ = ! is_mret;
  assign _080_ = ! is_ecall;
  assign _081_ = ! is_ebreak;
  assign _082_ = mem_read || mem_write;
  assign _083_ = rs1_data < rs2_data;
  function [31:0] _258_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _258_ = b[31:0];
      4'b??1?:
        _258_ = b[63:32];
      4'b?1??:
        _258_ = b[95:64];
      4'b1???:
        _258_ = b[127:96];
      default:
        _258_ = a;
    endcase
  endfunction
  assign _011_ = _258_(32'hxxxxxxxx, { mdu_product[31:0], mdu_product[63:32], mdu_quotient, mdu_remainder }, { _091_, _052_, _051_, _050_ });
  assign _084_ = mdu_funct3 == 3'h7;
  assign _085_ = mdu_funct3 == 3'h6;
  assign _086_ = mdu_funct3 == 3'h5;
  assign _087_ = mdu_funct3 == 3'h4;
  assign _088_ = mdu_funct3 == 3'h3;
  assign _089_ = mdu_funct3 == 3'h2;
  assign _090_ = mdu_funct3 == 3'h1;
  assign _091_ = ! mdu_funct3;
  function [3:0] _267_;
    input [3:0] a;
    input [7:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _267_ = b[3:0];
      2'b1?:
        _267_ = b[7:4];
      default:
        _267_ = a;
    endcase
  endfunction
  assign _093_ = _267_(4'hf, { _157_, _158_ }, { _063_, _064_ });
  function [31:0] _268_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _268_ = b[31:0];
      2'b1?:
        _268_ = b[63:32];
      default:
        _268_ = a;
    endcase
  endfunction
  assign _095_ = _268_(rs2_data, { rs2_data[7:0], rs2_data[7:0], rs2_data[7:0], rs2_data[7:0], rs2_data[15:0], rs2_data[15:0] }, { _063_, _064_ });
  assign _096_ = dwb_ack_i ? 1'h0 : 1'h1;
  assign _097_ = iwb_ack_i ? 1'h0 : 1'h1;
  assign _100_ = _070_ ? 2'h0 : 2'hx;
  assign _101_ = _069_ ? 2'h2 : _100_;
  assign _102_ = _077_ ? 2'h1 : _101_;
  function [1:0] _274_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _274_ = b[1:0];
      2'b1?:
        _274_ = b[3:2];
      default:
        _274_ = a;
    endcase
  endfunction
  assign _002_ = _274_(2'hx, { _105_, _102_ }, { _099_, _092_ });
  assign _103_ = is_m ? 2'h0 : 2'hx;
  assign _104_ = is_mret ? 2'hx : _103_;
  assign _105_ = exception_taken ? 2'hx : _104_;
  function [0:0] _278_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _278_ = b[0:0];
      2'b1?:
        _278_ = b[1:1];
      default:
        _278_ = a;
    endcase
  endfunction
  assign _001_ = _278_(1'hx, { _108_, 1'h0 }, { _092_, instr_retired });
  assign _106_ = _070_ ? 1'h1 : 1'hx;
  assign _107_ = _069_ ? 1'hx : _106_;
  assign _108_ = _077_ ? 1'hx : _107_;
  function [0:0] _282_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _282_ = b[0:0];
      2'b1?:
        _282_ = b[1:1];
      default:
        _282_ = a;
    endcase
  endfunction
  assign _003_ = _282_(1'hx, { _111_, 1'h0 }, { _099_, _092_ });
  assign _109_ = is_m ? 1'h1 : 1'hx;
  assign _110_ = is_mret ? 1'hx : _109_;
  assign _111_ = exception_taken ? 1'hx : _110_;
  assign _112_ = _070_ ? mdu_result_reg : 32'hxxxxxxxx;
  assign _113_ = _069_ ? 32'hxxxxxxxx : _112_;
  assign _114_ = _077_ ? 32'hxxxxxxxx : _113_;
  function [31:0] _289_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _289_ = b[31:0];
      2'b1?:
        _289_ = b[63:32];
      default:
        _289_ = a;
    endcase
  endfunction
  assign _000_ = _289_(32'hxxxxxxxx, { _117_, _114_ }, { _099_, _092_ });
  assign _115_ = is_m ? 32'hxxxxxxxx : alu_result;
  assign _116_ = is_mret ? 32'hxxxxxxxx : _115_;
  assign _117_ = exception_taken ? 32'hxxxxxxxx : _116_;
  assign _118_ = _072_ ? _013_ : _012_;
  function [31:0] _294_;
    input [31:0] a;
    input [191:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _294_ = b[31:0];
      6'b????1?:
        _294_ = b[63:32];
      6'b???1??:
        _294_ = b[95:64];
      6'b??1???:
        _294_ = b[127:96];
      6'b?1????:
        _294_ = b[159:128];
      6'b1?????:
        _294_ = b[191:160];
      default:
        _294_ = a;
    endcase
  endfunction
  assign _119_ = _294_(_012_, { _126_, _125_, _124_, _123_, _121_, _118_ }, { _063_, _064_, _065_, _066_, _122_, _120_ });
  assign _120_ = funct3 == 3'h7;
  assign _121_ = _083_ ? _013_ : _012_;
  assign _122_ = funct3 == 3'h6;
  assign _123_ = alu_result[31] ? _012_ : _013_;
  assign _066_ = funct3 == 3'h5;
  assign _124_ = alu_result[31] ? _013_ : _012_;
  assign _065_ = funct3 == 3'h4;
  assign _125_ = alu_zero ? _012_ : _013_;
  assign _064_ = funct3 == 3'h1;
  assign _126_ = alu_zero ? _013_ : _012_;
  assign _063_ = ! funct3;
  assign _127_ = is_branch ? _119_ : _012_;
  assign _128_ = _071_ ? _013_ : { _014_[31:1], 1'h0 };
  assign _129_ = is_jump ? _128_ : _127_;
  function [31:0] _309_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _309_ = b[31:0];
      3'b?1?:
        _309_ = b[63:32];
      3'b1??:
        _309_ = b[95:64];
      default:
        _309_ = a;
    endcase
  endfunction
  assign _004_ = _309_(32'hxxxxxxxx, { _132_, trap_vector, _129_ }, { _099_, _130_, instr_retired });
  assign _131_ = is_mret ? epc_out : 32'hxxxxxxxx;
  assign _132_ = exception_taken ? 32'hxxxxxxxx : _131_;
  assign _133_ = exception_taken ? exception_val : 32'hxxxxxxxx;
  function [31:0] _313_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _313_ = b[31:0];
      2'b1?:
        _313_ = b[63:32];
      default:
        _313_ = a;
    endcase
  endfunction
  assign _010_ = _313_(32'hxxxxxxxx, { _134_, _133_ }, { _098_, _099_ });
  assign _134_ = interrupt_pending ? 32'd0 : 32'hxxxxxxxx;
  assign _135_ = exception_taken ? exception_cause : 32'hxxxxxxxx;
  function [31:0] _316_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _316_ = b[31:0];
      2'b1?:
        _316_ = b[63:32];
      default:
        _316_ = a;
    endcase
  endfunction
  assign _006_ = _316_(32'hxxxxxxxx, { _136_, _135_ }, { _098_, _099_ });
  assign _136_ = interrupt_pending ? interrupt_cause : 32'hxxxxxxxx;
  assign _137_ = exception_taken ? pc : 32'hxxxxxxxx;
  function [31:0] _319_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _319_ = b[31:0];
      2'b1?:
        _319_ = b[63:32];
      default:
        _319_ = a;
    endcase
  endfunction
  assign _008_ = _319_(32'hxxxxxxxx, { _138_, _137_ }, { _098_, _099_ });
  assign _138_ = interrupt_pending ? pc : 32'hxxxxxxxx;
  assign _139_ = is_mret ? 1'h1 : 1'hx;
  assign _140_ = exception_taken ? 1'hx : _139_;
  function [0:0] _323_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _323_ = b[0:0];
      2'b1?:
        _323_ = b[1:1];
      default:
        _323_ = a;
    endcase
  endfunction
  assign _009_ = _323_(1'hx, { 1'h0, _140_ }, { _098_, _099_ });
  function [0:0] _324_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _324_ = b[0:0];
      3'b?1?:
        _324_ = b[1:1];
      3'b1??:
        _324_ = b[2:2];
      default:
        _324_ = a;
    endcase
  endfunction
  assign _007_ = _324_(1'hx, { _142_, _141_, 1'h0 }, { _098_, _099_, _130_ });
  assign _141_ = exception_taken ? 1'h1 : 1'hx;
  assign _142_ = interrupt_pending ? 1'h1 : 1'hx;
  function [2:0] _327_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _327_ = b[2:0];
      6'b????1?:
        _327_ = b[5:3];
      6'b???1??:
        _327_ = b[8:6];
      6'b??1???:
        _327_ = b[11:9];
      6'b?1????:
        _327_ = b[14:12];
      6'b1?????:
        _327_ = b[17:15];
      default:
        _327_ = a;
    endcase
  endfunction
  assign _005_ = _327_(3'hx, { _156_, 3'h2, _153_, _147_, _144_, 3'h0 }, { _098_, _154_, _099_, _092_, _094_, _053_ });
  assign instr_retired = state == 3'h4;
  assign _143_ = dwb_ack_i ? 3'h4 : 3'hx;
  assign _144_ = _082_ ? _143_ : 3'h4;
  assign _094_ = state == 3'h3;
  assign _145_ = _070_ ? 3'h4 : 3'h5;
  assign _146_ = _069_ ? 3'h5 : _145_;
  assign _147_ = _077_ ? 3'h5 : _146_;
  assign _092_ = state == 3'h5;
  assign _130_ = state == 3'h6;
  assign _148_ = _082_ ? 3'h3 : 3'h4;
  assign _149_ = dwb_cyc_reg ? 3'h2 : 3'h4;
  assign _150_ = _067_ ? _149_ : _148_;
  assign _151_ = is_m ? 3'h5 : _150_;
  assign _152_ = is_mret ? 3'h0 : _151_;
  assign _153_ = exception_taken ? 3'h6 : _152_;
  assign _099_ = state == 3'h2;
  assign _154_ = state == 3'h1;
  assign _155_ = iwb_ack_i ? 3'h1 : 3'hx;
  assign _156_ = interrupt_pending ? 3'h6 : _155_;
  assign _098_ = ! state;
  assign _157_ = 4'h1 << alu_result_reg[1:0];
  assign _158_ = 4'h3 << { alu_result_reg[1], 1'h0 };
  assign alu_operand_a = _058_ ? pc : _159_;
  assign _159_ = _059_ ? 32'd0 : rs1_data;
  assign alu_operand_b = alu_src_imm ? immediate : rs2_data;
  assign load_byte = _060_ ? mem_data_reg[7:0] : _160_;
  assign _160_ = _061_ ? mem_data_reg[15:8] : _161_;
  assign _161_ = _062_ ? mem_data_reg[23:16] : mem_data_reg[31:24];
  assign load_halfword = _060_ ? mem_data_reg[15:0] : _162_;
  assign _162_ = _061_ ? mem_data_reg[23:8] : mem_data_reg[31:16];
  assign load_sign_bit = _063_ ? load_byte[7] : load_halfword[15];
  assign load_data_processed = _063_ ? { load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_byte } : _163_;
  assign _163_ = _064_ ? { load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_sign_bit, load_halfword } : _164_;
  assign _164_ = _065_ ? { 24'h000000, load_byte } : _165_;
  assign _165_ = _066_ ? { 16'h0000, load_halfword } : mem_data_reg;
  assign rd_data = mem_read ? load_data_processed : _166_;
  assign _166_ = is_system ? csr_rdata : _167_;
  assign _167_ = is_jump ? _012_ : alu_result_reg;
  assign csr_wdata = funct3[2] ? { 27'h0000000, instruction[19:15] } : rs1_data;
  assign csr_op = _076_ ? funct3 : 3'h0;
  alu alu_inst (
    .alu_op(alu_op),
    .operand_a(alu_operand_a),
    .operand_b(alu_operand_b),
    .result(alu_result),
    .zero(alu_zero)
  );
  csr_unit csr_inst (
    .clk(clk),
    .csr_addr(instruction[31:20]),
    .csr_op(csr_op),
    .csr_rdata(csr_rdata),
    .csr_valid(csr_valid),
    .csr_wdata(csr_wdata),
    .epc_out(epc_out),
    .instr_retired(instr_retired),
    .interrupt_cause(interrupt_cause),
    .interrupt_enabled(interrupt_enabled),
    .interrupt_pending(interrupt_pending),
    .interrupts_i(interrupts),
    .rst_n(rst_n),
    .trap_cause(trap_cause),
    .trap_entry(trap_entry),
    .trap_pc(trap_pc),
    .trap_return(trap_return),
    .trap_val(trap_val),
    .trap_vector(trap_vector)
  );
  decoder decoder_inst (
    .alu_op(alu_op),
    .alu_src_imm(alu_src_imm),
    .funct3(funct3),
    .funct7(funct7),
    .illegal_instr(illegal_instr),
    .immediate(immediate),
    .instruction(instruction),
    .is_branch(is_branch),
    .is_ebreak(is_ebreak),
    .is_ecall(is_ecall),
    .is_jump(is_jump),
    .is_m(is_m),
    .is_mret(is_mret),
    .is_system(is_system),
    .is_zpec(is_zpec),
    .mem_read(mem_read),
    .mem_write(mem_write),
    .opcode(opcode),
    .rd_addr(rd_addr),
    .reg_write(reg_write),
    .rs1_addr(rs1_addr),
    .rs2_addr(rs2_addr)
  );
  exception_unit exc_unit (
    .bus_error(dwb_err_i),
    .ebreak(is_ebreak),
    .ecall(is_ecall),
    .exception_cause(exception_cause),
    .exception_taken(exception_taken),
    .exception_val(exception_val),
    .funct3(funct3),
    .illegal_instr(illegal_instr),
    .instruction(instruction),
    .mem_addr(alu_result),
    .mem_read(mem_read),
    .mem_write(mem_write),
    .pc(pc)
  );
  mdu mdu_inst (
    .a(rs1_data),
    .ack(mdu_ack),
    .b(rs2_data),
    .busy(mdu_busy),
    .clk(clk),
    .done(mdu_done),
    .funct3(funct3),
    .product(mdu_product),
    .quotient(mdu_quotient),
    .remainder(mdu_remainder),
    .rst_n(rst_n),
    .start(mdu_start)
  );
  regfile regfile_inst (
    .clk(clk),
    .rd_addr(rd_addr),
    .rd_data(rd_data),
    .rd_wen(rd_wen),
    .rs1_addr(rs1_addr),
    .rs1_data(rs1_data),
    .rs2_addr(rs2_addr),
    .rs2_data(rs2_data),
    .rst_n(rst_n)
  );
  assign csr_addr = instruction[31:20];
  assign dwb_adr_o = dwb_adr_reg;
  assign dwb_cyc_o = dwb_cyc_reg;
  assign dwb_dat_o = dwb_dat_reg;
  assign dwb_sel_o = dwb_sel_reg;
  assign dwb_stb_o = dwb_cyc_reg;
  assign dwb_stb_reg = dwb_cyc_reg;
  assign dwb_we_o = dwb_we_reg;
  assign interrupt_req = interrupt_pending;
  assign iwb_adr_o = pc;
  assign iwb_cyc_o = iwb_cyc_reg;
  assign iwb_stb_o = iwb_cyc_reg;
  assign iwb_stb_reg = iwb_cyc_reg;
  assign load_addr_offset = alu_result_reg[1:0];
  assign stall = 1'h0;
endmodule

module decoder(instruction, opcode, funct3, funct7, rs1_addr, rs2_addr, rd_addr, immediate, alu_op, alu_src_imm, mem_read, mem_write, reg_write, is_branch, is_jump, is_system, is_m, is_zpec, is_ecall, is_ebreak, is_mret
, is_wfi, illegal_instr);
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [3:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire [3:0] _014_;
  wire [3:0] _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire [5:0] _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire [3:0] _044_;
  wire [3:0] _045_;
  output [3:0] alu_op;
  wire [3:0] alu_op;
  output alu_src_imm;
  wire alu_src_imm;
  output [2:0] funct3;
  wire [2:0] funct3;
  output [6:0] funct7;
  wire [6:0] funct7;
  output illegal_instr;
  wire illegal_instr;
  output [31:0] immediate;
  wire [31:0] immediate;
  input [31:0] instruction;
  wire [31:0] instruction;
  output is_branch;
  wire is_branch;
  output is_ebreak;
  wire is_ebreak;
  output is_ecall;
  wire is_ecall;
  output is_jump;
  wire is_jump;
  output is_m;
  wire is_m;
  output is_mret;
  wire is_mret;
  output is_system;
  wire is_system;
  output is_wfi;
  wire is_wfi;
  output is_zpec;
  wire is_zpec;
  output mem_read;
  wire mem_read;
  output mem_write;
  wire mem_write;
  output [6:0] opcode;
  wire [6:0] opcode;
  output [4:0] rd_addr;
  wire [4:0] rd_addr;
  output reg_write;
  wire reg_write;
  output [4:0] rs1_addr;
  wire [4:0] rs1_addr;
  output [4:0] rs2_addr;
  wire [4:0] rs2_addr;
  reg [3:0] \$auto$proc_rom.cc:150:do_switch$272  [7:0];
  initial begin
    \$auto$proc_rom.cc:150:do_switch$272 [0] = 4'ha;
    \$auto$proc_rom.cc:150:do_switch$272 [1] = 4'hb;
    \$auto$proc_rom.cc:150:do_switch$272 [2] = 4'hc;
    \$auto$proc_rom.cc:150:do_switch$272 [3] = 4'hd;
    \$auto$proc_rom.cc:150:do_switch$272 [4] = 4'he;
    \$auto$proc_rom.cc:150:do_switch$272 [5] = 4'hf;
    \$auto$proc_rom.cc:150:do_switch$272 [6] = 4'he;
    \$auto$proc_rom.cc:150:do_switch$272 [7] = 4'hf;
  end
  assign _014_ = \$auto$proc_rom.cc:150:do_switch$272 [instruction[14:12]];
  assign _016_ = | { _039_, _038_, _037_, _036_, _035_, _033_, _032_ };
  assign _017_ = | { _041_, _040_, _039_, _038_, _037_, _036_, _035_, _034_, _033_, _032_ };
  assign _018_ = | { _040_, _039_, _038_, _037_, _036_, _035_, _033_ };
  assign _019_ = | { _028_, _027_, _026_, _023_ };
  assign _020_ = | { _038_, _037_ };
  assign _021_ = instruction[31:25] == 7'h01;
  assign _022_ = | instruction[11:7];
  assign _011_ = _023_ ? 1'h1 : 1'h0;
  assign _009_ = _019_ ? 1'h0 : 1'h1;
  assign _023_ = ! instruction[31:20];
  assign _013_ = _026_ ? 1'h1 : 1'h0;
  assign _026_ = instruction[31:20] == 12'h105;
  assign _012_ = _027_ ? 1'h1 : 1'h0;
  assign _027_ = instruction[31:20] == 12'h302;
  assign _010_ = _028_ ? 1'h1 : 1'h0;
  assign _028_ = instruction[31:20] == 12'h001;
  function [0:0] _064_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _064_ = b[0:0];
      2'b1?:
        _064_ = b[1:1];
      default:
        _064_ = a;
    endcase
  endfunction
  assign _001_ = _064_(1'h1, { _009_, 1'h0 }, { _024_, _030_ });
  assign _006_ = _024_ ? _013_ : 1'h0;
  assign _005_ = _024_ ? _012_ : 1'h0;
  assign _002_ = _024_ ? _010_ : 1'h0;
  assign _003_ = _024_ ? _011_ : 1'h0;
  assign _007_ = _030_ ? _022_ : 1'h0;
  assign _030_ = | _029_;
  function [3:0] _071_;
    input [3:0] a;
    input [31:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _071_ = b[3:0];
      8'b??????1?:
        _071_ = b[7:4];
      8'b?????1??:
        _071_ = b[11:8];
      8'b????1???:
        _071_ = b[15:12];
      8'b???1????:
        _071_ = b[19:16];
      8'b??1?????:
        _071_ = b[23:20];
      8'b?1??????:
        _071_ = b[27:24];
      8'b1???????:
        _071_ = b[31:28];
      default:
        _071_ = a;
    endcase
  endfunction
  assign _015_ = _071_(4'hx, { _045_, 16'h5894, _044_, 8'h32 }, { _024_, _029_[0], _029_[1], _029_[2], _031_, _029_[3], _029_[4], _029_[5] });
  assign _008_ = _021_ ? _014_ : _015_;
  assign _004_ = _021_ ? 1'h1 : 1'h0;
  function [3:0] _074_;
    input [3:0] a;
    input [31:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _074_ = b[3:0];
      8'b??????1?:
        _074_ = b[7:4];
      8'b?????1??:
        _074_ = b[11:8];
      8'b????1???:
        _074_ = b[15:12];
      8'b???1????:
        _074_ = b[19:16];
      8'b??1?????:
        _074_ = b[23:20];
      8'b?1??????:
        _074_ = b[27:24];
      8'b1???????:
        _074_ = b[31:28];
      default:
        _074_ = a;
    endcase
  endfunction
  assign _000_ = _074_(4'hx, { 28'h0894325, _044_ }, { _024_, _029_[1], _029_[2], _031_, _029_[4], _029_[5], _029_[0], _029_[3] });
  assign _029_[3] = instruction[14:12] == 3'h5;
  assign _029_[0] = instruction[14:12] == 3'h1;
  assign _029_[5] = instruction[14:12] == 3'h7;
  assign _029_[4] = instruction[14:12] == 3'h6;
  assign _031_ = instruction[14:12] == 3'h4;
  assign _029_[2] = instruction[14:12] == 3'h3;
  assign _029_[1] = instruction[14:12] == 3'h2;
  assign _024_ = ! instruction[14:12];
  function [3:0] _083_;
    input [3:0] a;
    input [11:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _083_ = b[3:0];
      3'b?1?:
        _083_ = b[7:4];
      3'b1??:
        _083_ = b[11:8];
      default:
        _083_ = a;
    endcase
  endfunction
  assign alu_op = _083_(4'h0, { _000_, _008_, 4'h1 }, { _033_, _032_, _034_ });
  function [0:0] _084_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _084_ = b[0:0];
      2'b1?:
        _084_ = b[1:1];
      default:
        _084_ = a;
    endcase
  endfunction
  assign reg_write = _084_(1'h0, { 1'h1, _007_ }, { _016_, _025_ });
  assign alu_src_imm = _018_ ? 1'h1 : 1'h0;
  function [0:0] _086_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _086_ = b[0:0];
      2'b1?:
        _086_ = b[1:1];
      default:
        _086_ = a;
    endcase
  endfunction
  assign illegal_instr = _086_(1'h1, { _001_, 1'h0 }, { _025_, _017_ });
  assign _041_ = instruction[6:0] == 7'h0f;
  assign is_wfi = _025_ ? _006_ : 1'h0;
  assign is_mret = _025_ ? _005_ : 1'h0;
  assign is_ebreak = _025_ ? _002_ : 1'h0;
  assign is_ecall = _025_ ? _003_ : 1'h0;
  assign is_m = _032_ ? _004_ : 1'h0;
  assign _032_ = instruction[6:0] == 7'h33;
  assign is_system = _025_ ? 1'h1 : 1'h0;
  assign _025_ = instruction[6:0] == 7'h73;
  assign is_jump = _020_ ? 1'h1 : 1'h0;
  assign is_branch = _034_ ? 1'h1 : 1'h0;
  assign mem_write = _040_ ? 1'h1 : 1'h0;
  assign mem_read = _039_ ? 1'h1 : 1'h0;
  function [31:0] _100_;
    input [31:0] a;
    input [159:0] b;
    input [4:0] s;
    casez (s) // synopsys parallel_case
      5'b????1:
        _100_ = b[31:0];
      5'b???1?:
        _100_ = b[63:32];
      5'b??1??:
        _100_ = b[95:64];
      5'b?1???:
        _100_ = b[127:96];
      5'b1????:
        _100_ = b[159:128];
      default:
        _100_ = a;
    endcase
  endfunction
  assign immediate = _100_(32'd0, { instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31:20], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31:25], instruction[11:7], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[7], instruction[30:25], instruction[11:8], 1'h0, instruction[31:12], 12'h000, instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[31], instruction[19:12], instruction[20], instruction[30:21], 1'h0 }, { _043_, _040_, _034_, _042_, _038_ });
  assign _038_ = instruction[6:0] == 7'h6f;
  assign _042_ = | { _036_, _035_ };
  assign _036_ = instruction[6:0] == 7'h37;
  assign _035_ = instruction[6:0] == 7'h17;
  assign _034_ = instruction[6:0] == 7'h63;
  assign _040_ = instruction[6:0] == 7'h23;
  assign _043_ = | { _039_, _037_, _033_ };
  assign _033_ = instruction[6:0] == 7'h13;
  assign _039_ = instruction[6:0] == 7'h03;
  assign _037_ = instruction[6:0] == 7'h67;
  assign _045_ = instruction[30] ? 4'h1 : 4'h0;
  assign _044_ = instruction[30] ? 4'h7 : 4'h6;
  assign funct3 = instruction[14:12];
  assign funct7 = instruction[31:25];
  assign is_zpec = 1'h0;
  assign opcode = instruction[6:0];
  assign rd_addr = instruction[11:7];
  assign rs1_addr = instruction[19:15];
  assign rs2_addr = instruction[24:20];
endmodule

module exception_unit(pc, instruction, funct3, mem_addr, mem_read, mem_write, bus_error, illegal_instr, ecall, ebreak, exception_taken, exception_cause, exception_val);
  wire [31:0] _00_;
  wire _01_;
  wire [31:0] _02_;
  wire [31:0] _03_;
  wire _04_;
  wire [31:0] _05_;
  wire [31:0] _06_;
  wire _07_;
  wire [31:0] _08_;
  wire _09_;
  wire [31:0] _10_;
  wire [31:0] _11_;
  wire _12_;
  wire [31:0] _13_;
  wire [31:0] _14_;
  wire _15_;
  wire [31:0] _16_;
  wire [31:0] _17_;
  wire _18_;
  wire [31:0] _19_;
  wire [31:0] _20_;
  wire [31:0] _21_;
  wire [31:0] _22_;
  wire _23_;
  wire [31:0] _24_;
  wire [31:0] _25_;
  wire _26_;
  wire [31:0] _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  input bus_error;
  wire bus_error;
  input ebreak;
  wire ebreak;
  input ecall;
  wire ecall;
  output [31:0] exception_cause;
  wire [31:0] exception_cause;
  output exception_taken;
  wire exception_taken;
  output [31:0] exception_val;
  wire [31:0] exception_val;
  input [2:0] funct3;
  wire [2:0] funct3;
  input illegal_instr;
  wire illegal_instr;
  input [31:0] instruction;
  wire [31:0] instruction;
  input [31:0] mem_addr;
  wire [31:0] mem_addr;
  input mem_read;
  wire mem_read;
  input mem_write;
  wire mem_write;
  input [31:0] pc;
  wire [31:0] pc;
  assign _29_ = funct3 == 3'h5;
  assign _28_ = funct3 == 3'h1;
  assign _30_ = funct3 == 3'h2;
  assign _31_ = _34_ && mem_addr[0];
  assign _33_ = _28_ && mem_addr[0];
  assign _32_ = _30_ && _36_;
  assign _34_ = _28_ || _29_;
  assign _35_ = | pc[1:0];
  assign _36_ = | mem_addr[1:0];
  assign _21_ = bus_error ? 32'd5 : 32'd0;
  assign _04_ = bus_error ? 1'h1 : 1'h0;
  assign _20_ = _32_ ? 32'd4 : _21_;
  assign _19_ = _31_ ? mem_addr : _02_;
  assign _17_ = _31_ ? 32'd4 : _20_;
  assign _18_ = _31_ ? 1'h1 : _01_;
  assign _16_ = mem_read ? _19_ : _24_;
  assign _14_ = mem_read ? _17_ : _22_;
  assign _15_ = mem_read ? _18_ : _23_;
  assign _13_ = ebreak ? pc : _16_;
  assign _11_ = ebreak ? 32'd3 : _14_;
  assign _12_ = ebreak ? 1'h1 : _15_;
  assign _10_ = illegal_instr ? instruction : _13_;
  assign _08_ = illegal_instr ? 32'd2 : _11_;
  assign _09_ = illegal_instr ? 1'h1 : _12_;
  assign exception_val = _35_ ? pc : _10_;
  assign exception_cause = _35_ ? 32'd0 : _08_;
  assign exception_taken = _35_ ? 1'h1 : _09_;
  assign _06_ = ecall ? 32'd11 : 32'd0;
  assign _07_ = ecall ? 1'h1 : 1'h0;
  assign _03_ = bus_error ? 32'd7 : 32'd0;
  assign _02_ = _32_ ? mem_addr : _05_;
  assign _00_ = _32_ ? 32'd6 : _03_;
  assign _01_ = _32_ ? 1'h1 : _04_;
  assign _27_ = _33_ ? mem_addr : _02_;
  assign _25_ = _33_ ? 32'd6 : _00_;
  assign _26_ = _33_ ? 1'h1 : _01_;
  assign _24_ = mem_write ? _27_ : 32'd0;
  assign _22_ = mem_write ? _25_ : _06_;
  assign _23_ = mem_write ? _26_ : _07_;
  assign _05_ = bus_error ? mem_addr : 32'd0;
endmodule

module mdu(clk, rst_n, start, ack, funct3, a, b, busy, done, product, quotient, remainder);
  wire [63:0] _000_;
  wire _001_;
  wire [5:0] _002_;
  wire _003_;
  wire [5:0] _004_;
  wire [63:0] _005_;
  wire [31:0] _006_;
  wire [31:0] _007_;
  wire [31:0] _008_;
  wire [31:0] _009_;
  wire [32:0] _010_;
  wire [1:0] _011_;
  wire [31:0] _012_;
  wire [31:0] _013_;
  wire [63:0] _014_;
  wire [31:0] _015_;
  wire [63:0] _016_;
  wire [31:0] _017_;
  wire [31:0] _018_;
  wire [31:0] _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire [31:0] _073_;
  wire [31:0] _074_;
  wire [63:0] _075_;
  wire [31:0] _076_;
  wire [31:0] _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [5:0] _081_;
  wire [5:0] _082_;
  wire _083_;
  wire [5:0] _084_;
  wire [5:0] _085_;
  wire [32:0] _086_;
  wire [32:0] _087_;
  wire [32:0] _088_;
  wire [32:0] _089_;
  wire [32:0] _090_;
  wire [31:0] _091_;
  wire [31:0] _092_;
  wire [31:0] _093_;
  wire [31:0] _094_;
  wire [31:0] _095_;
  wire [31:0] _096_;
  wire [31:0] _097_;
  wire [5:0] _098_;
  wire _099_;
  wire [5:0] _100_;
  wire [5:0] _101_;
  wire [63:0] _102_;
  wire [63:0] _103_;
  wire [63:0] _104_;
  wire [63:0] _105_;
  wire [31:0] _106_;
  wire [31:0] _107_;
  wire [31:0] _108_;
  wire [63:0] _109_;
  wire [63:0] _110_;
  wire [63:0] _111_;
  wire _112_;
  wire [1:0] _113_;
  wire [1:0] _114_;
  wire [1:0] _115_;
  wire [1:0] _116_;
  wire [1:0] _117_;
  wire [31:0] _118_;
  wire [31:0] _119_;
  wire [31:0] _120_;
  wire [31:0] _121_;
  wire [63:0] _122_;
  wire [63:0] _123_;
  wire [63:0] _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire [31:0] _133_;
  wire [31:0] _134_;
  wire [31:0] _135_;
  wire [31:0] _136_;
  wire [31:0] _137_;
  wire [31:0] _138_;
  wire [31:0] _139_;
  wire [31:0] _140_;
  wire _141_;
  input [31:0] a;
  wire [31:0] a;
  reg [31:0] a_latched;
  reg [63:0] acc;
  input ack;
  wire ack;
  input [31:0] b;
  wire [31:0] b;
  reg [31:0] b_latched;
  output busy;
  reg busy;
  input clk;
  wire clk;
  reg [5:0] div_count;
  reg div_sign_q;
  reg div_sign_r;
  reg [31:0] dividend;
  reg [31:0] divisor;
  output done;
  reg done;
  input [2:0] funct3;
  wire [2:0] funct3;
  reg [5:0] mul_count;
  wire mul_signed_b;
  reg [63:0] multiplicand;
  reg [31:0] multiplier;
  reg [2:0] op_latched;
  output [63:0] product;
  reg [63:0] product;
  output [31:0] quotient;
  reg [31:0] quotient;
  reg [31:0] quotient_reg;
  output [31:0] remainder;
  reg [31:0] remainder;
  reg [32:0] remainder_reg;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  reg [1:0] state;
  assign _012_ = _073_ + 1'h1;
  assign _013_ = _074_ + 1'h1;
  assign _014_ = acc + multiplicand;
  assign _015_ = mul_count + 32'd1;
  assign _016_ = _075_ + 64'h0000000000000001;
  assign _017_ = div_count + 32'd1;
  assign _018_ = _076_ + 1'h1;
  assign _019_ = _077_ + 1'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) busy <= 1'h0;
    else if (_035_) busy <= _001_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) product <= 64'h0000000000000000;
    else if (_036_) product <= _124_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) quotient <= 32'd0;
    else if (_037_) quotient <= _007_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) remainder <= 32'd0;
    else if (_037_) remainder <= _009_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state <= 2'h0;
    else if (_038_) state <= _011_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) multiplicand <= 64'h0000000000000000;
    else if (_039_) multiplicand <= _005_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) multiplier <= 32'd0;
    else if (_039_) multiplier <= _006_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) acc <= 64'h0000000000000000;
    else if (_040_) acc <= _000_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) b_latched <= 32'd0;
    else if (_041_) b_latched <= b;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) a_latched <= 32'd0;
    else if (_041_) a_latched <= a;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) op_latched <= 3'h0;
    else if (_041_) op_latched <= funct3;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mul_count <= 6'h00;
    else if (_039_) mul_count <= _004_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) div_sign_r <= 1'h0;
    else if (_042_) div_sign_r <= _079_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) div_sign_q <= 1'h0;
    else if (_042_) div_sign_q <= _080_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) div_count <= 6'h00;
    else if (_043_) div_count <= _002_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dividend <= 32'd0;
    else if (_042_) dividend <= _097_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) divisor <= 32'd0;
    else if (_042_) divisor <= _096_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) quotient_reg <= 32'd0;
    else if (_043_) quotient_reg <= _008_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) remainder_reg <= 33'h000000000;
    else if (_043_) remainder_reg <= _010_;
  assign _020_ = { _078_, start } != 2'h2;
  assign _021_ = { _099_, _071_ } != 2'h3;
  assign _022_ = { _083_, _056_ } != 2'h2;
  assign _023_ = | { _078_, _099_, _083_, _112_ };
  assign _024_ = { _044_, _112_, _057_, _059_ } != 4'h4;
  assign _025_ = | { _083_, _112_ };
  assign _026_ = { _083_, _072_, _056_ } != 3'h6;
  assign _027_ = { _078_, _068_, start } != 3'h5;
  assign _028_ = { _099_, _071_ } != 2'h2;
  assign _029_ = | { _078_, _099_ };
  assign _030_ = { _099_, _071_, multiplier[0] } != 3'h6;
  assign _031_ = { _078_, _068_, start } != 3'h7;
  assign _032_ = { _083_, _072_, _056_ } != 3'h4;
  assign _033_ = { _083_, _056_ } != 2'h3;
  assign _034_ = | { _078_, _083_ };
  assign _046_ = ~ _071_;
  assign _047_ = ~ _068_;
  assign _035_ = & { _023_, _022_, _021_, _020_ };
  assign _036_ = & { _046_, _099_ };
  assign _037_ = & { _025_, _024_, _022_ };
  assign _038_ = & { _023_, _021_, _020_, _026_ };
  assign _039_ = & { _020_, _027_, _029_, _028_ };
  assign _040_ = & { _020_, _027_, _030_, _029_, _028_ };
  assign _041_ = & { _078_, start };
  assign _042_ = & { _047_, _078_, start };
  assign _043_ = & { _034_, _033_, _032_, _031_, _020_ };
  assign _044_ = | { _060_, _058_ };
  assign _045_ = | { _059_, _057_ };
  assign _048_ = ! funct3;
  assign _051_ = funct3 == 3'h3;
  assign _050_ = funct3 == 3'h2;
  assign _049_ = funct3 == 3'h1;
  assign _052_ = funct3 == 3'h4;
  assign _053_ = funct3 == 3'h6;
  assign mul_signed_b = op_latched == 3'h1;
  assign _055_ = op_latched == 3'h2;
  assign _056_ = ! b_latched;
  assign _061_ = { remainder_reg[30:0], _132_ } >= divisor;
  assign _062_ = _069_ && a[31];
  assign _063_ = _049_ && b[31];
  assign _064_ = _055_ && a_latched[31];
  assign _065_ = ack && done;
  assign _066_ = _048_ || _049_;
  assign _067_ = _066_ || _050_;
  assign _068_ = _067_ || _051_;
  assign _069_ = _049_ || _050_;
  assign _070_ = _052_ || _053_;
  assign _071_ = mul_count < 32'd32;
  assign _072_ = div_count < 32'd32;
  assign _073_ = ~ a;
  assign _074_ = ~ b;
  assign _075_ = ~ acc;
  assign _076_ = ~ quotient_reg;
  assign _077_ = ~ remainder_reg[31:0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) done <= 1'h0;
    else done <= _003_;
  assign _079_ = _070_ ? a[31] : 1'h0;
  assign _080_ = _070_ ? _141_ : 1'h0;
  assign _081_ = _072_ ? _017_[5:0] : 6'hxx;
  assign _082_ = _056_ ? 6'hxx : _081_;
  function [5:0] _228_;
    input [5:0] a;
    input [11:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _228_ = b[5:0];
      2'b1?:
        _228_ = b[11:6];
      default:
        _228_ = a;
    endcase
  endfunction
  assign _002_ = _228_(6'hxx, { _085_, _082_ }, { _078_, _083_ });
  assign _084_ = _068_ ? 6'hxx : 6'h00;
  assign _085_ = start ? _084_ : 6'hxx;
  assign _086_ = _061_ ? { 1'h0, _134_ } : { remainder_reg[31:0], _132_ };
  assign _087_ = _072_ ? _086_ : 33'hxxxxxxxxx;
  assign _088_ = _056_ ? 33'hxxxxxxxxx : _087_;
  function [32:0] _234_;
    input [32:0] a;
    input [65:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _234_ = b[32:0];
      2'b1?:
        _234_ = b[65:33];
      default:
        _234_ = a;
    endcase
  endfunction
  assign _010_ = _234_(33'hxxxxxxxxx, { _090_, _088_ }, { _078_, _083_ });
  assign _089_ = _068_ ? 33'hxxxxxxxxx : 33'h000000000;
  assign _090_ = start ? _089_ : 33'hxxxxxxxxx;
  assign _091_ = _061_ ? { quotient_reg[30:0], 1'h1 } : { quotient_reg[30:0], 1'h0 };
  assign _092_ = _072_ ? _091_ : 32'hxxxxxxxx;
  assign _093_ = _056_ ? 32'hxxxxxxxx : _092_;
  function [31:0] _240_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _240_ = b[31:0];
      2'b1?:
        _240_ = b[63:32];
      default:
        _240_ = a;
    endcase
  endfunction
  assign _008_ = _240_(32'hxxxxxxxx, { _095_, _093_ }, { _078_, _083_ });
  assign _094_ = _068_ ? 32'hxxxxxxxx : 32'd0;
  assign _095_ = start ? _094_ : 32'hxxxxxxxx;
  assign _096_ = _070_ ? _138_ : b;
  assign _097_ = _070_ ? _137_ : a;
  assign _098_ = _071_ ? _015_[5:0] : 6'hxx;
  function [5:0] _246_;
    input [5:0] a;
    input [11:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _246_ = b[5:0];
      2'b1?:
        _246_ = b[11:6];
      default:
        _246_ = a;
    endcase
  endfunction
  assign _004_ = _246_(6'hxx, { _101_, _098_ }, { _078_, _099_ });
  assign _100_ = _068_ ? 6'h00 : 6'hxx;
  assign _101_ = start ? _100_ : 6'hxx;
  assign _102_ = multiplier[0] ? _014_ : 64'hxxxxxxxxxxxxxxxx;
  assign _103_ = _071_ ? _102_ : 64'hxxxxxxxxxxxxxxxx;
  function [63:0] _251_;
    input [63:0] a;
    input [127:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _251_ = b[63:0];
      2'b1?:
        _251_ = b[127:64];
      default:
        _251_ = a;
    endcase
  endfunction
  assign _000_ = _251_(64'hxxxxxxxxxxxxxxxx, { _105_, _103_ }, { _078_, _099_ });
  assign _104_ = _068_ ? 64'h0000000000000000 : 64'hxxxxxxxxxxxxxxxx;
  assign _105_ = start ? _104_ : 64'hxxxxxxxxxxxxxxxx;
  assign _106_ = _071_ ? { 1'h0, multiplier[31:1] } : 32'hxxxxxxxx;
  function [31:0] _255_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _255_ = b[31:0];
      2'b1?:
        _255_ = b[63:32];
      default:
        _255_ = a;
    endcase
  endfunction
  assign _006_ = _255_(32'hxxxxxxxx, { _108_, _106_ }, { _078_, _099_ });
  assign _107_ = _068_ ? _136_ : 32'hxxxxxxxx;
  assign _108_ = start ? _107_ : 32'hxxxxxxxx;
  assign _109_ = _071_ ? { multiplicand[62:0], 1'h0 } : 64'hxxxxxxxxxxxxxxxx;
  function [63:0] _259_;
    input [63:0] a;
    input [127:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _259_ = b[63:0];
      2'b1?:
        _259_ = b[127:64];
      default:
        _259_ = a;
    endcase
  endfunction
  assign _005_ = _259_(64'hxxxxxxxxxxxxxxxx, { _111_, _109_ }, { _078_, _099_ });
  assign _110_ = _068_ ? { 32'h00000000, _135_ } : 64'hxxxxxxxxxxxxxxxx;
  assign _111_ = start ? _110_ : 64'hxxxxxxxxxxxxxxxx;
  function [1:0] _262_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _262_ = b[1:0];
      4'b??1?:
        _262_ = b[3:2];
      4'b?1??:
        _262_ = b[5:4];
      4'b1???:
        _262_ = b[7:6];
      default:
        _262_ = a;
    endcase
  endfunction
  assign _011_ = _262_(2'hx, { _117_, _115_, _114_, 2'h0 }, { _078_, _099_, _083_, _112_ });
  assign _113_ = _072_ ? 2'hx : 2'h3;
  assign _114_ = _056_ ? 2'h0 : _113_;
  assign _115_ = _071_ ? 2'hx : 2'h0;
  assign _116_ = _068_ ? 2'h1 : 2'h2;
  assign _117_ = start ? _116_ : 2'hx;
  function [31:0] _268_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _268_ = b[31:0];
      2'b1?:
        _268_ = b[63:32];
      default:
        _268_ = a;
    endcase
  endfunction
  assign _118_ = _268_(32'hxxxxxxxx, { _140_, remainder_reg[31:0] }, { _045_, _044_ });
  function [31:0] _269_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _269_ = b[31:0];
      2'b1?:
        _269_ = b[63:32];
      default:
        _269_ = a;
    endcase
  endfunction
  assign _009_ = _269_(32'hxxxxxxxx, { _119_, _118_ }, { _083_, _112_ });
  assign _119_ = _056_ ? a_latched : 32'hxxxxxxxx;
  function [31:0] _271_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _271_ = b[31:0];
      2'b1?:
        _271_ = b[63:32];
      default:
        _271_ = a;
    endcase
  endfunction
  assign _120_ = _271_(32'hxxxxxxxx, { _139_, quotient_reg }, { _045_, _044_ });
  assign _060_ = op_latched == 3'h7;
  assign _059_ = op_latched == 3'h6;
  assign _058_ = op_latched == 3'h5;
  assign _057_ = op_latched == 3'h4;
  function [31:0] _276_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _276_ = b[31:0];
      2'b1?:
        _276_ = b[63:32];
      default:
        _276_ = a;
    endcase
  endfunction
  assign _007_ = _276_(32'hxxxxxxxx, { _121_, _120_ }, { _083_, _112_ });
  assign _121_ = _056_ ? 32'd4294967295 : 32'hxxxxxxxx;
  assign _122_ = _064_ ? _016_ : acc;
  assign _123_ = _054_ ? _016_ : acc;
  assign _124_ = mul_signed_b ? _123_ : _122_;
  assign _125_ = _065_ ? 1'h0 : done;
  function [0:0] _282_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _282_ = b[0:0];
      4'b??1?:
        _282_ = b[1:1];
      4'b?1??:
        _282_ = b[2:2];
      4'b1???:
        _282_ = b[3:3];
      default:
        _282_ = a;
    endcase
  endfunction
  assign _003_ = _282_(_125_, { _128_, _127_, _126_, 1'h1 }, { _078_, _099_, _083_, _112_ });
  assign _126_ = _056_ ? 1'h1 : _125_;
  assign _127_ = _071_ ? _125_ : 1'h1;
  assign _128_ = start ? 1'h0 : _125_;
  function [0:0] _286_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _286_ = b[0:0];
      4'b??1?:
        _286_ = b[1:1];
      4'b?1??:
        _286_ = b[2:2];
      4'b1???:
        _286_ = b[3:3];
      default:
        _286_ = a;
    endcase
  endfunction
  assign _001_ = _286_(1'hx, { _131_, _130_, _129_, 1'h0 }, { _078_, _099_, _083_, _112_ });
  assign _112_ = state == 2'h3;
  assign _129_ = _056_ ? 1'h0 : 1'hx;
  assign _083_ = state == 2'h2;
  assign _130_ = _071_ ? 1'hx : 1'h0;
  assign _099_ = state == 2'h1;
  assign _131_ = start ? 1'h1 : 1'hx;
  assign _078_ = ! state;
  wire [31:0] _305_ = dividend;
  assign _132_ = _305_[$signed(_133_) +: 1];
  assign _133_ = 32'd31 - div_count;
  assign _134_ = { remainder_reg[30:0], _132_ } - divisor;
  assign _135_ = _062_ ? _012_ : a;
  assign _136_ = _063_ ? _013_ : b;
  assign _137_ = a[31] ? _012_ : { 1'h0, a[30:0] };
  assign _138_ = b[31] ? _013_ : { 1'h0, b[30:0] };
  assign _139_ = div_sign_q ? _018_ : quotient_reg;
  assign _140_ = div_sign_r ? _019_ : remainder_reg[31:0];
  assign _141_ = a[31] ^ b[31];
  assign _054_ = a_latched[31] ^ b_latched[31];
endmodule

module regfile(clk, rst_n, rs1_addr, rs1_data, rs2_addr, rs2_data, rd_addr, rd_data, rd_wen);
  wire [31:0] _000_;
  wire [31:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  input clk;
  wire clk;
  wire [31:0] i;
  input [4:0] rd_addr;
  wire [4:0] rd_addr;
  input [31:0] rd_data;
  wire [31:0] rd_data;
  input rd_wen;
  wire rd_wen;
  reg [31:0] \registers[10] ;
  reg [31:0] \registers[11] ;
  reg [31:0] \registers[12] ;
  reg [31:0] \registers[13] ;
  reg [31:0] \registers[14] ;
  reg [31:0] \registers[15] ;
  reg [31:0] \registers[16] ;
  reg [31:0] \registers[17] ;
  reg [31:0] \registers[18] ;
  reg [31:0] \registers[19] ;
  reg [31:0] \registers[1] ;
  reg [31:0] \registers[20] ;
  reg [31:0] \registers[21] ;
  reg [31:0] \registers[22] ;
  reg [31:0] \registers[23] ;
  reg [31:0] \registers[24] ;
  reg [31:0] \registers[25] ;
  reg [31:0] \registers[26] ;
  reg [31:0] \registers[27] ;
  reg [31:0] \registers[28] ;
  reg [31:0] \registers[29] ;
  reg [31:0] \registers[2] ;
  reg [31:0] \registers[30] ;
  reg [31:0] \registers[31] ;
  reg [31:0] \registers[3] ;
  reg [31:0] \registers[4] ;
  reg [31:0] \registers[5] ;
  reg [31:0] \registers[6] ;
  reg [31:0] \registers[7] ;
  reg [31:0] \registers[8] ;
  reg [31:0] \registers[9] ;
  input [4:0] rs1_addr;
  wire [4:0] rs1_addr;
  output [31:0] rs1_data;
  wire [31:0] rs1_data;
  input [4:0] rs2_addr;
  wire [4:0] rs2_addr;
  output [31:0] rs2_data;
  wire [31:0] rs2_data;
  input rst_n;
  wire rst_n;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[30]  <= 32'd0;
    else if (_002_) \registers[30]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[31]  <= 32'd0;
    else if (_003_) \registers[31]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[1]  <= 32'd0;
    else if (_004_) \registers[1]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[2]  <= 32'd0;
    else if (_005_) \registers[2]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[3]  <= 32'd0;
    else if (_006_) \registers[3]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[4]  <= 32'd0;
    else if (_007_) \registers[4]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[5]  <= 32'd0;
    else if (_008_) \registers[5]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[6]  <= 32'd0;
    else if (_009_) \registers[6]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[7]  <= 32'd0;
    else if (_010_) \registers[7]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[8]  <= 32'd0;
    else if (_011_) \registers[8]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[9]  <= 32'd0;
    else if (_012_) \registers[9]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[10]  <= 32'd0;
    else if (_013_) \registers[10]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[11]  <= 32'd0;
    else if (_014_) \registers[11]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[12]  <= 32'd0;
    else if (_015_) \registers[12]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[13]  <= 32'd0;
    else if (_016_) \registers[13]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[14]  <= 32'd0;
    else if (_017_) \registers[14]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[15]  <= 32'd0;
    else if (_018_) \registers[15]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[16]  <= 32'd0;
    else if (_019_) \registers[16]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[17]  <= 32'd0;
    else if (_020_) \registers[17]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[18]  <= 32'd0;
    else if (_021_) \registers[18]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[19]  <= 32'd0;
    else if (_022_) \registers[19]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[20]  <= 32'd0;
    else if (_023_) \registers[20]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[21]  <= 32'd0;
    else if (_024_) \registers[21]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[22]  <= 32'd0;
    else if (_025_) \registers[22]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[23]  <= 32'd0;
    else if (_026_) \registers[23]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[24]  <= 32'd0;
    else if (_027_) \registers[24]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[25]  <= 32'd0;
    else if (_028_) \registers[25]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[26]  <= 32'd0;
    else if (_029_) \registers[26]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[27]  <= 32'd0;
    else if (_030_) \registers[27]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[28]  <= 32'd0;
    else if (_031_) \registers[28]  <= rd_data;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \registers[29]  <= 32'd0;
    else if (_032_) \registers[29]  <= rd_data;
  assign _002_ = & { _100_, _035_ };
  assign _003_ = & { _099_, _035_ };
  assign _004_ = & { _129_, _035_ };
  assign _005_ = & { _128_, _035_ };
  assign _006_ = & { _127_, _035_ };
  assign _007_ = & { _126_, _035_ };
  assign _008_ = & { _125_, _035_ };
  assign _009_ = & { _124_, _035_ };
  assign _010_ = & { _123_, _035_ };
  assign _011_ = & { _122_, _035_ };
  assign _012_ = & { _121_, _035_ };
  assign _013_ = & { _120_, _035_ };
  assign _014_ = & { _119_, _035_ };
  assign _015_ = & { _118_, _035_ };
  assign _016_ = & { _117_, _035_ };
  assign _017_ = & { _116_, _035_ };
  assign _018_ = & { _115_, _035_ };
  assign _019_ = & { _114_, _035_ };
  assign _020_ = & { _113_, _035_ };
  assign _021_ = & { _112_, _035_ };
  assign _022_ = & { _111_, _035_ };
  assign _023_ = & { _110_, _035_ };
  assign _024_ = & { _109_, _035_ };
  assign _025_ = & { _108_, _035_ };
  assign _026_ = & { _107_, _035_ };
  assign _027_ = & { _106_, _035_ };
  assign _028_ = & { _105_, _035_ };
  assign _029_ = & { _104_, _035_ };
  assign _030_ = & { _103_, _035_ };
  assign _031_ = & { _102_, _035_ };
  assign _032_ = & { _101_, _035_ };
  assign _035_ = rd_wen && _036_;
  assign _036_ = | rd_addr;
  function [31:0] _194_;
    input [31:0] a;
    input [991:0] b;
    input [30:0] s;
    casez (s) // synopsys parallel_case
      31'b??????????????????????????????1:
        _194_ = b[31:0];
      31'b?????????????????????????????1?:
        _194_ = b[63:32];
      31'b????????????????????????????1??:
        _194_ = b[95:64];
      31'b???????????????????????????1???:
        _194_ = b[127:96];
      31'b??????????????????????????1????:
        _194_ = b[159:128];
      31'b?????????????????????????1?????:
        _194_ = b[191:160];
      31'b????????????????????????1??????:
        _194_ = b[223:192];
      31'b???????????????????????1???????:
        _194_ = b[255:224];
      31'b??????????????????????1????????:
        _194_ = b[287:256];
      31'b?????????????????????1?????????:
        _194_ = b[319:288];
      31'b????????????????????1??????????:
        _194_ = b[351:320];
      31'b???????????????????1???????????:
        _194_ = b[383:352];
      31'b??????????????????1????????????:
        _194_ = b[415:384];
      31'b?????????????????1?????????????:
        _194_ = b[447:416];
      31'b????????????????1??????????????:
        _194_ = b[479:448];
      31'b???????????????1???????????????:
        _194_ = b[511:480];
      31'b??????????????1????????????????:
        _194_ = b[543:512];
      31'b?????????????1?????????????????:
        _194_ = b[575:544];
      31'b????????????1??????????????????:
        _194_ = b[607:576];
      31'b???????????1???????????????????:
        _194_ = b[639:608];
      31'b??????????1????????????????????:
        _194_ = b[671:640];
      31'b?????????1?????????????????????:
        _194_ = b[703:672];
      31'b????????1??????????????????????:
        _194_ = b[735:704];
      31'b???????1???????????????????????:
        _194_ = b[767:736];
      31'b??????1????????????????????????:
        _194_ = b[799:768];
      31'b?????1?????????????????????????:
        _194_ = b[831:800];
      31'b????1??????????????????????????:
        _194_ = b[863:832];
      31'b???1???????????????????????????:
        _194_ = b[895:864];
      31'b??1????????????????????????????:
        _194_ = b[927:896];
      31'b?1?????????????????????????????:
        _194_ = b[959:928];
      31'b1??????????????????????????????:
        _194_ = b[991:960];
      default:
        _194_ = a;
    endcase
  endfunction
  assign _001_ = _194_(32'hxxxxxxxx, { \registers[1] , \registers[2] , \registers[3] , \registers[4] , \registers[5] , \registers[6] , \registers[7] , \registers[8] , \registers[9] , \registers[10] , \registers[11] , \registers[12] , \registers[13] , \registers[14] , \registers[15] , \registers[16] , \registers[17] , \registers[18] , \registers[19] , \registers[20] , \registers[21] , \registers[22] , \registers[23] , \registers[24] , \registers[25] , \registers[26] , \registers[27] , \registers[28] , \registers[29] , \registers[30] , \registers[31]  }, { _067_, _066_, _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_, _057_, _056_, _055_, _054_, _053_, _052_, _051_, _050_, _049_, _048_, _047_, _046_, _045_, _044_, _043_, _042_, _041_, _040_, _039_, _038_, _037_ });
  assign _037_ = rs2_addr == 5'h1f;
  assign _038_ = rs2_addr == 5'h1e;
  assign _039_ = rs2_addr == 5'h1d;
  assign _040_ = rs2_addr == 5'h1c;
  assign _041_ = rs2_addr == 5'h1b;
  assign _042_ = rs2_addr == 5'h1a;
  assign _043_ = rs2_addr == 5'h19;
  assign _044_ = rs2_addr == 5'h18;
  assign _045_ = rs2_addr == 5'h17;
  assign _046_ = rs2_addr == 5'h16;
  assign _047_ = rs2_addr == 5'h15;
  assign _048_ = rs2_addr == 5'h14;
  assign _049_ = rs2_addr == 5'h13;
  assign _050_ = rs2_addr == 5'h12;
  assign _051_ = rs2_addr == 5'h11;
  assign _052_ = rs2_addr == 5'h10;
  assign _053_ = rs2_addr == 5'h0f;
  assign _054_ = rs2_addr == 5'h0e;
  assign _055_ = rs2_addr == 5'h0d;
  assign _056_ = rs2_addr == 5'h0c;
  assign _057_ = rs2_addr == 5'h0b;
  assign _058_ = rs2_addr == 5'h0a;
  assign _059_ = rs2_addr == 5'h09;
  assign _060_ = rs2_addr == 5'h08;
  assign _061_ = rs2_addr == 5'h07;
  assign _062_ = rs2_addr == 5'h06;
  assign _063_ = rs2_addr == 5'h05;
  assign _064_ = rs2_addr == 5'h04;
  assign _065_ = rs2_addr == 5'h03;
  assign _066_ = rs2_addr == 5'h02;
  assign _067_ = rs2_addr == 5'h01;
  assign _034_ = ! rs2_addr;
  function [31:0] _227_;
    input [31:0] a;
    input [991:0] b;
    input [30:0] s;
    casez (s) // synopsys parallel_case
      31'b??????????????????????????????1:
        _227_ = b[31:0];
      31'b?????????????????????????????1?:
        _227_ = b[63:32];
      31'b????????????????????????????1??:
        _227_ = b[95:64];
      31'b???????????????????????????1???:
        _227_ = b[127:96];
      31'b??????????????????????????1????:
        _227_ = b[159:128];
      31'b?????????????????????????1?????:
        _227_ = b[191:160];
      31'b????????????????????????1??????:
        _227_ = b[223:192];
      31'b???????????????????????1???????:
        _227_ = b[255:224];
      31'b??????????????????????1????????:
        _227_ = b[287:256];
      31'b?????????????????????1?????????:
        _227_ = b[319:288];
      31'b????????????????????1??????????:
        _227_ = b[351:320];
      31'b???????????????????1???????????:
        _227_ = b[383:352];
      31'b??????????????????1????????????:
        _227_ = b[415:384];
      31'b?????????????????1?????????????:
        _227_ = b[447:416];
      31'b????????????????1??????????????:
        _227_ = b[479:448];
      31'b???????????????1???????????????:
        _227_ = b[511:480];
      31'b??????????????1????????????????:
        _227_ = b[543:512];
      31'b?????????????1?????????????????:
        _227_ = b[575:544];
      31'b????????????1??????????????????:
        _227_ = b[607:576];
      31'b???????????1???????????????????:
        _227_ = b[639:608];
      31'b??????????1????????????????????:
        _227_ = b[671:640];
      31'b?????????1?????????????????????:
        _227_ = b[703:672];
      31'b????????1??????????????????????:
        _227_ = b[735:704];
      31'b???????1???????????????????????:
        _227_ = b[767:736];
      31'b??????1????????????????????????:
        _227_ = b[799:768];
      31'b?????1?????????????????????????:
        _227_ = b[831:800];
      31'b????1??????????????????????????:
        _227_ = b[863:832];
      31'b???1???????????????????????????:
        _227_ = b[895:864];
      31'b??1????????????????????????????:
        _227_ = b[927:896];
      31'b?1?????????????????????????????:
        _227_ = b[959:928];
      31'b1??????????????????????????????:
        _227_ = b[991:960];
      default:
        _227_ = a;
    endcase
  endfunction
  assign _000_ = _227_(32'hxxxxxxxx, { \registers[1] , \registers[2] , \registers[3] , \registers[4] , \registers[5] , \registers[6] , \registers[7] , \registers[8] , \registers[9] , \registers[10] , \registers[11] , \registers[12] , \registers[13] , \registers[14] , \registers[15] , \registers[16] , \registers[17] , \registers[18] , \registers[19] , \registers[20] , \registers[21] , \registers[22] , \registers[23] , \registers[24] , \registers[25] , \registers[26] , \registers[27] , \registers[28] , \registers[29] , \registers[30] , \registers[31]  }, { _098_, _097_, _096_, _095_, _094_, _093_, _092_, _091_, _090_, _089_, _088_, _087_, _086_, _085_, _084_, _083_, _082_, _081_, _080_, _079_, _078_, _077_, _076_, _075_, _074_, _073_, _072_, _071_, _070_, _069_, _068_ });
  assign _068_ = rs1_addr == 5'h1f;
  assign _069_ = rs1_addr == 5'h1e;
  assign _070_ = rs1_addr == 5'h1d;
  assign _071_ = rs1_addr == 5'h1c;
  assign _072_ = rs1_addr == 5'h1b;
  assign _073_ = rs1_addr == 5'h1a;
  assign _074_ = rs1_addr == 5'h19;
  assign _075_ = rs1_addr == 5'h18;
  assign _076_ = rs1_addr == 5'h17;
  assign _077_ = rs1_addr == 5'h16;
  assign _078_ = rs1_addr == 5'h15;
  assign _079_ = rs1_addr == 5'h14;
  assign _080_ = rs1_addr == 5'h13;
  assign _081_ = rs1_addr == 5'h12;
  assign _082_ = rs1_addr == 5'h11;
  assign _083_ = rs1_addr == 5'h10;
  assign _084_ = rs1_addr == 5'h0f;
  assign _085_ = rs1_addr == 5'h0e;
  assign _086_ = rs1_addr == 5'h0d;
  assign _087_ = rs1_addr == 5'h0c;
  assign _088_ = rs1_addr == 5'h0b;
  assign _089_ = rs1_addr == 5'h0a;
  assign _090_ = rs1_addr == 5'h09;
  assign _091_ = rs1_addr == 5'h08;
  assign _092_ = rs1_addr == 5'h07;
  assign _093_ = rs1_addr == 5'h06;
  assign _094_ = rs1_addr == 5'h05;
  assign _095_ = rs1_addr == 5'h04;
  assign _096_ = rs1_addr == 5'h03;
  assign _097_ = rs1_addr == 5'h02;
  assign _098_ = rs1_addr == 5'h01;
  assign _033_ = ! rs1_addr;
  assign _099_ = rd_addr == 5'h1f;
  assign _100_ = rd_addr == 5'h1e;
  assign _101_ = rd_addr == 5'h1d;
  assign _102_ = rd_addr == 5'h1c;
  assign _103_ = rd_addr == 5'h1b;
  assign _104_ = rd_addr == 5'h1a;
  assign _105_ = rd_addr == 5'h19;
  assign _106_ = rd_addr == 5'h18;
  assign _107_ = rd_addr == 5'h17;
  assign _108_ = rd_addr == 5'h16;
  assign _109_ = rd_addr == 5'h15;
  assign _110_ = rd_addr == 5'h14;
  assign _111_ = rd_addr == 5'h13;
  assign _112_ = rd_addr == 5'h12;
  assign _113_ = rd_addr == 5'h11;
  assign _114_ = rd_addr == 5'h10;
  assign _115_ = rd_addr == 5'h0f;
  assign _116_ = rd_addr == 5'h0e;
  assign _117_ = rd_addr == 5'h0d;
  assign _118_ = rd_addr == 5'h0c;
  assign _119_ = rd_addr == 5'h0b;
  assign _120_ = rd_addr == 5'h0a;
  assign _121_ = rd_addr == 5'h09;
  assign _122_ = rd_addr == 5'h08;
  assign _123_ = rd_addr == 5'h07;
  assign _124_ = rd_addr == 5'h06;
  assign _125_ = rd_addr == 5'h05;
  assign _126_ = rd_addr == 5'h04;
  assign _127_ = rd_addr == 5'h03;
  assign _128_ = rd_addr == 5'h02;
  assign _129_ = rd_addr == 5'h01;
  assign rs1_data = _033_ ? 32'd0 : _000_;
  assign rs2_data = _034_ ? 32'd0 : _001_;
  assign i = 32'd32;
endmodule
