
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Dec 25 2025 11:39:34 +03 (Dec 25 2025 08:39:34 UTC)

// Verification Directory fv/rv32im_soc_with_integrated_core 

module adc_subsystem_macro(clk, rst_n, wb_adr_i, wb_dat_o, wb_dat_i,
     wb_we_i, wb_sel_i, wb_cyc_i, wb_stb_i, wb_ack_o, wb_err_o,
     adc_data_in, adc_clk_out, ch0_data, ch1_data, ch2_data, ch3_data,
     adc_data_valid, irq, adc_status);
  input clk, rst_n, wb_we_i, wb_cyc_i, wb_stb_i;
  input [31:0] wb_adr_i, wb_dat_i;
  input [3:0] wb_sel_i, adc_data_in;
  output [31:0] wb_dat_o, adc_status;
  output wb_ack_o, wb_err_o, irq;
  output [3:0] adc_clk_out, adc_data_valid;
  output [15:0] ch0_data, ch1_data, ch2_data, ch3_data;
  wire clk, rst_n, wb_we_i, wb_cyc_i, wb_stb_i;
  wire [31:0] wb_adr_i, wb_dat_i;
  wire [3:0] wb_sel_i, adc_data_in;
  wire [31:0] wb_dat_o, adc_status;
  wire wb_ack_o, wb_err_o, irq;
  wire [3:0] adc_clk_out, adc_data_valid;
  wire [15:0] ch0_data, ch1_data, ch2_data, ch3_data;
endmodule

module rv32im_integrated_macro(clk, rst_n, iwb_adr_o, iwb_dat_i,
     iwb_cyc_o, iwb_stb_o, iwb_ack_i, dwb_adr_o, dwb_dat_o, dwb_dat_i,
     dwb_we_o, dwb_sel_o, dwb_cyc_o, dwb_stb_o, dwb_ack_i, dwb_err_i,
     interrupts);
  input clk, rst_n, iwb_ack_i, dwb_ack_i, dwb_err_i;
  input [31:0] iwb_dat_i, dwb_dat_i, interrupts;
  output [31:0] iwb_adr_o, dwb_adr_o, dwb_dat_o;
  output iwb_cyc_o, iwb_stb_o, dwb_we_o, dwb_cyc_o, dwb_stb_o;
  output [3:0] dwb_sel_o;
  wire clk, rst_n, iwb_ack_i, dwb_ack_i, dwb_err_i;
  wire [31:0] iwb_dat_i, dwb_dat_i, interrupts;
  wire [31:0] iwb_adr_o, dwb_adr_o, dwb_dat_o;
  wire iwb_cyc_o, iwb_stb_o, dwb_we_o, dwb_cyc_o, dwb_stb_o;
  wire [3:0] dwb_sel_o;
endmodule

module memory_macro(clk, rst_n, iwb_adr_i, iwb_dat_o, iwb_dat_i,
     iwb_we_i, iwb_sel_i, iwb_cyc_i, iwb_stb_i, iwb_ack_o, iwb_err_o,
     dwb_adr_i, dwb_dat_o, dwb_dat_i, dwb_we_i, dwb_sel_i, dwb_cyc_i,
     dwb_stb_i, dwb_ack_o, dwb_err_o, ext_mem_adr_o, ext_mem_dat_o,
     ext_mem_dat_i, ext_mem_we_o, ext_mem_sel_o, ext_mem_cyc_o,
     ext_mem_stb_o, ext_mem_ack_i, ext_mem_err_i, rom_ready, ram_ready,
     memory_status);
  input clk, rst_n, iwb_we_i, iwb_cyc_i, iwb_stb_i, dwb_we_i,
       dwb_cyc_i, dwb_stb_i, ext_mem_ack_i, ext_mem_err_i;
  input [31:0] iwb_adr_i, iwb_dat_i, dwb_adr_i, dwb_dat_i,
       ext_mem_dat_i;
  input [3:0] iwb_sel_i, dwb_sel_i;
  output [31:0] iwb_dat_o, dwb_dat_o, ext_mem_adr_o, ext_mem_dat_o,
       memory_status;
  output iwb_ack_o, iwb_err_o, dwb_ack_o, dwb_err_o, ext_mem_we_o,
       ext_mem_cyc_o, ext_mem_stb_o, rom_ready, ram_ready;
  output [3:0] ext_mem_sel_o;
  wire clk, rst_n, iwb_we_i, iwb_cyc_i, iwb_stb_i, dwb_we_i, dwb_cyc_i,
       dwb_stb_i, ext_mem_ack_i, ext_mem_err_i;
  wire [31:0] iwb_adr_i, iwb_dat_i, dwb_adr_i, dwb_dat_i, ext_mem_dat_i;
  wire [3:0] iwb_sel_i, dwb_sel_i;
  wire [31:0] iwb_dat_o, dwb_dat_o, ext_mem_adr_o, ext_mem_dat_o,
       memory_status;
  wire iwb_ack_o, iwb_err_o, dwb_ack_o, dwb_err_o, ext_mem_we_o,
       ext_mem_cyc_o, ext_mem_stb_o, rom_ready, ram_ready;
  wire [3:0] ext_mem_sel_o;
endmodule

module protection_macro(clk, rst_n, wb_adr_i, wb_dat_o, wb_dat_i,
     wb_we_i, wb_sel_i, wb_cyc_i, wb_stb_i, wb_ack_o, wb_err_o,
     current_sense, voltage_sense, thermal_alert_in, emergency_stop,
     channel_disable, system_reset, watchdog_kick, watchdog_timeout,
     irq, protection_status);
  input clk, rst_n, wb_we_i, wb_cyc_i, wb_stb_i, thermal_alert_in,
       watchdog_kick;
  input [31:0] wb_adr_i, wb_dat_i;
  input [3:0] wb_sel_i, current_sense, voltage_sense;
  output [31:0] wb_dat_o, protection_status;
  output wb_ack_o, wb_err_o, emergency_stop, system_reset,
       watchdog_timeout, irq;
  output [3:0] channel_disable;
  wire clk, rst_n, wb_we_i, wb_cyc_i, wb_stb_i, thermal_alert_in,
       watchdog_kick;
  wire [31:0] wb_adr_i, wb_dat_i;
  wire [3:0] wb_sel_i, current_sense, voltage_sense;
  wire [31:0] wb_dat_o, protection_status;
  wire wb_ack_o, wb_err_o, emergency_stop, system_reset,
       watchdog_timeout, irq;
  wire [3:0] channel_disable;
endmodule

module pwm_accelerator_macro(clk, rst_n, wb_adr_i, wb_dat_o, wb_dat_i,
     wb_we_i, wb_sel_i, wb_cyc_i, wb_stb_i, wb_ack_o, wb_err_o,
     pwm_out, pwm_out_n, irq, pwm_sync_out, pwm_sync_in, pwm_status);
  input clk, rst_n, wb_we_i, wb_cyc_i, wb_stb_i, pwm_sync_in;
  input [31:0] wb_adr_i, wb_dat_i;
  input [3:0] wb_sel_i;
  output [31:0] wb_dat_o, pwm_status;
  output wb_ack_o, wb_err_o, irq, pwm_sync_out;
  output [7:0] pwm_out, pwm_out_n;
  wire clk, rst_n, wb_we_i, wb_cyc_i, wb_stb_i, pwm_sync_in;
  wire [31:0] wb_adr_i, wb_dat_i;
  wire [3:0] wb_sel_i;
  wire [31:0] wb_dat_o, pwm_status;
  wire wb_ack_o, wb_err_o, irq, pwm_sync_out;
  wire [7:0] pwm_out, pwm_out_n;
endmodule

module rv32im_soc_with_integrated_core(clk, rst_n, ext_mem_adr_o,
     ext_mem_dat_o, ext_mem_dat_i, ext_mem_we_o, ext_mem_sel_o,
     ext_mem_cyc_o, ext_mem_stb_o, ext_mem_ack_i, ext_mem_err_i,
     uart_tx, uart_rx, spi_sclk, spi_mosi, spi_miso, spi_cs_n, gpio,
     pwm_out, pwm_out_n, adc_data_in, adc_clk_out, ch0_data, ch1_data,
     ch2_data, ch3_data, adc_data_valid, current_sense, voltage_sense,
     thermal_alert_in, emergency_stop, channel_disable, system_reset,
     watchdog_timeout, timer_interrupt, timer_compare_out,
     ext_interrupts);
  input clk, rst_n, ext_mem_ack_i, ext_mem_err_i, uart_rx, spi_miso,
       thermal_alert_in;
  input [31:0] ext_mem_dat_i;
  input [3:0] adc_data_in, current_sense, voltage_sense;
  input [7:0] ext_interrupts;
  output [31:0] ext_mem_adr_o, ext_mem_dat_o;
  output ext_mem_we_o, ext_mem_cyc_o, ext_mem_stb_o, uart_tx, spi_sclk,
       spi_mosi, spi_cs_n, emergency_stop, system_reset,
       watchdog_timeout, timer_interrupt;
  output [3:0] ext_mem_sel_o, adc_clk_out, adc_data_valid,
       channel_disable, timer_compare_out;
  output [7:0] pwm_out, pwm_out_n;
  output [15:0] ch0_data, ch1_data, ch2_data, ch3_data;
  inout [15:0] gpio;
  wire clk, rst_n, ext_mem_ack_i, ext_mem_err_i, uart_rx, spi_miso,
       thermal_alert_in;
  wire [31:0] ext_mem_dat_i;
  wire [3:0] adc_data_in, current_sense, voltage_sense;
  wire [7:0] ext_interrupts;
  wire [31:0] ext_mem_adr_o, ext_mem_dat_o;
  wire ext_mem_we_o, ext_mem_cyc_o, ext_mem_stb_o, uart_tx, spi_sclk,
       spi_mosi, spi_cs_n, emergency_stop, system_reset,
       watchdog_timeout, timer_interrupt;
  wire [3:0] ext_mem_sel_o, adc_clk_out, adc_data_valid,
       channel_disable, timer_compare_out;
  wire [7:0] pwm_out, pwm_out_n;
  wire [15:0] ch0_data, ch1_data, ch2_data, ch3_data;
  wire [15:0] gpio;
  wire [31:0] adc_wb_dat_miso;
  wire [31:0] comm_wb_dat_miso;
  wire [31:0] iwb_dat_miso;
  wire [31:0] iwb_adr;
  wire [31:0] dwb_adr;
  wire [31:0] dwb_dat_mosi;
  wire [3:0] dwb_sel;
  wire [31:0] mem_wb_dat_miso;
  wire [31:0] prot_wb_dat_miso;
  wire [31:0] pwm_wb_dat_miso;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, UNCONNECTED69, UNCONNECTED70;
  wire UNCONNECTED71, UNCONNECTED72, UNCONNECTED73, UNCONNECTED74,
       UNCONNECTED75, UNCONNECTED76, UNCONNECTED77, UNCONNECTED78;
  wire UNCONNECTED79, UNCONNECTED80, UNCONNECTED81, UNCONNECTED82,
       UNCONNECTED83, UNCONNECTED84, UNCONNECTED85, UNCONNECTED86;
  wire UNCONNECTED87, UNCONNECTED88, UNCONNECTED89, UNCONNECTED90,
       UNCONNECTED91, UNCONNECTED92, UNCONNECTED93, UNCONNECTED94;
  wire UNCONNECTED95, UNCONNECTED96, UNCONNECTED97, UNCONNECTED98,
       UNCONNECTED99, UNCONNECTED100, UNCONNECTED101, UNCONNECTED102;
  wire UNCONNECTED103, UNCONNECTED104, UNCONNECTED105, UNCONNECTED106,
       UNCONNECTED107, UNCONNECTED108, UNCONNECTED109, UNCONNECTED110;
  wire UNCONNECTED111, UNCONNECTED112, UNCONNECTED113, UNCONNECTED114,
       UNCONNECTED115, UNCONNECTED116, UNCONNECTED117, UNCONNECTED118;
  wire UNCONNECTED119, UNCONNECTED120, UNCONNECTED121, UNCONNECTED122,
       UNCONNECTED123, UNCONNECTED124, UNCONNECTED125, UNCONNECTED126;
  wire UNCONNECTED127, UNCONNECTED128, UNCONNECTED129, UNCONNECTED130,
       UNCONNECTED131, UNCONNECTED132, UNCONNECTED133, UNCONNECTED134;
  wire UNCONNECTED135, UNCONNECTED136, UNCONNECTED137, UNCONNECTED138,
       UNCONNECTED139, UNCONNECTED140, UNCONNECTED141, UNCONNECTED142;
  wire UNCONNECTED143, UNCONNECTED144, UNCONNECTED145, UNCONNECTED146,
       UNCONNECTED147, UNCONNECTED148, UNCONNECTED149, UNCONNECTED150;
  wire UNCONNECTED151, UNCONNECTED152, UNCONNECTED153, UNCONNECTED154,
       UNCONNECTED155, UNCONNECTED156, UNCONNECTED157, UNCONNECTED158;
  wire UNCONNECTED159, UNCONNECTED160, UNCONNECTED161, UNCONNECTED162,
       UNCONNECTED163, UNCONNECTED164, UNCONNECTED165, UNCONNECTED166;
  wire UNCONNECTED167, UNCONNECTED168, UNCONNECTED169, UNCONNECTED170,
       UNCONNECTED171, UNCONNECTED172, UNCONNECTED173, UNCONNECTED174;
  wire UNCONNECTED175, UNCONNECTED176, UNCONNECTED177, UNCONNECTED178,
       UNCONNECTED179, UNCONNECTED180, UNCONNECTED181, UNCONNECTED182;
  wire UNCONNECTED183, UNCONNECTED184, UNCONNECTED185, UNCONNECTED186,
       UNCONNECTED187, UNCONNECTED188, UNCONNECTED189, UNCONNECTED190;
  wire UNCONNECTED191, UNCONNECTED192, UNCONNECTED193, UNCONNECTED194,
       UNCONNECTED195, UNCONNECTED196, UNCONNECTED197, UNCONNECTED198;
  wire UNCONNECTED199, UNCONNECTED200, UNCONNECTED201, adc_irq,
       adc_sel, adc_wb_ack, adc_wb_err, comm_irq;
  wire comm_sel, comm_wb_ack, comm_wb_err, dwb_cyc, dwb_stb, dwb_we,
       iwb_ack, iwb_cyc;
  wire iwb_stb, mem_wb_ack, mem_wb_err, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_318, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_352;
  wire n_353, n_354, n_355, n_356, n_357, n_358, n_359, n_360;
  wire n_361, n_362, n_363, n_364, n_365, n_366, n_367, n_368;
  wire n_369, n_370, n_375, n_376, n_377, n_378, n_379, n_380;
  wire n_381, n_382, n_383, n_384, n_385, n_386, n_387, n_388;
  wire n_389, n_390, n_391, n_392, n_393, n_394, n_395, n_396;
  wire n_397, n_398, n_399, n_400, n_401, n_402, n_403, n_404;
  wire n_405, n_406, n_407, n_408, n_409, n_410, n_411, n_412;
  wire n_413, n_414, n_415, n_416, n_417, n_418, n_419, n_420;
  wire n_421, n_422, n_423, n_424, n_425, n_426, n_427, n_428;
  wire n_429, n_430, n_431, n_432, n_433, n_434, n_435, n_436;
  wire n_437, n_438, n_439, n_440, n_441, n_442, n_443, n_444;
  wire n_445, n_446, n_447, n_448, n_449, n_450, n_451, n_452;
  wire n_453, n_454, n_455, n_456, n_457, n_458, n_459, n_460;
  wire n_461, n_462, n_463, n_464, n_465, n_466, n_467, n_468;
  wire n_469, n_470, n_471, n_472, n_473, n_474, n_475, n_476;
  wire n_477, n_478, n_479, n_480, n_481, n_482, n_483, n_484;
  wire n_485, n_486, n_487, n_488, n_489, n_490, n_491, n_492;
  wire n_493, n_494, n_495, n_496, n_497, n_498, n_499, n_500;
  wire n_501, n_502, n_503, n_504, n_505, n_506, n_507, n_508;
  wire n_509, n_510, n_511, n_512, n_513, n_514, n_515, n_516;
  wire n_517, n_518, n_519, n_520, n_521, n_522, n_523, n_524;
  wire n_525, n_526, n_527, n_528, n_529, n_530, n_531, n_532;
  wire n_533, n_534, n_535, n_536, n_537, n_538, n_539, n_540;
  wire n_541, n_542, n_543, n_544, n_545, n_546, n_547, n_548;
  wire n_549, n_550, n_551, n_552, n_553, n_554, n_555, n_556;
  wire n_557, n_558, n_559, n_560, n_561, n_562, n_563, n_564;
  wire n_565, n_566, n_567, n_568, n_569, n_570, n_571, n_572;
  wire n_573, n_574, n_575, n_576, n_577, n_578, n_579, n_580;
  wire n_581, n_582, n_583, prot_irq, prot_sel, prot_wb_ack,
       prot_wb_err, pwm_irq;
  wire pwm_wb_ack, pwm_wb_err;
  assign timer_compare_out[0] = 1'b0;
  assign timer_compare_out[1] = 1'b0;
  assign timer_compare_out[2] = 1'b0;
  assign timer_compare_out[3] = 1'b0;
  assign timer_interrupt = 1'b0;
  assign ext_mem_stb_o = 1'b0;
  assign ext_mem_cyc_o = 1'b0;
  assign ext_mem_sel_o[0] = 1'b0;
  assign ext_mem_sel_o[1] = 1'b0;
  assign ext_mem_sel_o[2] = 1'b0;
  assign ext_mem_sel_o[3] = 1'b0;
  assign ext_mem_we_o = 1'b0;
  assign ext_mem_dat_o[0] = 1'b0;
  assign ext_mem_dat_o[1] = 1'b0;
  assign ext_mem_dat_o[2] = 1'b0;
  assign ext_mem_dat_o[3] = 1'b0;
  assign ext_mem_dat_o[4] = 1'b0;
  assign ext_mem_dat_o[5] = 1'b0;
  assign ext_mem_dat_o[6] = 1'b0;
  assign ext_mem_dat_o[7] = 1'b0;
  assign ext_mem_dat_o[8] = 1'b0;
  assign ext_mem_dat_o[9] = 1'b0;
  assign ext_mem_dat_o[10] = 1'b0;
  assign ext_mem_dat_o[11] = 1'b0;
  assign ext_mem_dat_o[12] = 1'b0;
  assign ext_mem_dat_o[13] = 1'b0;
  assign ext_mem_dat_o[14] = 1'b0;
  assign ext_mem_dat_o[15] = 1'b0;
  assign ext_mem_dat_o[16] = 1'b0;
  assign ext_mem_dat_o[17] = 1'b0;
  assign ext_mem_dat_o[18] = 1'b0;
  assign ext_mem_dat_o[19] = 1'b0;
  assign ext_mem_dat_o[20] = 1'b0;
  assign ext_mem_dat_o[21] = 1'b0;
  assign ext_mem_dat_o[22] = 1'b0;
  assign ext_mem_dat_o[23] = 1'b0;
  assign ext_mem_dat_o[24] = 1'b0;
  assign ext_mem_dat_o[25] = 1'b0;
  assign ext_mem_dat_o[26] = 1'b0;
  assign ext_mem_dat_o[27] = 1'b0;
  assign ext_mem_dat_o[28] = 1'b0;
  assign ext_mem_dat_o[29] = 1'b0;
  assign ext_mem_dat_o[30] = 1'b0;
  assign ext_mem_dat_o[31] = 1'b0;
  assign ext_mem_adr_o[0] = 1'b0;
  assign ext_mem_adr_o[1] = 1'b0;
  assign ext_mem_adr_o[2] = 1'b0;
  assign ext_mem_adr_o[3] = 1'b0;
  assign ext_mem_adr_o[4] = 1'b0;
  assign ext_mem_adr_o[5] = 1'b0;
  assign ext_mem_adr_o[6] = 1'b0;
  assign ext_mem_adr_o[7] = 1'b0;
  assign ext_mem_adr_o[8] = 1'b0;
  assign ext_mem_adr_o[9] = 1'b0;
  assign ext_mem_adr_o[10] = 1'b0;
  assign ext_mem_adr_o[11] = 1'b0;
  assign ext_mem_adr_o[12] = 1'b0;
  assign ext_mem_adr_o[13] = 1'b0;
  assign ext_mem_adr_o[14] = 1'b0;
  assign ext_mem_adr_o[15] = 1'b0;
  assign ext_mem_adr_o[16] = 1'b0;
  assign ext_mem_adr_o[17] = 1'b0;
  assign ext_mem_adr_o[18] = 1'b0;
  assign ext_mem_adr_o[19] = 1'b0;
  assign ext_mem_adr_o[20] = 1'b0;
  assign ext_mem_adr_o[21] = 1'b0;
  assign ext_mem_adr_o[22] = 1'b0;
  assign ext_mem_adr_o[23] = 1'b0;
  assign ext_mem_adr_o[24] = 1'b0;
  assign ext_mem_adr_o[25] = 1'b0;
  assign ext_mem_adr_o[26] = 1'b0;
  assign ext_mem_adr_o[27] = 1'b0;
  assign ext_mem_adr_o[28] = 1'b0;
  assign ext_mem_adr_o[29] = 1'b0;
  assign ext_mem_adr_o[30] = 1'b0;
  assign ext_mem_adr_o[31] = 1'b0;
  adc_subsystem_macro u_adc(.clk (clk), .rst_n (rst_n), .wb_adr_i
       ({16'b0, n_412, n_413, n_414, n_415, n_416, n_417, n_418, n_419,
       n_420, n_421, n_422, n_423, n_424, n_425, n_426, n_427}),
       .wb_dat_o (adc_wb_dat_miso), .wb_dat_i ({n_380, n_381, n_382,
       n_383, n_384, n_385, n_386, n_387, n_388, n_389, n_390, n_391,
       n_392, n_393, n_394, n_395, n_396, n_397, n_398, n_399, n_400,
       n_401, n_402, n_403, n_404, n_405, n_406, n_407, n_408, n_409,
       n_410, n_411}), .wb_we_i (n_379), .wb_sel_i ({n_375, n_376,
       n_377, n_378}), .wb_cyc_i (adc_sel), .wb_stb_i (adc_sel),
       .wb_ack_o (adc_wb_ack), .wb_err_o (adc_wb_err), .adc_data_in
       (adc_data_in), .adc_clk_out (adc_clk_out), .ch0_data (ch0_data),
       .ch1_data (ch1_data), .ch2_data (ch2_data), .ch3_data
       (ch3_data), .adc_data_valid (adc_data_valid), .irq (adc_irq),
       .adc_status ({UNCONNECTED30, UNCONNECTED29, UNCONNECTED28,
       UNCONNECTED27, UNCONNECTED26, UNCONNECTED25, UNCONNECTED24,
       UNCONNECTED23, UNCONNECTED22, UNCONNECTED21, UNCONNECTED20,
       UNCONNECTED19, UNCONNECTED18, UNCONNECTED17, UNCONNECTED16,
       UNCONNECTED15, UNCONNECTED14, UNCONNECTED13, UNCONNECTED12,
       UNCONNECTED11, UNCONNECTED10, UNCONNECTED9, UNCONNECTED8,
       UNCONNECTED7, UNCONNECTED6, UNCONNECTED5, UNCONNECTED4,
       UNCONNECTED3, UNCONNECTED2, UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED}));
  communication_macro u_communication(.clk (clk), .rst_n (rst_n),
       .wb_adr_i ({n_211, n_210, n_209, n_208, n_207, n_206, n_205,
       n_204, n_203, n_202, n_201, n_200, n_199, n_198, n_197, n_196}),
       .wb_dat_o (comm_wb_dat_miso), .wb_dat_i ({n_195, n_194, n_193,
       n_192, n_191, n_190, n_189, n_188, n_187, n_186, n_185, n_184,
       n_183, n_182, n_181, n_180, n_179, n_178, n_177, n_176, n_175,
       n_174, n_173, n_172, n_171, n_170, n_169, n_168, n_167, n_166,
       n_165, n_164}), .wb_we_i (n_163), .wb_sel_i ({n_162, n_161,
       n_160, n_159}), .wb_cyc_i (comm_sel), .wb_stb_i (comm_sel),
       .wb_ack_o (comm_wb_ack), .wb_err_o (comm_wb_err), .uart_tx
       (uart_tx), .uart_rx (uart_rx), .spi_sclk (spi_sclk), .spi_mosi
       (spi_mosi), .spi_miso (spi_miso), .spi_cs_n (spi_cs_n), .gpio
       (gpio), .irq (comm_irq));
  rv32im_integrated_macro u_cpu_core(.clk (clk), .rst_n (n_583),
       .iwb_adr_o (iwb_adr), .iwb_dat_i (iwb_dat_miso), .iwb_cyc_o
       (iwb_cyc), .iwb_stb_o (iwb_stb), .iwb_ack_i (iwb_ack),
       .dwb_adr_o (dwb_adr), .dwb_dat_o (dwb_dat_mosi), .dwb_dat_i
       ({n_551, n_552, n_553, n_554, n_555, n_556, n_557, n_558, n_559,
       n_560, n_561, n_562, n_563, n_564, n_565, n_566, n_567, n_568,
       n_569, n_570, n_571, n_572, n_573, n_574, n_575, n_576, n_577,
       n_578, n_579, n_580, n_581, n_582}), .dwb_we_o (dwb_we),
       .dwb_sel_o (dwb_sel), .dwb_cyc_o (dwb_cyc), .dwb_stb_o
       (dwb_stb), .dwb_ack_i (n_550), .dwb_err_i (n_549), .interrupts
       ({16'b0, ext_interrupts, 1'b0, emergency_stop, watchdog_timeout,
       prot_irq, adc_irq, pwm_irq, 1'b0, comm_irq}));
  memory_macro u_memory(.clk (clk), .rst_n (rst_n), .iwb_adr_i
       (iwb_adr), .iwb_dat_o (iwb_dat_miso), .iwb_dat_i (32'b0),
       .iwb_we_i (1'b0), .iwb_sel_i (4'b1111), .iwb_cyc_i (iwb_cyc),
       .iwb_stb_i (iwb_stb), .iwb_ack_o (iwb_ack), .iwb_err_o
       (UNCONNECTED31), .dwb_adr_i ({3'b0, n_520, n_521, n_522, n_523,
       n_524, n_525, n_526, n_527, n_528, n_529, n_530, n_531, n_532,
       n_533, n_534, n_535, n_536, n_537, n_538, n_539, n_540, n_541,
       n_542, n_543, n_544, n_545, n_546, n_547, n_548}), .dwb_dat_o
       (mem_wb_dat_miso), .dwb_dat_i ({n_488, n_489, n_490, n_491,
       n_492, n_493, n_494, n_495, n_496, n_497, n_498, n_499, n_500,
       n_501, n_502, n_503, n_504, n_505, n_506, n_507, n_508, n_509,
       n_510, n_511, n_512, n_513, n_514, n_515, n_516, n_517, n_518,
       n_519}), .dwb_we_i (n_487), .dwb_sel_i ({n_483, n_484, n_485,
       n_486}), .dwb_cyc_i (n_482), .dwb_stb_i (n_482), .dwb_ack_o
       (mem_wb_ack), .dwb_err_o (mem_wb_err), .ext_mem_adr_o
       ({UNCONNECTED63, UNCONNECTED62, UNCONNECTED61, UNCONNECTED60,
       UNCONNECTED59, UNCONNECTED58, UNCONNECTED57, UNCONNECTED56,
       UNCONNECTED55, UNCONNECTED54, UNCONNECTED53, UNCONNECTED52,
       UNCONNECTED51, UNCONNECTED50, UNCONNECTED49, UNCONNECTED48,
       UNCONNECTED47, UNCONNECTED46, UNCONNECTED45, UNCONNECTED44,
       UNCONNECTED43, UNCONNECTED42, UNCONNECTED41, UNCONNECTED40,
       UNCONNECTED39, UNCONNECTED38, UNCONNECTED37, UNCONNECTED36,
       UNCONNECTED35, UNCONNECTED34, UNCONNECTED33, UNCONNECTED32}),
       .ext_mem_dat_o ({UNCONNECTED95, UNCONNECTED94, UNCONNECTED93,
       UNCONNECTED92, UNCONNECTED91, UNCONNECTED90, UNCONNECTED89,
       UNCONNECTED88, UNCONNECTED87, UNCONNECTED86, UNCONNECTED85,
       UNCONNECTED84, UNCONNECTED83, UNCONNECTED82, UNCONNECTED81,
       UNCONNECTED80, UNCONNECTED79, UNCONNECTED78, UNCONNECTED77,
       UNCONNECTED76, UNCONNECTED75, UNCONNECTED74, UNCONNECTED73,
       UNCONNECTED72, UNCONNECTED71, UNCONNECTED70, UNCONNECTED69,
       UNCONNECTED68, UNCONNECTED67, UNCONNECTED66, UNCONNECTED65,
       UNCONNECTED64}), .ext_mem_dat_i (32'b0), .ext_mem_we_o
       (UNCONNECTED96), .ext_mem_sel_o ({UNCONNECTED100, UNCONNECTED99,
       UNCONNECTED98, UNCONNECTED97}), .ext_mem_cyc_o (UNCONNECTED101),
       .ext_mem_stb_o (UNCONNECTED102), .ext_mem_ack_i (1'b0),
       .ext_mem_err_i (1'b0), .rom_ready (UNCONNECTED103), .ram_ready
       (UNCONNECTED104), .memory_status ({UNCONNECTED136,
       UNCONNECTED135, UNCONNECTED134, UNCONNECTED133, UNCONNECTED132,
       UNCONNECTED131, UNCONNECTED130, UNCONNECTED129, UNCONNECTED128,
       UNCONNECTED127, UNCONNECTED126, UNCONNECTED125, UNCONNECTED124,
       UNCONNECTED123, UNCONNECTED122, UNCONNECTED121, UNCONNECTED120,
       UNCONNECTED119, UNCONNECTED118, UNCONNECTED117, UNCONNECTED116,
       UNCONNECTED115, UNCONNECTED114, UNCONNECTED113, UNCONNECTED112,
       UNCONNECTED111, UNCONNECTED110, UNCONNECTED109, UNCONNECTED108,
       UNCONNECTED107, UNCONNECTED106, UNCONNECTED105}));
  protection_macro u_protection(.clk (clk), .rst_n (rst_n), .wb_adr_i
       ({16'b0, n_355, n_356, n_357, n_358, n_359, n_360, n_361, n_362,
       n_363, n_364, n_365, n_366, n_367, n_368, n_369, n_370}),
       .wb_dat_o (prot_wb_dat_miso), .wb_dat_i ({n_323, n_324, n_325,
       n_326, n_327, n_328, n_329, n_330, n_331, n_332, n_333, n_334,
       n_335, n_336, n_337, n_338, n_339, n_340, n_341, n_342, n_343,
       n_344, n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_352,
       n_353, n_354}), .wb_we_i (n_322), .wb_sel_i ({n_318, n_319,
       n_320, n_321}), .wb_cyc_i (prot_sel), .wb_stb_i (prot_sel),
       .wb_ack_o (prot_wb_ack), .wb_err_o (prot_wb_err), .current_sense
       (current_sense), .voltage_sense (voltage_sense),
       .thermal_alert_in (thermal_alert_in), .emergency_stop
       (emergency_stop), .channel_disable (channel_disable),
       .system_reset (system_reset), .watchdog_kick (1'b0),
       .watchdog_timeout (watchdog_timeout), .irq (prot_irq),
       .protection_status ({UNCONNECTED168, UNCONNECTED167,
       UNCONNECTED166, UNCONNECTED165, UNCONNECTED164, UNCONNECTED163,
       UNCONNECTED162, UNCONNECTED161, UNCONNECTED160, UNCONNECTED159,
       UNCONNECTED158, UNCONNECTED157, UNCONNECTED156, UNCONNECTED155,
       UNCONNECTED154, UNCONNECTED153, UNCONNECTED152, UNCONNECTED151,
       UNCONNECTED150, UNCONNECTED149, UNCONNECTED148, UNCONNECTED147,
       UNCONNECTED146, UNCONNECTED145, UNCONNECTED144, UNCONNECTED143,
       UNCONNECTED142, UNCONNECTED141, UNCONNECTED140, UNCONNECTED139,
       UNCONNECTED138, UNCONNECTED137}));
  pwm_accelerator_macro u_pwm(.clk (clk), .rst_n (rst_n), .wb_adr_i
       ({16'b0, n_466, n_467, n_468, n_469, n_470, n_471, n_472, n_473,
       n_474, n_475, n_476, n_477, n_478, n_479, n_480, n_481}),
       .wb_dat_o (pwm_wb_dat_miso), .wb_dat_i ({n_434, n_435, n_436,
       n_437, n_438, n_439, n_440, n_441, n_442, n_443, n_444, n_445,
       n_446, n_447, n_448, n_449, n_450, n_451, n_452, n_453, n_454,
       n_455, n_456, n_457, n_458, n_459, n_460, n_461, n_462, n_463,
       n_464, n_465}), .wb_we_i (n_433), .wb_sel_i ({n_429, n_430,
       n_431, n_432}), .wb_cyc_i (n_428), .wb_stb_i (n_428), .wb_ack_o
       (pwm_wb_ack), .wb_err_o (pwm_wb_err), .pwm_out (pwm_out),
       .pwm_out_n (pwm_out_n), .irq (pwm_irq), .pwm_sync_out
       (UNCONNECTED169), .pwm_sync_in (1'b0), .pwm_status
       ({UNCONNECTED201, UNCONNECTED200, UNCONNECTED199,
       UNCONNECTED198, UNCONNECTED197, UNCONNECTED196, UNCONNECTED195,
       UNCONNECTED194, UNCONNECTED193, UNCONNECTED192, UNCONNECTED191,
       UNCONNECTED190, UNCONNECTED189, UNCONNECTED188, UNCONNECTED187,
       UNCONNECTED186, UNCONNECTED185, UNCONNECTED184, UNCONNECTED183,
       UNCONNECTED182, UNCONNECTED181, UNCONNECTED180, UNCONNECTED179,
       UNCONNECTED178, UNCONNECTED177, UNCONNECTED176, UNCONNECTED175,
       UNCONNECTED174, UNCONNECTED173, UNCONNECTED172, UNCONNECTED171,
       UNCONNECTED170}));
  sky130_osu_sc_18T_ms__nand2_l g7283__2398(.A (n_128), .B (n_76), .Y
       (n_560));
  sky130_osu_sc_18T_ms__nand2_l g7284__5107(.A (n_130), .B (n_89), .Y
       (n_569));
  sky130_osu_sc_18T_ms__nand2_l g7285__6260(.A (n_124), .B (n_31), .Y
       (n_564));
  sky130_osu_sc_18T_ms__nand2_l g7286__4319(.A (n_125), .B (n_41), .Y
       (n_578));
  sky130_osu_sc_18T_ms__nand2_l g7287__8428(.A (n_123), .B (n_26), .Y
       (n_582));
  sky130_osu_sc_18T_ms__nand2_l g7288__5526(.A (n_131), .B (n_86), .Y
       (n_549));
  sky130_osu_sc_18T_ms__nand2_l g7289__6783(.A (n_129), .B (n_87), .Y
       (n_570));
  sky130_osu_sc_18T_ms__nand2_l g7290__3680(.A (n_126), .B (n_48), .Y
       (n_576));
  sky130_osu_sc_18T_ms__nand2_l g7291__1617(.A (n_127), .B (n_51), .Y
       (n_561));
  sky130_osu_sc_18T_ms__nand2_l g7292__2802(.A (n_132), .B (n_21), .Y
       (n_556));
  sky130_osu_sc_18T_ms__nand2_l g7293__1705(.A (n_154), .B (n_100), .Y
       (n_566));
  sky130_osu_sc_18T_ms__nand2_l g7294__5122(.A (n_153), .B (n_97), .Y
       (n_567));
  sky130_osu_sc_18T_ms__nand2_l g7295__8246(.A (n_151), .B (n_96), .Y
       (n_557));
  sky130_osu_sc_18T_ms__nand2_l g7296__7098(.A (n_152), .B (n_94), .Y
       (n_568));
  sky130_osu_sc_18T_ms__nand2_l g7297__6131(.A (n_150), .B (n_90), .Y
       (n_558));
  sky130_osu_sc_18T_ms__nand2_l g7298__1881(.A (n_156), .B (n_98), .Y
       (n_552));
  sky130_osu_sc_18T_ms__nand2_l g7299__5115(.A (n_148), .B (n_82), .Y
       (n_559));
  sky130_osu_sc_18T_ms__nand2_l g7300__7482(.A (n_149), .B (n_83), .Y
       (n_571));
  sky130_osu_sc_18T_ms__nand2_l g7301__4733(.A (n_147), .B (n_79), .Y
       (n_572));
  sky130_osu_sc_18T_ms__nand2_l g7302__6161(.A (n_146), .B (n_80), .Y
       (n_553));
  sky130_osu_sc_18T_ms__nand2_l g7303__9315(.A (n_145), .B (n_75), .Y
       (n_573));
  sky130_osu_sc_18T_ms__nand2_l g7304__9945(.A (n_144), .B (n_71), .Y
       (n_574));
  sky130_osu_sc_18T_ms__nand2_l g7305__2883(.A (n_142), .B (n_52), .Y
       (n_575));
  sky130_osu_sc_18T_ms__nand2_l g7306__2346(.A (n_143), .B (n_53), .Y
       (n_554));
  sky130_osu_sc_18T_ms__nand2_l g7307__1666(.A (n_141), .B (n_45), .Y
       (n_562));
  sky130_osu_sc_18T_ms__nand2_l g7308__7410(.A (n_140), .B (n_44), .Y
       (n_577));
  sky130_osu_sc_18T_ms__nand2_l g7309__6417(.A (n_136), .B (n_32), .Y
       (n_555));
  sky130_osu_sc_18T_ms__nand2_l g7310__5477(.A (n_138), .B (n_36), .Y
       (n_563));
  sky130_osu_sc_18T_ms__nand2_l g7311__2398(.A (n_139), .B (n_38), .Y
       (n_579));
  sky130_osu_sc_18T_ms__nand2_l g7312__5107(.A (n_134), .B (n_24), .Y
       (n_551));
  sky130_osu_sc_18T_ms__nand2_l g7313__6260(.A (n_137), .B (n_35), .Y
       (n_580));
  sky130_osu_sc_18T_ms__nand2_l g7314__4319(.A (n_135), .B (n_30), .Y
       (n_581));
  sky130_osu_sc_18T_ms__nand2_l g7315__8428(.A (n_155), .B (n_23), .Y
       (n_565));
  sky130_osu_sc_18T_ms__nand2_l g7316__5526(.A (n_133), .B (n_22), .Y
       (n_550));
  sky130_osu_sc_18T_ms__aoi21_l g7317__6783(.A0 (prot_wb_dat_miso[30]),
       .A1 (prot_sel), .B0 (n_114), .Y (n_156));
  sky130_osu_sc_18T_ms__aoi21_l g7318__3680(.A0 (prot_wb_dat_miso[17]),
       .A1 (prot_sel), .B0 (n_120), .Y (n_155));
  sky130_osu_sc_18T_ms__aoi21_l g7319__1617(.A0 (prot_wb_dat_miso[16]),
       .A1 (prot_sel), .B0 (n_118), .Y (n_154));
  sky130_osu_sc_18T_ms__aoi21_l g7320__2802(.A0 (prot_wb_dat_miso[15]),
       .A1 (prot_sel), .B0 (n_117), .Y (n_153));
  sky130_osu_sc_18T_ms__aoi21_l g7321__1705(.A0 (prot_wb_dat_miso[14]),
       .A1 (prot_sel), .B0 (n_115), .Y (n_152));
  sky130_osu_sc_18T_ms__aoi21_l g7322__5122(.A0 (prot_wb_dat_miso[25]),
       .A1 (prot_sel), .B0 (n_116), .Y (n_151));
  sky130_osu_sc_18T_ms__aoi21_l g7323__8246(.A0 (prot_wb_dat_miso[24]),
       .A1 (prot_sel), .B0 (n_111), .Y (n_150));
  sky130_osu_sc_18T_ms__aoi21_l g7324__7098(.A0 (pwm_wb_dat_miso[11]),
       .A1 (n_428), .B0 (n_110), .Y (n_149));
  sky130_osu_sc_18T_ms__aoi21_l g7325__6131(.A0 (pwm_wb_dat_miso[23]),
       .A1 (n_428), .B0 (n_108), .Y (n_148));
  sky130_osu_sc_18T_ms__aoi21_l g7326__1881(.A0 (pwm_wb_dat_miso[10]),
       .A1 (n_428), .B0 (n_109), .Y (n_147));
  sky130_osu_sc_18T_ms__aoi21_l g7327__5115(.A0 (pwm_wb_dat_miso[29]),
       .A1 (n_428), .B0 (n_107), .Y (n_146));
  sky130_osu_sc_18T_ms__aoi21_l g7328__7482(.A0 (pwm_wb_dat_miso[9]),
       .A1 (n_428), .B0 (n_106), .Y (n_145));
  sky130_osu_sc_18T_ms__aoi21_l g7329__4733(.A0 (pwm_wb_dat_miso[8]),
       .A1 (n_428), .B0 (n_70), .Y (n_144));
  sky130_osu_sc_18T_ms__aoi21_l g7330__6161(.A0 (prot_wb_dat_miso[28]),
       .A1 (prot_sel), .B0 (n_62), .Y (n_143));
  sky130_osu_sc_18T_ms__aoi21_l g7331__9315(.A0 (prot_wb_dat_miso[7]),
       .A1 (prot_sel), .B0 (n_69), .Y (n_142));
  sky130_osu_sc_18T_ms__aoi21_l g7332__9945(.A0 (prot_wb_dat_miso[20]),
       .A1 (prot_sel), .B0 (n_64), .Y (n_141));
  sky130_osu_sc_18T_ms__aoi21_l g7333__2883(.A0 (prot_wb_dat_miso[5]),
       .A1 (prot_sel), .B0 (n_65), .Y (n_140));
  sky130_osu_sc_18T_ms__aoi21_l g7334__2346(.A0 (prot_wb_dat_miso[3]),
       .A1 (prot_sel), .B0 (n_61), .Y (n_139));
  sky130_osu_sc_18T_ms__aoi21_l g7335__1666(.A0 (pwm_wb_dat_miso[19]),
       .A1 (n_428), .B0 (n_60), .Y (n_138));
  sky130_osu_sc_18T_ms__aoi21_l g7336__7410(.A0 (prot_wb_dat_miso[2]),
       .A1 (prot_sel), .B0 (n_59), .Y (n_137));
  sky130_osu_sc_18T_ms__aoi21_l g7337__6417(.A0 (prot_wb_dat_miso[27]),
       .A1 (prot_sel), .B0 (n_58), .Y (n_136));
  sky130_osu_sc_18T_ms__aoi21_l g7338__5477(.A0 (pwm_wb_dat_miso[1]),
       .A1 (n_428), .B0 (n_57), .Y (n_135));
  sky130_osu_sc_18T_ms__aoi21_l g7339__2398(.A0 (pwm_wb_dat_miso[31]),
       .A1 (n_428), .B0 (n_122), .Y (n_134));
  sky130_osu_sc_18T_ms__aoi21_l g7340__5107(.A0 (prot_wb_ack), .A1
       (prot_sel), .B0 (n_121), .Y (n_133));
  sky130_osu_sc_18T_ms__aoi21_l g7341__6260(.A0 (comm_wb_dat_miso[26]),
       .A1 (comm_sel), .B0 (n_119), .Y (n_132));
  sky130_osu_sc_18T_ms__aoi21_l g7342__4319(.A0 (comm_wb_err), .A1
       (comm_sel), .B0 (n_68), .Y (n_131));
  sky130_osu_sc_18T_ms__aoi21_l g7343__8428(.A0 (adc_wb_dat_miso[13]),
       .A1 (adc_sel), .B0 (n_113), .Y (n_130));
  sky130_osu_sc_18T_ms__aoi21_l g7344__5526(.A0 (comm_wb_dat_miso[12]),
       .A1 (comm_sel), .B0 (n_112), .Y (n_129));
  sky130_osu_sc_18T_ms__aoi21_l g7345__6783(.A0 (adc_wb_dat_miso[22]),
       .A1 (adc_sel), .B0 (n_105), .Y (n_128));
  sky130_osu_sc_18T_ms__aoi21_l g7346__3680(.A0 (comm_wb_dat_miso[21]),
       .A1 (comm_sel), .B0 (n_67), .Y (n_127));
  sky130_osu_sc_18T_ms__aoi21_l g7347__1617(.A0 (comm_wb_dat_miso[6]),
       .A1 (comm_sel), .B0 (n_66), .Y (n_126));
  sky130_osu_sc_18T_ms__aoi21_l g7348__2802(.A0 (adc_wb_dat_miso[4]),
       .A1 (adc_sel), .B0 (n_63), .Y (n_125));
  sky130_osu_sc_18T_ms__aoi21_l g7349__1705(.A0 (adc_wb_dat_miso[18]),
       .A1 (adc_sel), .B0 (n_56), .Y (n_124));
  sky130_osu_sc_18T_ms__aoi21_l g7350__5122(.A0 (adc_wb_dat_miso[0]),
       .A1 (adc_sel), .B0 (n_55), .Y (n_123));
  sky130_osu_sc_18T_ms__inv_1 g7351(.A (n_104), .Y (n_122));
  sky130_osu_sc_18T_ms__inv_1 g7352(.A (n_103), .Y (n_121));
  sky130_osu_sc_18T_ms__inv_1 g7353(.A (n_102), .Y (n_120));
  sky130_osu_sc_18T_ms__inv_1 g7354(.A (n_101), .Y (n_119));
  sky130_osu_sc_18T_ms__inv_1 g7355(.A (n_99), .Y (n_118));
  sky130_osu_sc_18T_ms__inv_1 g7356(.A (n_95), .Y (n_117));
  sky130_osu_sc_18T_ms__inv_1 g7357(.A (n_93), .Y (n_116));
  sky130_osu_sc_18T_ms__inv_1 g7358(.A (n_92), .Y (n_115));
  sky130_osu_sc_18T_ms__inv_1 g7359(.A (n_91), .Y (n_114));
  sky130_osu_sc_18T_ms__inv_1 g7360(.A (n_88), .Y (n_113));
  sky130_osu_sc_18T_ms__inv_1 g7361(.A (n_85), .Y (n_112));
  sky130_osu_sc_18T_ms__inv_1 g7362(.A (n_84), .Y (n_111));
  sky130_osu_sc_18T_ms__inv_1 g7363(.A (n_81), .Y (n_110));
  sky130_osu_sc_18T_ms__inv_1 g7364(.A (n_78), .Y (n_109));
  sky130_osu_sc_18T_ms__inv_1 g7365(.A (n_77), .Y (n_108));
  sky130_osu_sc_18T_ms__inv_1 g7366(.A (n_74), .Y (n_107));
  sky130_osu_sc_18T_ms__inv_1 g7367(.A (n_73), .Y (n_106));
  sky130_osu_sc_18T_ms__inv_1 g7368(.A (n_72), .Y (n_105));
  sky130_osu_sc_18T_ms__aoi22_l g7369__8246(.A0 (prot_wb_dat_miso[31]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[31]), .Y
       (n_104));
  sky130_osu_sc_18T_ms__aoi22_l g7370__7098(.A0 (pwm_wb_ack), .A1
       (n_428), .B0 (adc_sel), .B1 (adc_wb_ack), .Y (n_103));
  sky130_osu_sc_18T_ms__aoi22_l g7371__6131(.A0 (adc_wb_dat_miso[17]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[17]), .Y
       (n_102));
  sky130_osu_sc_18T_ms__aoi22_l g7372__1881(.A0 (pwm_wb_dat_miso[26]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[26]), .Y (n_101));
  sky130_osu_sc_18T_ms__aoi22_l g7373__5115(.A0 (pwm_wb_dat_miso[16]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[16]), .Y (n_100));
  sky130_osu_sc_18T_ms__aoi22_l g7374__7482(.A0 (adc_wb_dat_miso[16]),
       .A1 (adc_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[16]), .Y
       (n_99));
  sky130_osu_sc_18T_ms__aoi22_l g7375__4733(.A0 (pwm_wb_dat_miso[30]),
       .A1 (n_428), .B0 (adc_sel), .B1 (adc_wb_dat_miso[30]), .Y
       (n_98));
  sky130_osu_sc_18T_ms__aoi22_l g7376__6161(.A0 (pwm_wb_dat_miso[15]),
       .A1 (n_428), .B0 (comm_sel), .B1 (comm_wb_dat_miso[15]), .Y
       (n_97));
  sky130_osu_sc_18T_ms__aoi22_l g7377__9315(.A0 (pwm_wb_dat_miso[25]),
       .A1 (n_428), .B0 (comm_sel), .B1 (comm_wb_dat_miso[25]), .Y
       (n_96));
  sky130_osu_sc_18T_ms__aoi22_l g7378__9945(.A0 (adc_wb_dat_miso[15]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[15]), .Y
       (n_95));
  sky130_osu_sc_18T_ms__aoi22_l g7379__2883(.A0 (comm_wb_dat_miso[14]),
       .A1 (comm_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[14]), .Y
       (n_94));
  sky130_osu_sc_18T_ms__aoi22_l g7380__2346(.A0 (adc_wb_dat_miso[25]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[25]), .Y
       (n_93));
  sky130_osu_sc_18T_ms__aoi22_l g7381__1666(.A0 (pwm_wb_dat_miso[14]),
       .A1 (n_428), .B0 (adc_sel), .B1 (adc_wb_dat_miso[14]), .Y
       (n_92));
  sky130_osu_sc_18T_ms__aoi22_l g7382__7410(.A0 (comm_wb_dat_miso[30]),
       .A1 (comm_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[30]), .Y
       (n_91));
  sky130_osu_sc_18T_ms__aoi22_l g7383__6417(.A0 (pwm_wb_dat_miso[24]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[24]), .Y (n_90));
  sky130_osu_sc_18T_ms__aoi22_l g7384__5477(.A0 (pwm_wb_dat_miso[13]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[13]), .Y (n_89));
  sky130_osu_sc_18T_ms__aoi22_l g7385__2398(.A0 (prot_wb_dat_miso[13]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[13]), .Y
       (n_88));
  sky130_osu_sc_18T_ms__aoi22_l g7386__5107(.A0 (pwm_wb_dat_miso[12]),
       .A1 (n_428), .B0 (prot_sel), .B1 (prot_wb_dat_miso[12]), .Y
       (n_87));
  sky130_osu_sc_18T_ms__aoi22_l g7387__6260(.A0 (adc_wb_err), .A1
       (adc_sel), .B0 (n_482), .B1 (mem_wb_err), .Y (n_86));
  sky130_osu_sc_18T_ms__aoi22_l g7388__4319(.A0 (adc_wb_dat_miso[12]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[12]), .Y
       (n_85));
  sky130_osu_sc_18T_ms__aoi22_l g7389__8428(.A0 (adc_wb_dat_miso[24]),
       .A1 (adc_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[24]), .Y
       (n_84));
  sky130_osu_sc_18T_ms__aoi22_l g7390__5526(.A0 (prot_wb_dat_miso[11]),
       .A1 (prot_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[11]), .Y
       (n_83));
  sky130_osu_sc_18T_ms__aoi22_l g7391__6783(.A0 (comm_wb_dat_miso[23]),
       .A1 (comm_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[23]), .Y
       (n_82));
  sky130_osu_sc_18T_ms__aoi22_l g7392__3680(.A0 (adc_wb_dat_miso[11]),
       .A1 (adc_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[11]), .Y
       (n_81));
  sky130_osu_sc_18T_ms__aoi22_l g7393__1617(.A0 (prot_wb_dat_miso[29]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[29]), .Y
       (n_80));
  sky130_osu_sc_18T_ms__aoi22_l g7394__2802(.A0 (comm_wb_dat_miso[10]),
       .A1 (comm_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[10]), .Y
       (n_79));
  sky130_osu_sc_18T_ms__aoi22_l g7395__1705(.A0 (adc_wb_dat_miso[10]),
       .A1 (adc_sel), .B0 (prot_sel), .B1 (prot_wb_dat_miso[10]), .Y
       (n_78));
  sky130_osu_sc_18T_ms__aoi22_l g7396__5122(.A0 (adc_wb_dat_miso[23]),
       .A1 (adc_sel), .B0 (prot_sel), .B1 (prot_wb_dat_miso[23]), .Y
       (n_77));
  sky130_osu_sc_18T_ms__aoi22_l g7397__8246(.A0 (prot_wb_dat_miso[22]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[22]), .Y
       (n_76));
  sky130_osu_sc_18T_ms__aoi22_l g7398__7098(.A0 (adc_wb_dat_miso[9]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[9]), .Y (n_75));
  sky130_osu_sc_18T_ms__aoi22_l g7399__6131(.A0 (adc_wb_dat_miso[29]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[29]), .Y
       (n_74));
  sky130_osu_sc_18T_ms__aoi22_l g7400__1881(.A0 (prot_wb_dat_miso[9]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[9]), .Y
       (n_73));
  sky130_osu_sc_18T_ms__aoi22_l g7401__5115(.A0 (pwm_wb_dat_miso[22]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[22]), .Y (n_72));
  sky130_osu_sc_18T_ms__aoi22_l g7402__7482(.A0 (prot_wb_dat_miso[8]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[8]), .Y
       (n_71));
  sky130_osu_sc_18T_ms__inv_1 g7403(.A (n_54), .Y (n_70));
  sky130_osu_sc_18T_ms__inv_1 g7404(.A (n_50), .Y (n_69));
  sky130_osu_sc_18T_ms__inv_1 g7405(.A (n_49), .Y (n_68));
  sky130_osu_sc_18T_ms__inv_1 g7406(.A (n_47), .Y (n_67));
  sky130_osu_sc_18T_ms__inv_1 g7407(.A (n_46), .Y (n_66));
  sky130_osu_sc_18T_ms__inv_1 g7408(.A (n_43), .Y (n_65));
  sky130_osu_sc_18T_ms__inv_1 g7409(.A (n_42), .Y (n_64));
  sky130_osu_sc_18T_ms__inv_1 g7410(.A (n_40), .Y (n_63));
  sky130_osu_sc_18T_ms__inv_1 g7411(.A (n_39), .Y (n_62));
  sky130_osu_sc_18T_ms__inv_1 g7412(.A (n_37), .Y (n_61));
  sky130_osu_sc_18T_ms__inv_1 g7413(.A (n_34), .Y (n_60));
  sky130_osu_sc_18T_ms__inv_1 g7414(.A (n_33), .Y (n_59));
  sky130_osu_sc_18T_ms__inv_1 g7415(.A (n_29), .Y (n_58));
  sky130_osu_sc_18T_ms__inv_1 g7416(.A (n_28), .Y (n_57));
  sky130_osu_sc_18T_ms__inv_1 g7417(.A (n_27), .Y (n_56));
  sky130_osu_sc_18T_ms__inv_1 g7418(.A (n_25), .Y (n_55));
  sky130_osu_sc_18T_ms__aoi22_l g7419__4733(.A0 (adc_wb_dat_miso[8]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[8]), .Y (n_54));
  sky130_osu_sc_18T_ms__aoi22_l g7420__6161(.A0 (pwm_wb_dat_miso[28]),
       .A1 (n_428), .B0 (adc_sel), .B1 (adc_wb_dat_miso[28]), .Y
       (n_53));
  sky130_osu_sc_18T_ms__aoi22_l g7421__9315(.A0 (adc_wb_dat_miso[7]),
       .A1 (adc_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[7]), .Y
       (n_52));
  sky130_osu_sc_18T_ms__aoi22_l g7422__9945(.A0 (pwm_wb_dat_miso[21]),
       .A1 (n_428), .B0 (prot_sel), .B1 (prot_wb_dat_miso[21]), .Y
       (n_51));
  sky130_osu_sc_18T_ms__aoi22_l g7423__2883(.A0 (pwm_wb_dat_miso[7]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[7]), .Y (n_50));
  sky130_osu_sc_18T_ms__aoi22_l g7424__2346(.A0 (pwm_wb_err), .A1
       (n_428), .B0 (prot_sel), .B1 (prot_wb_err), .Y (n_49));
  sky130_osu_sc_18T_ms__aoi22_l g7425__1666(.A0 (pwm_wb_dat_miso[6]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[6]), .Y (n_48));
  sky130_osu_sc_18T_ms__aoi22_l g7426__7410(.A0 (adc_wb_dat_miso[21]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[21]), .Y
       (n_47));
  sky130_osu_sc_18T_ms__aoi22_l g7427__6417(.A0 (adc_wb_dat_miso[6]),
       .A1 (adc_sel), .B0 (prot_sel), .B1 (prot_wb_dat_miso[6]), .Y
       (n_46));
  sky130_osu_sc_18T_ms__aoi22_l g7428__5477(.A0 (adc_wb_dat_miso[20]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[20]), .Y
       (n_45));
  sky130_osu_sc_18T_ms__aoi22_l g7429__2398(.A0 (pwm_wb_dat_miso[5]),
       .A1 (n_428), .B0 (comm_sel), .B1 (comm_wb_dat_miso[5]), .Y
       (n_44));
  sky130_osu_sc_18T_ms__aoi22_l g7430__5107(.A0 (adc_wb_dat_miso[5]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[5]), .Y (n_43));
  sky130_osu_sc_18T_ms__aoi22_l g7431__6260(.A0 (pwm_wb_dat_miso[20]),
       .A1 (n_428), .B0 (comm_sel), .B1 (comm_wb_dat_miso[20]), .Y
       (n_42));
  sky130_osu_sc_18T_ms__aoi22_l g7432__4319(.A0 (prot_wb_dat_miso[4]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[4]), .Y
       (n_41));
  sky130_osu_sc_18T_ms__aoi22_l g7433__8428(.A0 (pwm_wb_dat_miso[4]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[4]), .Y (n_40));
  sky130_osu_sc_18T_ms__aoi22_l g7434__5526(.A0 (comm_wb_dat_miso[28]),
       .A1 (comm_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[28]), .Y
       (n_39));
  sky130_osu_sc_18T_ms__aoi22_l g7435__6783(.A0 (pwm_wb_dat_miso[3]),
       .A1 (n_428), .B0 (n_482), .B1 (mem_wb_dat_miso[3]), .Y (n_38));
  sky130_osu_sc_18T_ms__aoi22_l g7436__3680(.A0 (adc_wb_dat_miso[3]),
       .A1 (adc_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[3]), .Y
       (n_37));
  sky130_osu_sc_18T_ms__aoi22_l g7437__1617(.A0 (adc_wb_dat_miso[19]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[19]), .Y
       (n_36));
  sky130_osu_sc_18T_ms__aoi22_l g7438__2802(.A0 (comm_wb_dat_miso[2]),
       .A1 (comm_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[2]), .Y
       (n_35));
  sky130_osu_sc_18T_ms__aoi22_l g7439__1705(.A0 (prot_wb_dat_miso[19]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[19]), .Y
       (n_34));
  sky130_osu_sc_18T_ms__aoi22_l g7440__5122(.A0 (pwm_wb_dat_miso[2]),
       .A1 (n_428), .B0 (adc_sel), .B1 (adc_wb_dat_miso[2]), .Y (n_33));
  sky130_osu_sc_18T_ms__aoi22_l g7441__8246(.A0 (comm_wb_dat_miso[27]),
       .A1 (comm_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[27]), .Y
       (n_32));
  sky130_osu_sc_18T_ms__aoi22_l g7442__7098(.A0 (pwm_wb_dat_miso[18]),
       .A1 (n_428), .B0 (prot_sel), .B1 (prot_wb_dat_miso[18]), .Y
       (n_31));
  sky130_osu_sc_18T_ms__aoi22_l g7443__6131(.A0 (prot_wb_dat_miso[1]),
       .A1 (prot_sel), .B0 (comm_sel), .B1 (comm_wb_dat_miso[1]), .Y
       (n_30));
  sky130_osu_sc_18T_ms__aoi22_l g7444__1881(.A0 (pwm_wb_dat_miso[27]),
       .A1 (n_428), .B0 (adc_sel), .B1 (adc_wb_dat_miso[27]), .Y
       (n_29));
  sky130_osu_sc_18T_ms__aoi22_l g7445__5115(.A0 (adc_wb_dat_miso[1]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[1]), .Y (n_28));
  sky130_osu_sc_18T_ms__aoi22_l g7446__7482(.A0 (comm_wb_dat_miso[18]),
       .A1 (comm_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[18]), .Y
       (n_27));
  sky130_osu_sc_18T_ms__aoi22_l g7447__4733(.A0 (pwm_wb_dat_miso[0]),
       .A1 (n_428), .B0 (comm_sel), .B1 (comm_wb_dat_miso[0]), .Y
       (n_26));
  sky130_osu_sc_18T_ms__aoi22_l g7448__6161(.A0 (prot_wb_dat_miso[0]),
       .A1 (prot_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[0]), .Y
       (n_25));
  sky130_osu_sc_18T_ms__aoi22_l g7449__9315(.A0 (adc_wb_dat_miso[31]),
       .A1 (adc_sel), .B0 (n_482), .B1 (mem_wb_dat_miso[31]), .Y
       (n_24));
  sky130_osu_sc_18T_ms__aoi22_l g7450__9945(.A0 (pwm_wb_dat_miso[17]),
       .A1 (n_428), .B0 (comm_sel), .B1 (comm_wb_dat_miso[17]), .Y
       (n_23));
  sky130_osu_sc_18T_ms__aoi22_l g7451__2883(.A0 (comm_wb_ack), .A1
       (comm_sel), .B0 (n_482), .B1 (mem_wb_ack), .Y (n_22));
  sky130_osu_sc_18T_ms__aoi22_l g7452__2346(.A0 (adc_wb_dat_miso[26]),
       .A1 (adc_sel), .B0 (prot_sel), .B1 (prot_wb_dat_miso[26]), .Y
       (n_21));
  sky130_osu_sc_18T_ms__and2_l g7453__1666(.A (comm_sel), .B (dwb_we),
       .Y (n_163));
  sky130_osu_sc_18T_ms__and2_l g7454__7410(.A (adc_sel), .B
       (dwb_dat_mosi[16]), .Y (n_395));
  sky130_osu_sc_18T_ms__and2_l g7455__6417(.A (adc_sel), .B
       (dwb_adr[6]), .Y (n_421));
  sky130_osu_sc_18T_ms__and2_l g7456__5477(.A (adc_sel), .B
       (dwb_adr[4]), .Y (n_423));
  sky130_osu_sc_18T_ms__and2_l g7457__2398(.A (adc_sel), .B
       (dwb_dat_mosi[14]), .Y (n_397));
  sky130_osu_sc_18T_ms__and2_l g7458__5107(.A (adc_sel), .B
       (dwb_dat_mosi[22]), .Y (n_389));
  sky130_osu_sc_18T_ms__and2_l g7459__6260(.A (adc_sel), .B
       (dwb_adr[8]), .Y (n_419));
  sky130_osu_sc_18T_ms__and2_l g7460__4319(.A (adc_sel), .B
       (dwb_dat_mosi[18]), .Y (n_393));
  sky130_osu_sc_18T_ms__and2_l g7461__8428(.A (adc_sel), .B
       (dwb_adr[10]), .Y (n_417));
  sky130_osu_sc_18T_ms__and2_l g7462__5526(.A (adc_sel), .B
       (dwb_sel[1]), .Y (n_377));
  sky130_osu_sc_18T_ms__and2_l g7463__6783(.A (adc_sel), .B
       (dwb_adr[2]), .Y (n_425));
  sky130_osu_sc_18T_ms__and2_l g7464__3680(.A (adc_sel), .B
       (dwb_sel[3]), .Y (n_375));
  sky130_osu_sc_18T_ms__and2_l g7465__1617(.A (adc_sel), .B
       (dwb_sel[2]), .Y (n_376));
  sky130_osu_sc_18T_ms__and2_l g7466__2802(.A (adc_sel), .B
       (dwb_sel[0]), .Y (n_378));
  sky130_osu_sc_18T_ms__and2_l g7467__1705(.A (adc_sel), .B (dwb_we),
       .Y (n_379));
  sky130_osu_sc_18T_ms__and2_l g7468__5122(.A (adc_sel), .B
       (dwb_dat_mosi[31]), .Y (n_380));
  sky130_osu_sc_18T_ms__and2_l g7469__8246(.A (adc_sel), .B
       (dwb_dat_mosi[29]), .Y (n_382));
  sky130_osu_sc_18T_ms__and2_l g7470__7098(.A (adc_sel), .B
       (dwb_dat_mosi[28]), .Y (n_383));
  sky130_osu_sc_18T_ms__and2_l g7471__6131(.A (adc_sel), .B
       (dwb_dat_mosi[27]), .Y (n_384));
  sky130_osu_sc_18T_ms__and2_l g7472__1881(.A (adc_sel), .B
       (dwb_dat_mosi[25]), .Y (n_386));
  sky130_osu_sc_18T_ms__and2_l g7473__5115(.A (adc_sel), .B
       (dwb_dat_mosi[24]), .Y (n_387));
  sky130_osu_sc_18T_ms__and2_l g7474__7482(.A (adc_sel), .B
       (dwb_dat_mosi[23]), .Y (n_388));
  sky130_osu_sc_18T_ms__and2_l g7475__4733(.A (adc_sel), .B
       (dwb_dat_mosi[21]), .Y (n_390));
  sky130_osu_sc_18T_ms__and2_l g7476__6161(.A (adc_sel), .B
       (dwb_dat_mosi[20]), .Y (n_391));
  sky130_osu_sc_18T_ms__and2_l g7477__9315(.A (adc_sel), .B
       (dwb_dat_mosi[19]), .Y (n_392));
  sky130_osu_sc_18T_ms__and2_l g7478__9945(.A (adc_sel), .B
       (dwb_dat_mosi[26]), .Y (n_385));
  sky130_osu_sc_18T_ms__and2_l g7479__2883(.A (adc_sel), .B
       (dwb_dat_mosi[17]), .Y (n_394));
  sky130_osu_sc_18T_ms__and2_l g7480__2346(.A (adc_sel), .B
       (dwb_dat_mosi[15]), .Y (n_396));
  sky130_osu_sc_18T_ms__and2_l g7481__1666(.A (adc_sel), .B
       (dwb_dat_mosi[10]), .Y (n_401));
  sky130_osu_sc_18T_ms__and2_l g7482__7410(.A (adc_sel), .B
       (dwb_dat_mosi[13]), .Y (n_398));
  sky130_osu_sc_18T_ms__and2_l g7483__6417(.A (adc_sel), .B
       (dwb_dat_mosi[12]), .Y (n_399));
  sky130_osu_sc_18T_ms__and2_l g7484__5477(.A (adc_sel), .B
       (dwb_dat_mosi[11]), .Y (n_400));
  sky130_osu_sc_18T_ms__and2_l g7485__2398(.A (adc_sel), .B
       (dwb_dat_mosi[9]), .Y (n_402));
  sky130_osu_sc_18T_ms__and2_l g7486__5107(.A (adc_sel), .B
       (dwb_dat_mosi[8]), .Y (n_403));
  sky130_osu_sc_18T_ms__and2_l g7487__6260(.A (adc_sel), .B
       (dwb_dat_mosi[7]), .Y (n_404));
  sky130_osu_sc_18T_ms__and2_l g7488__4319(.A (adc_sel), .B
       (dwb_dat_mosi[5]), .Y (n_406));
  sky130_osu_sc_18T_ms__and2_l g7489__8428(.A (adc_sel), .B
       (dwb_dat_mosi[4]), .Y (n_407));
  sky130_osu_sc_18T_ms__and2_l g7490__5526(.A (adc_sel), .B
       (dwb_dat_mosi[3]), .Y (n_408));
  sky130_osu_sc_18T_ms__and2_l g7491__6783(.A (adc_sel), .B
       (dwb_dat_mosi[1]), .Y (n_410));
  sky130_osu_sc_18T_ms__and2_l g7492__3680(.A (adc_sel), .B
       (dwb_adr[15]), .Y (n_412));
  sky130_osu_sc_18T_ms__and2_l g7493__1617(.A (adc_sel), .B
       (dwb_adr[13]), .Y (n_414));
  sky130_osu_sc_18T_ms__and2_l g7494__2802(.A (adc_sel), .B
       (dwb_adr[12]), .Y (n_415));
  sky130_osu_sc_18T_ms__and2_l g7495__1705(.A (adc_sel), .B
       (dwb_adr[11]), .Y (n_416));
  sky130_osu_sc_18T_ms__and2_l g7496__5122(.A (adc_sel), .B
       (dwb_adr[9]), .Y (n_418));
  sky130_osu_sc_18T_ms__and2_l g7497__8246(.A (adc_sel), .B
       (dwb_adr[7]), .Y (n_420));
  sky130_osu_sc_18T_ms__and2_l g7498__7098(.A (adc_sel), .B
       (dwb_adr[5]), .Y (n_422));
  sky130_osu_sc_18T_ms__and2_l g7499__6131(.A (adc_sel), .B
       (dwb_adr[3]), .Y (n_424));
  sky130_osu_sc_18T_ms__and2_l g7500__1881(.A (adc_sel), .B
       (dwb_adr[1]), .Y (n_426));
  sky130_osu_sc_18T_ms__and2_l g7501__5115(.A (adc_sel), .B
       (dwb_adr[0]), .Y (n_427));
  sky130_osu_sc_18T_ms__and2_l g7502__7482(.A (adc_sel), .B
       (dwb_dat_mosi[2]), .Y (n_409));
  sky130_osu_sc_18T_ms__and2_l g7503__4733(.A (adc_sel), .B
       (dwb_dat_mosi[0]), .Y (n_411));
  sky130_osu_sc_18T_ms__and2_l g7504__6161(.A (adc_sel), .B
       (dwb_dat_mosi[6]), .Y (n_405));
  sky130_osu_sc_18T_ms__and2_l g7505__9315(.A (adc_sel), .B
       (dwb_dat_mosi[30]), .Y (n_381));
  sky130_osu_sc_18T_ms__and2_l g7506__9945(.A (adc_sel), .B
       (dwb_adr[14]), .Y (n_413));
  sky130_osu_sc_18T_ms__and2_l g7507__2883(.A (comm_sel), .B
       (dwb_dat_mosi[12]), .Y (n_176));
  sky130_osu_sc_18T_ms__and2_l g7508__2346(.A (comm_sel), .B
       (dwb_dat_mosi[8]), .Y (n_172));
  sky130_osu_sc_18T_ms__and2_l g7509__1666(.A (comm_sel), .B
       (dwb_dat_mosi[14]), .Y (n_178));
  sky130_osu_sc_18T_ms__and2_l g7510__7410(.A (comm_sel), .B
       (dwb_dat_mosi[16]), .Y (n_180));
  sky130_osu_sc_18T_ms__and2_l g7511__6417(.A (comm_sel), .B
       (dwb_dat_mosi[20]), .Y (n_184));
  sky130_osu_sc_18T_ms__and2_l g7512__5477(.A (comm_sel), .B
       (dwb_sel[3]), .Y (n_162));
  sky130_osu_sc_18T_ms__and2_l g7513__2398(.A (comm_sel), .B
       (dwb_sel[2]), .Y (n_161));
  sky130_osu_sc_18T_ms__and2_l g7514__5107(.A (comm_sel), .B
       (dwb_sel[1]), .Y (n_160));
  sky130_osu_sc_18T_ms__and2_l g7515__6260(.A (comm_sel), .B
       (dwb_sel[0]), .Y (n_159));
  sky130_osu_sc_18T_ms__and2_l g7516__4319(.A (comm_sel), .B
       (dwb_dat_mosi[31]), .Y (n_195));
  sky130_osu_sc_18T_ms__and2_l g7517__8428(.A (comm_sel), .B
       (dwb_dat_mosi[30]), .Y (n_194));
  sky130_osu_sc_18T_ms__and2_l g7518__5526(.A (comm_sel), .B
       (dwb_dat_mosi[29]), .Y (n_193));
  sky130_osu_sc_18T_ms__and2_l g7519__6783(.A (comm_sel), .B
       (dwb_dat_mosi[27]), .Y (n_191));
  sky130_osu_sc_18T_ms__and2_l g7520__3680(.A (comm_sel), .B
       (dwb_dat_mosi[26]), .Y (n_190));
  sky130_osu_sc_18T_ms__and2_l g7521__1617(.A (comm_sel), .B
       (dwb_dat_mosi[25]), .Y (n_189));
  sky130_osu_sc_18T_ms__and2_l g7522__2802(.A (comm_sel), .B
       (dwb_dat_mosi[23]), .Y (n_187));
  sky130_osu_sc_18T_ms__and2_l g7523__1705(.A (comm_sel), .B
       (dwb_dat_mosi[22]), .Y (n_186));
  sky130_osu_sc_18T_ms__and2_l g7524__5122(.A (comm_sel), .B
       (dwb_dat_mosi[21]), .Y (n_185));
  sky130_osu_sc_18T_ms__and2_l g7525__8246(.A (comm_sel), .B
       (dwb_dat_mosi[24]), .Y (n_188));
  sky130_osu_sc_18T_ms__and2_l g7526__7098(.A (comm_sel), .B
       (dwb_dat_mosi[19]), .Y (n_183));
  sky130_osu_sc_18T_ms__and2_l g7527__6131(.A (comm_sel), .B
       (dwb_dat_mosi[18]), .Y (n_182));
  sky130_osu_sc_18T_ms__and2_l g7528__1881(.A (comm_sel), .B
       (dwb_dat_mosi[17]), .Y (n_181));
  sky130_osu_sc_18T_ms__and2_l g7529__5115(.A (comm_sel), .B
       (dwb_dat_mosi[15]), .Y (n_179));
  sky130_osu_sc_18T_ms__and2_l g7530__7482(.A (comm_sel), .B
       (dwb_dat_mosi[13]), .Y (n_177));
  sky130_osu_sc_18T_ms__and2_l g7531__4733(.A (comm_sel), .B
       (dwb_dat_mosi[11]), .Y (n_175));
  sky130_osu_sc_18T_ms__and2_l g7532__6161(.A (comm_sel), .B
       (dwb_dat_mosi[10]), .Y (n_174));
  sky130_osu_sc_18T_ms__and2_l g7533__9315(.A (comm_sel), .B
       (dwb_dat_mosi[9]), .Y (n_173));
  sky130_osu_sc_18T_ms__and2_l g7534__9945(.A (comm_sel), .B
       (dwb_dat_mosi[7]), .Y (n_171));
  sky130_osu_sc_18T_ms__and2_l g7535__2883(.A (comm_sel), .B
       (dwb_dat_mosi[5]), .Y (n_169));
  sky130_osu_sc_18T_ms__and2_l g7536__2346(.A (comm_sel), .B
       (dwb_dat_mosi[3]), .Y (n_167));
  sky130_osu_sc_18T_ms__and2_l g7537__1666(.A (comm_sel), .B
       (dwb_dat_mosi[2]), .Y (n_166));
  sky130_osu_sc_18T_ms__and2_l g7538__7410(.A (comm_sel), .B
       (dwb_dat_mosi[1]), .Y (n_165));
  sky130_osu_sc_18T_ms__and2_l g7539__6417(.A (comm_sel), .B
       (dwb_adr[15]), .Y (n_211));
  sky130_osu_sc_18T_ms__and2_l g7540__5477(.A (comm_sel), .B
       (dwb_adr[14]), .Y (n_210));
  sky130_osu_sc_18T_ms__and2_l g7541__2398(.A (comm_sel), .B
       (dwb_adr[13]), .Y (n_209));
  sky130_osu_sc_18T_ms__and2_l g7542__5107(.A (comm_sel), .B
       (dwb_adr[11]), .Y (n_207));
  sky130_osu_sc_18T_ms__and2_l g7543__6260(.A (comm_sel), .B
       (dwb_adr[10]), .Y (n_206));
  sky130_osu_sc_18T_ms__and2_l g7544__4319(.A (comm_sel), .B
       (dwb_adr[9]), .Y (n_205));
  sky130_osu_sc_18T_ms__and2_l g7545__8428(.A (comm_sel), .B
       (dwb_adr[7]), .Y (n_203));
  sky130_osu_sc_18T_ms__and2_l g7546__5526(.A (comm_sel), .B
       (dwb_adr[6]), .Y (n_202));
  sky130_osu_sc_18T_ms__and2_l g7547__6783(.A (comm_sel), .B
       (dwb_adr[3]), .Y (n_199));
  sky130_osu_sc_18T_ms__and2_l g7548__3680(.A (comm_sel), .B
       (dwb_adr[2]), .Y (n_198));
  sky130_osu_sc_18T_ms__and2_l g7549__1617(.A (comm_sel), .B
       (dwb_adr[1]), .Y (n_197));
  sky130_osu_sc_18T_ms__and2_l g7550__2802(.A (comm_sel), .B
       (dwb_dat_mosi[28]), .Y (n_192));
  sky130_osu_sc_18T_ms__and2_l g7551__1705(.A (comm_sel), .B
       (dwb_dat_mosi[6]), .Y (n_170));
  sky130_osu_sc_18T_ms__and2_l g7552__5122(.A (comm_sel), .B
       (dwb_adr[0]), .Y (n_196));
  sky130_osu_sc_18T_ms__and2_l g7553__8246(.A (comm_sel), .B
       (dwb_adr[5]), .Y (n_201));
  sky130_osu_sc_18T_ms__and2_l g7554__7098(.A (comm_sel), .B
       (dwb_adr[4]), .Y (n_200));
  sky130_osu_sc_18T_ms__and2_l g7555__6131(.A (comm_sel), .B
       (dwb_adr[8]), .Y (n_204));
  sky130_osu_sc_18T_ms__and2_l g7556__1881(.A (comm_sel), .B
       (dwb_dat_mosi[4]), .Y (n_168));
  sky130_osu_sc_18T_ms__and2_l g7557__5115(.A (comm_sel), .B
       (dwb_adr[12]), .Y (n_208));
  sky130_osu_sc_18T_ms__and2_l g7558__7482(.A (comm_sel), .B
       (dwb_dat_mosi[0]), .Y (n_164));
  sky130_osu_sc_18T_ms__and2_l g7559__4733(.A (prot_sel), .B
       (dwb_dat_mosi[26]), .Y (n_328));
  sky130_osu_sc_18T_ms__and2_l g7560__6161(.A (prot_sel), .B
       (dwb_adr[0]), .Y (n_370));
  sky130_osu_sc_18T_ms__and2_l g7561__9315(.A (prot_sel), .B
       (dwb_dat_mosi[25]), .Y (n_329));
  sky130_osu_sc_18T_ms__and2_l g7562__9945(.A (prot_sel), .B
       (dwb_adr[2]), .Y (n_368));
  sky130_osu_sc_18T_ms__and2_l g7563__2883(.A (prot_sel), .B
       (dwb_adr[13]), .Y (n_357));
  sky130_osu_sc_18T_ms__and2_l g7564__2346(.A (prot_sel), .B
       (dwb_adr[11]), .Y (n_359));
  sky130_osu_sc_18T_ms__and2_l g7565__1666(.A (prot_sel), .B
       (dwb_dat_mosi[1]), .Y (n_353));
  sky130_osu_sc_18T_ms__and2_l g7566__7410(.A (prot_sel), .B
       (dwb_adr[15]), .Y (n_355));
  sky130_osu_sc_18T_ms__and2_l g7567__6417(.A (prot_sel), .B
       (dwb_dat_mosi[5]), .Y (n_349));
  sky130_osu_sc_18T_ms__and2_l g7568__5477(.A (prot_sel), .B
       (dwb_dat_mosi[3]), .Y (n_351));
  sky130_osu_sc_18T_ms__and2_l g7569__2398(.A (n_428), .B
       (dwb_dat_mosi[31]), .Y (n_434));
  sky130_osu_sc_18T_ms__and2_l g7570__5107(.A (prot_sel), .B
       (dwb_dat_mosi[9]), .Y (n_345));
  sky130_osu_sc_18T_ms__and2_l g7571__6260(.A (n_428), .B
       (dwb_dat_mosi[30]), .Y (n_435));
  sky130_osu_sc_18T_ms__and2_l g7572__4319(.A (n_428), .B
       (dwb_dat_mosi[29]), .Y (n_436));
  sky130_osu_sc_18T_ms__and2_l g7573__8428(.A (n_428), .B
       (dwb_dat_mosi[28]), .Y (n_437));
  sky130_osu_sc_18T_ms__and2_l g7574__5526(.A (n_428), .B
       (dwb_dat_mosi[26]), .Y (n_439));
  sky130_osu_sc_18T_ms__and2_l g7575__6783(.A (n_428), .B
       (dwb_dat_mosi[25]), .Y (n_440));
  sky130_osu_sc_18T_ms__and2_l g7576__3680(.A (n_428), .B
       (dwb_dat_mosi[22]), .Y (n_443));
  sky130_osu_sc_18T_ms__and2_l g7577__1617(.A (n_428), .B
       (dwb_dat_mosi[21]), .Y (n_444));
  sky130_osu_sc_18T_ms__and2_l g7578__2802(.A (n_428), .B
       (dwb_dat_mosi[20]), .Y (n_445));
  sky130_osu_sc_18T_ms__and2_l g7579__1705(.A (n_428), .B
       (dwb_dat_mosi[18]), .Y (n_447));
  sky130_osu_sc_18T_ms__and2_l g7580__5122(.A (n_428), .B
       (dwb_dat_mosi[17]), .Y (n_448));
  sky130_osu_sc_18T_ms__and2_l g7581__8246(.A (n_428), .B
       (dwb_dat_mosi[14]), .Y (n_451));
  sky130_osu_sc_18T_ms__and2_l g7582__7098(.A (n_428), .B
       (dwb_dat_mosi[13]), .Y (n_452));
  sky130_osu_sc_18T_ms__and2_l g7583__6131(.A (n_428), .B
       (dwb_dat_mosi[12]), .Y (n_453));
  sky130_osu_sc_18T_ms__and2_l g7584__1881(.A (n_428), .B (dwb_sel[2]),
       .Y (n_430));
  sky130_osu_sc_18T_ms__and2_l g7585__5115(.A (n_428), .B
       (dwb_dat_mosi[10]), .Y (n_455));
  sky130_osu_sc_18T_ms__and2_l g7586__7482(.A (n_428), .B
       (dwb_dat_mosi[8]), .Y (n_457));
  sky130_osu_sc_18T_ms__and2_l g7587__4733(.A (prot_sel), .B
       (dwb_dat_mosi[15]), .Y (n_339));
  sky130_osu_sc_18T_ms__and2_l g7588__6161(.A (prot_sel), .B
       (dwb_adr[1]), .Y (n_369));
  sky130_osu_sc_18T_ms__and2_l g7589__9315(.A (n_428), .B
       (dwb_dat_mosi[6]), .Y (n_459));
  sky130_osu_sc_18T_ms__and2_l g7590__9945(.A (n_428), .B
       (dwb_dat_mosi[4]), .Y (n_461));
  sky130_osu_sc_18T_ms__and2_l g7591__2883(.A (n_428), .B
       (dwb_dat_mosi[2]), .Y (n_463));
  sky130_osu_sc_18T_ms__and2_l g7592__2346(.A (n_428), .B
       (dwb_dat_mosi[1]), .Y (n_464));
  sky130_osu_sc_18T_ms__and2_l g7593__1666(.A (n_428), .B
       (dwb_dat_mosi[0]), .Y (n_465));
  sky130_osu_sc_18T_ms__and2_l g7594__7410(.A (n_428), .B
       (dwb_adr[14]), .Y (n_467));
  sky130_osu_sc_18T_ms__and2_l g7595__6417(.A (n_428), .B
       (dwb_adr[13]), .Y (n_468));
  sky130_osu_sc_18T_ms__and2_l g7596__5477(.A (n_428), .B
       (dwb_adr[12]), .Y (n_469));
  sky130_osu_sc_18T_ms__and2_l g7597__2398(.A (n_428), .B
       (dwb_adr[10]), .Y (n_471));
  sky130_osu_sc_18T_ms__and2_l g7598__5107(.A (n_428), .B (dwb_adr[8]),
       .Y (n_473));
  sky130_osu_sc_18T_ms__and2_l g7599__6260(.A (n_428), .B (dwb_adr[6]),
       .Y (n_475));
  sky130_osu_sc_18T_ms__and2_l g7600__4319(.A (n_428), .B (dwb_adr[5]),
       .Y (n_476));
  sky130_osu_sc_18T_ms__and2_l g7601__8428(.A (n_428), .B (dwb_adr[4]),
       .Y (n_477));
  sky130_osu_sc_18T_ms__and2_l g7602__5526(.A (n_428), .B (dwb_adr[2]),
       .Y (n_479));
  sky130_osu_sc_18T_ms__and2_l g7603__6783(.A (n_428), .B (dwb_adr[1]),
       .Y (n_480));
  sky130_osu_sc_18T_ms__and2_l g7604__3680(.A (prot_sel), .B
       (dwb_dat_mosi[13]), .Y (n_341));
  sky130_osu_sc_18T_ms__and2_l g7605__1617(.A (prot_sel), .B
       (dwb_dat_mosi[17]), .Y (n_337));
  sky130_osu_sc_18T_ms__and2_l g7606__2802(.A (prot_sel), .B
       (dwb_dat_mosi[19]), .Y (n_335));
  sky130_osu_sc_18T_ms__and2_l g7607__1705(.A (prot_sel), .B
       (dwb_sel[3]), .Y (n_318));
  sky130_osu_sc_18T_ms__and2_l g7608__5122(.A (prot_sel), .B
       (dwb_sel[1]), .Y (n_320));
  sky130_osu_sc_18T_ms__and2_l g7609__8246(.A (prot_sel), .B (dwb_we),
       .Y (n_322));
  sky130_osu_sc_18T_ms__and2_l g7610__7098(.A (prot_sel), .B
       (dwb_dat_mosi[31]), .Y (n_323));
  sky130_osu_sc_18T_ms__and2_l g7611__6131(.A (prot_sel), .B
       (dwb_dat_mosi[28]), .Y (n_326));
  sky130_osu_sc_18T_ms__and2_l g7612__1881(.A (prot_sel), .B
       (dwb_adr[9]), .Y (n_361));
  sky130_osu_sc_18T_ms__and2_l g7613__5115(.A (prot_sel), .B
       (dwb_dat_mosi[24]), .Y (n_330));
  sky130_osu_sc_18T_ms__and2_l g7614__7482(.A (prot_sel), .B
       (dwb_dat_mosi[23]), .Y (n_331));
  sky130_osu_sc_18T_ms__and2_l g7615__4733(.A (prot_sel), .B
       (dwb_dat_mosi[22]), .Y (n_332));
  sky130_osu_sc_18T_ms__and2_l g7616__6161(.A (prot_sel), .B
       (dwb_dat_mosi[21]), .Y (n_333));
  sky130_osu_sc_18T_ms__and2_l g7617__9315(.A (prot_sel), .B
       (dwb_dat_mosi[20]), .Y (n_334));
  sky130_osu_sc_18T_ms__and2_l g7618__9945(.A (prot_sel), .B
       (dwb_dat_mosi[18]), .Y (n_336));
  sky130_osu_sc_18T_ms__and2_l g7619__2883(.A (prot_sel), .B
       (dwb_dat_mosi[16]), .Y (n_338));
  sky130_osu_sc_18T_ms__and2_l g7620__2346(.A (prot_sel), .B
       (dwb_dat_mosi[14]), .Y (n_340));
  sky130_osu_sc_18T_ms__and2_l g7621__1666(.A (prot_sel), .B
       (dwb_dat_mosi[12]), .Y (n_342));
  sky130_osu_sc_18T_ms__and2_l g7622__7410(.A (prot_sel), .B
       (dwb_dat_mosi[11]), .Y (n_343));
  sky130_osu_sc_18T_ms__and2_l g7623__6417(.A (prot_sel), .B
       (dwb_dat_mosi[10]), .Y (n_344));
  sky130_osu_sc_18T_ms__and2_l g7624__5477(.A (prot_sel), .B
       (dwb_dat_mosi[8]), .Y (n_346));
  sky130_osu_sc_18T_ms__and2_l g7625__2398(.A (prot_sel), .B
       (dwb_dat_mosi[7]), .Y (n_347));
  sky130_osu_sc_18T_ms__and2_l g7626__5107(.A (prot_sel), .B
       (dwb_dat_mosi[6]), .Y (n_348));
  sky130_osu_sc_18T_ms__and2_l g7627__6260(.A (prot_sel), .B
       (dwb_dat_mosi[4]), .Y (n_350));
  sky130_osu_sc_18T_ms__and2_l g7628__4319(.A (prot_sel), .B
       (dwb_dat_mosi[2]), .Y (n_352));
  sky130_osu_sc_18T_ms__and2_l g7629__8428(.A (prot_sel), .B
       (dwb_dat_mosi[0]), .Y (n_354));
  sky130_osu_sc_18T_ms__and2_l g7630__5526(.A (prot_sel), .B
       (dwb_adr[14]), .Y (n_356));
  sky130_osu_sc_18T_ms__and2_l g7631__6783(.A (prot_sel), .B
       (dwb_adr[12]), .Y (n_358));
  sky130_osu_sc_18T_ms__and2_l g7632__3680(.A (prot_sel), .B
       (dwb_adr[10]), .Y (n_360));
  sky130_osu_sc_18T_ms__and2_l g7633__1617(.A (prot_sel), .B
       (dwb_adr[8]), .Y (n_362));
  sky130_osu_sc_18T_ms__and2_l g7634__2802(.A (prot_sel), .B
       (dwb_adr[7]), .Y (n_363));
  sky130_osu_sc_18T_ms__and2_l g7635__1705(.A (prot_sel), .B
       (dwb_adr[4]), .Y (n_366));
  sky130_osu_sc_18T_ms__and2_l g7636__5122(.A (n_428), .B (dwb_adr[0]),
       .Y (n_481));
  sky130_osu_sc_18T_ms__and2_l g7637__8246(.A (n_428), .B
       (dwb_dat_mosi[11]), .Y (n_454));
  sky130_osu_sc_18T_ms__and2_l g7638__7098(.A (n_428), .B (dwb_adr[3]),
       .Y (n_478));
  sky130_osu_sc_18T_ms__and2_l g7639__6131(.A (n_428), .B (dwb_we), .Y
       (n_433));
  sky130_osu_sc_18T_ms__and2_l g7640__1881(.A (n_428), .B (dwb_sel[1]),
       .Y (n_431));
  sky130_osu_sc_18T_ms__and2_l g7641__5115(.A (n_428), .B (dwb_sel[3]),
       .Y (n_429));
  sky130_osu_sc_18T_ms__and2_l g7642__7482(.A (prot_sel), .B
       (dwb_dat_mosi[27]), .Y (n_327));
  sky130_osu_sc_18T_ms__and2_l g7643__4733(.A (n_428), .B (dwb_adr[7]),
       .Y (n_474));
  sky130_osu_sc_18T_ms__and2_l g7644__6161(.A (n_428), .B
       (dwb_adr[11]), .Y (n_470));
  sky130_osu_sc_18T_ms__and2_l g7645__9315(.A (n_428), .B (dwb_adr[9]),
       .Y (n_472));
  sky130_osu_sc_18T_ms__and2_l g7646__9945(.A (n_428), .B
       (dwb_dat_mosi[3]), .Y (n_462));
  sky130_osu_sc_18T_ms__and2_l g7647__2883(.A (n_428), .B
       (dwb_adr[15]), .Y (n_466));
  sky130_osu_sc_18T_ms__and2_l g7648__2346(.A (prot_sel), .B
       (dwb_dat_mosi[30]), .Y (n_324));
  sky130_osu_sc_18T_ms__and2_l g7649__1666(.A (n_428), .B
       (dwb_dat_mosi[9]), .Y (n_456));
  sky130_osu_sc_18T_ms__and2_l g7650__7410(.A (n_428), .B
       (dwb_dat_mosi[5]), .Y (n_460));
  sky130_osu_sc_18T_ms__and2_l g7651__6417(.A (prot_sel), .B
       (dwb_dat_mosi[29]), .Y (n_325));
  sky130_osu_sc_18T_ms__and2_l g7652__5477(.A (n_428), .B
       (dwb_dat_mosi[7]), .Y (n_458));
  sky130_osu_sc_18T_ms__and2_l g7653__2398(.A (n_428), .B
       (dwb_dat_mosi[24]), .Y (n_441));
  sky130_osu_sc_18T_ms__and2_l g7654__5107(.A (n_428), .B
       (dwb_dat_mosi[15]), .Y (n_450));
  sky130_osu_sc_18T_ms__and2_l g7655__6260(.A (prot_sel), .B
       (dwb_adr[3]), .Y (n_367));
  sky130_osu_sc_18T_ms__and2_l g7656__4319(.A (n_428), .B
       (dwb_dat_mosi[16]), .Y (n_449));
  sky130_osu_sc_18T_ms__and2_l g7657__8428(.A (n_428), .B
       (dwb_dat_mosi[19]), .Y (n_446));
  sky130_osu_sc_18T_ms__and2_l g7658__5526(.A (n_428), .B
       (dwb_dat_mosi[23]), .Y (n_442));
  sky130_osu_sc_18T_ms__and2_l g7659__6783(.A (prot_sel), .B
       (dwb_sel[0]), .Y (n_321));
  sky130_osu_sc_18T_ms__and2_l g7660__3680(.A (prot_sel), .B
       (dwb_sel[2]), .Y (n_319));
  sky130_osu_sc_18T_ms__and2_l g7661__1617(.A (n_428), .B
       (dwb_dat_mosi[27]), .Y (n_438));
  sky130_osu_sc_18T_ms__and2_l g7662__2802(.A (prot_sel), .B
       (dwb_adr[6]), .Y (n_364));
  sky130_osu_sc_18T_ms__and2_l g7663__1705(.A (prot_sel), .B
       (dwb_adr[5]), .Y (n_365));
  sky130_osu_sc_18T_ms__and2_l g7664__5122(.A (n_428), .B (dwb_sel[0]),
       .Y (n_432));
  sky130_osu_sc_18T_ms__nor2_l g7665__8246(.A (n_0), .B (n_19), .Y
       (comm_sel));
  sky130_osu_sc_18T_ms__nor2_l g7666__7098(.A (dwb_adr[16]), .B (n_20),
       .Y (n_428));
  sky130_osu_sc_18T_ms__nor2_l g7667__6131(.A (n_0), .B (n_20), .Y
       (adc_sel));
  sky130_osu_sc_18T_ms__nor2_l g7668__1881(.A (dwb_adr[16]), .B (n_19),
       .Y (prot_sel));
  sky130_osu_sc_18T_ms__or2_l g7669__5115(.A (dwb_adr[17]), .B (n_18),
       .Y (n_20));
  sky130_osu_sc_18T_ms__nand2_l g7670__7482(.A (n_17), .B
       (dwb_adr[17]), .Y (n_19));
  sky130_osu_sc_18T_ms__inv_l g7671(.A (n_17), .Y (n_18));
  sky130_osu_sc_18T_ms__nor2_l g7672__4733(.A (dwb_adr[18]), .B (n_16),
       .Y (n_17));
  sky130_osu_sc_18T_ms__or2_l g7673__6161(.A (dwb_adr[19]), .B (n_15),
       .Y (n_16));
  sky130_osu_sc_18T_ms__or2_l g7674__9315(.A (dwb_adr[22]), .B (n_14),
       .Y (n_15));
  sky130_osu_sc_18T_ms__or2_l g7675__9945(.A (dwb_adr[23]), .B (n_13),
       .Y (n_14));
  sky130_osu_sc_18T_ms__or2_l g7676__2883(.A (dwb_adr[27]), .B (n_12),
       .Y (n_13));
  sky130_osu_sc_18T_ms__nand2_l g7677__2346(.A (n_11), .B
       (dwb_adr[30]), .Y (n_12));
  sky130_osu_sc_18T_ms__nor2_l g7678__1666(.A (dwb_adr[21]), .B (n_10),
       .Y (n_11));
  sky130_osu_sc_18T_ms__or2_l g7679__7410(.A (dwb_adr[20]), .B (n_9),
       .Y (n_10));
  sky130_osu_sc_18T_ms__or2_l g7680__6417(.A (dwb_adr[24]), .B (n_8),
       .Y (n_9));
  sky130_osu_sc_18T_ms__or2_l g7681__5477(.A (dwb_adr[25]), .B (n_7),
       .Y (n_8));
  sky130_osu_sc_18T_ms__and2_l g7682__2398(.A (n_482), .B
       (dwb_adr[14]), .Y (n_534));
  sky130_osu_sc_18T_ms__and2_l g7683__5107(.A (n_482), .B
       (dwb_adr[28]), .Y (n_520));
  sky130_osu_sc_18T_ms__and2_l g7684__6260(.A (n_482), .B
       (dwb_adr[27]), .Y (n_521));
  sky130_osu_sc_18T_ms__and2_l g7685__4319(.A (n_482), .B
       (dwb_adr[26]), .Y (n_522));
  sky130_osu_sc_18T_ms__and2_l g7686__8428(.A (n_482), .B
       (dwb_adr[24]), .Y (n_524));
  sky130_osu_sc_18T_ms__and2_l g7687__5526(.A (n_482), .B
       (dwb_adr[23]), .Y (n_525));
  sky130_osu_sc_18T_ms__and2_l g7688__6783(.A (n_482), .B
       (dwb_adr[22]), .Y (n_526));
  sky130_osu_sc_18T_ms__and2_l g7689__3680(.A (n_482), .B
       (dwb_adr[20]), .Y (n_528));
  sky130_osu_sc_18T_ms__and2_l g7690__1617(.A (n_482), .B
       (dwb_adr[19]), .Y (n_529));
  sky130_osu_sc_18T_ms__and2_l g7691__2802(.A (n_482), .B
       (dwb_adr[18]), .Y (n_530));
  sky130_osu_sc_18T_ms__and2_l g7692__1705(.A (n_482), .B
       (dwb_adr[17]), .Y (n_531));
  sky130_osu_sc_18T_ms__nor2_l g7693__5122(.A (n_0), .B (n_5), .Y
       (n_532));
  sky130_osu_sc_18T_ms__and2_l g7694__8246(.A (n_482), .B
       (dwb_adr[15]), .Y (n_533));
  sky130_osu_sc_18T_ms__and2_l g7695__7098(.A (n_482), .B
       (dwb_adr[13]), .Y (n_535));
  sky130_osu_sc_18T_ms__and2_l g7696__6131(.A (n_482), .B
       (dwb_adr[12]), .Y (n_536));
  sky130_osu_sc_18T_ms__and2_l g7697__1881(.A (n_482), .B
       (dwb_adr[11]), .Y (n_537));
  sky130_osu_sc_18T_ms__or2_l g7698__5115(.A (dwb_adr[26]), .B (n_6),
       .Y (n_7));
  sky130_osu_sc_18T_ms__and2_l g7699__7482(.A (n_482), .B (dwb_adr[9]),
       .Y (n_539));
  sky130_osu_sc_18T_ms__and2_l g7700__4733(.A (n_482), .B (dwb_adr[8]),
       .Y (n_540));
  sky130_osu_sc_18T_ms__and2_l g7701__6161(.A (n_482), .B (dwb_adr[7]),
       .Y (n_541));
  sky130_osu_sc_18T_ms__and2_l g7702__9315(.A (n_482), .B (dwb_adr[6]),
       .Y (n_542));
  sky130_osu_sc_18T_ms__and2_l g7703__9945(.A (n_482), .B (dwb_adr[5]),
       .Y (n_543));
  sky130_osu_sc_18T_ms__and2_l g7704__2883(.A (n_482), .B (dwb_adr[4]),
       .Y (n_544));
  sky130_osu_sc_18T_ms__and2_l g7705__2346(.A (n_482), .B (dwb_adr[3]),
       .Y (n_545));
  sky130_osu_sc_18T_ms__and2_l g7706__1666(.A (n_482), .B (dwb_adr[2]),
       .Y (n_546));
  sky130_osu_sc_18T_ms__and2_l g7707__7410(.A (n_482), .B (dwb_adr[1]),
       .Y (n_547));
  sky130_osu_sc_18T_ms__and2_l g7708__6417(.A (n_482), .B (dwb_adr[0]),
       .Y (n_548));
  sky130_osu_sc_18T_ms__and2_l g7709__5477(.A (n_482), .B (dwb_sel[3]),
       .Y (n_483));
  sky130_osu_sc_18T_ms__and2_l g7710__2398(.A (n_482), .B (dwb_sel[2]),
       .Y (n_484));
  sky130_osu_sc_18T_ms__and2_l g7711__5107(.A (n_482), .B (dwb_sel[1]),
       .Y (n_485));
  sky130_osu_sc_18T_ms__and2_l g7712__6260(.A (n_482), .B (dwb_sel[0]),
       .Y (n_486));
  sky130_osu_sc_18T_ms__and2_l g7713__4319(.A (n_482), .B
       (dwb_dat_mosi[31]), .Y (n_488));
  sky130_osu_sc_18T_ms__and2_l g7714__8428(.A (n_482), .B
       (dwb_dat_mosi[30]), .Y (n_489));
  sky130_osu_sc_18T_ms__and2_l g7715__5526(.A (n_482), .B
       (dwb_dat_mosi[3]), .Y (n_516));
  sky130_osu_sc_18T_ms__and2_l g7716__6783(.A (n_482), .B
       (dwb_dat_mosi[28]), .Y (n_491));
  sky130_osu_sc_18T_ms__and2_l g7717__3680(.A (n_482), .B
       (dwb_dat_mosi[27]), .Y (n_492));
  sky130_osu_sc_18T_ms__and2_l g7718__1617(.A (n_482), .B
       (dwb_dat_mosi[8]), .Y (n_511));
  sky130_osu_sc_18T_ms__and2_l g7719__2802(.A (n_482), .B
       (dwb_dat_mosi[9]), .Y (n_510));
  sky130_osu_sc_18T_ms__and2_l g7720__1705(.A (n_482), .B
       (dwb_dat_mosi[26]), .Y (n_493));
  sky130_osu_sc_18T_ms__and2_l g7721__5122(.A (n_482), .B
       (dwb_dat_mosi[25]), .Y (n_494));
  sky130_osu_sc_18T_ms__and2_l g7722__8246(.A (n_482), .B
       (dwb_dat_mosi[24]), .Y (n_495));
  sky130_osu_sc_18T_ms__and2_l g7723__7098(.A (n_482), .B
       (dwb_dat_mosi[15]), .Y (n_504));
  sky130_osu_sc_18T_ms__and2_l g7724__6131(.A (n_482), .B
       (dwb_dat_mosi[16]), .Y (n_503));
  sky130_osu_sc_18T_ms__and2_l g7725__1881(.A (n_482), .B
       (dwb_dat_mosi[17]), .Y (n_502));
  sky130_osu_sc_18T_ms__and2_l g7726__5115(.A (n_482), .B
       (dwb_dat_mosi[22]), .Y (n_497));
  sky130_osu_sc_18T_ms__and2_l g7727__7482(.A (n_482), .B
       (dwb_dat_mosi[21]), .Y (n_498));
  sky130_osu_sc_18T_ms__and2_l g7728__4733(.A (n_482), .B
       (dwb_dat_mosi[20]), .Y (n_499));
  sky130_osu_sc_18T_ms__and2_l g7729__6161(.A (n_482), .B
       (dwb_adr[21]), .Y (n_527));
  sky130_osu_sc_18T_ms__and2_l g7730__9315(.A (n_482), .B
       (dwb_dat_mosi[18]), .Y (n_501));
  sky130_osu_sc_18T_ms__and2_l g7731__9945(.A (n_482), .B
       (dwb_dat_mosi[7]), .Y (n_512));
  sky130_osu_sc_18T_ms__and2_l g7732__2883(.A (n_482), .B
       (dwb_dat_mosi[14]), .Y (n_505));
  sky130_osu_sc_18T_ms__and2_l g7733__2346(.A (n_482), .B
       (dwb_dat_mosi[13]), .Y (n_506));
  sky130_osu_sc_18T_ms__and2_l g7734__1666(.A (n_482), .B
       (dwb_dat_mosi[12]), .Y (n_507));
  sky130_osu_sc_18T_ms__and2_l g7735__7410(.A (n_482), .B
       (dwb_dat_mosi[11]), .Y (n_508));
  sky130_osu_sc_18T_ms__and2_l g7736__6417(.A (n_482), .B
       (dwb_adr[25]), .Y (n_523));
  sky130_osu_sc_18T_ms__and2_l g7737__5477(.A (n_482), .B
       (dwb_dat_mosi[10]), .Y (n_509));
  sky130_osu_sc_18T_ms__and2_l g7738__2398(.A (n_482), .B
       (dwb_dat_mosi[6]), .Y (n_513));
  sky130_osu_sc_18T_ms__and2_l g7739__5107(.A (n_482), .B
       (dwb_dat_mosi[5]), .Y (n_514));
  sky130_osu_sc_18T_ms__and2_l g7740__6260(.A (n_482), .B
       (dwb_dat_mosi[4]), .Y (n_515));
  sky130_osu_sc_18T_ms__and2_l g7741__4319(.A (n_482), .B
       (dwb_dat_mosi[2]), .Y (n_517));
  sky130_osu_sc_18T_ms__and2_l g7742__8428(.A (n_482), .B
       (dwb_dat_mosi[1]), .Y (n_518));
  sky130_osu_sc_18T_ms__and2_l g7743__5526(.A (n_482), .B
       (dwb_dat_mosi[0]), .Y (n_519));
  sky130_osu_sc_18T_ms__and2_l g7744__6783(.A (n_482), .B
       (dwb_dat_mosi[19]), .Y (n_500));
  sky130_osu_sc_18T_ms__and2_l g7745__3680(.A (n_482), .B
       (dwb_dat_mosi[23]), .Y (n_496));
  sky130_osu_sc_18T_ms__and2_l g7746__1617(.A (n_482), .B
       (dwb_dat_mosi[29]), .Y (n_490));
  sky130_osu_sc_18T_ms__and2_l g7747__2802(.A (n_482), .B (dwb_we), .Y
       (n_487));
  sky130_osu_sc_18T_ms__and2_l g7748__1705(.A (n_482), .B
       (dwb_adr[10]), .Y (n_538));
  sky130_osu_sc_18T_ms__or2_l g7749__5122(.A (dwb_adr[28]), .B (n_4),
       .Y (n_6));
  sky130_osu_sc_18T_ms__inv_1 g7750(.A (n_482), .Y (n_5));
  sky130_osu_sc_18T_ms__nor2_l g7751__8246(.A (dwb_adr[30]), .B (n_4),
       .Y (n_482));
  sky130_osu_sc_18T_ms__nand2_l g7752__7098(.A (n_2), .B (n_3), .Y
       (n_4));
  sky130_osu_sc_18T_ms__nor2_l g7753__6131(.A (system_reset), .B (n_1),
       .Y (n_583));
  sky130_osu_sc_18T_ms__nor2_l g7754__1881(.A (dwb_adr[29]), .B
       (dwb_adr[31]), .Y (n_3));
  sky130_osu_sc_18T_ms__and2_l g7755__5115(.A (dwb_cyc), .B (dwb_stb),
       .Y (n_2));
  sky130_osu_sc_18T_ms__inv_1 g7756(.A (rst_n), .Y (n_1));
  sky130_osu_sc_18T_ms__inv_1 g7757(.A (dwb_adr[16]), .Y (n_0));
endmodule

