
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point wb_adr_i[31] wb_adr_i[31] -type PI PI
add mapped point wb_adr_i[30] wb_adr_i[30] -type PI PI
add mapped point wb_adr_i[29] wb_adr_i[29] -type PI PI
add mapped point wb_adr_i[28] wb_adr_i[28] -type PI PI
add mapped point wb_adr_i[27] wb_adr_i[27] -type PI PI
add mapped point wb_adr_i[26] wb_adr_i[26] -type PI PI
add mapped point wb_adr_i[25] wb_adr_i[25] -type PI PI
add mapped point wb_adr_i[24] wb_adr_i[24] -type PI PI
add mapped point wb_adr_i[23] wb_adr_i[23] -type PI PI
add mapped point wb_adr_i[22] wb_adr_i[22] -type PI PI
add mapped point wb_adr_i[21] wb_adr_i[21] -type PI PI
add mapped point wb_adr_i[20] wb_adr_i[20] -type PI PI
add mapped point wb_adr_i[19] wb_adr_i[19] -type PI PI
add mapped point wb_adr_i[18] wb_adr_i[18] -type PI PI
add mapped point wb_adr_i[17] wb_adr_i[17] -type PI PI
add mapped point wb_adr_i[16] wb_adr_i[16] -type PI PI
add mapped point wb_adr_i[15] wb_adr_i[15] -type PI PI
add mapped point wb_adr_i[14] wb_adr_i[14] -type PI PI
add mapped point wb_adr_i[13] wb_adr_i[13] -type PI PI
add mapped point wb_adr_i[12] wb_adr_i[12] -type PI PI
add mapped point wb_adr_i[11] wb_adr_i[11] -type PI PI
add mapped point wb_adr_i[10] wb_adr_i[10] -type PI PI
add mapped point wb_adr_i[9] wb_adr_i[9] -type PI PI
add mapped point wb_adr_i[8] wb_adr_i[8] -type PI PI
add mapped point wb_adr_i[7] wb_adr_i[7] -type PI PI
add mapped point wb_adr_i[6] wb_adr_i[6] -type PI PI
add mapped point wb_adr_i[5] wb_adr_i[5] -type PI PI
add mapped point wb_adr_i[4] wb_adr_i[4] -type PI PI
add mapped point wb_adr_i[3] wb_adr_i[3] -type PI PI
add mapped point wb_adr_i[2] wb_adr_i[2] -type PI PI
add mapped point wb_adr_i[1] wb_adr_i[1] -type PI PI
add mapped point wb_adr_i[0] wb_adr_i[0] -type PI PI
add mapped point wb_dat_i[31] wb_dat_i[31] -type PI PI
add mapped point wb_dat_i[30] wb_dat_i[30] -type PI PI
add mapped point wb_dat_i[29] wb_dat_i[29] -type PI PI
add mapped point wb_dat_i[28] wb_dat_i[28] -type PI PI
add mapped point wb_dat_i[27] wb_dat_i[27] -type PI PI
add mapped point wb_dat_i[26] wb_dat_i[26] -type PI PI
add mapped point wb_dat_i[25] wb_dat_i[25] -type PI PI
add mapped point wb_dat_i[24] wb_dat_i[24] -type PI PI
add mapped point wb_dat_i[23] wb_dat_i[23] -type PI PI
add mapped point wb_dat_i[22] wb_dat_i[22] -type PI PI
add mapped point wb_dat_i[21] wb_dat_i[21] -type PI PI
add mapped point wb_dat_i[20] wb_dat_i[20] -type PI PI
add mapped point wb_dat_i[19] wb_dat_i[19] -type PI PI
add mapped point wb_dat_i[18] wb_dat_i[18] -type PI PI
add mapped point wb_dat_i[17] wb_dat_i[17] -type PI PI
add mapped point wb_dat_i[16] wb_dat_i[16] -type PI PI
add mapped point wb_dat_i[15] wb_dat_i[15] -type PI PI
add mapped point wb_dat_i[14] wb_dat_i[14] -type PI PI
add mapped point wb_dat_i[13] wb_dat_i[13] -type PI PI
add mapped point wb_dat_i[12] wb_dat_i[12] -type PI PI
add mapped point wb_dat_i[11] wb_dat_i[11] -type PI PI
add mapped point wb_dat_i[10] wb_dat_i[10] -type PI PI
add mapped point wb_dat_i[9] wb_dat_i[9] -type PI PI
add mapped point wb_dat_i[8] wb_dat_i[8] -type PI PI
add mapped point wb_dat_i[7] wb_dat_i[7] -type PI PI
add mapped point wb_dat_i[6] wb_dat_i[6] -type PI PI
add mapped point wb_dat_i[5] wb_dat_i[5] -type PI PI
add mapped point wb_dat_i[4] wb_dat_i[4] -type PI PI
add mapped point wb_dat_i[3] wb_dat_i[3] -type PI PI
add mapped point wb_dat_i[2] wb_dat_i[2] -type PI PI
add mapped point wb_dat_i[1] wb_dat_i[1] -type PI PI
add mapped point wb_dat_i[0] wb_dat_i[0] -type PI PI
add mapped point wb_we_i wb_we_i -type PI PI
add mapped point wb_sel_i[3] wb_sel_i[3] -type PI PI
add mapped point wb_sel_i[2] wb_sel_i[2] -type PI PI
add mapped point wb_sel_i[1] wb_sel_i[1] -type PI PI
add mapped point wb_sel_i[0] wb_sel_i[0] -type PI PI
add mapped point wb_cyc_i wb_cyc_i -type PI PI
add mapped point wb_stb_i wb_stb_i -type PI PI
add mapped point pwm_sync_in pwm_sync_in -type PI PI

//output ports
add mapped point wb_dat_o[31] wb_dat_o[31] -type PO PO
add mapped point wb_dat_o[30] wb_dat_o[30] -type PO PO
add mapped point wb_dat_o[29] wb_dat_o[29] -type PO PO
add mapped point wb_dat_o[28] wb_dat_o[28] -type PO PO
add mapped point wb_dat_o[27] wb_dat_o[27] -type PO PO
add mapped point wb_dat_o[26] wb_dat_o[26] -type PO PO
add mapped point wb_dat_o[25] wb_dat_o[25] -type PO PO
add mapped point wb_dat_o[24] wb_dat_o[24] -type PO PO
add mapped point wb_dat_o[23] wb_dat_o[23] -type PO PO
add mapped point wb_dat_o[22] wb_dat_o[22] -type PO PO
add mapped point wb_dat_o[21] wb_dat_o[21] -type PO PO
add mapped point wb_dat_o[20] wb_dat_o[20] -type PO PO
add mapped point wb_dat_o[19] wb_dat_o[19] -type PO PO
add mapped point wb_dat_o[18] wb_dat_o[18] -type PO PO
add mapped point wb_dat_o[17] wb_dat_o[17] -type PO PO
add mapped point wb_dat_o[16] wb_dat_o[16] -type PO PO
add mapped point wb_dat_o[15] wb_dat_o[15] -type PO PO
add mapped point wb_dat_o[14] wb_dat_o[14] -type PO PO
add mapped point wb_dat_o[13] wb_dat_o[13] -type PO PO
add mapped point wb_dat_o[12] wb_dat_o[12] -type PO PO
add mapped point wb_dat_o[11] wb_dat_o[11] -type PO PO
add mapped point wb_dat_o[10] wb_dat_o[10] -type PO PO
add mapped point wb_dat_o[9] wb_dat_o[9] -type PO PO
add mapped point wb_dat_o[8] wb_dat_o[8] -type PO PO
add mapped point wb_dat_o[7] wb_dat_o[7] -type PO PO
add mapped point wb_dat_o[6] wb_dat_o[6] -type PO PO
add mapped point wb_dat_o[5] wb_dat_o[5] -type PO PO
add mapped point wb_dat_o[4] wb_dat_o[4] -type PO PO
add mapped point wb_dat_o[3] wb_dat_o[3] -type PO PO
add mapped point wb_dat_o[2] wb_dat_o[2] -type PO PO
add mapped point wb_dat_o[1] wb_dat_o[1] -type PO PO
add mapped point wb_dat_o[0] wb_dat_o[0] -type PO PO
add mapped point wb_ack_o wb_ack_o -type PO PO
add mapped point wb_err_o wb_err_o -type PO PO
add mapped point pwm_out[7] pwm_out[7] -type PO PO
add mapped point pwm_out[6] pwm_out[6] -type PO PO
add mapped point pwm_out[5] pwm_out[5] -type PO PO
add mapped point pwm_out[4] pwm_out[4] -type PO PO
add mapped point pwm_out[3] pwm_out[3] -type PO PO
add mapped point pwm_out[2] pwm_out[2] -type PO PO
add mapped point pwm_out[1] pwm_out[1] -type PO PO
add mapped point pwm_out[0] pwm_out[0] -type PO PO
add mapped point pwm_out_n[7] pwm_out_n[7] -type PO PO
add mapped point pwm_out_n[6] pwm_out_n[6] -type PO PO
add mapped point pwm_out_n[5] pwm_out_n[5] -type PO PO
add mapped point pwm_out_n[4] pwm_out_n[4] -type PO PO
add mapped point pwm_out_n[3] pwm_out_n[3] -type PO PO
add mapped point pwm_out_n[2] pwm_out_n[2] -type PO PO
add mapped point pwm_out_n[1] pwm_out_n[1] -type PO PO
add mapped point pwm_out_n[0] pwm_out_n[0] -type PO PO
add mapped point irq irq -type PO PO
add mapped point pwm_sync_out pwm_sync_out -type PO PO
add mapped point pwm_status[31] pwm_status[31] -type PO PO
add mapped point pwm_status[30] pwm_status[30] -type PO PO
add mapped point pwm_status[29] pwm_status[29] -type PO PO
add mapped point pwm_status[28] pwm_status[28] -type PO PO
add mapped point pwm_status[27] pwm_status[27] -type PO PO
add mapped point pwm_status[26] pwm_status[26] -type PO PO
add mapped point pwm_status[25] pwm_status[25] -type PO PO
add mapped point pwm_status[24] pwm_status[24] -type PO PO
add mapped point pwm_status[23] pwm_status[23] -type PO PO
add mapped point pwm_status[22] pwm_status[22] -type PO PO
add mapped point pwm_status[21] pwm_status[21] -type PO PO
add mapped point pwm_status[20] pwm_status[20] -type PO PO
add mapped point pwm_status[19] pwm_status[19] -type PO PO
add mapped point pwm_status[18] pwm_status[18] -type PO PO
add mapped point pwm_status[17] pwm_status[17] -type PO PO
add mapped point pwm_status[16] pwm_status[16] -type PO PO
add mapped point pwm_status[15] pwm_status[15] -type PO PO
add mapped point pwm_status[14] pwm_status[14] -type PO PO
add mapped point pwm_status[13] pwm_status[13] -type PO PO
add mapped point pwm_status[12] pwm_status[12] -type PO PO
add mapped point pwm_status[11] pwm_status[11] -type PO PO
add mapped point pwm_status[10] pwm_status[10] -type PO PO
add mapped point pwm_status[9] pwm_status[9] -type PO PO
add mapped point pwm_status[8] pwm_status[8] -type PO PO
add mapped point pwm_status[7] pwm_status[7] -type PO PO
add mapped point pwm_status[6] pwm_status[6] -type PO PO
add mapped point pwm_status[5] pwm_status[5] -type PO PO
add mapped point pwm_status[4] pwm_status[4] -type PO PO
add mapped point pwm_status[3] pwm_status[3] -type PO PO
add mapped point pwm_status[2] pwm_status[2] -type PO PO
add mapped point pwm_status[1] pwm_status[1] -type PO PO
add mapped point pwm_status[0] pwm_status[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point pwm_raw_n[0]/q pwm_raw_n_reg[0]/Q -type DFF DFF
add mapped point pwm_raw_n[1]/q pwm_raw_n_reg[1]/Q -type DFF DFF
add mapped point pwm_raw_n[2]/q pwm_raw_n_reg[2]/Q -type DFF DFF
add mapped point pwm_raw_n[3]/q pwm_raw_n_reg[3]/Q -type DFF DFF
add mapped point pwm_raw_n[4]/q pwm_raw_n_reg[4]/Q -type DFF DFF
add mapped point pwm_raw_n[5]/q pwm_raw_n_reg[5]/Q -type DFF DFF
add mapped point pwm_raw_n[6]/q pwm_raw_n_reg[6]/Q -type DFF DFF
add mapped point pwm_raw_n[7]/q pwm_raw_n_reg[7]/Q -type DFF DFF
add mapped point pwm_raw[0]/q pwm_raw_reg[0]/Q -type DFF DFF
add mapped point pwm_raw[1]/q pwm_raw_reg[1]/Q -type DFF DFF
add mapped point pwm_raw[2]/q pwm_raw_reg[2]/Q -type DFF DFF
add mapped point pwm_raw[3]/q pwm_raw_reg[3]/Q -type DFF DFF
add mapped point pwm_raw[4]/q pwm_raw_reg[4]/Q -type DFF DFF
add mapped point pwm_raw[5]/q pwm_raw_reg[5]/Q -type DFF DFF
add mapped point pwm_raw[6]/q pwm_raw_reg[6]/Q -type DFF DFF
add mapped point pwm_raw[7]/q pwm_raw_reg[7]/Q -type DFF DFF
add mapped point wb_ack_reg/q wb_ack_reg_reg/Q -type DFF DFF
add mapped point control_reg[0]/q control_reg_reg[0]/Q -type DFF DFF
add mapped point control_reg[1]/q control_reg_reg[1]/Q -type DFF DFF
add mapped point control_reg[2]/q control_reg_reg[2]/Q -type DFF DFF
add mapped point control_reg[3]/q control_reg_reg[3]/Q -type DFF DFF
add mapped point control_reg[4]/q control_reg_reg[4]/Q -type DFF DFF
add mapped point control_reg[5]/q control_reg_reg[5]/Q -type DFF DFF
add mapped point control_reg[6]/q control_reg_reg[6]/Q -type DFF DFF
add mapped point control_reg[7]/q control_reg_reg[7]/Q -type DFF DFF
add mapped point control_reg[8]/q control_reg_reg[8]/Q -type DFF DFF
add mapped point control_reg[9]/q control_reg_reg[9]/Q -type DFF DFF
add mapped point control_reg[10]/q control_reg_reg[10]/Q -type DFF DFF
add mapped point control_reg[11]/q control_reg_reg[11]/Q -type DFF DFF
add mapped point control_reg[12]/q control_reg_reg[12]/Q -type DFF DFF
add mapped point control_reg[13]/q control_reg_reg[13]/Q -type DFF DFF
add mapped point control_reg[14]/q control_reg_reg[14]/Q -type DFF DFF
add mapped point control_reg[15]/q control_reg_reg[15]/Q -type DFF DFF
add mapped point control_reg[16]/q control_reg_reg[16]/Q -type DFF DFF
add mapped point control_reg[17]/q control_reg_reg[17]/Q -type DFF DFF
add mapped point control_reg[18]/q control_reg_reg[18]/Q -type DFF DFF
add mapped point control_reg[19]/q control_reg_reg[19]/Q -type DFF DFF
add mapped point control_reg[20]/q control_reg_reg[20]/Q -type DFF DFF
add mapped point control_reg[21]/q control_reg_reg[21]/Q -type DFF DFF
add mapped point control_reg[22]/q control_reg_reg[22]/Q -type DFF DFF
add mapped point control_reg[23]/q control_reg_reg[23]/Q -type DFF DFF
add mapped point control_reg[24]/q control_reg_reg[24]/Q -type DFF DFF
add mapped point control_reg[25]/q control_reg_reg[25]/Q -type DFF DFF
add mapped point control_reg[26]/q control_reg_reg[26]/Q -type DFF DFF
add mapped point control_reg[27]/q control_reg_reg[27]/Q -type DFF DFF
add mapped point control_reg[28]/q control_reg_reg[28]/Q -type DFF DFF
add mapped point control_reg[29]/q control_reg_reg[29]/Q -type DFF DFF
add mapped point control_reg[30]/q control_reg_reg[30]/Q -type DFF DFF
add mapped point control_reg[31]/q control_reg_reg[31]/Q -type DFF DFF
add mapped point deadtime_counter[0][0]/q deadtime_counter_reg[0][0]/Q -type DFF DFF
add mapped point deadtime_counter[0][1]/q deadtime_counter_reg[0][1]/Q -type DFF DFF
add mapped point deadtime_counter[0][2]/q deadtime_counter_reg[0][2]/Q -type DFF DFF
add mapped point deadtime_counter[0][3]/q deadtime_counter_reg[0][3]/Q -type DFF DFF
add mapped point deadtime_counter[0][4]/q deadtime_counter_reg[0][4]/Q -type DFF DFF
add mapped point deadtime_counter[0][5]/q deadtime_counter_reg[0][5]/Q -type DFF DFF
add mapped point deadtime_counter[0][6]/q deadtime_counter_reg[0][6]/Q -type DFF DFF
add mapped point deadtime_counter[0][7]/q deadtime_counter_reg[0][7]/Q -type DFF DFF
add mapped point deadtime_counter[0][8]/q deadtime_counter_reg[0][8]/Q -type DFF DFF
add mapped point deadtime_counter[0][9]/q deadtime_counter_reg[0][9]/Q -type DFF DFF
add mapped point deadtime_counter[0][10]/q deadtime_counter_reg[0][10]/Q -type DFF DFF
add mapped point deadtime_counter[0][11]/q deadtime_counter_reg[0][11]/Q -type DFF DFF
add mapped point deadtime_counter[0][12]/q deadtime_counter_reg[0][12]/Q -type DFF DFF
add mapped point deadtime_counter[0][13]/q deadtime_counter_reg[0][13]/Q -type DFF DFF
add mapped point deadtime_counter[0][14]/q deadtime_counter_reg[0][14]/Q -type DFF DFF
add mapped point deadtime_counter[0][15]/q deadtime_counter_reg[0][15]/Q -type DFF DFF
add mapped point deadtime_counter[0][16]/q deadtime_counter_reg[0][16]/Q -type DFF DFF
add mapped point deadtime_counter[0][17]/q deadtime_counter_reg[0][17]/Q -type DFF DFF
add mapped point deadtime_counter[0][18]/q deadtime_counter_reg[0][18]/Q -type DFF DFF
add mapped point deadtime_counter[0][19]/q deadtime_counter_reg[0][19]/Q -type DFF DFF
add mapped point deadtime_counter[0][20]/q deadtime_counter_reg[0][20]/Q -type DFF DFF
add mapped point deadtime_counter[0][21]/q deadtime_counter_reg[0][21]/Q -type DFF DFF
add mapped point deadtime_counter[0][22]/q deadtime_counter_reg[0][22]/Q -type DFF DFF
add mapped point deadtime_counter[0][23]/q deadtime_counter_reg[0][23]/Q -type DFF DFF
add mapped point deadtime_counter[0][24]/q deadtime_counter_reg[0][24]/Q -type DFF DFF
add mapped point deadtime_counter[0][25]/q deadtime_counter_reg[0][25]/Q -type DFF DFF
add mapped point deadtime_counter[0][26]/q deadtime_counter_reg[0][26]/Q -type DFF DFF
add mapped point deadtime_counter[0][27]/q deadtime_counter_reg[0][27]/Q -type DFF DFF
add mapped point deadtime_counter[0][28]/q deadtime_counter_reg[0][28]/Q -type DFF DFF
add mapped point deadtime_counter[0][29]/q deadtime_counter_reg[0][29]/Q -type DFF DFF
add mapped point deadtime_counter[0][30]/q deadtime_counter_reg[0][30]/Q -type DFF DFF
add mapped point deadtime_counter[0][31]/q deadtime_counter_reg[0][31]/Q -type DFF DFF
add mapped point deadtime_counter[1][0]/q deadtime_counter_reg[1][0]/Q -type DFF DFF
add mapped point deadtime_counter[1][1]/q deadtime_counter_reg[1][1]/Q -type DFF DFF
add mapped point deadtime_counter[1][2]/q deadtime_counter_reg[1][2]/Q -type DFF DFF
add mapped point deadtime_counter[1][3]/q deadtime_counter_reg[1][3]/Q -type DFF DFF
add mapped point deadtime_counter[1][4]/q deadtime_counter_reg[1][4]/Q -type DFF DFF
add mapped point deadtime_counter[1][5]/q deadtime_counter_reg[1][5]/Q -type DFF DFF
add mapped point deadtime_counter[1][6]/q deadtime_counter_reg[1][6]/Q -type DFF DFF
add mapped point deadtime_counter[1][7]/q deadtime_counter_reg[1][7]/Q -type DFF DFF
add mapped point deadtime_counter[1][8]/q deadtime_counter_reg[1][8]/Q -type DFF DFF
add mapped point deadtime_counter[1][9]/q deadtime_counter_reg[1][9]/Q -type DFF DFF
add mapped point deadtime_counter[1][10]/q deadtime_counter_reg[1][10]/Q -type DFF DFF
add mapped point deadtime_counter[1][11]/q deadtime_counter_reg[1][11]/Q -type DFF DFF
add mapped point deadtime_counter[1][12]/q deadtime_counter_reg[1][12]/Q -type DFF DFF
add mapped point deadtime_counter[1][13]/q deadtime_counter_reg[1][13]/Q -type DFF DFF
add mapped point deadtime_counter[1][14]/q deadtime_counter_reg[1][14]/Q -type DFF DFF
add mapped point deadtime_counter[1][15]/q deadtime_counter_reg[1][15]/Q -type DFF DFF
add mapped point deadtime_counter[1][16]/q deadtime_counter_reg[1][16]/Q -type DFF DFF
add mapped point deadtime_counter[1][17]/q deadtime_counter_reg[1][17]/Q -type DFF DFF
add mapped point deadtime_counter[1][18]/q deadtime_counter_reg[1][18]/Q -type DFF DFF
add mapped point deadtime_counter[1][19]/q deadtime_counter_reg[1][19]/Q -type DFF DFF
add mapped point deadtime_counter[1][20]/q deadtime_counter_reg[1][20]/Q -type DFF DFF
add mapped point deadtime_counter[1][21]/q deadtime_counter_reg[1][21]/Q -type DFF DFF
add mapped point deadtime_counter[1][22]/q deadtime_counter_reg[1][22]/Q -type DFF DFF
add mapped point deadtime_counter[1][23]/q deadtime_counter_reg[1][23]/Q -type DFF DFF
add mapped point deadtime_counter[1][24]/q deadtime_counter_reg[1][24]/Q -type DFF DFF
add mapped point deadtime_counter[1][25]/q deadtime_counter_reg[1][25]/Q -type DFF DFF
add mapped point deadtime_counter[1][26]/q deadtime_counter_reg[1][26]/Q -type DFF DFF
add mapped point deadtime_counter[1][27]/q deadtime_counter_reg[1][27]/Q -type DFF DFF
add mapped point deadtime_counter[1][28]/q deadtime_counter_reg[1][28]/Q -type DFF DFF
add mapped point deadtime_counter[1][29]/q deadtime_counter_reg[1][29]/Q -type DFF DFF
add mapped point deadtime_counter[1][30]/q deadtime_counter_reg[1][30]/Q -type DFF DFF
add mapped point deadtime_counter[1][31]/q deadtime_counter_reg[1][31]/Q -type DFF DFF
add mapped point deadtime_counter[2][0]/q deadtime_counter_reg[2][0]/Q -type DFF DFF
add mapped point deadtime_counter[2][1]/q deadtime_counter_reg[2][1]/Q -type DFF DFF
add mapped point deadtime_counter[2][2]/q deadtime_counter_reg[2][2]/Q -type DFF DFF
add mapped point deadtime_counter[2][3]/q deadtime_counter_reg[2][3]/Q -type DFF DFF
add mapped point deadtime_counter[2][4]/q deadtime_counter_reg[2][4]/Q -type DFF DFF
add mapped point deadtime_counter[2][5]/q deadtime_counter_reg[2][5]/Q -type DFF DFF
add mapped point deadtime_counter[2][6]/q deadtime_counter_reg[2][6]/Q -type DFF DFF
add mapped point deadtime_counter[2][7]/q deadtime_counter_reg[2][7]/Q -type DFF DFF
add mapped point deadtime_counter[2][8]/q deadtime_counter_reg[2][8]/Q -type DFF DFF
add mapped point deadtime_counter[2][9]/q deadtime_counter_reg[2][9]/Q -type DFF DFF
add mapped point deadtime_counter[2][10]/q deadtime_counter_reg[2][10]/Q -type DFF DFF
add mapped point deadtime_counter[2][11]/q deadtime_counter_reg[2][11]/Q -type DFF DFF
add mapped point deadtime_counter[2][12]/q deadtime_counter_reg[2][12]/Q -type DFF DFF
add mapped point deadtime_counter[2][13]/q deadtime_counter_reg[2][13]/Q -type DFF DFF
add mapped point deadtime_counter[2][14]/q deadtime_counter_reg[2][14]/Q -type DFF DFF
add mapped point deadtime_counter[2][15]/q deadtime_counter_reg[2][15]/Q -type DFF DFF
add mapped point deadtime_counter[2][16]/q deadtime_counter_reg[2][16]/Q -type DFF DFF
add mapped point deadtime_counter[2][17]/q deadtime_counter_reg[2][17]/Q -type DFF DFF
add mapped point deadtime_counter[2][18]/q deadtime_counter_reg[2][18]/Q -type DFF DFF
add mapped point deadtime_counter[2][19]/q deadtime_counter_reg[2][19]/Q -type DFF DFF
add mapped point deadtime_counter[2][20]/q deadtime_counter_reg[2][20]/Q -type DFF DFF
add mapped point deadtime_counter[2][21]/q deadtime_counter_reg[2][21]/Q -type DFF DFF
add mapped point deadtime_counter[2][22]/q deadtime_counter_reg[2][22]/Q -type DFF DFF
add mapped point deadtime_counter[2][23]/q deadtime_counter_reg[2][23]/Q -type DFF DFF
add mapped point deadtime_counter[2][24]/q deadtime_counter_reg[2][24]/Q -type DFF DFF
add mapped point deadtime_counter[2][25]/q deadtime_counter_reg[2][25]/Q -type DFF DFF
add mapped point deadtime_counter[2][26]/q deadtime_counter_reg[2][26]/Q -type DFF DFF
add mapped point deadtime_counter[2][27]/q deadtime_counter_reg[2][27]/Q -type DFF DFF
add mapped point deadtime_counter[2][28]/q deadtime_counter_reg[2][28]/Q -type DFF DFF
add mapped point deadtime_counter[2][29]/q deadtime_counter_reg[2][29]/Q -type DFF DFF
add mapped point deadtime_counter[2][30]/q deadtime_counter_reg[2][30]/Q -type DFF DFF
add mapped point deadtime_counter[2][31]/q deadtime_counter_reg[2][31]/Q -type DFF DFF
add mapped point deadtime_counter[3][0]/q deadtime_counter_reg[3][0]/Q -type DFF DFF
add mapped point deadtime_counter[3][1]/q deadtime_counter_reg[3][1]/Q -type DFF DFF
add mapped point deadtime_counter[3][2]/q deadtime_counter_reg[3][2]/Q -type DFF DFF
add mapped point deadtime_counter[3][3]/q deadtime_counter_reg[3][3]/Q -type DFF DFF
add mapped point deadtime_counter[3][4]/q deadtime_counter_reg[3][4]/Q -type DFF DFF
add mapped point deadtime_counter[3][5]/q deadtime_counter_reg[3][5]/Q -type DFF DFF
add mapped point deadtime_counter[3][6]/q deadtime_counter_reg[3][6]/Q -type DFF DFF
add mapped point deadtime_counter[3][7]/q deadtime_counter_reg[3][7]/Q -type DFF DFF
add mapped point deadtime_counter[3][8]/q deadtime_counter_reg[3][8]/Q -type DFF DFF
add mapped point deadtime_counter[3][9]/q deadtime_counter_reg[3][9]/Q -type DFF DFF
add mapped point deadtime_counter[3][10]/q deadtime_counter_reg[3][10]/Q -type DFF DFF
add mapped point deadtime_counter[3][11]/q deadtime_counter_reg[3][11]/Q -type DFF DFF
add mapped point deadtime_counter[3][12]/q deadtime_counter_reg[3][12]/Q -type DFF DFF
add mapped point deadtime_counter[3][13]/q deadtime_counter_reg[3][13]/Q -type DFF DFF
add mapped point deadtime_counter[3][14]/q deadtime_counter_reg[3][14]/Q -type DFF DFF
add mapped point deadtime_counter[3][15]/q deadtime_counter_reg[3][15]/Q -type DFF DFF
add mapped point deadtime_counter[3][16]/q deadtime_counter_reg[3][16]/Q -type DFF DFF
add mapped point deadtime_counter[3][17]/q deadtime_counter_reg[3][17]/Q -type DFF DFF
add mapped point deadtime_counter[3][18]/q deadtime_counter_reg[3][18]/Q -type DFF DFF
add mapped point deadtime_counter[3][19]/q deadtime_counter_reg[3][19]/Q -type DFF DFF
add mapped point deadtime_counter[3][20]/q deadtime_counter_reg[3][20]/Q -type DFF DFF
add mapped point deadtime_counter[3][21]/q deadtime_counter_reg[3][21]/Q -type DFF DFF
add mapped point deadtime_counter[3][22]/q deadtime_counter_reg[3][22]/Q -type DFF DFF
add mapped point deadtime_counter[3][23]/q deadtime_counter_reg[3][23]/Q -type DFF DFF
add mapped point deadtime_counter[3][24]/q deadtime_counter_reg[3][24]/Q -type DFF DFF
add mapped point deadtime_counter[3][25]/q deadtime_counter_reg[3][25]/Q -type DFF DFF
add mapped point deadtime_counter[3][26]/q deadtime_counter_reg[3][26]/Q -type DFF DFF
add mapped point deadtime_counter[3][27]/q deadtime_counter_reg[3][27]/Q -type DFF DFF
add mapped point deadtime_counter[3][28]/q deadtime_counter_reg[3][28]/Q -type DFF DFF
add mapped point deadtime_counter[3][29]/q deadtime_counter_reg[3][29]/Q -type DFF DFF
add mapped point deadtime_counter[3][30]/q deadtime_counter_reg[3][30]/Q -type DFF DFF
add mapped point deadtime_counter[3][31]/q deadtime_counter_reg[3][31]/Q -type DFF DFF
add mapped point deadtime_counter[4][0]/q deadtime_counter_reg[4][0]/Q -type DFF DFF
add mapped point deadtime_counter[4][1]/q deadtime_counter_reg[4][1]/Q -type DFF DFF
add mapped point deadtime_counter[4][2]/q deadtime_counter_reg[4][2]/Q -type DFF DFF
add mapped point deadtime_counter[4][3]/q deadtime_counter_reg[4][3]/Q -type DFF DFF
add mapped point deadtime_counter[4][4]/q deadtime_counter_reg[4][4]/Q -type DFF DFF
add mapped point deadtime_counter[4][5]/q deadtime_counter_reg[4][5]/Q -type DFF DFF
add mapped point deadtime_counter[4][6]/q deadtime_counter_reg[4][6]/Q -type DFF DFF
add mapped point deadtime_counter[4][7]/q deadtime_counter_reg[4][7]/Q -type DFF DFF
add mapped point deadtime_counter[4][8]/q deadtime_counter_reg[4][8]/Q -type DFF DFF
add mapped point deadtime_counter[4][9]/q deadtime_counter_reg[4][9]/Q -type DFF DFF
add mapped point deadtime_counter[4][10]/q deadtime_counter_reg[4][10]/Q -type DFF DFF
add mapped point deadtime_counter[4][11]/q deadtime_counter_reg[4][11]/Q -type DFF DFF
add mapped point deadtime_counter[4][12]/q deadtime_counter_reg[4][12]/Q -type DFF DFF
add mapped point deadtime_counter[4][13]/q deadtime_counter_reg[4][13]/Q -type DFF DFF
add mapped point deadtime_counter[4][14]/q deadtime_counter_reg[4][14]/Q -type DFF DFF
add mapped point deadtime_counter[4][15]/q deadtime_counter_reg[4][15]/Q -type DFF DFF
add mapped point deadtime_counter[4][16]/q deadtime_counter_reg[4][16]/Q -type DFF DFF
add mapped point deadtime_counter[4][17]/q deadtime_counter_reg[4][17]/Q -type DFF DFF
add mapped point deadtime_counter[4][18]/q deadtime_counter_reg[4][18]/Q -type DFF DFF
add mapped point deadtime_counter[4][19]/q deadtime_counter_reg[4][19]/Q -type DFF DFF
add mapped point deadtime_counter[4][20]/q deadtime_counter_reg[4][20]/Q -type DFF DFF
add mapped point deadtime_counter[4][21]/q deadtime_counter_reg[4][21]/Q -type DFF DFF
add mapped point deadtime_counter[4][22]/q deadtime_counter_reg[4][22]/Q -type DFF DFF
add mapped point deadtime_counter[4][23]/q deadtime_counter_reg[4][23]/Q -type DFF DFF
add mapped point deadtime_counter[4][24]/q deadtime_counter_reg[4][24]/Q -type DFF DFF
add mapped point deadtime_counter[4][25]/q deadtime_counter_reg[4][25]/Q -type DFF DFF
add mapped point deadtime_counter[4][26]/q deadtime_counter_reg[4][26]/Q -type DFF DFF
add mapped point deadtime_counter[4][27]/q deadtime_counter_reg[4][27]/Q -type DFF DFF
add mapped point deadtime_counter[4][28]/q deadtime_counter_reg[4][28]/Q -type DFF DFF
add mapped point deadtime_counter[4][29]/q deadtime_counter_reg[4][29]/Q -type DFF DFF
add mapped point deadtime_counter[4][30]/q deadtime_counter_reg[4][30]/Q -type DFF DFF
add mapped point deadtime_counter[4][31]/q deadtime_counter_reg[4][31]/Q -type DFF DFF
add mapped point deadtime_counter[5][0]/q deadtime_counter_reg[5][0]/Q -type DFF DFF
add mapped point deadtime_counter[5][1]/q deadtime_counter_reg[5][1]/Q -type DFF DFF
add mapped point deadtime_counter[5][2]/q deadtime_counter_reg[5][2]/Q -type DFF DFF
add mapped point deadtime_counter[5][3]/q deadtime_counter_reg[5][3]/Q -type DFF DFF
add mapped point deadtime_counter[5][4]/q deadtime_counter_reg[5][4]/Q -type DFF DFF
add mapped point deadtime_counter[5][5]/q deadtime_counter_reg[5][5]/Q -type DFF DFF
add mapped point deadtime_counter[5][6]/q deadtime_counter_reg[5][6]/Q -type DFF DFF
add mapped point deadtime_counter[5][7]/q deadtime_counter_reg[5][7]/Q -type DFF DFF
add mapped point deadtime_counter[5][8]/q deadtime_counter_reg[5][8]/Q -type DFF DFF
add mapped point deadtime_counter[5][9]/q deadtime_counter_reg[5][9]/Q -type DFF DFF
add mapped point deadtime_counter[5][10]/q deadtime_counter_reg[5][10]/Q -type DFF DFF
add mapped point deadtime_counter[5][11]/q deadtime_counter_reg[5][11]/Q -type DFF DFF
add mapped point deadtime_counter[5][12]/q deadtime_counter_reg[5][12]/Q -type DFF DFF
add mapped point deadtime_counter[5][13]/q deadtime_counter_reg[5][13]/Q -type DFF DFF
add mapped point deadtime_counter[5][14]/q deadtime_counter_reg[5][14]/Q -type DFF DFF
add mapped point deadtime_counter[5][15]/q deadtime_counter_reg[5][15]/Q -type DFF DFF
add mapped point deadtime_counter[5][16]/q deadtime_counter_reg[5][16]/Q -type DFF DFF
add mapped point deadtime_counter[5][17]/q deadtime_counter_reg[5][17]/Q -type DFF DFF
add mapped point deadtime_counter[5][18]/q deadtime_counter_reg[5][18]/Q -type DFF DFF
add mapped point deadtime_counter[5][19]/q deadtime_counter_reg[5][19]/Q -type DFF DFF
add mapped point deadtime_counter[5][20]/q deadtime_counter_reg[5][20]/Q -type DFF DFF
add mapped point deadtime_counter[5][21]/q deadtime_counter_reg[5][21]/Q -type DFF DFF
add mapped point deadtime_counter[5][22]/q deadtime_counter_reg[5][22]/Q -type DFF DFF
add mapped point deadtime_counter[5][23]/q deadtime_counter_reg[5][23]/Q -type DFF DFF
add mapped point deadtime_counter[5][24]/q deadtime_counter_reg[5][24]/Q -type DFF DFF
add mapped point deadtime_counter[5][25]/q deadtime_counter_reg[5][25]/Q -type DFF DFF
add mapped point deadtime_counter[5][26]/q deadtime_counter_reg[5][26]/Q -type DFF DFF
add mapped point deadtime_counter[5][27]/q deadtime_counter_reg[5][27]/Q -type DFF DFF
add mapped point deadtime_counter[5][28]/q deadtime_counter_reg[5][28]/Q -type DFF DFF
add mapped point deadtime_counter[5][29]/q deadtime_counter_reg[5][29]/Q -type DFF DFF
add mapped point deadtime_counter[5][30]/q deadtime_counter_reg[5][30]/Q -type DFF DFF
add mapped point deadtime_counter[5][31]/q deadtime_counter_reg[5][31]/Q -type DFF DFF
add mapped point deadtime_counter[6][0]/q deadtime_counter_reg[6][0]/Q -type DFF DFF
add mapped point deadtime_counter[6][1]/q deadtime_counter_reg[6][1]/Q -type DFF DFF
add mapped point deadtime_counter[6][2]/q deadtime_counter_reg[6][2]/Q -type DFF DFF
add mapped point deadtime_counter[6][3]/q deadtime_counter_reg[6][3]/Q -type DFF DFF
add mapped point deadtime_counter[6][4]/q deadtime_counter_reg[6][4]/Q -type DFF DFF
add mapped point deadtime_counter[6][5]/q deadtime_counter_reg[6][5]/Q -type DFF DFF
add mapped point deadtime_counter[6][6]/q deadtime_counter_reg[6][6]/Q -type DFF DFF
add mapped point deadtime_counter[6][7]/q deadtime_counter_reg[6][7]/Q -type DFF DFF
add mapped point deadtime_counter[6][8]/q deadtime_counter_reg[6][8]/Q -type DFF DFF
add mapped point deadtime_counter[6][9]/q deadtime_counter_reg[6][9]/Q -type DFF DFF
add mapped point deadtime_counter[6][10]/q deadtime_counter_reg[6][10]/Q -type DFF DFF
add mapped point deadtime_counter[6][11]/q deadtime_counter_reg[6][11]/Q -type DFF DFF
add mapped point deadtime_counter[6][12]/q deadtime_counter_reg[6][12]/Q -type DFF DFF
add mapped point deadtime_counter[6][13]/q deadtime_counter_reg[6][13]/Q -type DFF DFF
add mapped point deadtime_counter[6][14]/q deadtime_counter_reg[6][14]/Q -type DFF DFF
add mapped point deadtime_counter[6][15]/q deadtime_counter_reg[6][15]/Q -type DFF DFF
add mapped point deadtime_counter[6][16]/q deadtime_counter_reg[6][16]/Q -type DFF DFF
add mapped point deadtime_counter[6][17]/q deadtime_counter_reg[6][17]/Q -type DFF DFF
add mapped point deadtime_counter[6][18]/q deadtime_counter_reg[6][18]/Q -type DFF DFF
add mapped point deadtime_counter[6][19]/q deadtime_counter_reg[6][19]/Q -type DFF DFF
add mapped point deadtime_counter[6][20]/q deadtime_counter_reg[6][20]/Q -type DFF DFF
add mapped point deadtime_counter[6][21]/q deadtime_counter_reg[6][21]/Q -type DFF DFF
add mapped point deadtime_counter[6][22]/q deadtime_counter_reg[6][22]/Q -type DFF DFF
add mapped point deadtime_counter[6][23]/q deadtime_counter_reg[6][23]/Q -type DFF DFF
add mapped point deadtime_counter[6][24]/q deadtime_counter_reg[6][24]/Q -type DFF DFF
add mapped point deadtime_counter[6][25]/q deadtime_counter_reg[6][25]/Q -type DFF DFF
add mapped point deadtime_counter[6][26]/q deadtime_counter_reg[6][26]/Q -type DFF DFF
add mapped point deadtime_counter[6][27]/q deadtime_counter_reg[6][27]/Q -type DFF DFF
add mapped point deadtime_counter[6][28]/q deadtime_counter_reg[6][28]/Q -type DFF DFF
add mapped point deadtime_counter[6][29]/q deadtime_counter_reg[6][29]/Q -type DFF DFF
add mapped point deadtime_counter[6][30]/q deadtime_counter_reg[6][30]/Q -type DFF DFF
add mapped point deadtime_counter[6][31]/q deadtime_counter_reg[6][31]/Q -type DFF DFF
add mapped point deadtime_counter[7][0]/q deadtime_counter_reg[7][0]/Q -type DFF DFF
add mapped point deadtime_counter[7][1]/q deadtime_counter_reg[7][1]/Q -type DFF DFF
add mapped point deadtime_counter[7][2]/q deadtime_counter_reg[7][2]/Q -type DFF DFF
add mapped point deadtime_counter[7][3]/q deadtime_counter_reg[7][3]/Q -type DFF DFF
add mapped point deadtime_counter[7][4]/q deadtime_counter_reg[7][4]/Q -type DFF DFF
add mapped point deadtime_counter[7][5]/q deadtime_counter_reg[7][5]/Q -type DFF DFF
add mapped point deadtime_counter[7][6]/q deadtime_counter_reg[7][6]/Q -type DFF DFF
add mapped point deadtime_counter[7][7]/q deadtime_counter_reg[7][7]/Q -type DFF DFF
add mapped point deadtime_counter[7][8]/q deadtime_counter_reg[7][8]/Q -type DFF DFF
add mapped point deadtime_counter[7][9]/q deadtime_counter_reg[7][9]/Q -type DFF DFF
add mapped point deadtime_counter[7][10]/q deadtime_counter_reg[7][10]/Q -type DFF DFF
add mapped point deadtime_counter[7][11]/q deadtime_counter_reg[7][11]/Q -type DFF DFF
add mapped point deadtime_counter[7][12]/q deadtime_counter_reg[7][12]/Q -type DFF DFF
add mapped point deadtime_counter[7][13]/q deadtime_counter_reg[7][13]/Q -type DFF DFF
add mapped point deadtime_counter[7][14]/q deadtime_counter_reg[7][14]/Q -type DFF DFF
add mapped point deadtime_counter[7][15]/q deadtime_counter_reg[7][15]/Q -type DFF DFF
add mapped point deadtime_counter[7][16]/q deadtime_counter_reg[7][16]/Q -type DFF DFF
add mapped point deadtime_counter[7][17]/q deadtime_counter_reg[7][17]/Q -type DFF DFF
add mapped point deadtime_counter[7][18]/q deadtime_counter_reg[7][18]/Q -type DFF DFF
add mapped point deadtime_counter[7][19]/q deadtime_counter_reg[7][19]/Q -type DFF DFF
add mapped point deadtime_counter[7][20]/q deadtime_counter_reg[7][20]/Q -type DFF DFF
add mapped point deadtime_counter[7][21]/q deadtime_counter_reg[7][21]/Q -type DFF DFF
add mapped point deadtime_counter[7][22]/q deadtime_counter_reg[7][22]/Q -type DFF DFF
add mapped point deadtime_counter[7][23]/q deadtime_counter_reg[7][23]/Q -type DFF DFF
add mapped point deadtime_counter[7][24]/q deadtime_counter_reg[7][24]/Q -type DFF DFF
add mapped point deadtime_counter[7][25]/q deadtime_counter_reg[7][25]/Q -type DFF DFF
add mapped point deadtime_counter[7][26]/q deadtime_counter_reg[7][26]/Q -type DFF DFF
add mapped point deadtime_counter[7][27]/q deadtime_counter_reg[7][27]/Q -type DFF DFF
add mapped point deadtime_counter[7][28]/q deadtime_counter_reg[7][28]/Q -type DFF DFF
add mapped point deadtime_counter[7][29]/q deadtime_counter_reg[7][29]/Q -type DFF DFF
add mapped point deadtime_counter[7][30]/q deadtime_counter_reg[7][30]/Q -type DFF DFF
add mapped point deadtime_counter[7][31]/q deadtime_counter_reg[7][31]/Q -type DFF DFF
add mapped point deadtime_reg[0]/q deadtime_reg_reg[0]/Q -type DFF DFF
add mapped point deadtime_reg[1]/q deadtime_reg_reg[1]/Q -type DFF DFF
add mapped point deadtime_reg[2]/q deadtime_reg_reg[2]/Q -type DFF DFF
add mapped point deadtime_reg[3]/q deadtime_reg_reg[3]/Q -type DFF DFF
add mapped point deadtime_reg[4]/q deadtime_reg_reg[4]/Q -type DFF DFF
add mapped point deadtime_reg[5]/q deadtime_reg_reg[5]/Q -type DFF DFF
add mapped point deadtime_reg[6]/q deadtime_reg_reg[6]/Q -type DFF DFF
add mapped point deadtime_reg[7]/q deadtime_reg_reg[7]/Q -type DFF DFF
add mapped point deadtime_reg[8]/q deadtime_reg_reg[8]/Q -type DFF DFF
add mapped point deadtime_reg[9]/q deadtime_reg_reg[9]/Q -type DFF DFF
add mapped point deadtime_reg[10]/q deadtime_reg_reg[10]/Q -type DFF DFF
add mapped point deadtime_reg[11]/q deadtime_reg_reg[11]/Q -type DFF DFF
add mapped point deadtime_reg[12]/q deadtime_reg_reg[12]/Q -type DFF DFF
add mapped point deadtime_reg[13]/q deadtime_reg_reg[13]/Q -type DFF DFF
add mapped point deadtime_reg[14]/q deadtime_reg_reg[14]/Q -type DFF DFF
add mapped point deadtime_reg[15]/q deadtime_reg_reg[15]/Q -type DFF DFF
add mapped point deadtime_reg[16]/q deadtime_reg_reg[16]/Q -type DFF DFF
add mapped point deadtime_reg[17]/q deadtime_reg_reg[17]/Q -type DFF DFF
add mapped point deadtime_reg[18]/q deadtime_reg_reg[18]/Q -type DFF DFF
add mapped point deadtime_reg[19]/q deadtime_reg_reg[19]/Q -type DFF DFF
add mapped point deadtime_reg[20]/q deadtime_reg_reg[20]/Q -type DFF DFF
add mapped point deadtime_reg[21]/q deadtime_reg_reg[21]/Q -type DFF DFF
add mapped point deadtime_reg[22]/q deadtime_reg_reg[22]/Q -type DFF DFF
add mapped point deadtime_reg[23]/q deadtime_reg_reg[23]/Q -type DFF DFF
add mapped point deadtime_reg[24]/q deadtime_reg_reg[24]/Q -type DFF DFF
add mapped point deadtime_reg[25]/q deadtime_reg_reg[25]/Q -type DFF DFF
add mapped point deadtime_reg[26]/q deadtime_reg_reg[26]/Q -type DFF DFF
add mapped point deadtime_reg[27]/q deadtime_reg_reg[27]/Q -type DFF DFF
add mapped point deadtime_reg[28]/q deadtime_reg_reg[28]/Q -type DFF DFF
add mapped point deadtime_reg[29]/q deadtime_reg_reg[29]/Q -type DFF DFF
add mapped point deadtime_reg[30]/q deadtime_reg_reg[30]/Q -type DFF DFF
add mapped point deadtime_reg[31]/q deadtime_reg_reg[31]/Q -type DFF DFF
add mapped point duty_cycle[0][0]/q duty_cycle_reg[0][0]/Q -type DFF DFF
add mapped point duty_cycle[0][1]/q duty_cycle_reg[0][1]/Q -type DFF DFF
add mapped point duty_cycle[0][2]/q duty_cycle_reg[0][2]/Q -type DFF DFF
add mapped point duty_cycle[0][3]/q duty_cycle_reg[0][3]/Q -type DFF DFF
add mapped point duty_cycle[0][4]/q duty_cycle_reg[0][4]/Q -type DFF DFF
add mapped point duty_cycle[0][5]/q duty_cycle_reg[0][5]/Q -type DFF DFF
add mapped point duty_cycle[0][6]/q duty_cycle_reg[0][6]/Q -type DFF DFF
add mapped point duty_cycle[0][7]/q duty_cycle_reg[0][7]/Q -type DFF DFF
add mapped point duty_cycle[0][8]/q duty_cycle_reg[0][8]/Q -type DFF DFF
add mapped point duty_cycle[0][9]/q duty_cycle_reg[0][9]/Q -type DFF DFF
add mapped point duty_cycle[0][10]/q duty_cycle_reg[0][10]/Q -type DFF DFF
add mapped point duty_cycle[0][11]/q duty_cycle_reg[0][11]/Q -type DFF DFF
add mapped point duty_cycle[0][12]/q duty_cycle_reg[0][12]/Q -type DFF DFF
add mapped point duty_cycle[0][13]/q duty_cycle_reg[0][13]/Q -type DFF DFF
add mapped point duty_cycle[0][14]/q duty_cycle_reg[0][14]/Q -type DFF DFF
add mapped point duty_cycle[0][15]/q duty_cycle_reg[0][15]/Q -type DFF DFF
add mapped point duty_cycle[0][16]/q duty_cycle_reg[0][16]/Q -type DFF DFF
add mapped point duty_cycle[0][17]/q duty_cycle_reg[0][17]/Q -type DFF DFF
add mapped point duty_cycle[0][18]/q duty_cycle_reg[0][18]/Q -type DFF DFF
add mapped point duty_cycle[0][19]/q duty_cycle_reg[0][19]/Q -type DFF DFF
add mapped point duty_cycle[0][20]/q duty_cycle_reg[0][20]/Q -type DFF DFF
add mapped point duty_cycle[0][21]/q duty_cycle_reg[0][21]/Q -type DFF DFF
add mapped point duty_cycle[0][22]/q duty_cycle_reg[0][22]/Q -type DFF DFF
add mapped point duty_cycle[0][23]/q duty_cycle_reg[0][23]/Q -type DFF DFF
add mapped point duty_cycle[0][24]/q duty_cycle_reg[0][24]/Q -type DFF DFF
add mapped point duty_cycle[0][25]/q duty_cycle_reg[0][25]/Q -type DFF DFF
add mapped point duty_cycle[0][26]/q duty_cycle_reg[0][26]/Q -type DFF DFF
add mapped point duty_cycle[0][27]/q duty_cycle_reg[0][27]/Q -type DFF DFF
add mapped point duty_cycle[0][28]/q duty_cycle_reg[0][28]/Q -type DFF DFF
add mapped point duty_cycle[0][29]/q duty_cycle_reg[0][29]/Q -type DFF DFF
add mapped point duty_cycle[0][30]/q duty_cycle_reg[0][30]/Q -type DFF DFF
add mapped point duty_cycle[0][31]/q duty_cycle_reg[0][31]/Q -type DFF DFF
add mapped point duty_cycle[1][0]/q duty_cycle_reg[1][0]/Q -type DFF DFF
add mapped point duty_cycle[1][1]/q duty_cycle_reg[1][1]/Q -type DFF DFF
add mapped point duty_cycle[1][2]/q duty_cycle_reg[1][2]/Q -type DFF DFF
add mapped point duty_cycle[1][3]/q duty_cycle_reg[1][3]/Q -type DFF DFF
add mapped point duty_cycle[1][4]/q duty_cycle_reg[1][4]/Q -type DFF DFF
add mapped point duty_cycle[1][5]/q duty_cycle_reg[1][5]/Q -type DFF DFF
add mapped point duty_cycle[1][6]/q duty_cycle_reg[1][6]/Q -type DFF DFF
add mapped point duty_cycle[1][7]/q duty_cycle_reg[1][7]/Q -type DFF DFF
add mapped point duty_cycle[1][8]/q duty_cycle_reg[1][8]/Q -type DFF DFF
add mapped point duty_cycle[1][9]/q duty_cycle_reg[1][9]/Q -type DFF DFF
add mapped point duty_cycle[1][10]/q duty_cycle_reg[1][10]/Q -type DFF DFF
add mapped point duty_cycle[1][11]/q duty_cycle_reg[1][11]/Q -type DFF DFF
add mapped point duty_cycle[1][12]/q duty_cycle_reg[1][12]/Q -type DFF DFF
add mapped point duty_cycle[1][13]/q duty_cycle_reg[1][13]/Q -type DFF DFF
add mapped point duty_cycle[1][14]/q duty_cycle_reg[1][14]/Q -type DFF DFF
add mapped point duty_cycle[1][15]/q duty_cycle_reg[1][15]/Q -type DFF DFF
add mapped point duty_cycle[1][16]/q duty_cycle_reg[1][16]/Q -type DFF DFF
add mapped point duty_cycle[1][17]/q duty_cycle_reg[1][17]/Q -type DFF DFF
add mapped point duty_cycle[1][18]/q duty_cycle_reg[1][18]/Q -type DFF DFF
add mapped point duty_cycle[1][19]/q duty_cycle_reg[1][19]/Q -type DFF DFF
add mapped point duty_cycle[1][20]/q duty_cycle_reg[1][20]/Q -type DFF DFF
add mapped point duty_cycle[1][21]/q duty_cycle_reg[1][21]/Q -type DFF DFF
add mapped point duty_cycle[1][22]/q duty_cycle_reg[1][22]/Q -type DFF DFF
add mapped point duty_cycle[1][23]/q duty_cycle_reg[1][23]/Q -type DFF DFF
add mapped point duty_cycle[1][24]/q duty_cycle_reg[1][24]/Q -type DFF DFF
add mapped point duty_cycle[1][25]/q duty_cycle_reg[1][25]/Q -type DFF DFF
add mapped point duty_cycle[1][26]/q duty_cycle_reg[1][26]/Q -type DFF DFF
add mapped point duty_cycle[1][27]/q duty_cycle_reg[1][27]/Q -type DFF DFF
add mapped point duty_cycle[1][28]/q duty_cycle_reg[1][28]/Q -type DFF DFF
add mapped point duty_cycle[1][29]/q duty_cycle_reg[1][29]/Q -type DFF DFF
add mapped point duty_cycle[1][30]/q duty_cycle_reg[1][30]/Q -type DFF DFF
add mapped point duty_cycle[1][31]/q duty_cycle_reg[1][31]/Q -type DFF DFF
add mapped point duty_cycle[2][0]/q duty_cycle_reg[2][0]/Q -type DFF DFF
add mapped point duty_cycle[2][1]/q duty_cycle_reg[2][1]/Q -type DFF DFF
add mapped point duty_cycle[2][2]/q duty_cycle_reg[2][2]/Q -type DFF DFF
add mapped point duty_cycle[2][3]/q duty_cycle_reg[2][3]/Q -type DFF DFF
add mapped point duty_cycle[2][4]/q duty_cycle_reg[2][4]/Q -type DFF DFF
add mapped point duty_cycle[2][5]/q duty_cycle_reg[2][5]/Q -type DFF DFF
add mapped point duty_cycle[2][6]/q duty_cycle_reg[2][6]/Q -type DFF DFF
add mapped point duty_cycle[2][7]/q duty_cycle_reg[2][7]/Q -type DFF DFF
add mapped point duty_cycle[2][8]/q duty_cycle_reg[2][8]/Q -type DFF DFF
add mapped point duty_cycle[2][9]/q duty_cycle_reg[2][9]/Q -type DFF DFF
add mapped point duty_cycle[2][10]/q duty_cycle_reg[2][10]/Q -type DFF DFF
add mapped point duty_cycle[2][11]/q duty_cycle_reg[2][11]/Q -type DFF DFF
add mapped point duty_cycle[2][12]/q duty_cycle_reg[2][12]/Q -type DFF DFF
add mapped point duty_cycle[2][13]/q duty_cycle_reg[2][13]/Q -type DFF DFF
add mapped point duty_cycle[2][14]/q duty_cycle_reg[2][14]/Q -type DFF DFF
add mapped point duty_cycle[2][15]/q duty_cycle_reg[2][15]/Q -type DFF DFF
add mapped point duty_cycle[2][16]/q duty_cycle_reg[2][16]/Q -type DFF DFF
add mapped point duty_cycle[2][17]/q duty_cycle_reg[2][17]/Q -type DFF DFF
add mapped point duty_cycle[2][18]/q duty_cycle_reg[2][18]/Q -type DFF DFF
add mapped point duty_cycle[2][19]/q duty_cycle_reg[2][19]/Q -type DFF DFF
add mapped point duty_cycle[2][20]/q duty_cycle_reg[2][20]/Q -type DFF DFF
add mapped point duty_cycle[2][21]/q duty_cycle_reg[2][21]/Q -type DFF DFF
add mapped point duty_cycle[2][22]/q duty_cycle_reg[2][22]/Q -type DFF DFF
add mapped point duty_cycle[2][23]/q duty_cycle_reg[2][23]/Q -type DFF DFF
add mapped point duty_cycle[2][24]/q duty_cycle_reg[2][24]/Q -type DFF DFF
add mapped point duty_cycle[2][25]/q duty_cycle_reg[2][25]/Q -type DFF DFF
add mapped point duty_cycle[2][26]/q duty_cycle_reg[2][26]/Q -type DFF DFF
add mapped point duty_cycle[2][27]/q duty_cycle_reg[2][27]/Q -type DFF DFF
add mapped point duty_cycle[2][28]/q duty_cycle_reg[2][28]/Q -type DFF DFF
add mapped point duty_cycle[2][29]/q duty_cycle_reg[2][29]/Q -type DFF DFF
add mapped point duty_cycle[2][30]/q duty_cycle_reg[2][30]/Q -type DFF DFF
add mapped point duty_cycle[2][31]/q duty_cycle_reg[2][31]/Q -type DFF DFF
add mapped point duty_cycle[3][0]/q duty_cycle_reg[3][0]/Q -type DFF DFF
add mapped point duty_cycle[3][1]/q duty_cycle_reg[3][1]/Q -type DFF DFF
add mapped point duty_cycle[3][2]/q duty_cycle_reg[3][2]/Q -type DFF DFF
add mapped point duty_cycle[3][3]/q duty_cycle_reg[3][3]/Q -type DFF DFF
add mapped point duty_cycle[3][4]/q duty_cycle_reg[3][4]/Q -type DFF DFF
add mapped point duty_cycle[3][5]/q duty_cycle_reg[3][5]/Q -type DFF DFF
add mapped point duty_cycle[3][6]/q duty_cycle_reg[3][6]/Q -type DFF DFF
add mapped point duty_cycle[3][7]/q duty_cycle_reg[3][7]/Q -type DFF DFF
add mapped point duty_cycle[3][8]/q duty_cycle_reg[3][8]/Q -type DFF DFF
add mapped point duty_cycle[3][9]/q duty_cycle_reg[3][9]/Q -type DFF DFF
add mapped point duty_cycle[3][10]/q duty_cycle_reg[3][10]/Q -type DFF DFF
add mapped point duty_cycle[3][11]/q duty_cycle_reg[3][11]/Q -type DFF DFF
add mapped point duty_cycle[3][12]/q duty_cycle_reg[3][12]/Q -type DFF DFF
add mapped point duty_cycle[3][13]/q duty_cycle_reg[3][13]/Q -type DFF DFF
add mapped point duty_cycle[3][14]/q duty_cycle_reg[3][14]/Q -type DFF DFF
add mapped point duty_cycle[3][15]/q duty_cycle_reg[3][15]/Q -type DFF DFF
add mapped point duty_cycle[3][16]/q duty_cycle_reg[3][16]/Q -type DFF DFF
add mapped point duty_cycle[3][17]/q duty_cycle_reg[3][17]/Q -type DFF DFF
add mapped point duty_cycle[3][18]/q duty_cycle_reg[3][18]/Q -type DFF DFF
add mapped point duty_cycle[3][19]/q duty_cycle_reg[3][19]/Q -type DFF DFF
add mapped point duty_cycle[3][20]/q duty_cycle_reg[3][20]/Q -type DFF DFF
add mapped point duty_cycle[3][21]/q duty_cycle_reg[3][21]/Q -type DFF DFF
add mapped point duty_cycle[3][22]/q duty_cycle_reg[3][22]/Q -type DFF DFF
add mapped point duty_cycle[3][23]/q duty_cycle_reg[3][23]/Q -type DFF DFF
add mapped point duty_cycle[3][24]/q duty_cycle_reg[3][24]/Q -type DFF DFF
add mapped point duty_cycle[3][25]/q duty_cycle_reg[3][25]/Q -type DFF DFF
add mapped point duty_cycle[3][26]/q duty_cycle_reg[3][26]/Q -type DFF DFF
add mapped point duty_cycle[3][27]/q duty_cycle_reg[3][27]/Q -type DFF DFF
add mapped point duty_cycle[3][28]/q duty_cycle_reg[3][28]/Q -type DFF DFF
add mapped point duty_cycle[3][29]/q duty_cycle_reg[3][29]/Q -type DFF DFF
add mapped point duty_cycle[3][30]/q duty_cycle_reg[3][30]/Q -type DFF DFF
add mapped point duty_cycle[3][31]/q duty_cycle_reg[3][31]/Q -type DFF DFF
add mapped point duty_cycle[4][0]/q duty_cycle_reg[4][0]/Q -type DFF DFF
add mapped point duty_cycle[4][1]/q duty_cycle_reg[4][1]/Q -type DFF DFF
add mapped point duty_cycle[4][2]/q duty_cycle_reg[4][2]/Q -type DFF DFF
add mapped point duty_cycle[4][3]/q duty_cycle_reg[4][3]/Q -type DFF DFF
add mapped point duty_cycle[4][4]/q duty_cycle_reg[4][4]/Q -type DFF DFF
add mapped point duty_cycle[4][5]/q duty_cycle_reg[4][5]/Q -type DFF DFF
add mapped point duty_cycle[4][6]/q duty_cycle_reg[4][6]/Q -type DFF DFF
add mapped point duty_cycle[4][7]/q duty_cycle_reg[4][7]/Q -type DFF DFF
add mapped point duty_cycle[4][8]/q duty_cycle_reg[4][8]/Q -type DFF DFF
add mapped point duty_cycle[4][9]/q duty_cycle_reg[4][9]/Q -type DFF DFF
add mapped point duty_cycle[4][10]/q duty_cycle_reg[4][10]/Q -type DFF DFF
add mapped point duty_cycle[4][11]/q duty_cycle_reg[4][11]/Q -type DFF DFF
add mapped point duty_cycle[4][12]/q duty_cycle_reg[4][12]/Q -type DFF DFF
add mapped point duty_cycle[4][13]/q duty_cycle_reg[4][13]/Q -type DFF DFF
add mapped point duty_cycle[4][14]/q duty_cycle_reg[4][14]/Q -type DFF DFF
add mapped point duty_cycle[4][15]/q duty_cycle_reg[4][15]/Q -type DFF DFF
add mapped point duty_cycle[4][16]/q duty_cycle_reg[4][16]/Q -type DFF DFF
add mapped point duty_cycle[4][17]/q duty_cycle_reg[4][17]/Q -type DFF DFF
add mapped point duty_cycle[4][18]/q duty_cycle_reg[4][18]/Q -type DFF DFF
add mapped point duty_cycle[4][19]/q duty_cycle_reg[4][19]/Q -type DFF DFF
add mapped point duty_cycle[4][20]/q duty_cycle_reg[4][20]/Q -type DFF DFF
add mapped point duty_cycle[4][21]/q duty_cycle_reg[4][21]/Q -type DFF DFF
add mapped point duty_cycle[4][22]/q duty_cycle_reg[4][22]/Q -type DFF DFF
add mapped point duty_cycle[4][23]/q duty_cycle_reg[4][23]/Q -type DFF DFF
add mapped point duty_cycle[4][24]/q duty_cycle_reg[4][24]/Q -type DFF DFF
add mapped point duty_cycle[4][25]/q duty_cycle_reg[4][25]/Q -type DFF DFF
add mapped point duty_cycle[4][26]/q duty_cycle_reg[4][26]/Q -type DFF DFF
add mapped point duty_cycle[4][27]/q duty_cycle_reg[4][27]/Q -type DFF DFF
add mapped point duty_cycle[4][28]/q duty_cycle_reg[4][28]/Q -type DFF DFF
add mapped point duty_cycle[4][29]/q duty_cycle_reg[4][29]/Q -type DFF DFF
add mapped point duty_cycle[4][30]/q duty_cycle_reg[4][30]/Q -type DFF DFF
add mapped point duty_cycle[4][31]/q duty_cycle_reg[4][31]/Q -type DFF DFF
add mapped point duty_cycle[5][0]/q duty_cycle_reg[5][0]/Q -type DFF DFF
add mapped point duty_cycle[5][1]/q duty_cycle_reg[5][1]/Q -type DFF DFF
add mapped point duty_cycle[5][2]/q duty_cycle_reg[5][2]/Q -type DFF DFF
add mapped point duty_cycle[5][3]/q duty_cycle_reg[5][3]/Q -type DFF DFF
add mapped point duty_cycle[5][4]/q duty_cycle_reg[5][4]/Q -type DFF DFF
add mapped point duty_cycle[5][5]/q duty_cycle_reg[5][5]/Q -type DFF DFF
add mapped point duty_cycle[5][6]/q duty_cycle_reg[5][6]/Q -type DFF DFF
add mapped point duty_cycle[5][7]/q duty_cycle_reg[5][7]/Q -type DFF DFF
add mapped point duty_cycle[5][8]/q duty_cycle_reg[5][8]/Q -type DFF DFF
add mapped point duty_cycle[5][9]/q duty_cycle_reg[5][9]/Q -type DFF DFF
add mapped point duty_cycle[5][10]/q duty_cycle_reg[5][10]/Q -type DFF DFF
add mapped point duty_cycle[5][11]/q duty_cycle_reg[5][11]/Q -type DFF DFF
add mapped point duty_cycle[5][12]/q duty_cycle_reg[5][12]/Q -type DFF DFF
add mapped point duty_cycle[5][13]/q duty_cycle_reg[5][13]/Q -type DFF DFF
add mapped point duty_cycle[5][14]/q duty_cycle_reg[5][14]/Q -type DFF DFF
add mapped point duty_cycle[5][15]/q duty_cycle_reg[5][15]/Q -type DFF DFF
add mapped point duty_cycle[5][16]/q duty_cycle_reg[5][16]/Q -type DFF DFF
add mapped point duty_cycle[5][17]/q duty_cycle_reg[5][17]/Q -type DFF DFF
add mapped point duty_cycle[5][18]/q duty_cycle_reg[5][18]/Q -type DFF DFF
add mapped point duty_cycle[5][19]/q duty_cycle_reg[5][19]/Q -type DFF DFF
add mapped point duty_cycle[5][20]/q duty_cycle_reg[5][20]/Q -type DFF DFF
add mapped point duty_cycle[5][21]/q duty_cycle_reg[5][21]/Q -type DFF DFF
add mapped point duty_cycle[5][22]/q duty_cycle_reg[5][22]/Q -type DFF DFF
add mapped point duty_cycle[5][23]/q duty_cycle_reg[5][23]/Q -type DFF DFF
add mapped point duty_cycle[5][24]/q duty_cycle_reg[5][24]/Q -type DFF DFF
add mapped point duty_cycle[5][25]/q duty_cycle_reg[5][25]/Q -type DFF DFF
add mapped point duty_cycle[5][26]/q duty_cycle_reg[5][26]/Q -type DFF DFF
add mapped point duty_cycle[5][27]/q duty_cycle_reg[5][27]/Q -type DFF DFF
add mapped point duty_cycle[5][28]/q duty_cycle_reg[5][28]/Q -type DFF DFF
add mapped point duty_cycle[5][29]/q duty_cycle_reg[5][29]/Q -type DFF DFF
add mapped point duty_cycle[5][30]/q duty_cycle_reg[5][30]/Q -type DFF DFF
add mapped point duty_cycle[5][31]/q duty_cycle_reg[5][31]/Q -type DFF DFF
add mapped point duty_cycle[6][0]/q duty_cycle_reg[6][0]/Q -type DFF DFF
add mapped point duty_cycle[6][1]/q duty_cycle_reg[6][1]/Q -type DFF DFF
add mapped point duty_cycle[6][2]/q duty_cycle_reg[6][2]/Q -type DFF DFF
add mapped point duty_cycle[6][3]/q duty_cycle_reg[6][3]/Q -type DFF DFF
add mapped point duty_cycle[6][4]/q duty_cycle_reg[6][4]/Q -type DFF DFF
add mapped point duty_cycle[6][5]/q duty_cycle_reg[6][5]/Q -type DFF DFF
add mapped point duty_cycle[6][6]/q duty_cycle_reg[6][6]/Q -type DFF DFF
add mapped point duty_cycle[6][7]/q duty_cycle_reg[6][7]/Q -type DFF DFF
add mapped point duty_cycle[6][8]/q duty_cycle_reg[6][8]/Q -type DFF DFF
add mapped point duty_cycle[6][9]/q duty_cycle_reg[6][9]/Q -type DFF DFF
add mapped point duty_cycle[6][10]/q duty_cycle_reg[6][10]/Q -type DFF DFF
add mapped point duty_cycle[6][11]/q duty_cycle_reg[6][11]/Q -type DFF DFF
add mapped point duty_cycle[6][12]/q duty_cycle_reg[6][12]/Q -type DFF DFF
add mapped point duty_cycle[6][13]/q duty_cycle_reg[6][13]/Q -type DFF DFF
add mapped point duty_cycle[6][14]/q duty_cycle_reg[6][14]/Q -type DFF DFF
add mapped point duty_cycle[6][15]/q duty_cycle_reg[6][15]/Q -type DFF DFF
add mapped point duty_cycle[6][16]/q duty_cycle_reg[6][16]/Q -type DFF DFF
add mapped point duty_cycle[6][17]/q duty_cycle_reg[6][17]/Q -type DFF DFF
add mapped point duty_cycle[6][18]/q duty_cycle_reg[6][18]/Q -type DFF DFF
add mapped point duty_cycle[6][19]/q duty_cycle_reg[6][19]/Q -type DFF DFF
add mapped point duty_cycle[6][20]/q duty_cycle_reg[6][20]/Q -type DFF DFF
add mapped point duty_cycle[6][21]/q duty_cycle_reg[6][21]/Q -type DFF DFF
add mapped point duty_cycle[6][22]/q duty_cycle_reg[6][22]/Q -type DFF DFF
add mapped point duty_cycle[6][23]/q duty_cycle_reg[6][23]/Q -type DFF DFF
add mapped point duty_cycle[6][24]/q duty_cycle_reg[6][24]/Q -type DFF DFF
add mapped point duty_cycle[6][25]/q duty_cycle_reg[6][25]/Q -type DFF DFF
add mapped point duty_cycle[6][26]/q duty_cycle_reg[6][26]/Q -type DFF DFF
add mapped point duty_cycle[6][27]/q duty_cycle_reg[6][27]/Q -type DFF DFF
add mapped point duty_cycle[6][28]/q duty_cycle_reg[6][28]/Q -type DFF DFF
add mapped point duty_cycle[6][29]/q duty_cycle_reg[6][29]/Q -type DFF DFF
add mapped point duty_cycle[6][30]/q duty_cycle_reg[6][30]/Q -type DFF DFF
add mapped point duty_cycle[6][31]/q duty_cycle_reg[6][31]/Q -type DFF DFF
add mapped point duty_cycle[7][0]/q duty_cycle_reg[7][0]/Q -type DFF DFF
add mapped point duty_cycle[7][1]/q duty_cycle_reg[7][1]/Q -type DFF DFF
add mapped point duty_cycle[7][2]/q duty_cycle_reg[7][2]/Q -type DFF DFF
add mapped point duty_cycle[7][3]/q duty_cycle_reg[7][3]/Q -type DFF DFF
add mapped point duty_cycle[7][4]/q duty_cycle_reg[7][4]/Q -type DFF DFF
add mapped point duty_cycle[7][5]/q duty_cycle_reg[7][5]/Q -type DFF DFF
add mapped point duty_cycle[7][6]/q duty_cycle_reg[7][6]/Q -type DFF DFF
add mapped point duty_cycle[7][7]/q duty_cycle_reg[7][7]/Q -type DFF DFF
add mapped point duty_cycle[7][8]/q duty_cycle_reg[7][8]/Q -type DFF DFF
add mapped point duty_cycle[7][9]/q duty_cycle_reg[7][9]/Q -type DFF DFF
add mapped point duty_cycle[7][10]/q duty_cycle_reg[7][10]/Q -type DFF DFF
add mapped point duty_cycle[7][11]/q duty_cycle_reg[7][11]/Q -type DFF DFF
add mapped point duty_cycle[7][12]/q duty_cycle_reg[7][12]/Q -type DFF DFF
add mapped point duty_cycle[7][13]/q duty_cycle_reg[7][13]/Q -type DFF DFF
add mapped point duty_cycle[7][14]/q duty_cycle_reg[7][14]/Q -type DFF DFF
add mapped point duty_cycle[7][15]/q duty_cycle_reg[7][15]/Q -type DFF DFF
add mapped point duty_cycle[7][16]/q duty_cycle_reg[7][16]/Q -type DFF DFF
add mapped point duty_cycle[7][17]/q duty_cycle_reg[7][17]/Q -type DFF DFF
add mapped point duty_cycle[7][18]/q duty_cycle_reg[7][18]/Q -type DFF DFF
add mapped point duty_cycle[7][19]/q duty_cycle_reg[7][19]/Q -type DFF DFF
add mapped point duty_cycle[7][20]/q duty_cycle_reg[7][20]/Q -type DFF DFF
add mapped point duty_cycle[7][21]/q duty_cycle_reg[7][21]/Q -type DFF DFF
add mapped point duty_cycle[7][22]/q duty_cycle_reg[7][22]/Q -type DFF DFF
add mapped point duty_cycle[7][23]/q duty_cycle_reg[7][23]/Q -type DFF DFF
add mapped point duty_cycle[7][24]/q duty_cycle_reg[7][24]/Q -type DFF DFF
add mapped point duty_cycle[7][25]/q duty_cycle_reg[7][25]/Q -type DFF DFF
add mapped point duty_cycle[7][26]/q duty_cycle_reg[7][26]/Q -type DFF DFF
add mapped point duty_cycle[7][27]/q duty_cycle_reg[7][27]/Q -type DFF DFF
add mapped point duty_cycle[7][28]/q duty_cycle_reg[7][28]/Q -type DFF DFF
add mapped point duty_cycle[7][29]/q duty_cycle_reg[7][29]/Q -type DFF DFF
add mapped point duty_cycle[7][30]/q duty_cycle_reg[7][30]/Q -type DFF DFF
add mapped point duty_cycle[7][31]/q duty_cycle_reg[7][31]/Q -type DFF DFF
add mapped point int_enable[0]/q int_enable_reg[0]/Q -type DFF DFF
add mapped point int_enable[1]/q int_enable_reg[1]/Q -type DFF DFF
add mapped point int_enable[2]/q int_enable_reg[2]/Q -type DFF DFF
add mapped point int_enable[3]/q int_enable_reg[3]/Q -type DFF DFF
add mapped point int_enable[4]/q int_enable_reg[4]/Q -type DFF DFF
add mapped point int_enable[5]/q int_enable_reg[5]/Q -type DFF DFF
add mapped point int_enable[6]/q int_enable_reg[6]/Q -type DFF DFF
add mapped point int_enable[7]/q int_enable_reg[7]/Q -type DFF DFF
add mapped point int_enable[8]/q int_enable_reg[8]/Q -type DFF DFF
add mapped point int_enable[9]/q int_enable_reg[9]/Q -type DFF DFF
add mapped point int_enable[10]/q int_enable_reg[10]/Q -type DFF DFF
add mapped point int_enable[11]/q int_enable_reg[11]/Q -type DFF DFF
add mapped point int_enable[12]/q int_enable_reg[12]/Q -type DFF DFF
add mapped point int_enable[13]/q int_enable_reg[13]/Q -type DFF DFF
add mapped point int_enable[14]/q int_enable_reg[14]/Q -type DFF DFF
add mapped point int_enable[15]/q int_enable_reg[15]/Q -type DFF DFF
add mapped point int_enable[16]/q int_enable_reg[16]/Q -type DFF DFF
add mapped point int_enable[17]/q int_enable_reg[17]/Q -type DFF DFF
add mapped point int_enable[18]/q int_enable_reg[18]/Q -type DFF DFF
add mapped point int_enable[19]/q int_enable_reg[19]/Q -type DFF DFF
add mapped point int_enable[20]/q int_enable_reg[20]/Q -type DFF DFF
add mapped point int_enable[21]/q int_enable_reg[21]/Q -type DFF DFF
add mapped point int_enable[22]/q int_enable_reg[22]/Q -type DFF DFF
add mapped point int_enable[23]/q int_enable_reg[23]/Q -type DFF DFF
add mapped point int_enable[24]/q int_enable_reg[24]/Q -type DFF DFF
add mapped point int_enable[25]/q int_enable_reg[25]/Q -type DFF DFF
add mapped point int_enable[26]/q int_enable_reg[26]/Q -type DFF DFF
add mapped point int_enable[27]/q int_enable_reg[27]/Q -type DFF DFF
add mapped point int_enable[28]/q int_enable_reg[28]/Q -type DFF DFF
add mapped point int_enable[29]/q int_enable_reg[29]/Q -type DFF DFF
add mapped point int_enable[30]/q int_enable_reg[30]/Q -type DFF DFF
add mapped point int_enable[31]/q int_enable_reg[31]/Q -type DFF DFF
add mapped point int_status[0]/q int_status_reg[0]/Q -type DFF DFF
add mapped point int_status[0]/q int_status_reg[0]1223/Q -type DFF DFF
add mapped point main_counter[0]/q main_counter_reg[0]/Q -type DFF DFF
add mapped point main_counter[1]/q main_counter_reg[1]/Q -type DFF DFF
add mapped point main_counter[2]/q main_counter_reg[2]/Q -type DFF DFF
add mapped point main_counter[3]/q main_counter_reg[3]/Q -type DFF DFF
add mapped point main_counter[4]/q main_counter_reg[4]/Q -type DFF DFF
add mapped point main_counter[5]/q main_counter_reg[5]/Q -type DFF DFF
add mapped point main_counter[6]/q main_counter_reg[6]/Q -type DFF DFF
add mapped point main_counter[7]/q main_counter_reg[7]/Q -type DFF DFF
add mapped point main_counter[8]/q main_counter_reg[8]/Q -type DFF DFF
add mapped point main_counter[9]/q main_counter_reg[9]/Q -type DFF DFF
add mapped point main_counter[10]/q main_counter_reg[10]/Q -type DFF DFF
add mapped point main_counter[11]/q main_counter_reg[11]/Q -type DFF DFF
add mapped point main_counter[12]/q main_counter_reg[12]/Q -type DFF DFF
add mapped point main_counter[13]/q main_counter_reg[13]/Q -type DFF DFF
add mapped point main_counter[14]/q main_counter_reg[14]/Q -type DFF DFF
add mapped point main_counter[15]/q main_counter_reg[15]/Q -type DFF DFF
add mapped point main_counter[16]/q main_counter_reg[16]/Q -type DFF DFF
add mapped point main_counter[17]/q main_counter_reg[17]/Q -type DFF DFF
add mapped point main_counter[18]/q main_counter_reg[18]/Q -type DFF DFF
add mapped point main_counter[19]/q main_counter_reg[19]/Q -type DFF DFF
add mapped point main_counter[20]/q main_counter_reg[20]/Q -type DFF DFF
add mapped point main_counter[21]/q main_counter_reg[21]/Q -type DFF DFF
add mapped point main_counter[22]/q main_counter_reg[22]/Q -type DFF DFF
add mapped point main_counter[23]/q main_counter_reg[23]/Q -type DFF DFF
add mapped point main_counter[24]/q main_counter_reg[24]/Q -type DFF DFF
add mapped point main_counter[25]/q main_counter_reg[25]/Q -type DFF DFF
add mapped point main_counter[26]/q main_counter_reg[26]/Q -type DFF DFF
add mapped point main_counter[27]/q main_counter_reg[27]/Q -type DFF DFF
add mapped point main_counter[28]/q main_counter_reg[28]/Q -type DFF DFF
add mapped point main_counter[29]/q main_counter_reg[29]/Q -type DFF DFF
add mapped point main_counter[30]/q main_counter_reg[30]/Q -type DFF DFF
add mapped point main_counter[31]/q main_counter_reg[31]/Q -type DFF DFF
add mapped point period_reg[0]/q period_reg_reg[0]/Q -type DFF DFF
add mapped point period_reg[1]/q period_reg_reg[1]/Q -type DFF DFF
add mapped point period_reg[2]/q period_reg_reg[2]/Q -type DFF DFF
add mapped point period_reg[3]/q period_reg_reg[3]/Q -type DFF DFF
add mapped point period_reg[4]/q period_reg_reg[4]/Q -type DFF DFF
add mapped point period_reg[5]/q period_reg_reg[5]/Q -type DFF DFF
add mapped point period_reg[6]/q period_reg_reg[6]/Q -type DFF DFF
add mapped point period_reg[7]/q period_reg_reg[7]/Q -type DFF DFF
add mapped point period_reg[8]/q period_reg_reg[8]/Q -type DFF DFF
add mapped point period_reg[9]/q period_reg_reg[9]/Q -type DFF DFF
add mapped point period_reg[10]/q period_reg_reg[10]/Q -type DFF DFF
add mapped point period_reg[11]/q period_reg_reg[11]/Q -type DFF DFF
add mapped point period_reg[12]/q period_reg_reg[12]/Q -type DFF DFF
add mapped point period_reg[13]/q period_reg_reg[13]/Q -type DFF DFF
add mapped point period_reg[14]/q period_reg_reg[14]/Q -type DFF DFF
add mapped point period_reg[15]/q period_reg_reg[15]/Q -type DFF DFF
add mapped point period_reg[16]/q period_reg_reg[16]/Q -type DFF DFF
add mapped point period_reg[17]/q period_reg_reg[17]/Q -type DFF DFF
add mapped point period_reg[18]/q period_reg_reg[18]/Q -type DFF DFF
add mapped point period_reg[19]/q period_reg_reg[19]/Q -type DFF DFF
add mapped point period_reg[20]/q period_reg_reg[20]/Q -type DFF DFF
add mapped point period_reg[21]/q period_reg_reg[21]/Q -type DFF DFF
add mapped point period_reg[22]/q period_reg_reg[22]/Q -type DFF DFF
add mapped point period_reg[23]/q period_reg_reg[23]/Q -type DFF DFF
add mapped point period_reg[24]/q period_reg_reg[24]/Q -type DFF DFF
add mapped point period_reg[25]/q period_reg_reg[25]/Q -type DFF DFF
add mapped point period_reg[26]/q period_reg_reg[26]/Q -type DFF DFF
add mapped point period_reg[27]/q period_reg_reg[27]/Q -type DFF DFF
add mapped point period_reg[28]/q period_reg_reg[28]/Q -type DFF DFF
add mapped point period_reg[29]/q period_reg_reg[29]/Q -type DFF DFF
add mapped point period_reg[30]/q period_reg_reg[30]/Q -type DFF DFF
add mapped point period_reg[31]/q period_reg_reg[31]/Q -type DFF DFF
add mapped point phase_offset[0][0]/q phase_offset_reg[0][0]/Q -type DFF DFF
add mapped point phase_offset[0][1]/q phase_offset_reg[0][1]/Q -type DFF DFF
add mapped point phase_offset[0][2]/q phase_offset_reg[0][2]/Q -type DFF DFF
add mapped point phase_offset[0][3]/q phase_offset_reg[0][3]/Q -type DFF DFF
add mapped point phase_offset[0][4]/q phase_offset_reg[0][4]/Q -type DFF DFF
add mapped point phase_offset[0][5]/q phase_offset_reg[0][5]/Q -type DFF DFF
add mapped point phase_offset[0][6]/q phase_offset_reg[0][6]/Q -type DFF DFF
add mapped point phase_offset[0][7]/q phase_offset_reg[0][7]/Q -type DFF DFF
add mapped point phase_offset[0][8]/q phase_offset_reg[0][8]/Q -type DFF DFF
add mapped point phase_offset[0][9]/q phase_offset_reg[0][9]/Q -type DFF DFF
add mapped point phase_offset[0][10]/q phase_offset_reg[0][10]/Q -type DFF DFF
add mapped point phase_offset[0][11]/q phase_offset_reg[0][11]/Q -type DFF DFF
add mapped point phase_offset[0][12]/q phase_offset_reg[0][12]/Q -type DFF DFF
add mapped point phase_offset[0][13]/q phase_offset_reg[0][13]/Q -type DFF DFF
add mapped point phase_offset[0][14]/q phase_offset_reg[0][14]/Q -type DFF DFF
add mapped point phase_offset[0][15]/q phase_offset_reg[0][15]/Q -type DFF DFF
add mapped point phase_offset[0][16]/q phase_offset_reg[0][16]/Q -type DFF DFF
add mapped point phase_offset[0][17]/q phase_offset_reg[0][17]/Q -type DFF DFF
add mapped point phase_offset[0][18]/q phase_offset_reg[0][18]/Q -type DFF DFF
add mapped point phase_offset[0][19]/q phase_offset_reg[0][19]/Q -type DFF DFF
add mapped point phase_offset[0][20]/q phase_offset_reg[0][20]/Q -type DFF DFF
add mapped point phase_offset[0][21]/q phase_offset_reg[0][21]/Q -type DFF DFF
add mapped point phase_offset[0][22]/q phase_offset_reg[0][22]/Q -type DFF DFF
add mapped point phase_offset[0][23]/q phase_offset_reg[0][23]/Q -type DFF DFF
add mapped point phase_offset[0][24]/q phase_offset_reg[0][24]/Q -type DFF DFF
add mapped point phase_offset[0][25]/q phase_offset_reg[0][25]/Q -type DFF DFF
add mapped point phase_offset[0][26]/q phase_offset_reg[0][26]/Q -type DFF DFF
add mapped point phase_offset[0][27]/q phase_offset_reg[0][27]/Q -type DFF DFF
add mapped point phase_offset[0][28]/q phase_offset_reg[0][28]/Q -type DFF DFF
add mapped point phase_offset[0][29]/q phase_offset_reg[0][29]/Q -type DFF DFF
add mapped point phase_offset[0][30]/q phase_offset_reg[0][30]/Q -type DFF DFF
add mapped point phase_offset[0][31]/q phase_offset_reg[0][31]/Q -type DFF DFF
add mapped point phase_offset[1][0]/q phase_offset_reg[1][0]/Q -type DFF DFF
add mapped point phase_offset[1][1]/q phase_offset_reg[1][1]/Q -type DFF DFF
add mapped point phase_offset[1][2]/q phase_offset_reg[1][2]/Q -type DFF DFF
add mapped point phase_offset[1][3]/q phase_offset_reg[1][3]/Q -type DFF DFF
add mapped point phase_offset[1][4]/q phase_offset_reg[1][4]/Q -type DFF DFF
add mapped point phase_offset[1][5]/q phase_offset_reg[1][5]/Q -type DFF DFF
add mapped point phase_offset[1][6]/q phase_offset_reg[1][6]/Q -type DFF DFF
add mapped point phase_offset[1][7]/q phase_offset_reg[1][7]/Q -type DFF DFF
add mapped point phase_offset[1][8]/q phase_offset_reg[1][8]/Q -type DFF DFF
add mapped point phase_offset[1][9]/q phase_offset_reg[1][9]/Q -type DFF DFF
add mapped point phase_offset[1][10]/q phase_offset_reg[1][10]/Q -type DFF DFF
add mapped point phase_offset[1][11]/q phase_offset_reg[1][11]/Q -type DFF DFF
add mapped point phase_offset[1][12]/q phase_offset_reg[1][12]/Q -type DFF DFF
add mapped point phase_offset[1][13]/q phase_offset_reg[1][13]/Q -type DFF DFF
add mapped point phase_offset[1][14]/q phase_offset_reg[1][14]/Q -type DFF DFF
add mapped point phase_offset[1][15]/q phase_offset_reg[1][15]/Q -type DFF DFF
add mapped point phase_offset[1][16]/q phase_offset_reg[1][16]/Q -type DFF DFF
add mapped point phase_offset[1][17]/q phase_offset_reg[1][17]/Q -type DFF DFF
add mapped point phase_offset[1][18]/q phase_offset_reg[1][18]/Q -type DFF DFF
add mapped point phase_offset[1][19]/q phase_offset_reg[1][19]/Q -type DFF DFF
add mapped point phase_offset[1][20]/q phase_offset_reg[1][20]/Q -type DFF DFF
add mapped point phase_offset[1][21]/q phase_offset_reg[1][21]/Q -type DFF DFF
add mapped point phase_offset[1][22]/q phase_offset_reg[1][22]/Q -type DFF DFF
add mapped point phase_offset[1][23]/q phase_offset_reg[1][23]/Q -type DFF DFF
add mapped point phase_offset[1][24]/q phase_offset_reg[1][24]/Q -type DFF DFF
add mapped point phase_offset[1][25]/q phase_offset_reg[1][25]/Q -type DFF DFF
add mapped point phase_offset[1][26]/q phase_offset_reg[1][26]/Q -type DFF DFF
add mapped point phase_offset[1][27]/q phase_offset_reg[1][27]/Q -type DFF DFF
add mapped point phase_offset[1][28]/q phase_offset_reg[1][28]/Q -type DFF DFF
add mapped point phase_offset[1][29]/q phase_offset_reg[1][29]/Q -type DFF DFF
add mapped point phase_offset[1][30]/q phase_offset_reg[1][30]/Q -type DFF DFF
add mapped point phase_offset[1][31]/q phase_offset_reg[1][31]/Q -type DFF DFF
add mapped point phase_offset[2][0]/q phase_offset_reg[2][0]/Q -type DFF DFF
add mapped point phase_offset[2][1]/q phase_offset_reg[2][1]/Q -type DFF DFF
add mapped point phase_offset[2][2]/q phase_offset_reg[2][2]/Q -type DFF DFF
add mapped point phase_offset[2][3]/q phase_offset_reg[2][3]/Q -type DFF DFF
add mapped point phase_offset[2][4]/q phase_offset_reg[2][4]/Q -type DFF DFF
add mapped point phase_offset[2][5]/q phase_offset_reg[2][5]/Q -type DFF DFF
add mapped point phase_offset[2][6]/q phase_offset_reg[2][6]/Q -type DFF DFF
add mapped point phase_offset[2][7]/q phase_offset_reg[2][7]/Q -type DFF DFF
add mapped point phase_offset[2][8]/q phase_offset_reg[2][8]/Q -type DFF DFF
add mapped point phase_offset[2][9]/q phase_offset_reg[2][9]/Q -type DFF DFF
add mapped point phase_offset[2][10]/q phase_offset_reg[2][10]/Q -type DFF DFF
add mapped point phase_offset[2][11]/q phase_offset_reg[2][11]/Q -type DFF DFF
add mapped point phase_offset[2][12]/q phase_offset_reg[2][12]/Q -type DFF DFF
add mapped point phase_offset[2][13]/q phase_offset_reg[2][13]/Q -type DFF DFF
add mapped point phase_offset[2][14]/q phase_offset_reg[2][14]/Q -type DFF DFF
add mapped point phase_offset[2][15]/q phase_offset_reg[2][15]/Q -type DFF DFF
add mapped point phase_offset[2][16]/q phase_offset_reg[2][16]/Q -type DFF DFF
add mapped point phase_offset[2][17]/q phase_offset_reg[2][17]/Q -type DFF DFF
add mapped point phase_offset[2][18]/q phase_offset_reg[2][18]/Q -type DFF DFF
add mapped point phase_offset[2][19]/q phase_offset_reg[2][19]/Q -type DFF DFF
add mapped point phase_offset[2][20]/q phase_offset_reg[2][20]/Q -type DFF DFF
add mapped point phase_offset[2][21]/q phase_offset_reg[2][21]/Q -type DFF DFF
add mapped point phase_offset[2][22]/q phase_offset_reg[2][22]/Q -type DFF DFF
add mapped point phase_offset[2][23]/q phase_offset_reg[2][23]/Q -type DFF DFF
add mapped point phase_offset[2][24]/q phase_offset_reg[2][24]/Q -type DFF DFF
add mapped point phase_offset[2][25]/q phase_offset_reg[2][25]/Q -type DFF DFF
add mapped point phase_offset[2][26]/q phase_offset_reg[2][26]/Q -type DFF DFF
add mapped point phase_offset[2][27]/q phase_offset_reg[2][27]/Q -type DFF DFF
add mapped point phase_offset[2][28]/q phase_offset_reg[2][28]/Q -type DFF DFF
add mapped point phase_offset[2][29]/q phase_offset_reg[2][29]/Q -type DFF DFF
add mapped point phase_offset[2][30]/q phase_offset_reg[2][30]/Q -type DFF DFF
add mapped point phase_offset[2][31]/q phase_offset_reg[2][31]/Q -type DFF DFF
add mapped point phase_offset[3][0]/q phase_offset_reg[3][0]/Q -type DFF DFF
add mapped point phase_offset[3][1]/q phase_offset_reg[3][1]/Q -type DFF DFF
add mapped point phase_offset[3][2]/q phase_offset_reg[3][2]/Q -type DFF DFF
add mapped point phase_offset[3][3]/q phase_offset_reg[3][3]/Q -type DFF DFF
add mapped point phase_offset[3][4]/q phase_offset_reg[3][4]/Q -type DFF DFF
add mapped point phase_offset[3][5]/q phase_offset_reg[3][5]/Q -type DFF DFF
add mapped point phase_offset[3][6]/q phase_offset_reg[3][6]/Q -type DFF DFF
add mapped point phase_offset[3][7]/q phase_offset_reg[3][7]/Q -type DFF DFF
add mapped point phase_offset[3][8]/q phase_offset_reg[3][8]/Q -type DFF DFF
add mapped point phase_offset[3][9]/q phase_offset_reg[3][9]/Q -type DFF DFF
add mapped point phase_offset[3][10]/q phase_offset_reg[3][10]/Q -type DFF DFF
add mapped point phase_offset[3][11]/q phase_offset_reg[3][11]/Q -type DFF DFF
add mapped point phase_offset[3][12]/q phase_offset_reg[3][12]/Q -type DFF DFF
add mapped point phase_offset[3][13]/q phase_offset_reg[3][13]/Q -type DFF DFF
add mapped point phase_offset[3][14]/q phase_offset_reg[3][14]/Q -type DFF DFF
add mapped point phase_offset[3][15]/q phase_offset_reg[3][15]/Q -type DFF DFF
add mapped point phase_offset[3][16]/q phase_offset_reg[3][16]/Q -type DFF DFF
add mapped point phase_offset[3][17]/q phase_offset_reg[3][17]/Q -type DFF DFF
add mapped point phase_offset[3][18]/q phase_offset_reg[3][18]/Q -type DFF DFF
add mapped point phase_offset[3][19]/q phase_offset_reg[3][19]/Q -type DFF DFF
add mapped point phase_offset[3][20]/q phase_offset_reg[3][20]/Q -type DFF DFF
add mapped point phase_offset[3][21]/q phase_offset_reg[3][21]/Q -type DFF DFF
add mapped point phase_offset[3][22]/q phase_offset_reg[3][22]/Q -type DFF DFF
add mapped point phase_offset[3][23]/q phase_offset_reg[3][23]/Q -type DFF DFF
add mapped point phase_offset[3][24]/q phase_offset_reg[3][24]/Q -type DFF DFF
add mapped point phase_offset[3][25]/q phase_offset_reg[3][25]/Q -type DFF DFF
add mapped point phase_offset[3][26]/q phase_offset_reg[3][26]/Q -type DFF DFF
add mapped point phase_offset[3][27]/q phase_offset_reg[3][27]/Q -type DFF DFF
add mapped point phase_offset[3][28]/q phase_offset_reg[3][28]/Q -type DFF DFF
add mapped point phase_offset[3][29]/q phase_offset_reg[3][29]/Q -type DFF DFF
add mapped point phase_offset[3][30]/q phase_offset_reg[3][30]/Q -type DFF DFF
add mapped point phase_offset[3][31]/q phase_offset_reg[3][31]/Q -type DFF DFF
add mapped point phase_offset[4][0]/q phase_offset_reg[4][0]/Q -type DFF DFF
add mapped point phase_offset[4][1]/q phase_offset_reg[4][1]/Q -type DFF DFF
add mapped point phase_offset[4][2]/q phase_offset_reg[4][2]/Q -type DFF DFF
add mapped point phase_offset[4][3]/q phase_offset_reg[4][3]/Q -type DFF DFF
add mapped point phase_offset[4][4]/q phase_offset_reg[4][4]/Q -type DFF DFF
add mapped point phase_offset[4][5]/q phase_offset_reg[4][5]/Q -type DFF DFF
add mapped point phase_offset[4][6]/q phase_offset_reg[4][6]/Q -type DFF DFF
add mapped point phase_offset[4][7]/q phase_offset_reg[4][7]/Q -type DFF DFF
add mapped point phase_offset[4][8]/q phase_offset_reg[4][8]/Q -type DFF DFF
add mapped point phase_offset[4][9]/q phase_offset_reg[4][9]/Q -type DFF DFF
add mapped point phase_offset[4][10]/q phase_offset_reg[4][10]/Q -type DFF DFF
add mapped point phase_offset[4][11]/q phase_offset_reg[4][11]/Q -type DFF DFF
add mapped point phase_offset[4][12]/q phase_offset_reg[4][12]/Q -type DFF DFF
add mapped point phase_offset[4][13]/q phase_offset_reg[4][13]/Q -type DFF DFF
add mapped point phase_offset[4][14]/q phase_offset_reg[4][14]/Q -type DFF DFF
add mapped point phase_offset[4][15]/q phase_offset_reg[4][15]/Q -type DFF DFF
add mapped point phase_offset[4][16]/q phase_offset_reg[4][16]/Q -type DFF DFF
add mapped point phase_offset[4][17]/q phase_offset_reg[4][17]/Q -type DFF DFF
add mapped point phase_offset[4][18]/q phase_offset_reg[4][18]/Q -type DFF DFF
add mapped point phase_offset[4][19]/q phase_offset_reg[4][19]/Q -type DFF DFF
add mapped point phase_offset[4][20]/q phase_offset_reg[4][20]/Q -type DFF DFF
add mapped point phase_offset[4][21]/q phase_offset_reg[4][21]/Q -type DFF DFF
add mapped point phase_offset[4][22]/q phase_offset_reg[4][22]/Q -type DFF DFF
add mapped point phase_offset[4][23]/q phase_offset_reg[4][23]/Q -type DFF DFF
add mapped point phase_offset[4][24]/q phase_offset_reg[4][24]/Q -type DFF DFF
add mapped point phase_offset[4][25]/q phase_offset_reg[4][25]/Q -type DFF DFF
add mapped point phase_offset[4][26]/q phase_offset_reg[4][26]/Q -type DFF DFF
add mapped point phase_offset[4][27]/q phase_offset_reg[4][27]/Q -type DFF DFF
add mapped point phase_offset[4][28]/q phase_offset_reg[4][28]/Q -type DFF DFF
add mapped point phase_offset[4][29]/q phase_offset_reg[4][29]/Q -type DFF DFF
add mapped point phase_offset[4][30]/q phase_offset_reg[4][30]/Q -type DFF DFF
add mapped point phase_offset[4][31]/q phase_offset_reg[4][31]/Q -type DFF DFF
add mapped point phase_offset[5][0]/q phase_offset_reg[5][0]/Q -type DFF DFF
add mapped point phase_offset[5][1]/q phase_offset_reg[5][1]/Q -type DFF DFF
add mapped point phase_offset[5][2]/q phase_offset_reg[5][2]/Q -type DFF DFF
add mapped point phase_offset[5][3]/q phase_offset_reg[5][3]/Q -type DFF DFF
add mapped point phase_offset[5][4]/q phase_offset_reg[5][4]/Q -type DFF DFF
add mapped point phase_offset[5][5]/q phase_offset_reg[5][5]/Q -type DFF DFF
add mapped point phase_offset[5][6]/q phase_offset_reg[5][6]/Q -type DFF DFF
add mapped point phase_offset[5][7]/q phase_offset_reg[5][7]/Q -type DFF DFF
add mapped point phase_offset[5][8]/q phase_offset_reg[5][8]/Q -type DFF DFF
add mapped point phase_offset[5][9]/q phase_offset_reg[5][9]/Q -type DFF DFF
add mapped point phase_offset[5][10]/q phase_offset_reg[5][10]/Q -type DFF DFF
add mapped point phase_offset[5][11]/q phase_offset_reg[5][11]/Q -type DFF DFF
add mapped point phase_offset[5][12]/q phase_offset_reg[5][12]/Q -type DFF DFF
add mapped point phase_offset[5][13]/q phase_offset_reg[5][13]/Q -type DFF DFF
add mapped point phase_offset[5][14]/q phase_offset_reg[5][14]/Q -type DFF DFF
add mapped point phase_offset[5][15]/q phase_offset_reg[5][15]/Q -type DFF DFF
add mapped point phase_offset[5][16]/q phase_offset_reg[5][16]/Q -type DFF DFF
add mapped point phase_offset[5][17]/q phase_offset_reg[5][17]/Q -type DFF DFF
add mapped point phase_offset[5][18]/q phase_offset_reg[5][18]/Q -type DFF DFF
add mapped point phase_offset[5][19]/q phase_offset_reg[5][19]/Q -type DFF DFF
add mapped point phase_offset[5][20]/q phase_offset_reg[5][20]/Q -type DFF DFF
add mapped point phase_offset[5][21]/q phase_offset_reg[5][21]/Q -type DFF DFF
add mapped point phase_offset[5][22]/q phase_offset_reg[5][22]/Q -type DFF DFF
add mapped point phase_offset[5][23]/q phase_offset_reg[5][23]/Q -type DFF DFF
add mapped point phase_offset[5][24]/q phase_offset_reg[5][24]/Q -type DFF DFF
add mapped point phase_offset[5][25]/q phase_offset_reg[5][25]/Q -type DFF DFF
add mapped point phase_offset[5][26]/q phase_offset_reg[5][26]/Q -type DFF DFF
add mapped point phase_offset[5][27]/q phase_offset_reg[5][27]/Q -type DFF DFF
add mapped point phase_offset[5][28]/q phase_offset_reg[5][28]/Q -type DFF DFF
add mapped point phase_offset[5][29]/q phase_offset_reg[5][29]/Q -type DFF DFF
add mapped point phase_offset[5][30]/q phase_offset_reg[5][30]/Q -type DFF DFF
add mapped point phase_offset[5][31]/q phase_offset_reg[5][31]/Q -type DFF DFF
add mapped point phase_offset[6][0]/q phase_offset_reg[6][0]/Q -type DFF DFF
add mapped point phase_offset[6][1]/q phase_offset_reg[6][1]/Q -type DFF DFF
add mapped point phase_offset[6][2]/q phase_offset_reg[6][2]/Q -type DFF DFF
add mapped point phase_offset[6][3]/q phase_offset_reg[6][3]/Q -type DFF DFF
add mapped point phase_offset[6][4]/q phase_offset_reg[6][4]/Q -type DFF DFF
add mapped point phase_offset[6][5]/q phase_offset_reg[6][5]/Q -type DFF DFF
add mapped point phase_offset[6][6]/q phase_offset_reg[6][6]/Q -type DFF DFF
add mapped point phase_offset[6][7]/q phase_offset_reg[6][7]/Q -type DFF DFF
add mapped point phase_offset[6][8]/q phase_offset_reg[6][8]/Q -type DFF DFF
add mapped point phase_offset[6][9]/q phase_offset_reg[6][9]/Q -type DFF DFF
add mapped point phase_offset[6][10]/q phase_offset_reg[6][10]/Q -type DFF DFF
add mapped point phase_offset[6][11]/q phase_offset_reg[6][11]/Q -type DFF DFF
add mapped point phase_offset[6][12]/q phase_offset_reg[6][12]/Q -type DFF DFF
add mapped point phase_offset[6][13]/q phase_offset_reg[6][13]/Q -type DFF DFF
add mapped point phase_offset[6][14]/q phase_offset_reg[6][14]/Q -type DFF DFF
add mapped point phase_offset[6][15]/q phase_offset_reg[6][15]/Q -type DFF DFF
add mapped point phase_offset[6][16]/q phase_offset_reg[6][16]/Q -type DFF DFF
add mapped point phase_offset[6][17]/q phase_offset_reg[6][17]/Q -type DFF DFF
add mapped point phase_offset[6][18]/q phase_offset_reg[6][18]/Q -type DFF DFF
add mapped point phase_offset[6][19]/q phase_offset_reg[6][19]/Q -type DFF DFF
add mapped point phase_offset[6][20]/q phase_offset_reg[6][20]/Q -type DFF DFF
add mapped point phase_offset[6][21]/q phase_offset_reg[6][21]/Q -type DFF DFF
add mapped point phase_offset[6][22]/q phase_offset_reg[6][22]/Q -type DFF DFF
add mapped point phase_offset[6][23]/q phase_offset_reg[6][23]/Q -type DFF DFF
add mapped point phase_offset[6][24]/q phase_offset_reg[6][24]/Q -type DFF DFF
add mapped point phase_offset[6][25]/q phase_offset_reg[6][25]/Q -type DFF DFF
add mapped point phase_offset[6][26]/q phase_offset_reg[6][26]/Q -type DFF DFF
add mapped point phase_offset[6][27]/q phase_offset_reg[6][27]/Q -type DFF DFF
add mapped point phase_offset[6][28]/q phase_offset_reg[6][28]/Q -type DFF DFF
add mapped point phase_offset[6][29]/q phase_offset_reg[6][29]/Q -type DFF DFF
add mapped point phase_offset[6][30]/q phase_offset_reg[6][30]/Q -type DFF DFF
add mapped point phase_offset[6][31]/q phase_offset_reg[6][31]/Q -type DFF DFF
add mapped point phase_offset[7][0]/q phase_offset_reg[7][0]/Q -type DFF DFF
add mapped point phase_offset[7][1]/q phase_offset_reg[7][1]/Q -type DFF DFF
add mapped point phase_offset[7][2]/q phase_offset_reg[7][2]/Q -type DFF DFF
add mapped point phase_offset[7][3]/q phase_offset_reg[7][3]/Q -type DFF DFF
add mapped point phase_offset[7][4]/q phase_offset_reg[7][4]/Q -type DFF DFF
add mapped point phase_offset[7][5]/q phase_offset_reg[7][5]/Q -type DFF DFF
add mapped point phase_offset[7][6]/q phase_offset_reg[7][6]/Q -type DFF DFF
add mapped point phase_offset[7][7]/q phase_offset_reg[7][7]/Q -type DFF DFF
add mapped point phase_offset[7][8]/q phase_offset_reg[7][8]/Q -type DFF DFF
add mapped point phase_offset[7][9]/q phase_offset_reg[7][9]/Q -type DFF DFF
add mapped point phase_offset[7][10]/q phase_offset_reg[7][10]/Q -type DFF DFF
add mapped point phase_offset[7][11]/q phase_offset_reg[7][11]/Q -type DFF DFF
add mapped point phase_offset[7][12]/q phase_offset_reg[7][12]/Q -type DFF DFF
add mapped point phase_offset[7][13]/q phase_offset_reg[7][13]/Q -type DFF DFF
add mapped point phase_offset[7][14]/q phase_offset_reg[7][14]/Q -type DFF DFF
add mapped point phase_offset[7][15]/q phase_offset_reg[7][15]/Q -type DFF DFF
add mapped point phase_offset[7][16]/q phase_offset_reg[7][16]/Q -type DFF DFF
add mapped point phase_offset[7][17]/q phase_offset_reg[7][17]/Q -type DFF DFF
add mapped point phase_offset[7][18]/q phase_offset_reg[7][18]/Q -type DFF DFF
add mapped point phase_offset[7][19]/q phase_offset_reg[7][19]/Q -type DFF DFF
add mapped point phase_offset[7][20]/q phase_offset_reg[7][20]/Q -type DFF DFF
add mapped point phase_offset[7][21]/q phase_offset_reg[7][21]/Q -type DFF DFF
add mapped point phase_offset[7][22]/q phase_offset_reg[7][22]/Q -type DFF DFF
add mapped point phase_offset[7][23]/q phase_offset_reg[7][23]/Q -type DFF DFF
add mapped point phase_offset[7][24]/q phase_offset_reg[7][24]/Q -type DFF DFF
add mapped point phase_offset[7][25]/q phase_offset_reg[7][25]/Q -type DFF DFF
add mapped point phase_offset[7][26]/q phase_offset_reg[7][26]/Q -type DFF DFF
add mapped point phase_offset[7][27]/q phase_offset_reg[7][27]/Q -type DFF DFF
add mapped point phase_offset[7][28]/q phase_offset_reg[7][28]/Q -type DFF DFF
add mapped point phase_offset[7][29]/q phase_offset_reg[7][29]/Q -type DFF DFF
add mapped point phase_offset[7][30]/q phase_offset_reg[7][30]/Q -type DFF DFF
add mapped point phase_offset[7][31]/q phase_offset_reg[7][31]/Q -type DFF DFF
add mapped point pwm_delayed[0]/q pwm_delayed_reg[0]/Q -type DFF DFF
add mapped point pwm_delayed[1]/q pwm_delayed_reg[1]/Q -type DFF DFF
add mapped point pwm_delayed[2]/q pwm_delayed_reg[2]/Q -type DFF DFF
add mapped point pwm_delayed[3]/q pwm_delayed_reg[3]/Q -type DFF DFF
add mapped point pwm_delayed[4]/q pwm_delayed_reg[4]/Q -type DFF DFF
add mapped point pwm_delayed[5]/q pwm_delayed_reg[5]/Q -type DFF DFF
add mapped point pwm_delayed[6]/q pwm_delayed_reg[6]/Q -type DFF DFF
add mapped point pwm_delayed[7]/q pwm_delayed_reg[7]/Q -type DFF DFF
add mapped point wb_dat_reg[0]/q wb_dat_reg_reg[0]/Q -type DFF DFF
add mapped point wb_dat_reg[1]/q wb_dat_reg_reg[1]/Q -type DFF DFF
add mapped point wb_dat_reg[2]/q wb_dat_reg_reg[2]/Q -type DFF DFF
add mapped point wb_dat_reg[3]/q wb_dat_reg_reg[3]/Q -type DFF DFF
add mapped point wb_dat_reg[4]/q wb_dat_reg_reg[4]/Q -type DFF DFF
add mapped point wb_dat_reg[5]/q wb_dat_reg_reg[5]/Q -type DFF DFF
add mapped point wb_dat_reg[6]/q wb_dat_reg_reg[6]/Q -type DFF DFF
add mapped point wb_dat_reg[7]/q wb_dat_reg_reg[7]/Q -type DFF DFF
add mapped point wb_dat_reg[8]/q wb_dat_reg_reg[8]/Q -type DFF DFF
add mapped point wb_dat_reg[9]/q wb_dat_reg_reg[9]/Q -type DFF DFF
add mapped point wb_dat_reg[10]/q wb_dat_reg_reg[10]/Q -type DFF DFF
add mapped point wb_dat_reg[11]/q wb_dat_reg_reg[11]/Q -type DFF DFF
add mapped point wb_dat_reg[12]/q wb_dat_reg_reg[12]/Q -type DFF DFF
add mapped point wb_dat_reg[13]/q wb_dat_reg_reg[13]/Q -type DFF DFF
add mapped point wb_dat_reg[14]/q wb_dat_reg_reg[14]/Q -type DFF DFF
add mapped point wb_dat_reg[15]/q wb_dat_reg_reg[15]/Q -type DFF DFF
add mapped point wb_dat_reg[16]/q wb_dat_reg_reg[16]/Q -type DFF DFF
add mapped point wb_dat_reg[17]/q wb_dat_reg_reg[17]/Q -type DFF DFF
add mapped point wb_dat_reg[18]/q wb_dat_reg_reg[18]/Q -type DFF DFF
add mapped point wb_dat_reg[19]/q wb_dat_reg_reg[19]/Q -type DFF DFF
add mapped point wb_dat_reg[20]/q wb_dat_reg_reg[20]/Q -type DFF DFF
add mapped point wb_dat_reg[21]/q wb_dat_reg_reg[21]/Q -type DFF DFF
add mapped point wb_dat_reg[22]/q wb_dat_reg_reg[22]/Q -type DFF DFF
add mapped point wb_dat_reg[23]/q wb_dat_reg_reg[23]/Q -type DFF DFF
add mapped point wb_dat_reg[24]/q wb_dat_reg_reg[24]/Q -type DFF DFF
add mapped point wb_dat_reg[25]/q wb_dat_reg_reg[25]/Q -type DFF DFF
add mapped point wb_dat_reg[26]/q wb_dat_reg_reg[26]/Q -type DFF DFF
add mapped point wb_dat_reg[27]/q wb_dat_reg_reg[27]/Q -type DFF DFF
add mapped point wb_dat_reg[28]/q wb_dat_reg_reg[28]/Q -type DFF DFF
add mapped point wb_dat_reg[29]/q wb_dat_reg_reg[29]/Q -type DFF DFF
add mapped point wb_dat_reg[30]/q wb_dat_reg_reg[30]/Q -type DFF DFF
add mapped point wb_dat_reg[31]/q wb_dat_reg_reg[31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
