
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point iwb_dat_i[31] iwb_dat_i[31] -type PI PI
add mapped point iwb_dat_i[30] iwb_dat_i[30] -type PI PI
add mapped point iwb_dat_i[29] iwb_dat_i[29] -type PI PI
add mapped point iwb_dat_i[28] iwb_dat_i[28] -type PI PI
add mapped point iwb_dat_i[27] iwb_dat_i[27] -type PI PI
add mapped point iwb_dat_i[26] iwb_dat_i[26] -type PI PI
add mapped point iwb_dat_i[25] iwb_dat_i[25] -type PI PI
add mapped point iwb_dat_i[24] iwb_dat_i[24] -type PI PI
add mapped point iwb_dat_i[23] iwb_dat_i[23] -type PI PI
add mapped point iwb_dat_i[22] iwb_dat_i[22] -type PI PI
add mapped point iwb_dat_i[21] iwb_dat_i[21] -type PI PI
add mapped point iwb_dat_i[20] iwb_dat_i[20] -type PI PI
add mapped point iwb_dat_i[19] iwb_dat_i[19] -type PI PI
add mapped point iwb_dat_i[18] iwb_dat_i[18] -type PI PI
add mapped point iwb_dat_i[17] iwb_dat_i[17] -type PI PI
add mapped point iwb_dat_i[16] iwb_dat_i[16] -type PI PI
add mapped point iwb_dat_i[15] iwb_dat_i[15] -type PI PI
add mapped point iwb_dat_i[14] iwb_dat_i[14] -type PI PI
add mapped point iwb_dat_i[13] iwb_dat_i[13] -type PI PI
add mapped point iwb_dat_i[12] iwb_dat_i[12] -type PI PI
add mapped point iwb_dat_i[11] iwb_dat_i[11] -type PI PI
add mapped point iwb_dat_i[10] iwb_dat_i[10] -type PI PI
add mapped point iwb_dat_i[9] iwb_dat_i[9] -type PI PI
add mapped point iwb_dat_i[8] iwb_dat_i[8] -type PI PI
add mapped point iwb_dat_i[7] iwb_dat_i[7] -type PI PI
add mapped point iwb_dat_i[6] iwb_dat_i[6] -type PI PI
add mapped point iwb_dat_i[5] iwb_dat_i[5] -type PI PI
add mapped point iwb_dat_i[4] iwb_dat_i[4] -type PI PI
add mapped point iwb_dat_i[3] iwb_dat_i[3] -type PI PI
add mapped point iwb_dat_i[2] iwb_dat_i[2] -type PI PI
add mapped point iwb_dat_i[1] iwb_dat_i[1] -type PI PI
add mapped point iwb_dat_i[0] iwb_dat_i[0] -type PI PI
add mapped point iwb_ack_i iwb_ack_i -type PI PI
add mapped point dwb_dat_i[31] dwb_dat_i[31] -type PI PI
add mapped point dwb_dat_i[30] dwb_dat_i[30] -type PI PI
add mapped point dwb_dat_i[29] dwb_dat_i[29] -type PI PI
add mapped point dwb_dat_i[28] dwb_dat_i[28] -type PI PI
add mapped point dwb_dat_i[27] dwb_dat_i[27] -type PI PI
add mapped point dwb_dat_i[26] dwb_dat_i[26] -type PI PI
add mapped point dwb_dat_i[25] dwb_dat_i[25] -type PI PI
add mapped point dwb_dat_i[24] dwb_dat_i[24] -type PI PI
add mapped point dwb_dat_i[23] dwb_dat_i[23] -type PI PI
add mapped point dwb_dat_i[22] dwb_dat_i[22] -type PI PI
add mapped point dwb_dat_i[21] dwb_dat_i[21] -type PI PI
add mapped point dwb_dat_i[20] dwb_dat_i[20] -type PI PI
add mapped point dwb_dat_i[19] dwb_dat_i[19] -type PI PI
add mapped point dwb_dat_i[18] dwb_dat_i[18] -type PI PI
add mapped point dwb_dat_i[17] dwb_dat_i[17] -type PI PI
add mapped point dwb_dat_i[16] dwb_dat_i[16] -type PI PI
add mapped point dwb_dat_i[15] dwb_dat_i[15] -type PI PI
add mapped point dwb_dat_i[14] dwb_dat_i[14] -type PI PI
add mapped point dwb_dat_i[13] dwb_dat_i[13] -type PI PI
add mapped point dwb_dat_i[12] dwb_dat_i[12] -type PI PI
add mapped point dwb_dat_i[11] dwb_dat_i[11] -type PI PI
add mapped point dwb_dat_i[10] dwb_dat_i[10] -type PI PI
add mapped point dwb_dat_i[9] dwb_dat_i[9] -type PI PI
add mapped point dwb_dat_i[8] dwb_dat_i[8] -type PI PI
add mapped point dwb_dat_i[7] dwb_dat_i[7] -type PI PI
add mapped point dwb_dat_i[6] dwb_dat_i[6] -type PI PI
add mapped point dwb_dat_i[5] dwb_dat_i[5] -type PI PI
add mapped point dwb_dat_i[4] dwb_dat_i[4] -type PI PI
add mapped point dwb_dat_i[3] dwb_dat_i[3] -type PI PI
add mapped point dwb_dat_i[2] dwb_dat_i[2] -type PI PI
add mapped point dwb_dat_i[1] dwb_dat_i[1] -type PI PI
add mapped point dwb_dat_i[0] dwb_dat_i[0] -type PI PI
add mapped point dwb_ack_i dwb_ack_i -type PI PI
add mapped point dwb_err_i dwb_err_i -type PI PI
add mapped point interrupts[31] interrupts[31] -type PI PI
add mapped point interrupts[30] interrupts[30] -type PI PI
add mapped point interrupts[29] interrupts[29] -type PI PI
add mapped point interrupts[28] interrupts[28] -type PI PI
add mapped point interrupts[27] interrupts[27] -type PI PI
add mapped point interrupts[26] interrupts[26] -type PI PI
add mapped point interrupts[25] interrupts[25] -type PI PI
add mapped point interrupts[24] interrupts[24] -type PI PI
add mapped point interrupts[23] interrupts[23] -type PI PI
add mapped point interrupts[22] interrupts[22] -type PI PI
add mapped point interrupts[21] interrupts[21] -type PI PI
add mapped point interrupts[20] interrupts[20] -type PI PI
add mapped point interrupts[19] interrupts[19] -type PI PI
add mapped point interrupts[18] interrupts[18] -type PI PI
add mapped point interrupts[17] interrupts[17] -type PI PI
add mapped point interrupts[16] interrupts[16] -type PI PI
add mapped point interrupts[15] interrupts[15] -type PI PI
add mapped point interrupts[14] interrupts[14] -type PI PI
add mapped point interrupts[13] interrupts[13] -type PI PI
add mapped point interrupts[12] interrupts[12] -type PI PI
add mapped point interrupts[11] interrupts[11] -type PI PI
add mapped point interrupts[10] interrupts[10] -type PI PI
add mapped point interrupts[9] interrupts[9] -type PI PI
add mapped point interrupts[8] interrupts[8] -type PI PI
add mapped point interrupts[7] interrupts[7] -type PI PI
add mapped point interrupts[6] interrupts[6] -type PI PI
add mapped point interrupts[5] interrupts[5] -type PI PI
add mapped point interrupts[4] interrupts[4] -type PI PI
add mapped point interrupts[3] interrupts[3] -type PI PI
add mapped point interrupts[2] interrupts[2] -type PI PI
add mapped point interrupts[1] interrupts[1] -type PI PI
add mapped point interrupts[0] interrupts[0] -type PI PI

//output ports
add mapped point iwb_adr_o[31] iwb_adr_o[31] -type PO PO
add mapped point iwb_adr_o[30] iwb_adr_o[30] -type PO PO
add mapped point iwb_adr_o[29] iwb_adr_o[29] -type PO PO
add mapped point iwb_adr_o[28] iwb_adr_o[28] -type PO PO
add mapped point iwb_adr_o[27] iwb_adr_o[27] -type PO PO
add mapped point iwb_adr_o[26] iwb_adr_o[26] -type PO PO
add mapped point iwb_adr_o[25] iwb_adr_o[25] -type PO PO
add mapped point iwb_adr_o[24] iwb_adr_o[24] -type PO PO
add mapped point iwb_adr_o[23] iwb_adr_o[23] -type PO PO
add mapped point iwb_adr_o[22] iwb_adr_o[22] -type PO PO
add mapped point iwb_adr_o[21] iwb_adr_o[21] -type PO PO
add mapped point iwb_adr_o[20] iwb_adr_o[20] -type PO PO
add mapped point iwb_adr_o[19] iwb_adr_o[19] -type PO PO
add mapped point iwb_adr_o[18] iwb_adr_o[18] -type PO PO
add mapped point iwb_adr_o[17] iwb_adr_o[17] -type PO PO
add mapped point iwb_adr_o[16] iwb_adr_o[16] -type PO PO
add mapped point iwb_adr_o[15] iwb_adr_o[15] -type PO PO
add mapped point iwb_adr_o[14] iwb_adr_o[14] -type PO PO
add mapped point iwb_adr_o[13] iwb_adr_o[13] -type PO PO
add mapped point iwb_adr_o[12] iwb_adr_o[12] -type PO PO
add mapped point iwb_adr_o[11] iwb_adr_o[11] -type PO PO
add mapped point iwb_adr_o[10] iwb_adr_o[10] -type PO PO
add mapped point iwb_adr_o[9] iwb_adr_o[9] -type PO PO
add mapped point iwb_adr_o[8] iwb_adr_o[8] -type PO PO
add mapped point iwb_adr_o[7] iwb_adr_o[7] -type PO PO
add mapped point iwb_adr_o[6] iwb_adr_o[6] -type PO PO
add mapped point iwb_adr_o[5] iwb_adr_o[5] -type PO PO
add mapped point iwb_adr_o[4] iwb_adr_o[4] -type PO PO
add mapped point iwb_adr_o[3] iwb_adr_o[3] -type PO PO
add mapped point iwb_adr_o[2] iwb_adr_o[2] -type PO PO
add mapped point iwb_adr_o[1] iwb_adr_o[1] -type PO PO
add mapped point iwb_adr_o[0] iwb_adr_o[0] -type PO PO
add mapped point iwb_cyc_o iwb_cyc_o -type PO PO
add mapped point iwb_stb_o iwb_stb_o -type PO PO
add mapped point dwb_adr_o[31] dwb_adr_o[31] -type PO PO
add mapped point dwb_adr_o[30] dwb_adr_o[30] -type PO PO
add mapped point dwb_adr_o[29] dwb_adr_o[29] -type PO PO
add mapped point dwb_adr_o[28] dwb_adr_o[28] -type PO PO
add mapped point dwb_adr_o[27] dwb_adr_o[27] -type PO PO
add mapped point dwb_adr_o[26] dwb_adr_o[26] -type PO PO
add mapped point dwb_adr_o[25] dwb_adr_o[25] -type PO PO
add mapped point dwb_adr_o[24] dwb_adr_o[24] -type PO PO
add mapped point dwb_adr_o[23] dwb_adr_o[23] -type PO PO
add mapped point dwb_adr_o[22] dwb_adr_o[22] -type PO PO
add mapped point dwb_adr_o[21] dwb_adr_o[21] -type PO PO
add mapped point dwb_adr_o[20] dwb_adr_o[20] -type PO PO
add mapped point dwb_adr_o[19] dwb_adr_o[19] -type PO PO
add mapped point dwb_adr_o[18] dwb_adr_o[18] -type PO PO
add mapped point dwb_adr_o[17] dwb_adr_o[17] -type PO PO
add mapped point dwb_adr_o[16] dwb_adr_o[16] -type PO PO
add mapped point dwb_adr_o[15] dwb_adr_o[15] -type PO PO
add mapped point dwb_adr_o[14] dwb_adr_o[14] -type PO PO
add mapped point dwb_adr_o[13] dwb_adr_o[13] -type PO PO
add mapped point dwb_adr_o[12] dwb_adr_o[12] -type PO PO
add mapped point dwb_adr_o[11] dwb_adr_o[11] -type PO PO
add mapped point dwb_adr_o[10] dwb_adr_o[10] -type PO PO
add mapped point dwb_adr_o[9] dwb_adr_o[9] -type PO PO
add mapped point dwb_adr_o[8] dwb_adr_o[8] -type PO PO
add mapped point dwb_adr_o[7] dwb_adr_o[7] -type PO PO
add mapped point dwb_adr_o[6] dwb_adr_o[6] -type PO PO
add mapped point dwb_adr_o[5] dwb_adr_o[5] -type PO PO
add mapped point dwb_adr_o[4] dwb_adr_o[4] -type PO PO
add mapped point dwb_adr_o[3] dwb_adr_o[3] -type PO PO
add mapped point dwb_adr_o[2] dwb_adr_o[2] -type PO PO
add mapped point dwb_adr_o[1] dwb_adr_o[1] -type PO PO
add mapped point dwb_adr_o[0] dwb_adr_o[0] -type PO PO
add mapped point dwb_dat_o[31] dwb_dat_o[31] -type PO PO
add mapped point dwb_dat_o[30] dwb_dat_o[30] -type PO PO
add mapped point dwb_dat_o[29] dwb_dat_o[29] -type PO PO
add mapped point dwb_dat_o[28] dwb_dat_o[28] -type PO PO
add mapped point dwb_dat_o[27] dwb_dat_o[27] -type PO PO
add mapped point dwb_dat_o[26] dwb_dat_o[26] -type PO PO
add mapped point dwb_dat_o[25] dwb_dat_o[25] -type PO PO
add mapped point dwb_dat_o[24] dwb_dat_o[24] -type PO PO
add mapped point dwb_dat_o[23] dwb_dat_o[23] -type PO PO
add mapped point dwb_dat_o[22] dwb_dat_o[22] -type PO PO
add mapped point dwb_dat_o[21] dwb_dat_o[21] -type PO PO
add mapped point dwb_dat_o[20] dwb_dat_o[20] -type PO PO
add mapped point dwb_dat_o[19] dwb_dat_o[19] -type PO PO
add mapped point dwb_dat_o[18] dwb_dat_o[18] -type PO PO
add mapped point dwb_dat_o[17] dwb_dat_o[17] -type PO PO
add mapped point dwb_dat_o[16] dwb_dat_o[16] -type PO PO
add mapped point dwb_dat_o[15] dwb_dat_o[15] -type PO PO
add mapped point dwb_dat_o[14] dwb_dat_o[14] -type PO PO
add mapped point dwb_dat_o[13] dwb_dat_o[13] -type PO PO
add mapped point dwb_dat_o[12] dwb_dat_o[12] -type PO PO
add mapped point dwb_dat_o[11] dwb_dat_o[11] -type PO PO
add mapped point dwb_dat_o[10] dwb_dat_o[10] -type PO PO
add mapped point dwb_dat_o[9] dwb_dat_o[9] -type PO PO
add mapped point dwb_dat_o[8] dwb_dat_o[8] -type PO PO
add mapped point dwb_dat_o[7] dwb_dat_o[7] -type PO PO
add mapped point dwb_dat_o[6] dwb_dat_o[6] -type PO PO
add mapped point dwb_dat_o[5] dwb_dat_o[5] -type PO PO
add mapped point dwb_dat_o[4] dwb_dat_o[4] -type PO PO
add mapped point dwb_dat_o[3] dwb_dat_o[3] -type PO PO
add mapped point dwb_dat_o[2] dwb_dat_o[2] -type PO PO
add mapped point dwb_dat_o[1] dwb_dat_o[1] -type PO PO
add mapped point dwb_dat_o[0] dwb_dat_o[0] -type PO PO
add mapped point dwb_we_o dwb_we_o -type PO PO
add mapped point dwb_sel_o[3] dwb_sel_o[3] -type PO PO
add mapped point dwb_sel_o[2] dwb_sel_o[2] -type PO PO
add mapped point dwb_sel_o[1] dwb_sel_o[1] -type PO PO
add mapped point dwb_sel_o[0] dwb_sel_o[0] -type PO PO
add mapped point dwb_cyc_o dwb_cyc_o -type PO PO
add mapped point dwb_stb_o dwb_stb_o -type PO PO

//inout ports




//Sequential Pins



//Black Boxes
add mapped point u_core_macro u_core_macro -type BBOX BBOX
add mapped point u_mdu_macro u_mdu_macro -type BBOX BBOX



//Empty Modules as Blackboxes
