
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point wb_adr_i[31] wb_adr_i[31] -type PI PI
add mapped point wb_adr_i[30] wb_adr_i[30] -type PI PI
add mapped point wb_adr_i[29] wb_adr_i[29] -type PI PI
add mapped point wb_adr_i[28] wb_adr_i[28] -type PI PI
add mapped point wb_adr_i[27] wb_adr_i[27] -type PI PI
add mapped point wb_adr_i[26] wb_adr_i[26] -type PI PI
add mapped point wb_adr_i[25] wb_adr_i[25] -type PI PI
add mapped point wb_adr_i[24] wb_adr_i[24] -type PI PI
add mapped point wb_adr_i[23] wb_adr_i[23] -type PI PI
add mapped point wb_adr_i[22] wb_adr_i[22] -type PI PI
add mapped point wb_adr_i[21] wb_adr_i[21] -type PI PI
add mapped point wb_adr_i[20] wb_adr_i[20] -type PI PI
add mapped point wb_adr_i[19] wb_adr_i[19] -type PI PI
add mapped point wb_adr_i[18] wb_adr_i[18] -type PI PI
add mapped point wb_adr_i[17] wb_adr_i[17] -type PI PI
add mapped point wb_adr_i[16] wb_adr_i[16] -type PI PI
add mapped point wb_adr_i[15] wb_adr_i[15] -type PI PI
add mapped point wb_adr_i[14] wb_adr_i[14] -type PI PI
add mapped point wb_adr_i[13] wb_adr_i[13] -type PI PI
add mapped point wb_adr_i[12] wb_adr_i[12] -type PI PI
add mapped point wb_adr_i[11] wb_adr_i[11] -type PI PI
add mapped point wb_adr_i[10] wb_adr_i[10] -type PI PI
add mapped point wb_adr_i[9] wb_adr_i[9] -type PI PI
add mapped point wb_adr_i[8] wb_adr_i[8] -type PI PI
add mapped point wb_adr_i[7] wb_adr_i[7] -type PI PI
add mapped point wb_adr_i[6] wb_adr_i[6] -type PI PI
add mapped point wb_adr_i[5] wb_adr_i[5] -type PI PI
add mapped point wb_adr_i[4] wb_adr_i[4] -type PI PI
add mapped point wb_adr_i[3] wb_adr_i[3] -type PI PI
add mapped point wb_adr_i[2] wb_adr_i[2] -type PI PI
add mapped point wb_adr_i[1] wb_adr_i[1] -type PI PI
add mapped point wb_adr_i[0] wb_adr_i[0] -type PI PI
add mapped point wb_dat_i[31] wb_dat_i[31] -type PI PI
add mapped point wb_dat_i[30] wb_dat_i[30] -type PI PI
add mapped point wb_dat_i[29] wb_dat_i[29] -type PI PI
add mapped point wb_dat_i[28] wb_dat_i[28] -type PI PI
add mapped point wb_dat_i[27] wb_dat_i[27] -type PI PI
add mapped point wb_dat_i[26] wb_dat_i[26] -type PI PI
add mapped point wb_dat_i[25] wb_dat_i[25] -type PI PI
add mapped point wb_dat_i[24] wb_dat_i[24] -type PI PI
add mapped point wb_dat_i[23] wb_dat_i[23] -type PI PI
add mapped point wb_dat_i[22] wb_dat_i[22] -type PI PI
add mapped point wb_dat_i[21] wb_dat_i[21] -type PI PI
add mapped point wb_dat_i[20] wb_dat_i[20] -type PI PI
add mapped point wb_dat_i[19] wb_dat_i[19] -type PI PI
add mapped point wb_dat_i[18] wb_dat_i[18] -type PI PI
add mapped point wb_dat_i[17] wb_dat_i[17] -type PI PI
add mapped point wb_dat_i[16] wb_dat_i[16] -type PI PI
add mapped point wb_dat_i[15] wb_dat_i[15] -type PI PI
add mapped point wb_dat_i[14] wb_dat_i[14] -type PI PI
add mapped point wb_dat_i[13] wb_dat_i[13] -type PI PI
add mapped point wb_dat_i[12] wb_dat_i[12] -type PI PI
add mapped point wb_dat_i[11] wb_dat_i[11] -type PI PI
add mapped point wb_dat_i[10] wb_dat_i[10] -type PI PI
add mapped point wb_dat_i[9] wb_dat_i[9] -type PI PI
add mapped point wb_dat_i[8] wb_dat_i[8] -type PI PI
add mapped point wb_dat_i[7] wb_dat_i[7] -type PI PI
add mapped point wb_dat_i[6] wb_dat_i[6] -type PI PI
add mapped point wb_dat_i[5] wb_dat_i[5] -type PI PI
add mapped point wb_dat_i[4] wb_dat_i[4] -type PI PI
add mapped point wb_dat_i[3] wb_dat_i[3] -type PI PI
add mapped point wb_dat_i[2] wb_dat_i[2] -type PI PI
add mapped point wb_dat_i[1] wb_dat_i[1] -type PI PI
add mapped point wb_dat_i[0] wb_dat_i[0] -type PI PI
add mapped point wb_we_i wb_we_i -type PI PI
add mapped point wb_sel_i[3] wb_sel_i[3] -type PI PI
add mapped point wb_sel_i[2] wb_sel_i[2] -type PI PI
add mapped point wb_sel_i[1] wb_sel_i[1] -type PI PI
add mapped point wb_sel_i[0] wb_sel_i[0] -type PI PI
add mapped point wb_cyc_i wb_cyc_i -type PI PI
add mapped point wb_stb_i wb_stb_i -type PI PI
add mapped point uart_rx uart_rx -type PI PI
add mapped point spi_miso spi_miso -type PI PI

//output ports
add mapped point wb_dat_o[31] wb_dat_o[31] -type PO PO
add mapped point wb_dat_o[30] wb_dat_o[30] -type PO PO
add mapped point wb_dat_o[29] wb_dat_o[29] -type PO PO
add mapped point wb_dat_o[28] wb_dat_o[28] -type PO PO
add mapped point wb_dat_o[27] wb_dat_o[27] -type PO PO
add mapped point wb_dat_o[26] wb_dat_o[26] -type PO PO
add mapped point wb_dat_o[25] wb_dat_o[25] -type PO PO
add mapped point wb_dat_o[24] wb_dat_o[24] -type PO PO
add mapped point wb_dat_o[23] wb_dat_o[23] -type PO PO
add mapped point wb_dat_o[22] wb_dat_o[22] -type PO PO
add mapped point wb_dat_o[21] wb_dat_o[21] -type PO PO
add mapped point wb_dat_o[20] wb_dat_o[20] -type PO PO
add mapped point wb_dat_o[19] wb_dat_o[19] -type PO PO
add mapped point wb_dat_o[18] wb_dat_o[18] -type PO PO
add mapped point wb_dat_o[17] wb_dat_o[17] -type PO PO
add mapped point wb_dat_o[16] wb_dat_o[16] -type PO PO
add mapped point wb_dat_o[15] wb_dat_o[15] -type PO PO
add mapped point wb_dat_o[14] wb_dat_o[14] -type PO PO
add mapped point wb_dat_o[13] wb_dat_o[13] -type PO PO
add mapped point wb_dat_o[12] wb_dat_o[12] -type PO PO
add mapped point wb_dat_o[11] wb_dat_o[11] -type PO PO
add mapped point wb_dat_o[10] wb_dat_o[10] -type PO PO
add mapped point wb_dat_o[9] wb_dat_o[9] -type PO PO
add mapped point wb_dat_o[8] wb_dat_o[8] -type PO PO
add mapped point wb_dat_o[7] wb_dat_o[7] -type PO PO
add mapped point wb_dat_o[6] wb_dat_o[6] -type PO PO
add mapped point wb_dat_o[5] wb_dat_o[5] -type PO PO
add mapped point wb_dat_o[4] wb_dat_o[4] -type PO PO
add mapped point wb_dat_o[3] wb_dat_o[3] -type PO PO
add mapped point wb_dat_o[2] wb_dat_o[2] -type PO PO
add mapped point wb_dat_o[1] wb_dat_o[1] -type PO PO
add mapped point wb_dat_o[0] wb_dat_o[0] -type PO PO
add mapped point wb_ack_o wb_ack_o -type PO PO
add mapped point wb_err_o wb_err_o -type PO PO
add mapped point uart_tx uart_tx -type PO PO
add mapped point timer_interrupt timer_interrupt -type PO PO
add mapped point timer_compare_out[3] timer_compare_out[3] -type PO PO
add mapped point timer_compare_out[2] timer_compare_out[2] -type PO PO
add mapped point timer_compare_out[1] timer_compare_out[1] -type PO PO
add mapped point timer_compare_out[0] timer_compare_out[0] -type PO PO
add mapped point spi_sclk spi_sclk -type PO PO
add mapped point spi_mosi spi_mosi -type PO PO
add mapped point spi_cs_n spi_cs_n -type PO PO
add mapped point irq irq -type PO PO
add mapped point comm_status[31] comm_status[31] -type PO PO
add mapped point comm_status[30] comm_status[30] -type PO PO
add mapped point comm_status[29] comm_status[29] -type PO PO
add mapped point comm_status[28] comm_status[28] -type PO PO
add mapped point comm_status[27] comm_status[27] -type PO PO
add mapped point comm_status[26] comm_status[26] -type PO PO
add mapped point comm_status[25] comm_status[25] -type PO PO
add mapped point comm_status[24] comm_status[24] -type PO PO
add mapped point comm_status[23] comm_status[23] -type PO PO
add mapped point comm_status[22] comm_status[22] -type PO PO
add mapped point comm_status[21] comm_status[21] -type PO PO
add mapped point comm_status[20] comm_status[20] -type PO PO
add mapped point comm_status[19] comm_status[19] -type PO PO
add mapped point comm_status[18] comm_status[18] -type PO PO
add mapped point comm_status[17] comm_status[17] -type PO PO
add mapped point comm_status[16] comm_status[16] -type PO PO
add mapped point comm_status[15] comm_status[15] -type PO PO
add mapped point comm_status[14] comm_status[14] -type PO PO
add mapped point comm_status[13] comm_status[13] -type PO PO
add mapped point comm_status[12] comm_status[12] -type PO PO
add mapped point comm_status[11] comm_status[11] -type PO PO
add mapped point comm_status[10] comm_status[10] -type PO PO
add mapped point comm_status[9] comm_status[9] -type PO PO
add mapped point comm_status[8] comm_status[8] -type PO PO
add mapped point comm_status[7] comm_status[7] -type PO PO
add mapped point comm_status[6] comm_status[6] -type PO PO
add mapped point comm_status[5] comm_status[5] -type PO PO
add mapped point comm_status[4] comm_status[4] -type PO PO
add mapped point comm_status[3] comm_status[3] -type PO PO
add mapped point comm_status[2] comm_status[2] -type PO PO
add mapped point comm_status[1] comm_status[1] -type PO PO
add mapped point comm_status[0] comm_status[0] -type PO PO

//inout ports
add mapped point gpio[15] gpio[15]
add mapped point gpio[14] gpio[14]
add mapped point gpio[13] gpio[13]
add mapped point gpio[12] gpio[12]
add mapped point gpio[11] gpio[11]
add mapped point gpio[10] gpio[10]
add mapped point gpio[9] gpio[9]
add mapped point gpio[8] gpio[8]
add mapped point gpio[7] gpio[7]
add mapped point gpio[6] gpio[6]
add mapped point gpio[5] gpio[5]
add mapped point gpio[4] gpio[4]
add mapped point gpio[3] gpio[3]
add mapped point gpio[2] gpio[2]
add mapped point gpio[1] gpio[1]
add mapped point gpio[0] gpio[0]




//Sequential Pins
add mapped point u_gpio/wb_dat_o[11]/q u_gpio/wb_dat_o_reg[11]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[14]/q u_gpio/wb_dat_o_reg[14]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[13]/q u_gpio/wb_dat_o_reg[13]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[12]/q u_gpio/wb_dat_o_reg[12]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[15]/q u_gpio/wb_dat_o_reg[15]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[10]/q u_gpio/wb_dat_o_reg[10]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[9]/q u_gpio/wb_dat_o_reg[9]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[8]/q u_gpio/wb_dat_o_reg[8]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[3]/q u_gpio/wb_dat_o_reg[3]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[6]/q u_gpio/wb_dat_o_reg[6]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[5]/q u_gpio/wb_dat_o_reg[5]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[4]/q u_gpio/wb_dat_o_reg[4]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[7]/q u_gpio/wb_dat_o_reg[7]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[2]/q u_gpio/wb_dat_o_reg[2]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[1]/q u_gpio/wb_dat_o_reg[1]/Q -type DFF DFF
add mapped point u_gpio/wb_dat_o[0]/q u_gpio/wb_dat_o_reg[0]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[0]/q u_gpio/gpio_out_reg_reg[0]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[5]/q u_gpio/gpio_out_reg_reg[5]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[6]/q u_gpio/gpio_out_reg_reg[6]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[7]/q u_gpio/gpio_out_reg_reg[7]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[8]/q u_gpio/gpio_out_reg_reg[8]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[9]/q u_gpio/gpio_out_reg_reg[9]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[10]/q u_gpio/gpio_out_reg_reg[10]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[11]/q u_gpio/gpio_out_reg_reg[11]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[12]/q u_gpio/gpio_out_reg_reg[12]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[13]/q u_gpio/gpio_out_reg_reg[13]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[14]/q u_gpio/gpio_out_reg_reg[14]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[15]/q u_gpio/gpio_out_reg_reg[15]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[3]/q u_gpio/gpio_out_reg_reg[3]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[2]/q u_gpio/gpio_out_reg_reg[2]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[1]/q u_gpio/gpio_out_reg_reg[1]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[15]/q u_gpio/gpio_dir_reg_reg[15]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[1]/q u_gpio/gpio_dir_reg_reg[1]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[14]/q u_gpio/gpio_dir_reg_reg[14]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[13]/q u_gpio/gpio_dir_reg_reg[13]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[12]/q u_gpio/gpio_dir_reg_reg[12]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[11]/q u_gpio/gpio_dir_reg_reg[11]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[10]/q u_gpio/gpio_dir_reg_reg[10]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[9]/q u_gpio/gpio_dir_reg_reg[9]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[8]/q u_gpio/gpio_dir_reg_reg[8]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[7]/q u_gpio/gpio_dir_reg_reg[7]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[6]/q u_gpio/gpio_dir_reg_reg[6]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[5]/q u_gpio/gpio_dir_reg_reg[5]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[4]/q u_gpio/gpio_dir_reg_reg[4]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[3]/q u_gpio/gpio_dir_reg_reg[3]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[2]/q u_gpio/gpio_dir_reg_reg[2]/Q -type DFF DFF
add mapped point u_gpio/gpio_dir_reg[0]/q u_gpio/gpio_dir_reg_reg[0]/Q -type DFF DFF
add mapped point u_gpio/gpio_out_reg[4]/q u_gpio/gpio_out_reg_reg[4]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[1]/q u_gpio/gpio_in_reg_reg[1]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[5]/q u_gpio/gpio_in_reg_reg[5]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[11]/q u_gpio/gpio_in_reg_reg[11]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[7]/q u_gpio/gpio_in_reg_reg[7]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[9]/q u_gpio/gpio_in_reg_reg[9]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[0]/q u_gpio/gpio_in_reg_reg[0]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[2]/q u_gpio/gpio_in_reg_reg[2]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[13]/q u_gpio/gpio_in_reg_reg[13]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[10]/q u_gpio/gpio_in_reg_reg[10]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[12]/q u_gpio/gpio_in_reg_reg[12]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[15]/q u_gpio/gpio_in_reg_reg[15]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[14]/q u_gpio/gpio_in_reg_reg[14]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[4]/q u_gpio/gpio_in_reg_reg[4]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[8]/q u_gpio/gpio_in_reg_reg[8]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[6]/q u_gpio/gpio_in_reg_reg[6]/Q -type DFF DFF
add mapped point u_gpio/gpio_in_reg[3]/q u_gpio/gpio_in_reg_reg[3]/Q -type DFF DFF
add mapped point u_gpio/wb_ack_o/q u_gpio/wb_ack_o_reg/Q -type DFF DFF
add mapped point u_spi/wb_ack_o/q u_spi/wb_ack_o_reg/Q -type DFF DFF
add mapped point u_spi/control_reg[0]/q u_spi/control_reg_reg[0]/Q -type DFF DFF
add mapped point u_spi/control_reg[1]/q u_spi/control_reg_reg[1]/Q -type DFF DFF
add mapped point u_spi/control_reg[2]/q u_spi/control_reg_reg[2]/Q -type DFF DFF
add mapped point u_spi/control_reg[3]/q u_spi/control_reg_reg[3]/Q -type DFF DFF
add mapped point u_spi/control_reg[4]/q u_spi/control_reg_reg[4]/Q -type DFF DFF
add mapped point u_spi/control_reg[5]/q u_spi/control_reg_reg[5]/Q -type DFF DFF
add mapped point u_spi/control_reg[6]/q u_spi/control_reg_reg[6]/Q -type DFF DFF
add mapped point u_spi/control_reg[7]/q u_spi/control_reg_reg[7]/Q -type DFF DFF
add mapped point u_spi/control_reg[8]/q u_spi/control_reg_reg[8]/Q -type DFF DFF
add mapped point u_spi/control_reg[9]/q u_spi/control_reg_reg[9]/Q -type DFF DFF
add mapped point u_spi/control_reg[10]/q u_spi/control_reg_reg[10]/Q -type DFF DFF
add mapped point u_spi/control_reg[11]/q u_spi/control_reg_reg[11]/Q -type DFF DFF
add mapped point u_spi/control_reg[12]/q u_spi/control_reg_reg[12]/Q -type DFF DFF
add mapped point u_spi/control_reg[13]/q u_spi/control_reg_reg[13]/Q -type DFF DFF
add mapped point u_spi/control_reg[14]/q u_spi/control_reg_reg[14]/Q -type DFF DFF
add mapped point u_spi/control_reg[15]/q u_spi/control_reg_reg[15]/Q -type DFF DFF
add mapped point u_spi/control_reg[16]/q u_spi/control_reg_reg[16]/Q -type DFF DFF
add mapped point u_spi/control_reg[17]/q u_spi/control_reg_reg[17]/Q -type DFF DFF
add mapped point u_spi/control_reg[18]/q u_spi/control_reg_reg[18]/Q -type DFF DFF
add mapped point u_spi/control_reg[19]/q u_spi/control_reg_reg[19]/Q -type DFF DFF
add mapped point u_spi/control_reg[20]/q u_spi/control_reg_reg[20]/Q -type DFF DFF
add mapped point u_spi/control_reg[21]/q u_spi/control_reg_reg[21]/Q -type DFF DFF
add mapped point u_spi/control_reg[22]/q u_spi/control_reg_reg[22]/Q -type DFF DFF
add mapped point u_spi/control_reg[23]/q u_spi/control_reg_reg[23]/Q -type DFF DFF
add mapped point u_spi/control_reg[24]/q u_spi/control_reg_reg[24]/Q -type DFF DFF
add mapped point u_spi/control_reg[25]/q u_spi/control_reg_reg[25]/Q -type DFF DFF
add mapped point u_spi/control_reg[26]/q u_spi/control_reg_reg[26]/Q -type DFF DFF
add mapped point u_spi/control_reg[27]/q u_spi/control_reg_reg[27]/Q -type DFF DFF
add mapped point u_spi/control_reg[28]/q u_spi/control_reg_reg[28]/Q -type DFF DFF
add mapped point u_spi/control_reg[29]/q u_spi/control_reg_reg[29]/Q -type DFF DFF
add mapped point u_spi/control_reg[30]/q u_spi/control_reg_reg[30]/Q -type DFF DFF
add mapped point u_spi/control_reg[31]/q u_spi/control_reg_reg[31]/Q -type DFF DFF
add mapped point u_spi/tx_data[0]/q u_spi/tx_data_reg[0]/Q -type DFF DFF
add mapped point u_spi/tx_data[1]/q u_spi/tx_data_reg[1]/Q -type DFF DFF
add mapped point u_spi/tx_data[2]/q u_spi/tx_data_reg[2]/Q -type DFF DFF
add mapped point u_spi/tx_data[3]/q u_spi/tx_data_reg[3]/Q -type DFF DFF
add mapped point u_spi/tx_data[4]/q u_spi/tx_data_reg[4]/Q -type DFF DFF
add mapped point u_spi/tx_data[5]/q u_spi/tx_data_reg[5]/Q -type DFF DFF
add mapped point u_spi/tx_data[6]/q u_spi/tx_data_reg[6]/Q -type DFF DFF
add mapped point u_spi/tx_data[7]/q u_spi/tx_data_reg[7]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[0]/q u_spi/wb_dat_o_reg[0]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[1]/q u_spi/wb_dat_o_reg[1]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[2]/q u_spi/wb_dat_o_reg[2]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[3]/q u_spi/wb_dat_o_reg[3]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[4]/q u_spi/wb_dat_o_reg[4]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[5]/q u_spi/wb_dat_o_reg[5]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[6]/q u_spi/wb_dat_o_reg[6]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[7]/q u_spi/wb_dat_o_reg[7]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[8]/q u_spi/wb_dat_o_reg[8]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[9]/q u_spi/wb_dat_o_reg[9]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[10]/q u_spi/wb_dat_o_reg[10]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[11]/q u_spi/wb_dat_o_reg[11]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[12]/q u_spi/wb_dat_o_reg[12]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[13]/q u_spi/wb_dat_o_reg[13]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[14]/q u_spi/wb_dat_o_reg[14]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[15]/q u_spi/wb_dat_o_reg[15]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[16]/q u_spi/wb_dat_o_reg[16]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[17]/q u_spi/wb_dat_o_reg[17]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[18]/q u_spi/wb_dat_o_reg[18]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[19]/q u_spi/wb_dat_o_reg[19]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[20]/q u_spi/wb_dat_o_reg[20]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[21]/q u_spi/wb_dat_o_reg[21]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[22]/q u_spi/wb_dat_o_reg[22]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[23]/q u_spi/wb_dat_o_reg[23]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[24]/q u_spi/wb_dat_o_reg[24]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[25]/q u_spi/wb_dat_o_reg[25]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[26]/q u_spi/wb_dat_o_reg[26]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[27]/q u_spi/wb_dat_o_reg[27]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[28]/q u_spi/wb_dat_o_reg[28]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[29]/q u_spi/wb_dat_o_reg[29]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[30]/q u_spi/wb_dat_o_reg[30]/Q -type DFF DFF
add mapped point u_spi/wb_dat_o[31]/q u_spi/wb_dat_o_reg[31]/Q -type DFF DFF
add mapped point u_timer/wb_ack_o/q u_timer/wb_ack_o_reg/Q -type DFF DFF
add mapped point u_timer/compare_out[0]/q u_timer/compare_out_reg[0]/Q -type DFF DFF
add mapped point u_timer/compare_out[1]/q u_timer/compare_out_reg[1]/Q -type DFF DFF
add mapped point u_timer/compare_out[2]/q u_timer/compare_out_reg[2]/Q -type DFF DFF
add mapped point u_timer/compare_out[3]/q u_timer/compare_out_reg[3]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][0]/q u_timer/compare_val_reg[0][0]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][1]/q u_timer/compare_val_reg[0][1]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][2]/q u_timer/compare_val_reg[0][2]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][3]/q u_timer/compare_val_reg[0][3]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][4]/q u_timer/compare_val_reg[0][4]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][5]/q u_timer/compare_val_reg[0][5]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][6]/q u_timer/compare_val_reg[0][6]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][7]/q u_timer/compare_val_reg[0][7]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][8]/q u_timer/compare_val_reg[0][8]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][9]/q u_timer/compare_val_reg[0][9]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][10]/q u_timer/compare_val_reg[0][10]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][11]/q u_timer/compare_val_reg[0][11]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][12]/q u_timer/compare_val_reg[0][12]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][13]/q u_timer/compare_val_reg[0][13]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][14]/q u_timer/compare_val_reg[0][14]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][15]/q u_timer/compare_val_reg[0][15]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][16]/q u_timer/compare_val_reg[0][16]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][17]/q u_timer/compare_val_reg[0][17]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][18]/q u_timer/compare_val_reg[0][18]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][19]/q u_timer/compare_val_reg[0][19]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][20]/q u_timer/compare_val_reg[0][20]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][21]/q u_timer/compare_val_reg[0][21]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][22]/q u_timer/compare_val_reg[0][22]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][23]/q u_timer/compare_val_reg[0][23]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][24]/q u_timer/compare_val_reg[0][24]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][25]/q u_timer/compare_val_reg[0][25]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][26]/q u_timer/compare_val_reg[0][26]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][27]/q u_timer/compare_val_reg[0][27]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][28]/q u_timer/compare_val_reg[0][28]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][29]/q u_timer/compare_val_reg[0][29]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][30]/q u_timer/compare_val_reg[0][30]/Q -type DFF DFF
add mapped point u_timer/compare_val[0][31]/q u_timer/compare_val_reg[0][31]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][0]/q u_timer/compare_val_reg[1][0]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][1]/q u_timer/compare_val_reg[1][1]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][2]/q u_timer/compare_val_reg[1][2]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][3]/q u_timer/compare_val_reg[1][3]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][4]/q u_timer/compare_val_reg[1][4]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][5]/q u_timer/compare_val_reg[1][5]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][6]/q u_timer/compare_val_reg[1][6]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][7]/q u_timer/compare_val_reg[1][7]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][8]/q u_timer/compare_val_reg[1][8]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][9]/q u_timer/compare_val_reg[1][9]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][10]/q u_timer/compare_val_reg[1][10]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][11]/q u_timer/compare_val_reg[1][11]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][12]/q u_timer/compare_val_reg[1][12]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][13]/q u_timer/compare_val_reg[1][13]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][14]/q u_timer/compare_val_reg[1][14]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][15]/q u_timer/compare_val_reg[1][15]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][16]/q u_timer/compare_val_reg[1][16]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][17]/q u_timer/compare_val_reg[1][17]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][18]/q u_timer/compare_val_reg[1][18]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][19]/q u_timer/compare_val_reg[1][19]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][20]/q u_timer/compare_val_reg[1][20]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][21]/q u_timer/compare_val_reg[1][21]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][22]/q u_timer/compare_val_reg[1][22]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][23]/q u_timer/compare_val_reg[1][23]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][24]/q u_timer/compare_val_reg[1][24]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][25]/q u_timer/compare_val_reg[1][25]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][26]/q u_timer/compare_val_reg[1][26]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][27]/q u_timer/compare_val_reg[1][27]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][28]/q u_timer/compare_val_reg[1][28]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][29]/q u_timer/compare_val_reg[1][29]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][30]/q u_timer/compare_val_reg[1][30]/Q -type DFF DFF
add mapped point u_timer/compare_val[1][31]/q u_timer/compare_val_reg[1][31]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][0]/q u_timer/compare_val_reg[2][0]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][1]/q u_timer/compare_val_reg[2][1]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][2]/q u_timer/compare_val_reg[2][2]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][3]/q u_timer/compare_val_reg[2][3]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][4]/q u_timer/compare_val_reg[2][4]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][5]/q u_timer/compare_val_reg[2][5]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][6]/q u_timer/compare_val_reg[2][6]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][7]/q u_timer/compare_val_reg[2][7]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][8]/q u_timer/compare_val_reg[2][8]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][9]/q u_timer/compare_val_reg[2][9]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][10]/q u_timer/compare_val_reg[2][10]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][11]/q u_timer/compare_val_reg[2][11]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][12]/q u_timer/compare_val_reg[2][12]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][13]/q u_timer/compare_val_reg[2][13]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][14]/q u_timer/compare_val_reg[2][14]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][15]/q u_timer/compare_val_reg[2][15]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][16]/q u_timer/compare_val_reg[2][16]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][17]/q u_timer/compare_val_reg[2][17]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][18]/q u_timer/compare_val_reg[2][18]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][19]/q u_timer/compare_val_reg[2][19]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][20]/q u_timer/compare_val_reg[2][20]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][21]/q u_timer/compare_val_reg[2][21]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][22]/q u_timer/compare_val_reg[2][22]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][23]/q u_timer/compare_val_reg[2][23]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][24]/q u_timer/compare_val_reg[2][24]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][25]/q u_timer/compare_val_reg[2][25]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][26]/q u_timer/compare_val_reg[2][26]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][27]/q u_timer/compare_val_reg[2][27]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][28]/q u_timer/compare_val_reg[2][28]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][29]/q u_timer/compare_val_reg[2][29]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][30]/q u_timer/compare_val_reg[2][30]/Q -type DFF DFF
add mapped point u_timer/compare_val[2][31]/q u_timer/compare_val_reg[2][31]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][0]/q u_timer/compare_val_reg[3][0]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][1]/q u_timer/compare_val_reg[3][1]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][2]/q u_timer/compare_val_reg[3][2]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][3]/q u_timer/compare_val_reg[3][3]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][4]/q u_timer/compare_val_reg[3][4]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][5]/q u_timer/compare_val_reg[3][5]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][6]/q u_timer/compare_val_reg[3][6]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][7]/q u_timer/compare_val_reg[3][7]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][8]/q u_timer/compare_val_reg[3][8]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][9]/q u_timer/compare_val_reg[3][9]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][10]/q u_timer/compare_val_reg[3][10]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][11]/q u_timer/compare_val_reg[3][11]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][12]/q u_timer/compare_val_reg[3][12]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][13]/q u_timer/compare_val_reg[3][13]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][14]/q u_timer/compare_val_reg[3][14]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][15]/q u_timer/compare_val_reg[3][15]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][16]/q u_timer/compare_val_reg[3][16]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][17]/q u_timer/compare_val_reg[3][17]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][18]/q u_timer/compare_val_reg[3][18]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][19]/q u_timer/compare_val_reg[3][19]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][20]/q u_timer/compare_val_reg[3][20]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][21]/q u_timer/compare_val_reg[3][21]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][22]/q u_timer/compare_val_reg[3][22]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][23]/q u_timer/compare_val_reg[3][23]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][24]/q u_timer/compare_val_reg[3][24]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][25]/q u_timer/compare_val_reg[3][25]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][26]/q u_timer/compare_val_reg[3][26]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][27]/q u_timer/compare_val_reg[3][27]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][28]/q u_timer/compare_val_reg[3][28]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][29]/q u_timer/compare_val_reg[3][29]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][30]/q u_timer/compare_val_reg[3][30]/Q -type DFF DFF
add mapped point u_timer/compare_val[3][31]/q u_timer/compare_val_reg[3][31]/Q -type DFF DFF
add mapped point u_timer/control_reg[0]/q u_timer/control_reg_reg[0]/Q -type DFF DFF
add mapped point u_timer/control_reg[1]/q u_timer/control_reg_reg[1]/Q -type DFF DFF
add mapped point u_timer/control_reg[2]/q u_timer/control_reg_reg[2]/Q -type DFF DFF
add mapped point u_timer/control_reg[3]/q u_timer/control_reg_reg[3]/Q -type DFF DFF
add mapped point u_timer/control_reg[4]/q u_timer/control_reg_reg[4]/Q -type DFF DFF
add mapped point u_timer/control_reg[5]/q u_timer/control_reg_reg[5]/Q -type DFF DFF
add mapped point u_timer/control_reg[6]/q u_timer/control_reg_reg[6]/Q -type DFF DFF
add mapped point u_timer/control_reg[7]/q u_timer/control_reg_reg[7]/Q -type DFF DFF
add mapped point u_timer/control_reg[8]/q u_timer/control_reg_reg[8]/Q -type DFF DFF
add mapped point u_timer/control_reg[9]/q u_timer/control_reg_reg[9]/Q -type DFF DFF
add mapped point u_timer/control_reg[10]/q u_timer/control_reg_reg[10]/Q -type DFF DFF
add mapped point u_timer/control_reg[11]/q u_timer/control_reg_reg[11]/Q -type DFF DFF
add mapped point u_timer/control_reg[12]/q u_timer/control_reg_reg[12]/Q -type DFF DFF
add mapped point u_timer/control_reg[13]/q u_timer/control_reg_reg[13]/Q -type DFF DFF
add mapped point u_timer/control_reg[14]/q u_timer/control_reg_reg[14]/Q -type DFF DFF
add mapped point u_timer/control_reg[15]/q u_timer/control_reg_reg[15]/Q -type DFF DFF
add mapped point u_timer/control_reg[16]/q u_timer/control_reg_reg[16]/Q -type DFF DFF
add mapped point u_timer/control_reg[17]/q u_timer/control_reg_reg[17]/Q -type DFF DFF
add mapped point u_timer/control_reg[18]/q u_timer/control_reg_reg[18]/Q -type DFF DFF
add mapped point u_timer/control_reg[19]/q u_timer/control_reg_reg[19]/Q -type DFF DFF
add mapped point u_timer/control_reg[20]/q u_timer/control_reg_reg[20]/Q -type DFF DFF
add mapped point u_timer/control_reg[21]/q u_timer/control_reg_reg[21]/Q -type DFF DFF
add mapped point u_timer/control_reg[22]/q u_timer/control_reg_reg[22]/Q -type DFF DFF
add mapped point u_timer/control_reg[23]/q u_timer/control_reg_reg[23]/Q -type DFF DFF
add mapped point u_timer/control_reg[24]/q u_timer/control_reg_reg[24]/Q -type DFF DFF
add mapped point u_timer/control_reg[25]/q u_timer/control_reg_reg[25]/Q -type DFF DFF
add mapped point u_timer/control_reg[26]/q u_timer/control_reg_reg[26]/Q -type DFF DFF
add mapped point u_timer/control_reg[27]/q u_timer/control_reg_reg[27]/Q -type DFF DFF
add mapped point u_timer/control_reg[28]/q u_timer/control_reg_reg[28]/Q -type DFF DFF
add mapped point u_timer/control_reg[29]/q u_timer/control_reg_reg[29]/Q -type DFF DFF
add mapped point u_timer/control_reg[30]/q u_timer/control_reg_reg[30]/Q -type DFF DFF
add mapped point u_timer/control_reg[31]/q u_timer/control_reg_reg[31]/Q -type DFF DFF
add mapped point u_timer/timer_counter[0]/q u_timer/timer_counter_reg[0]/Q -type DFF DFF
add mapped point u_timer/timer_counter[1]/q u_timer/timer_counter_reg[1]/Q -type DFF DFF
add mapped point u_timer/timer_counter[2]/q u_timer/timer_counter_reg[2]/Q -type DFF DFF
add mapped point u_timer/timer_counter[3]/q u_timer/timer_counter_reg[3]/Q -type DFF DFF
add mapped point u_timer/timer_counter[4]/q u_timer/timer_counter_reg[4]/Q -type DFF DFF
add mapped point u_timer/timer_counter[5]/q u_timer/timer_counter_reg[5]/Q -type DFF DFF
add mapped point u_timer/timer_counter[6]/q u_timer/timer_counter_reg[6]/Q -type DFF DFF
add mapped point u_timer/timer_counter[7]/q u_timer/timer_counter_reg[7]/Q -type DFF DFF
add mapped point u_timer/timer_counter[8]/q u_timer/timer_counter_reg[8]/Q -type DFF DFF
add mapped point u_timer/timer_counter[9]/q u_timer/timer_counter_reg[9]/Q -type DFF DFF
add mapped point u_timer/timer_counter[10]/q u_timer/timer_counter_reg[10]/Q -type DFF DFF
add mapped point u_timer/timer_counter[11]/q u_timer/timer_counter_reg[11]/Q -type DFF DFF
add mapped point u_timer/timer_counter[12]/q u_timer/timer_counter_reg[12]/Q -type DFF DFF
add mapped point u_timer/timer_counter[13]/q u_timer/timer_counter_reg[13]/Q -type DFF DFF
add mapped point u_timer/timer_counter[14]/q u_timer/timer_counter_reg[14]/Q -type DFF DFF
add mapped point u_timer/timer_counter[15]/q u_timer/timer_counter_reg[15]/Q -type DFF DFF
add mapped point u_timer/timer_counter[16]/q u_timer/timer_counter_reg[16]/Q -type DFF DFF
add mapped point u_timer/timer_counter[17]/q u_timer/timer_counter_reg[17]/Q -type DFF DFF
add mapped point u_timer/timer_counter[18]/q u_timer/timer_counter_reg[18]/Q -type DFF DFF
add mapped point u_timer/timer_counter[19]/q u_timer/timer_counter_reg[19]/Q -type DFF DFF
add mapped point u_timer/timer_counter[20]/q u_timer/timer_counter_reg[20]/Q -type DFF DFF
add mapped point u_timer/timer_counter[21]/q u_timer/timer_counter_reg[21]/Q -type DFF DFF
add mapped point u_timer/timer_counter[22]/q u_timer/timer_counter_reg[22]/Q -type DFF DFF
add mapped point u_timer/timer_counter[23]/q u_timer/timer_counter_reg[23]/Q -type DFF DFF
add mapped point u_timer/timer_counter[24]/q u_timer/timer_counter_reg[24]/Q -type DFF DFF
add mapped point u_timer/timer_counter[25]/q u_timer/timer_counter_reg[25]/Q -type DFF DFF
add mapped point u_timer/timer_counter[26]/q u_timer/timer_counter_reg[26]/Q -type DFF DFF
add mapped point u_timer/timer_counter[27]/q u_timer/timer_counter_reg[27]/Q -type DFF DFF
add mapped point u_timer/timer_counter[28]/q u_timer/timer_counter_reg[28]/Q -type DFF DFF
add mapped point u_timer/timer_counter[29]/q u_timer/timer_counter_reg[29]/Q -type DFF DFF
add mapped point u_timer/timer_counter[30]/q u_timer/timer_counter_reg[30]/Q -type DFF DFF
add mapped point u_timer/timer_counter[31]/q u_timer/timer_counter_reg[31]/Q -type DFF DFF
add mapped point u_timer/timer_interrupt/q u_timer/timer_interrupt_reg/Q -type DFF DFF
add mapped point u_timer/timer_period[0]/q u_timer/timer_period_reg[0]/Q -type DFF DFF
add mapped point u_timer/timer_period[1]/q u_timer/timer_period_reg[1]/Q -type DFF DFF
add mapped point u_timer/timer_period[2]/q u_timer/timer_period_reg[2]/Q -type DFF DFF
add mapped point u_timer/timer_period[3]/q u_timer/timer_period_reg[3]/Q -type DFF DFF
add mapped point u_timer/timer_period[4]/q u_timer/timer_period_reg[4]/Q -type DFF DFF
add mapped point u_timer/timer_period[5]/q u_timer/timer_period_reg[5]/Q -type DFF DFF
add mapped point u_timer/timer_period[6]/q u_timer/timer_period_reg[6]/Q -type DFF DFF
add mapped point u_timer/timer_period[7]/q u_timer/timer_period_reg[7]/Q -type DFF DFF
add mapped point u_timer/timer_period[8]/q u_timer/timer_period_reg[8]/Q -type DFF DFF
add mapped point u_timer/timer_period[9]/q u_timer/timer_period_reg[9]/Q -type DFF DFF
add mapped point u_timer/timer_period[10]/q u_timer/timer_period_reg[10]/Q -type DFF DFF
add mapped point u_timer/timer_period[11]/q u_timer/timer_period_reg[11]/Q -type DFF DFF
add mapped point u_timer/timer_period[12]/q u_timer/timer_period_reg[12]/Q -type DFF DFF
add mapped point u_timer/timer_period[13]/q u_timer/timer_period_reg[13]/Q -type DFF DFF
add mapped point u_timer/timer_period[14]/q u_timer/timer_period_reg[14]/Q -type DFF DFF
add mapped point u_timer/timer_period[15]/q u_timer/timer_period_reg[15]/Q -type DFF DFF
add mapped point u_timer/timer_period[16]/q u_timer/timer_period_reg[16]/Q -type DFF DFF
add mapped point u_timer/timer_period[17]/q u_timer/timer_period_reg[17]/Q -type DFF DFF
add mapped point u_timer/timer_period[18]/q u_timer/timer_period_reg[18]/Q -type DFF DFF
add mapped point u_timer/timer_period[19]/q u_timer/timer_period_reg[19]/Q -type DFF DFF
add mapped point u_timer/timer_period[20]/q u_timer/timer_period_reg[20]/Q -type DFF DFF
add mapped point u_timer/timer_period[21]/q u_timer/timer_period_reg[21]/Q -type DFF DFF
add mapped point u_timer/timer_period[22]/q u_timer/timer_period_reg[22]/Q -type DFF DFF
add mapped point u_timer/timer_period[23]/q u_timer/timer_period_reg[23]/Q -type DFF DFF
add mapped point u_timer/timer_period[24]/q u_timer/timer_period_reg[24]/Q -type DFF DFF
add mapped point u_timer/timer_period[25]/q u_timer/timer_period_reg[25]/Q -type DFF DFF
add mapped point u_timer/timer_period[26]/q u_timer/timer_period_reg[26]/Q -type DFF DFF
add mapped point u_timer/timer_period[27]/q u_timer/timer_period_reg[27]/Q -type DFF DFF
add mapped point u_timer/timer_period[28]/q u_timer/timer_period_reg[28]/Q -type DFF DFF
add mapped point u_timer/timer_period[29]/q u_timer/timer_period_reg[29]/Q -type DFF DFF
add mapped point u_timer/timer_period[30]/q u_timer/timer_period_reg[30]/Q -type DFF DFF
add mapped point u_timer/timer_period[31]/q u_timer/timer_period_reg[31]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[0]/q u_timer/wb_dat_o_reg[0]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[1]/q u_timer/wb_dat_o_reg[1]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[2]/q u_timer/wb_dat_o_reg[2]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[3]/q u_timer/wb_dat_o_reg[3]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[4]/q u_timer/wb_dat_o_reg[4]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[5]/q u_timer/wb_dat_o_reg[5]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[6]/q u_timer/wb_dat_o_reg[6]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[7]/q u_timer/wb_dat_o_reg[7]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[8]/q u_timer/wb_dat_o_reg[8]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[9]/q u_timer/wb_dat_o_reg[9]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[10]/q u_timer/wb_dat_o_reg[10]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[11]/q u_timer/wb_dat_o_reg[11]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[12]/q u_timer/wb_dat_o_reg[12]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[13]/q u_timer/wb_dat_o_reg[13]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[14]/q u_timer/wb_dat_o_reg[14]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[15]/q u_timer/wb_dat_o_reg[15]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[16]/q u_timer/wb_dat_o_reg[16]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[17]/q u_timer/wb_dat_o_reg[17]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[18]/q u_timer/wb_dat_o_reg[18]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[19]/q u_timer/wb_dat_o_reg[19]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[20]/q u_timer/wb_dat_o_reg[20]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[21]/q u_timer/wb_dat_o_reg[21]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[22]/q u_timer/wb_dat_o_reg[22]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[23]/q u_timer/wb_dat_o_reg[23]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[24]/q u_timer/wb_dat_o_reg[24]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[25]/q u_timer/wb_dat_o_reg[25]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[26]/q u_timer/wb_dat_o_reg[26]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[27]/q u_timer/wb_dat_o_reg[27]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[28]/q u_timer/wb_dat_o_reg[28]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[29]/q u_timer/wb_dat_o_reg[29]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[30]/q u_timer/wb_dat_o_reg[30]/Q -type DFF DFF
add mapped point u_timer/wb_dat_o[31]/q u_timer/wb_dat_o_reg[31]/Q -type DFF DFF
add mapped point u_uart/wb_ack_o/q u_uart/wb_ack_o_reg/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[0]/q u_uart/baud_div_reg_reg[0]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[1]/q u_uart/baud_div_reg_reg[1]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[2]/q u_uart/baud_div_reg_reg[2]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[3]/q u_uart/baud_div_reg_reg[3]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[4]/q u_uart/baud_div_reg_reg[4]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[5]/q u_uart/baud_div_reg_reg[5]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[6]/q u_uart/baud_div_reg_reg[6]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[7]/q u_uart/baud_div_reg_reg[7]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[8]/q u_uart/baud_div_reg_reg[8]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[9]/q u_uart/baud_div_reg_reg[9]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[10]/q u_uart/baud_div_reg_reg[10]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[11]/q u_uart/baud_div_reg_reg[11]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[12]/q u_uart/baud_div_reg_reg[12]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[13]/q u_uart/baud_div_reg_reg[13]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[14]/q u_uart/baud_div_reg_reg[14]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[15]/q u_uart/baud_div_reg_reg[15]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[16]/q u_uart/baud_div_reg_reg[16]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[17]/q u_uart/baud_div_reg_reg[17]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[18]/q u_uart/baud_div_reg_reg[18]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[19]/q u_uart/baud_div_reg_reg[19]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[20]/q u_uart/baud_div_reg_reg[20]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[21]/q u_uart/baud_div_reg_reg[21]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[22]/q u_uart/baud_div_reg_reg[22]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[23]/q u_uart/baud_div_reg_reg[23]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[24]/q u_uart/baud_div_reg_reg[24]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[25]/q u_uart/baud_div_reg_reg[25]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[26]/q u_uart/baud_div_reg_reg[26]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[27]/q u_uart/baud_div_reg_reg[27]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[28]/q u_uart/baud_div_reg_reg[28]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[29]/q u_uart/baud_div_reg_reg[29]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[30]/q u_uart/baud_div_reg_reg[30]/Q -type DFF DFF
add mapped point u_uart/baud_div_reg[31]/q u_uart/baud_div_reg_reg[31]/Q -type DFF DFF
add mapped point u_uart/control_reg[0]/q u_uart/control_reg_reg[0]/Q -type DFF DFF
add mapped point u_uart/control_reg[1]/q u_uart/control_reg_reg[1]/Q -type DFF DFF
add mapped point u_uart/control_reg[2]/q u_uart/control_reg_reg[2]/Q -type DFF DFF
add mapped point u_uart/control_reg[3]/q u_uart/control_reg_reg[3]/Q -type DFF DFF
add mapped point u_uart/control_reg[4]/q u_uart/control_reg_reg[4]/Q -type DFF DFF
add mapped point u_uart/control_reg[5]/q u_uart/control_reg_reg[5]/Q -type DFF DFF
add mapped point u_uart/control_reg[6]/q u_uart/control_reg_reg[6]/Q -type DFF DFF
add mapped point u_uart/control_reg[7]/q u_uart/control_reg_reg[7]/Q -type DFF DFF
add mapped point u_uart/control_reg[8]/q u_uart/control_reg_reg[8]/Q -type DFF DFF
add mapped point u_uart/control_reg[9]/q u_uart/control_reg_reg[9]/Q -type DFF DFF
add mapped point u_uart/control_reg[10]/q u_uart/control_reg_reg[10]/Q -type DFF DFF
add mapped point u_uart/control_reg[11]/q u_uart/control_reg_reg[11]/Q -type DFF DFF
add mapped point u_uart/control_reg[12]/q u_uart/control_reg_reg[12]/Q -type DFF DFF
add mapped point u_uart/control_reg[13]/q u_uart/control_reg_reg[13]/Q -type DFF DFF
add mapped point u_uart/control_reg[14]/q u_uart/control_reg_reg[14]/Q -type DFF DFF
add mapped point u_uart/control_reg[15]/q u_uart/control_reg_reg[15]/Q -type DFF DFF
add mapped point u_uart/control_reg[16]/q u_uart/control_reg_reg[16]/Q -type DFF DFF
add mapped point u_uart/control_reg[17]/q u_uart/control_reg_reg[17]/Q -type DFF DFF
add mapped point u_uart/control_reg[18]/q u_uart/control_reg_reg[18]/Q -type DFF DFF
add mapped point u_uart/control_reg[19]/q u_uart/control_reg_reg[19]/Q -type DFF DFF
add mapped point u_uart/control_reg[20]/q u_uart/control_reg_reg[20]/Q -type DFF DFF
add mapped point u_uart/control_reg[21]/q u_uart/control_reg_reg[21]/Q -type DFF DFF
add mapped point u_uart/control_reg[22]/q u_uart/control_reg_reg[22]/Q -type DFF DFF
add mapped point u_uart/control_reg[23]/q u_uart/control_reg_reg[23]/Q -type DFF DFF
add mapped point u_uart/control_reg[24]/q u_uart/control_reg_reg[24]/Q -type DFF DFF
add mapped point u_uart/control_reg[25]/q u_uart/control_reg_reg[25]/Q -type DFF DFF
add mapped point u_uart/control_reg[26]/q u_uart/control_reg_reg[26]/Q -type DFF DFF
add mapped point u_uart/control_reg[27]/q u_uart/control_reg_reg[27]/Q -type DFF DFF
add mapped point u_uart/control_reg[28]/q u_uart/control_reg_reg[28]/Q -type DFF DFF
add mapped point u_uart/control_reg[29]/q u_uart/control_reg_reg[29]/Q -type DFF DFF
add mapped point u_uart/control_reg[30]/q u_uart/control_reg_reg[30]/Q -type DFF DFF
add mapped point u_uart/control_reg[31]/q u_uart/control_reg_reg[31]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[0]/q u_uart/wb_dat_o_reg[0]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[1]/q u_uart/wb_dat_o_reg[1]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[2]/q u_uart/wb_dat_o_reg[2]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[3]/q u_uart/wb_dat_o_reg[3]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[4]/q u_uart/wb_dat_o_reg[4]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[5]/q u_uart/wb_dat_o_reg[5]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[6]/q u_uart/wb_dat_o_reg[6]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[7]/q u_uart/wb_dat_o_reg[7]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[8]/q u_uart/wb_dat_o_reg[8]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[9]/q u_uart/wb_dat_o_reg[9]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[10]/q u_uart/wb_dat_o_reg[10]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[11]/q u_uart/wb_dat_o_reg[11]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[12]/q u_uart/wb_dat_o_reg[12]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[13]/q u_uart/wb_dat_o_reg[13]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[14]/q u_uart/wb_dat_o_reg[14]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[15]/q u_uart/wb_dat_o_reg[15]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[16]/q u_uart/wb_dat_o_reg[16]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[17]/q u_uart/wb_dat_o_reg[17]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[18]/q u_uart/wb_dat_o_reg[18]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[19]/q u_uart/wb_dat_o_reg[19]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[20]/q u_uart/wb_dat_o_reg[20]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[21]/q u_uart/wb_dat_o_reg[21]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[22]/q u_uart/wb_dat_o_reg[22]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[23]/q u_uart/wb_dat_o_reg[23]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[24]/q u_uart/wb_dat_o_reg[24]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[25]/q u_uart/wb_dat_o_reg[25]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[26]/q u_uart/wb_dat_o_reg[26]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[27]/q u_uart/wb_dat_o_reg[27]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[28]/q u_uart/wb_dat_o_reg[28]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[29]/q u_uart/wb_dat_o_reg[29]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[30]/q u_uart/wb_dat_o_reg[30]/Q -type DFF DFF
add mapped point u_uart/wb_dat_o[31]/q u_uart/wb_dat_o_reg[31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
