
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point iwb_adr_i[31] iwb_adr_i[31] -type PI PI
add mapped point iwb_adr_i[30] iwb_adr_i[30] -type PI PI
add mapped point iwb_adr_i[29] iwb_adr_i[29] -type PI PI
add mapped point iwb_adr_i[28] iwb_adr_i[28] -type PI PI
add mapped point iwb_adr_i[27] iwb_adr_i[27] -type PI PI
add mapped point iwb_adr_i[26] iwb_adr_i[26] -type PI PI
add mapped point iwb_adr_i[25] iwb_adr_i[25] -type PI PI
add mapped point iwb_adr_i[24] iwb_adr_i[24] -type PI PI
add mapped point iwb_adr_i[23] iwb_adr_i[23] -type PI PI
add mapped point iwb_adr_i[22] iwb_adr_i[22] -type PI PI
add mapped point iwb_adr_i[21] iwb_adr_i[21] -type PI PI
add mapped point iwb_adr_i[20] iwb_adr_i[20] -type PI PI
add mapped point iwb_adr_i[19] iwb_adr_i[19] -type PI PI
add mapped point iwb_adr_i[18] iwb_adr_i[18] -type PI PI
add mapped point iwb_adr_i[17] iwb_adr_i[17] -type PI PI
add mapped point iwb_adr_i[16] iwb_adr_i[16] -type PI PI
add mapped point iwb_adr_i[15] iwb_adr_i[15] -type PI PI
add mapped point iwb_adr_i[14] iwb_adr_i[14] -type PI PI
add mapped point iwb_adr_i[13] iwb_adr_i[13] -type PI PI
add mapped point iwb_adr_i[12] iwb_adr_i[12] -type PI PI
add mapped point iwb_adr_i[11] iwb_adr_i[11] -type PI PI
add mapped point iwb_adr_i[10] iwb_adr_i[10] -type PI PI
add mapped point iwb_adr_i[9] iwb_adr_i[9] -type PI PI
add mapped point iwb_adr_i[8] iwb_adr_i[8] -type PI PI
add mapped point iwb_adr_i[7] iwb_adr_i[7] -type PI PI
add mapped point iwb_adr_i[6] iwb_adr_i[6] -type PI PI
add mapped point iwb_adr_i[5] iwb_adr_i[5] -type PI PI
add mapped point iwb_adr_i[4] iwb_adr_i[4] -type PI PI
add mapped point iwb_adr_i[3] iwb_adr_i[3] -type PI PI
add mapped point iwb_adr_i[2] iwb_adr_i[2] -type PI PI
add mapped point iwb_adr_i[1] iwb_adr_i[1] -type PI PI
add mapped point iwb_adr_i[0] iwb_adr_i[0] -type PI PI
add mapped point iwb_dat_i[31] iwb_dat_i[31] -type PI PI
add mapped point iwb_dat_i[30] iwb_dat_i[30] -type PI PI
add mapped point iwb_dat_i[29] iwb_dat_i[29] -type PI PI
add mapped point iwb_dat_i[28] iwb_dat_i[28] -type PI PI
add mapped point iwb_dat_i[27] iwb_dat_i[27] -type PI PI
add mapped point iwb_dat_i[26] iwb_dat_i[26] -type PI PI
add mapped point iwb_dat_i[25] iwb_dat_i[25] -type PI PI
add mapped point iwb_dat_i[24] iwb_dat_i[24] -type PI PI
add mapped point iwb_dat_i[23] iwb_dat_i[23] -type PI PI
add mapped point iwb_dat_i[22] iwb_dat_i[22] -type PI PI
add mapped point iwb_dat_i[21] iwb_dat_i[21] -type PI PI
add mapped point iwb_dat_i[20] iwb_dat_i[20] -type PI PI
add mapped point iwb_dat_i[19] iwb_dat_i[19] -type PI PI
add mapped point iwb_dat_i[18] iwb_dat_i[18] -type PI PI
add mapped point iwb_dat_i[17] iwb_dat_i[17] -type PI PI
add mapped point iwb_dat_i[16] iwb_dat_i[16] -type PI PI
add mapped point iwb_dat_i[15] iwb_dat_i[15] -type PI PI
add mapped point iwb_dat_i[14] iwb_dat_i[14] -type PI PI
add mapped point iwb_dat_i[13] iwb_dat_i[13] -type PI PI
add mapped point iwb_dat_i[12] iwb_dat_i[12] -type PI PI
add mapped point iwb_dat_i[11] iwb_dat_i[11] -type PI PI
add mapped point iwb_dat_i[10] iwb_dat_i[10] -type PI PI
add mapped point iwb_dat_i[9] iwb_dat_i[9] -type PI PI
add mapped point iwb_dat_i[8] iwb_dat_i[8] -type PI PI
add mapped point iwb_dat_i[7] iwb_dat_i[7] -type PI PI
add mapped point iwb_dat_i[6] iwb_dat_i[6] -type PI PI
add mapped point iwb_dat_i[5] iwb_dat_i[5] -type PI PI
add mapped point iwb_dat_i[4] iwb_dat_i[4] -type PI PI
add mapped point iwb_dat_i[3] iwb_dat_i[3] -type PI PI
add mapped point iwb_dat_i[2] iwb_dat_i[2] -type PI PI
add mapped point iwb_dat_i[1] iwb_dat_i[1] -type PI PI
add mapped point iwb_dat_i[0] iwb_dat_i[0] -type PI PI
add mapped point iwb_we_i iwb_we_i -type PI PI
add mapped point iwb_sel_i[3] iwb_sel_i[3] -type PI PI
add mapped point iwb_sel_i[2] iwb_sel_i[2] -type PI PI
add mapped point iwb_sel_i[1] iwb_sel_i[1] -type PI PI
add mapped point iwb_sel_i[0] iwb_sel_i[0] -type PI PI
add mapped point iwb_cyc_i iwb_cyc_i -type PI PI
add mapped point iwb_stb_i iwb_stb_i -type PI PI
add mapped point dwb_adr_i[31] dwb_adr_i[31] -type PI PI
add mapped point dwb_adr_i[30] dwb_adr_i[30] -type PI PI
add mapped point dwb_adr_i[29] dwb_adr_i[29] -type PI PI
add mapped point dwb_adr_i[28] dwb_adr_i[28] -type PI PI
add mapped point dwb_adr_i[27] dwb_adr_i[27] -type PI PI
add mapped point dwb_adr_i[26] dwb_adr_i[26] -type PI PI
add mapped point dwb_adr_i[25] dwb_adr_i[25] -type PI PI
add mapped point dwb_adr_i[24] dwb_adr_i[24] -type PI PI
add mapped point dwb_adr_i[23] dwb_adr_i[23] -type PI PI
add mapped point dwb_adr_i[22] dwb_adr_i[22] -type PI PI
add mapped point dwb_adr_i[21] dwb_adr_i[21] -type PI PI
add mapped point dwb_adr_i[20] dwb_adr_i[20] -type PI PI
add mapped point dwb_adr_i[19] dwb_adr_i[19] -type PI PI
add mapped point dwb_adr_i[18] dwb_adr_i[18] -type PI PI
add mapped point dwb_adr_i[17] dwb_adr_i[17] -type PI PI
add mapped point dwb_adr_i[16] dwb_adr_i[16] -type PI PI
add mapped point dwb_adr_i[15] dwb_adr_i[15] -type PI PI
add mapped point dwb_adr_i[14] dwb_adr_i[14] -type PI PI
add mapped point dwb_adr_i[13] dwb_adr_i[13] -type PI PI
add mapped point dwb_adr_i[12] dwb_adr_i[12] -type PI PI
add mapped point dwb_adr_i[11] dwb_adr_i[11] -type PI PI
add mapped point dwb_adr_i[10] dwb_adr_i[10] -type PI PI
add mapped point dwb_adr_i[9] dwb_adr_i[9] -type PI PI
add mapped point dwb_adr_i[8] dwb_adr_i[8] -type PI PI
add mapped point dwb_adr_i[7] dwb_adr_i[7] -type PI PI
add mapped point dwb_adr_i[6] dwb_adr_i[6] -type PI PI
add mapped point dwb_adr_i[5] dwb_adr_i[5] -type PI PI
add mapped point dwb_adr_i[4] dwb_adr_i[4] -type PI PI
add mapped point dwb_adr_i[3] dwb_adr_i[3] -type PI PI
add mapped point dwb_adr_i[2] dwb_adr_i[2] -type PI PI
add mapped point dwb_adr_i[1] dwb_adr_i[1] -type PI PI
add mapped point dwb_adr_i[0] dwb_adr_i[0] -type PI PI
add mapped point dwb_dat_i[31] dwb_dat_i[31] -type PI PI
add mapped point dwb_dat_i[30] dwb_dat_i[30] -type PI PI
add mapped point dwb_dat_i[29] dwb_dat_i[29] -type PI PI
add mapped point dwb_dat_i[28] dwb_dat_i[28] -type PI PI
add mapped point dwb_dat_i[27] dwb_dat_i[27] -type PI PI
add mapped point dwb_dat_i[26] dwb_dat_i[26] -type PI PI
add mapped point dwb_dat_i[25] dwb_dat_i[25] -type PI PI
add mapped point dwb_dat_i[24] dwb_dat_i[24] -type PI PI
add mapped point dwb_dat_i[23] dwb_dat_i[23] -type PI PI
add mapped point dwb_dat_i[22] dwb_dat_i[22] -type PI PI
add mapped point dwb_dat_i[21] dwb_dat_i[21] -type PI PI
add mapped point dwb_dat_i[20] dwb_dat_i[20] -type PI PI
add mapped point dwb_dat_i[19] dwb_dat_i[19] -type PI PI
add mapped point dwb_dat_i[18] dwb_dat_i[18] -type PI PI
add mapped point dwb_dat_i[17] dwb_dat_i[17] -type PI PI
add mapped point dwb_dat_i[16] dwb_dat_i[16] -type PI PI
add mapped point dwb_dat_i[15] dwb_dat_i[15] -type PI PI
add mapped point dwb_dat_i[14] dwb_dat_i[14] -type PI PI
add mapped point dwb_dat_i[13] dwb_dat_i[13] -type PI PI
add mapped point dwb_dat_i[12] dwb_dat_i[12] -type PI PI
add mapped point dwb_dat_i[11] dwb_dat_i[11] -type PI PI
add mapped point dwb_dat_i[10] dwb_dat_i[10] -type PI PI
add mapped point dwb_dat_i[9] dwb_dat_i[9] -type PI PI
add mapped point dwb_dat_i[8] dwb_dat_i[8] -type PI PI
add mapped point dwb_dat_i[7] dwb_dat_i[7] -type PI PI
add mapped point dwb_dat_i[6] dwb_dat_i[6] -type PI PI
add mapped point dwb_dat_i[5] dwb_dat_i[5] -type PI PI
add mapped point dwb_dat_i[4] dwb_dat_i[4] -type PI PI
add mapped point dwb_dat_i[3] dwb_dat_i[3] -type PI PI
add mapped point dwb_dat_i[2] dwb_dat_i[2] -type PI PI
add mapped point dwb_dat_i[1] dwb_dat_i[1] -type PI PI
add mapped point dwb_dat_i[0] dwb_dat_i[0] -type PI PI
add mapped point dwb_we_i dwb_we_i -type PI PI
add mapped point dwb_sel_i[3] dwb_sel_i[3] -type PI PI
add mapped point dwb_sel_i[2] dwb_sel_i[2] -type PI PI
add mapped point dwb_sel_i[1] dwb_sel_i[1] -type PI PI
add mapped point dwb_sel_i[0] dwb_sel_i[0] -type PI PI
add mapped point dwb_cyc_i dwb_cyc_i -type PI PI
add mapped point dwb_stb_i dwb_stb_i -type PI PI
add mapped point ext_mem_dat_i[31] ext_mem_dat_i[31] -type PI PI
add mapped point ext_mem_dat_i[30] ext_mem_dat_i[30] -type PI PI
add mapped point ext_mem_dat_i[29] ext_mem_dat_i[29] -type PI PI
add mapped point ext_mem_dat_i[28] ext_mem_dat_i[28] -type PI PI
add mapped point ext_mem_dat_i[27] ext_mem_dat_i[27] -type PI PI
add mapped point ext_mem_dat_i[26] ext_mem_dat_i[26] -type PI PI
add mapped point ext_mem_dat_i[25] ext_mem_dat_i[25] -type PI PI
add mapped point ext_mem_dat_i[24] ext_mem_dat_i[24] -type PI PI
add mapped point ext_mem_dat_i[23] ext_mem_dat_i[23] -type PI PI
add mapped point ext_mem_dat_i[22] ext_mem_dat_i[22] -type PI PI
add mapped point ext_mem_dat_i[21] ext_mem_dat_i[21] -type PI PI
add mapped point ext_mem_dat_i[20] ext_mem_dat_i[20] -type PI PI
add mapped point ext_mem_dat_i[19] ext_mem_dat_i[19] -type PI PI
add mapped point ext_mem_dat_i[18] ext_mem_dat_i[18] -type PI PI
add mapped point ext_mem_dat_i[17] ext_mem_dat_i[17] -type PI PI
add mapped point ext_mem_dat_i[16] ext_mem_dat_i[16] -type PI PI
add mapped point ext_mem_dat_i[15] ext_mem_dat_i[15] -type PI PI
add mapped point ext_mem_dat_i[14] ext_mem_dat_i[14] -type PI PI
add mapped point ext_mem_dat_i[13] ext_mem_dat_i[13] -type PI PI
add mapped point ext_mem_dat_i[12] ext_mem_dat_i[12] -type PI PI
add mapped point ext_mem_dat_i[11] ext_mem_dat_i[11] -type PI PI
add mapped point ext_mem_dat_i[10] ext_mem_dat_i[10] -type PI PI
add mapped point ext_mem_dat_i[9] ext_mem_dat_i[9] -type PI PI
add mapped point ext_mem_dat_i[8] ext_mem_dat_i[8] -type PI PI
add mapped point ext_mem_dat_i[7] ext_mem_dat_i[7] -type PI PI
add mapped point ext_mem_dat_i[6] ext_mem_dat_i[6] -type PI PI
add mapped point ext_mem_dat_i[5] ext_mem_dat_i[5] -type PI PI
add mapped point ext_mem_dat_i[4] ext_mem_dat_i[4] -type PI PI
add mapped point ext_mem_dat_i[3] ext_mem_dat_i[3] -type PI PI
add mapped point ext_mem_dat_i[2] ext_mem_dat_i[2] -type PI PI
add mapped point ext_mem_dat_i[1] ext_mem_dat_i[1] -type PI PI
add mapped point ext_mem_dat_i[0] ext_mem_dat_i[0] -type PI PI
add mapped point ext_mem_ack_i ext_mem_ack_i -type PI PI
add mapped point ext_mem_err_i ext_mem_err_i -type PI PI

//output ports
add mapped point iwb_dat_o[31] iwb_dat_o[31] -type PO PO
add mapped point iwb_dat_o[30] iwb_dat_o[30] -type PO PO
add mapped point iwb_dat_o[29] iwb_dat_o[29] -type PO PO
add mapped point iwb_dat_o[28] iwb_dat_o[28] -type PO PO
add mapped point iwb_dat_o[27] iwb_dat_o[27] -type PO PO
add mapped point iwb_dat_o[26] iwb_dat_o[26] -type PO PO
add mapped point iwb_dat_o[25] iwb_dat_o[25] -type PO PO
add mapped point iwb_dat_o[24] iwb_dat_o[24] -type PO PO
add mapped point iwb_dat_o[23] iwb_dat_o[23] -type PO PO
add mapped point iwb_dat_o[22] iwb_dat_o[22] -type PO PO
add mapped point iwb_dat_o[21] iwb_dat_o[21] -type PO PO
add mapped point iwb_dat_o[20] iwb_dat_o[20] -type PO PO
add mapped point iwb_dat_o[19] iwb_dat_o[19] -type PO PO
add mapped point iwb_dat_o[18] iwb_dat_o[18] -type PO PO
add mapped point iwb_dat_o[17] iwb_dat_o[17] -type PO PO
add mapped point iwb_dat_o[16] iwb_dat_o[16] -type PO PO
add mapped point iwb_dat_o[15] iwb_dat_o[15] -type PO PO
add mapped point iwb_dat_o[14] iwb_dat_o[14] -type PO PO
add mapped point iwb_dat_o[13] iwb_dat_o[13] -type PO PO
add mapped point iwb_dat_o[12] iwb_dat_o[12] -type PO PO
add mapped point iwb_dat_o[11] iwb_dat_o[11] -type PO PO
add mapped point iwb_dat_o[10] iwb_dat_o[10] -type PO PO
add mapped point iwb_dat_o[9] iwb_dat_o[9] -type PO PO
add mapped point iwb_dat_o[8] iwb_dat_o[8] -type PO PO
add mapped point iwb_dat_o[7] iwb_dat_o[7] -type PO PO
add mapped point iwb_dat_o[6] iwb_dat_o[6] -type PO PO
add mapped point iwb_dat_o[5] iwb_dat_o[5] -type PO PO
add mapped point iwb_dat_o[4] iwb_dat_o[4] -type PO PO
add mapped point iwb_dat_o[3] iwb_dat_o[3] -type PO PO
add mapped point iwb_dat_o[2] iwb_dat_o[2] -type PO PO
add mapped point iwb_dat_o[1] iwb_dat_o[1] -type PO PO
add mapped point iwb_dat_o[0] iwb_dat_o[0] -type PO PO
add mapped point iwb_ack_o iwb_ack_o -type PO PO
add mapped point iwb_err_o iwb_err_o -type PO PO
add mapped point dwb_dat_o[31] dwb_dat_o[31] -type PO PO
add mapped point dwb_dat_o[30] dwb_dat_o[30] -type PO PO
add mapped point dwb_dat_o[29] dwb_dat_o[29] -type PO PO
add mapped point dwb_dat_o[28] dwb_dat_o[28] -type PO PO
add mapped point dwb_dat_o[27] dwb_dat_o[27] -type PO PO
add mapped point dwb_dat_o[26] dwb_dat_o[26] -type PO PO
add mapped point dwb_dat_o[25] dwb_dat_o[25] -type PO PO
add mapped point dwb_dat_o[24] dwb_dat_o[24] -type PO PO
add mapped point dwb_dat_o[23] dwb_dat_o[23] -type PO PO
add mapped point dwb_dat_o[22] dwb_dat_o[22] -type PO PO
add mapped point dwb_dat_o[21] dwb_dat_o[21] -type PO PO
add mapped point dwb_dat_o[20] dwb_dat_o[20] -type PO PO
add mapped point dwb_dat_o[19] dwb_dat_o[19] -type PO PO
add mapped point dwb_dat_o[18] dwb_dat_o[18] -type PO PO
add mapped point dwb_dat_o[17] dwb_dat_o[17] -type PO PO
add mapped point dwb_dat_o[16] dwb_dat_o[16] -type PO PO
add mapped point dwb_dat_o[15] dwb_dat_o[15] -type PO PO
add mapped point dwb_dat_o[14] dwb_dat_o[14] -type PO PO
add mapped point dwb_dat_o[13] dwb_dat_o[13] -type PO PO
add mapped point dwb_dat_o[12] dwb_dat_o[12] -type PO PO
add mapped point dwb_dat_o[11] dwb_dat_o[11] -type PO PO
add mapped point dwb_dat_o[10] dwb_dat_o[10] -type PO PO
add mapped point dwb_dat_o[9] dwb_dat_o[9] -type PO PO
add mapped point dwb_dat_o[8] dwb_dat_o[8] -type PO PO
add mapped point dwb_dat_o[7] dwb_dat_o[7] -type PO PO
add mapped point dwb_dat_o[6] dwb_dat_o[6] -type PO PO
add mapped point dwb_dat_o[5] dwb_dat_o[5] -type PO PO
add mapped point dwb_dat_o[4] dwb_dat_o[4] -type PO PO
add mapped point dwb_dat_o[3] dwb_dat_o[3] -type PO PO
add mapped point dwb_dat_o[2] dwb_dat_o[2] -type PO PO
add mapped point dwb_dat_o[1] dwb_dat_o[1] -type PO PO
add mapped point dwb_dat_o[0] dwb_dat_o[0] -type PO PO
add mapped point dwb_ack_o dwb_ack_o -type PO PO
add mapped point dwb_err_o dwb_err_o -type PO PO
add mapped point ext_mem_adr_o[31] ext_mem_adr_o[31] -type PO PO
add mapped point ext_mem_adr_o[30] ext_mem_adr_o[30] -type PO PO
add mapped point ext_mem_adr_o[29] ext_mem_adr_o[29] -type PO PO
add mapped point ext_mem_adr_o[28] ext_mem_adr_o[28] -type PO PO
add mapped point ext_mem_adr_o[27] ext_mem_adr_o[27] -type PO PO
add mapped point ext_mem_adr_o[26] ext_mem_adr_o[26] -type PO PO
add mapped point ext_mem_adr_o[25] ext_mem_adr_o[25] -type PO PO
add mapped point ext_mem_adr_o[24] ext_mem_adr_o[24] -type PO PO
add mapped point ext_mem_adr_o[23] ext_mem_adr_o[23] -type PO PO
add mapped point ext_mem_adr_o[22] ext_mem_adr_o[22] -type PO PO
add mapped point ext_mem_adr_o[21] ext_mem_adr_o[21] -type PO PO
add mapped point ext_mem_adr_o[20] ext_mem_adr_o[20] -type PO PO
add mapped point ext_mem_adr_o[19] ext_mem_adr_o[19] -type PO PO
add mapped point ext_mem_adr_o[18] ext_mem_adr_o[18] -type PO PO
add mapped point ext_mem_adr_o[17] ext_mem_adr_o[17] -type PO PO
add mapped point ext_mem_adr_o[16] ext_mem_adr_o[16] -type PO PO
add mapped point ext_mem_adr_o[15] ext_mem_adr_o[15] -type PO PO
add mapped point ext_mem_adr_o[14] ext_mem_adr_o[14] -type PO PO
add mapped point ext_mem_adr_o[13] ext_mem_adr_o[13] -type PO PO
add mapped point ext_mem_adr_o[12] ext_mem_adr_o[12] -type PO PO
add mapped point ext_mem_adr_o[11] ext_mem_adr_o[11] -type PO PO
add mapped point ext_mem_adr_o[10] ext_mem_adr_o[10] -type PO PO
add mapped point ext_mem_adr_o[9] ext_mem_adr_o[9] -type PO PO
add mapped point ext_mem_adr_o[8] ext_mem_adr_o[8] -type PO PO
add mapped point ext_mem_adr_o[7] ext_mem_adr_o[7] -type PO PO
add mapped point ext_mem_adr_o[6] ext_mem_adr_o[6] -type PO PO
add mapped point ext_mem_adr_o[5] ext_mem_adr_o[5] -type PO PO
add mapped point ext_mem_adr_o[4] ext_mem_adr_o[4] -type PO PO
add mapped point ext_mem_adr_o[3] ext_mem_adr_o[3] -type PO PO
add mapped point ext_mem_adr_o[2] ext_mem_adr_o[2] -type PO PO
add mapped point ext_mem_adr_o[1] ext_mem_adr_o[1] -type PO PO
add mapped point ext_mem_adr_o[0] ext_mem_adr_o[0] -type PO PO
add mapped point ext_mem_dat_o[31] ext_mem_dat_o[31] -type PO PO
add mapped point ext_mem_dat_o[30] ext_mem_dat_o[30] -type PO PO
add mapped point ext_mem_dat_o[29] ext_mem_dat_o[29] -type PO PO
add mapped point ext_mem_dat_o[28] ext_mem_dat_o[28] -type PO PO
add mapped point ext_mem_dat_o[27] ext_mem_dat_o[27] -type PO PO
add mapped point ext_mem_dat_o[26] ext_mem_dat_o[26] -type PO PO
add mapped point ext_mem_dat_o[25] ext_mem_dat_o[25] -type PO PO
add mapped point ext_mem_dat_o[24] ext_mem_dat_o[24] -type PO PO
add mapped point ext_mem_dat_o[23] ext_mem_dat_o[23] -type PO PO
add mapped point ext_mem_dat_o[22] ext_mem_dat_o[22] -type PO PO
add mapped point ext_mem_dat_o[21] ext_mem_dat_o[21] -type PO PO
add mapped point ext_mem_dat_o[20] ext_mem_dat_o[20] -type PO PO
add mapped point ext_mem_dat_o[19] ext_mem_dat_o[19] -type PO PO
add mapped point ext_mem_dat_o[18] ext_mem_dat_o[18] -type PO PO
add mapped point ext_mem_dat_o[17] ext_mem_dat_o[17] -type PO PO
add mapped point ext_mem_dat_o[16] ext_mem_dat_o[16] -type PO PO
add mapped point ext_mem_dat_o[15] ext_mem_dat_o[15] -type PO PO
add mapped point ext_mem_dat_o[14] ext_mem_dat_o[14] -type PO PO
add mapped point ext_mem_dat_o[13] ext_mem_dat_o[13] -type PO PO
add mapped point ext_mem_dat_o[12] ext_mem_dat_o[12] -type PO PO
add mapped point ext_mem_dat_o[11] ext_mem_dat_o[11] -type PO PO
add mapped point ext_mem_dat_o[10] ext_mem_dat_o[10] -type PO PO
add mapped point ext_mem_dat_o[9] ext_mem_dat_o[9] -type PO PO
add mapped point ext_mem_dat_o[8] ext_mem_dat_o[8] -type PO PO
add mapped point ext_mem_dat_o[7] ext_mem_dat_o[7] -type PO PO
add mapped point ext_mem_dat_o[6] ext_mem_dat_o[6] -type PO PO
add mapped point ext_mem_dat_o[5] ext_mem_dat_o[5] -type PO PO
add mapped point ext_mem_dat_o[4] ext_mem_dat_o[4] -type PO PO
add mapped point ext_mem_dat_o[3] ext_mem_dat_o[3] -type PO PO
add mapped point ext_mem_dat_o[2] ext_mem_dat_o[2] -type PO PO
add mapped point ext_mem_dat_o[1] ext_mem_dat_o[1] -type PO PO
add mapped point ext_mem_dat_o[0] ext_mem_dat_o[0] -type PO PO
add mapped point ext_mem_we_o ext_mem_we_o -type PO PO
add mapped point ext_mem_sel_o[3] ext_mem_sel_o[3] -type PO PO
add mapped point ext_mem_sel_o[2] ext_mem_sel_o[2] -type PO PO
add mapped point ext_mem_sel_o[1] ext_mem_sel_o[1] -type PO PO
add mapped point ext_mem_sel_o[0] ext_mem_sel_o[0] -type PO PO
add mapped point ext_mem_cyc_o ext_mem_cyc_o -type PO PO
add mapped point ext_mem_stb_o ext_mem_stb_o -type PO PO
add mapped point rom_ready rom_ready -type PO PO
add mapped point ram_ready ram_ready -type PO PO
add mapped point memory_status[31] memory_status[31] -type PO PO
add mapped point memory_status[30] memory_status[30] -type PO PO
add mapped point memory_status[29] memory_status[29] -type PO PO
add mapped point memory_status[28] memory_status[28] -type PO PO
add mapped point memory_status[27] memory_status[27] -type PO PO
add mapped point memory_status[26] memory_status[26] -type PO PO
add mapped point memory_status[25] memory_status[25] -type PO PO
add mapped point memory_status[24] memory_status[24] -type PO PO
add mapped point memory_status[23] memory_status[23] -type PO PO
add mapped point memory_status[22] memory_status[22] -type PO PO
add mapped point memory_status[21] memory_status[21] -type PO PO
add mapped point memory_status[20] memory_status[20] -type PO PO
add mapped point memory_status[19] memory_status[19] -type PO PO
add mapped point memory_status[18] memory_status[18] -type PO PO
add mapped point memory_status[17] memory_status[17] -type PO PO
add mapped point memory_status[16] memory_status[16] -type PO PO
add mapped point memory_status[15] memory_status[15] -type PO PO
add mapped point memory_status[14] memory_status[14] -type PO PO
add mapped point memory_status[13] memory_status[13] -type PO PO
add mapped point memory_status[12] memory_status[12] -type PO PO
add mapped point memory_status[11] memory_status[11] -type PO PO
add mapped point memory_status[10] memory_status[10] -type PO PO
add mapped point memory_status[9] memory_status[9] -type PO PO
add mapped point memory_status[8] memory_status[8] -type PO PO
add mapped point memory_status[7] memory_status[7] -type PO PO
add mapped point memory_status[6] memory_status[6] -type PO PO
add mapped point memory_status[5] memory_status[5] -type PO PO
add mapped point memory_status[4] memory_status[4] -type PO PO
add mapped point memory_status[3] memory_status[3] -type PO PO
add mapped point memory_status[2] memory_status[2] -type PO PO
add mapped point memory_status[1] memory_status[1] -type PO PO
add mapped point memory_status[0] memory_status[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point rom_ack/q rom_ack_reg/Q -type DFF DFF
add mapped point ram_ack/q ram_ack_reg/Q -type DFF DFF
add mapped point ext_ack/q ext_ack_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
