
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Dec 24 2025 18:51:28 +03 (Dec 24 2025 15:51:28 UTC)

// Verification Directory fv/rv32im_integrated_macro 

module core_macro(clk, rst_n, iwb_adr_o, iwb_dat_i, iwb_cyc_o,
     iwb_stb_o, iwb_ack_i, dwb_adr_o, dwb_dat_o, dwb_dat_i, dwb_we_o,
     dwb_sel_o, dwb_cyc_o, dwb_stb_o, dwb_ack_i, dwb_err_i, mdu_start,
     mdu_ack, mdu_funct3, mdu_operand_a, mdu_operand_b, mdu_busy,
     mdu_done, mdu_product, mdu_quotient, mdu_remainder, interrupts);
  input clk, rst_n, iwb_ack_i, dwb_ack_i, dwb_err_i, mdu_busy, mdu_done;
  input [31:0] iwb_dat_i, dwb_dat_i, mdu_quotient, mdu_remainder,
       interrupts;
  input [63:0] mdu_product;
  output [31:0] iwb_adr_o, dwb_adr_o, dwb_dat_o, mdu_operand_a,
       mdu_operand_b;
  output iwb_cyc_o, iwb_stb_o, dwb_we_o, dwb_cyc_o, dwb_stb_o,
       mdu_start, mdu_ack;
  output [3:0] dwb_sel_o;
  output [2:0] mdu_funct3;
  wire clk, rst_n, iwb_ack_i, dwb_ack_i, dwb_err_i, mdu_busy, mdu_done;
  wire [31:0] iwb_dat_i, dwb_dat_i, mdu_quotient, mdu_remainder,
       interrupts;
  wire [63:0] mdu_product;
  wire [31:0] iwb_adr_o, dwb_adr_o, dwb_dat_o, mdu_operand_a,
       mdu_operand_b;
  wire iwb_cyc_o, iwb_stb_o, dwb_we_o, dwb_cyc_o, dwb_stb_o, mdu_start,
       mdu_ack;
  wire [3:0] dwb_sel_o;
  wire [2:0] mdu_funct3;
endmodule

module rv32im_integrated_macro(clk, rst_n, iwb_adr_o, iwb_dat_i,
     iwb_cyc_o, iwb_stb_o, iwb_ack_i, dwb_adr_o, dwb_dat_o, dwb_dat_i,
     dwb_we_o, dwb_sel_o, dwb_cyc_o, dwb_stb_o, dwb_ack_i, dwb_err_i,
     interrupts);
  input clk, rst_n, iwb_ack_i, dwb_ack_i, dwb_err_i;
  input [31:0] iwb_dat_i, dwb_dat_i, interrupts;
  output [31:0] iwb_adr_o, dwb_adr_o, dwb_dat_o;
  output iwb_cyc_o, iwb_stb_o, dwb_we_o, dwb_cyc_o, dwb_stb_o;
  output [3:0] dwb_sel_o;
  wire clk, rst_n, iwb_ack_i, dwb_ack_i, dwb_err_i;
  wire [31:0] iwb_dat_i, dwb_dat_i, interrupts;
  wire [31:0] iwb_adr_o, dwb_adr_o, dwb_dat_o;
  wire iwb_cyc_o, iwb_stb_o, dwb_we_o, dwb_cyc_o, dwb_stb_o;
  wire [3:0] dwb_sel_o;
  wire [63:0] mdu_product;
  wire [31:0] mdu_quotient;
  wire [31:0] mdu_remainder;
  wire [2:0] mdu_funct3;
  wire [31:0] mdu_operand_a;
  wire [31:0] mdu_operand_b;
  wire mdu_ack, mdu_busy, mdu_done, mdu_start;
  core_macro u_core_macro(.clk (clk), .rst_n (rst_n), .iwb_adr_o
       (iwb_adr_o), .iwb_dat_i (iwb_dat_i), .iwb_cyc_o (iwb_cyc_o),
       .iwb_stb_o (iwb_stb_o), .iwb_ack_i (iwb_ack_i), .dwb_adr_o
       (dwb_adr_o), .dwb_dat_o (dwb_dat_o), .dwb_dat_i (dwb_dat_i),
       .dwb_we_o (dwb_we_o), .dwb_sel_o (dwb_sel_o), .dwb_cyc_o
       (dwb_cyc_o), .dwb_stb_o (dwb_stb_o), .dwb_ack_i (dwb_ack_i),
       .dwb_err_i (dwb_err_i), .mdu_start (mdu_start), .mdu_ack
       (mdu_ack), .mdu_funct3 (mdu_funct3), .mdu_operand_a
       (mdu_operand_a), .mdu_operand_b (mdu_operand_b), .mdu_busy
       (mdu_busy), .mdu_done (mdu_done), .mdu_product (mdu_product),
       .mdu_quotient (mdu_quotient), .mdu_remainder (mdu_remainder),
       .interrupts (interrupts));
  mdu_macro u_mdu_macro(.clk (clk), .rst_n (rst_n), .start (mdu_start),
       .ack (mdu_ack), .funct3 (mdu_funct3), .operand_a
       (mdu_operand_a), .operand_b (mdu_operand_b), .busy (mdu_busy),
       .done (mdu_done), .product (mdu_product), .quotient
       (mdu_quotient), .remainder (mdu_remainder));
endmodule

