
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point wb_adr_i[31] wb_adr_i[31] -type PI PI
add mapped point wb_adr_i[30] wb_adr_i[30] -type PI PI
add mapped point wb_adr_i[29] wb_adr_i[29] -type PI PI
add mapped point wb_adr_i[28] wb_adr_i[28] -type PI PI
add mapped point wb_adr_i[27] wb_adr_i[27] -type PI PI
add mapped point wb_adr_i[26] wb_adr_i[26] -type PI PI
add mapped point wb_adr_i[25] wb_adr_i[25] -type PI PI
add mapped point wb_adr_i[24] wb_adr_i[24] -type PI PI
add mapped point wb_adr_i[23] wb_adr_i[23] -type PI PI
add mapped point wb_adr_i[22] wb_adr_i[22] -type PI PI
add mapped point wb_adr_i[21] wb_adr_i[21] -type PI PI
add mapped point wb_adr_i[20] wb_adr_i[20] -type PI PI
add mapped point wb_adr_i[19] wb_adr_i[19] -type PI PI
add mapped point wb_adr_i[18] wb_adr_i[18] -type PI PI
add mapped point wb_adr_i[17] wb_adr_i[17] -type PI PI
add mapped point wb_adr_i[16] wb_adr_i[16] -type PI PI
add mapped point wb_adr_i[15] wb_adr_i[15] -type PI PI
add mapped point wb_adr_i[14] wb_adr_i[14] -type PI PI
add mapped point wb_adr_i[13] wb_adr_i[13] -type PI PI
add mapped point wb_adr_i[12] wb_adr_i[12] -type PI PI
add mapped point wb_adr_i[11] wb_adr_i[11] -type PI PI
add mapped point wb_adr_i[10] wb_adr_i[10] -type PI PI
add mapped point wb_adr_i[9] wb_adr_i[9] -type PI PI
add mapped point wb_adr_i[8] wb_adr_i[8] -type PI PI
add mapped point wb_adr_i[7] wb_adr_i[7] -type PI PI
add mapped point wb_adr_i[6] wb_adr_i[6] -type PI PI
add mapped point wb_adr_i[5] wb_adr_i[5] -type PI PI
add mapped point wb_adr_i[4] wb_adr_i[4] -type PI PI
add mapped point wb_adr_i[3] wb_adr_i[3] -type PI PI
add mapped point wb_adr_i[2] wb_adr_i[2] -type PI PI
add mapped point wb_adr_i[1] wb_adr_i[1] -type PI PI
add mapped point wb_adr_i[0] wb_adr_i[0] -type PI PI
add mapped point wb_dat_i[31] wb_dat_i[31] -type PI PI
add mapped point wb_dat_i[30] wb_dat_i[30] -type PI PI
add mapped point wb_dat_i[29] wb_dat_i[29] -type PI PI
add mapped point wb_dat_i[28] wb_dat_i[28] -type PI PI
add mapped point wb_dat_i[27] wb_dat_i[27] -type PI PI
add mapped point wb_dat_i[26] wb_dat_i[26] -type PI PI
add mapped point wb_dat_i[25] wb_dat_i[25] -type PI PI
add mapped point wb_dat_i[24] wb_dat_i[24] -type PI PI
add mapped point wb_dat_i[23] wb_dat_i[23] -type PI PI
add mapped point wb_dat_i[22] wb_dat_i[22] -type PI PI
add mapped point wb_dat_i[21] wb_dat_i[21] -type PI PI
add mapped point wb_dat_i[20] wb_dat_i[20] -type PI PI
add mapped point wb_dat_i[19] wb_dat_i[19] -type PI PI
add mapped point wb_dat_i[18] wb_dat_i[18] -type PI PI
add mapped point wb_dat_i[17] wb_dat_i[17] -type PI PI
add mapped point wb_dat_i[16] wb_dat_i[16] -type PI PI
add mapped point wb_dat_i[15] wb_dat_i[15] -type PI PI
add mapped point wb_dat_i[14] wb_dat_i[14] -type PI PI
add mapped point wb_dat_i[13] wb_dat_i[13] -type PI PI
add mapped point wb_dat_i[12] wb_dat_i[12] -type PI PI
add mapped point wb_dat_i[11] wb_dat_i[11] -type PI PI
add mapped point wb_dat_i[10] wb_dat_i[10] -type PI PI
add mapped point wb_dat_i[9] wb_dat_i[9] -type PI PI
add mapped point wb_dat_i[8] wb_dat_i[8] -type PI PI
add mapped point wb_dat_i[7] wb_dat_i[7] -type PI PI
add mapped point wb_dat_i[6] wb_dat_i[6] -type PI PI
add mapped point wb_dat_i[5] wb_dat_i[5] -type PI PI
add mapped point wb_dat_i[4] wb_dat_i[4] -type PI PI
add mapped point wb_dat_i[3] wb_dat_i[3] -type PI PI
add mapped point wb_dat_i[2] wb_dat_i[2] -type PI PI
add mapped point wb_dat_i[1] wb_dat_i[1] -type PI PI
add mapped point wb_dat_i[0] wb_dat_i[0] -type PI PI
add mapped point wb_we_i wb_we_i -type PI PI
add mapped point wb_sel_i[3] wb_sel_i[3] -type PI PI
add mapped point wb_sel_i[2] wb_sel_i[2] -type PI PI
add mapped point wb_sel_i[1] wb_sel_i[1] -type PI PI
add mapped point wb_sel_i[0] wb_sel_i[0] -type PI PI
add mapped point wb_cyc_i wb_cyc_i -type PI PI
add mapped point wb_stb_i wb_stb_i -type PI PI
add mapped point current_sense[3] current_sense[3] -type PI PI
add mapped point current_sense[2] current_sense[2] -type PI PI
add mapped point current_sense[1] current_sense[1] -type PI PI
add mapped point current_sense[0] current_sense[0] -type PI PI
add mapped point voltage_sense[3] voltage_sense[3] -type PI PI
add mapped point voltage_sense[2] voltage_sense[2] -type PI PI
add mapped point voltage_sense[1] voltage_sense[1] -type PI PI
add mapped point voltage_sense[0] voltage_sense[0] -type PI PI
add mapped point thermal_alert thermal_alert -type PI PI
add mapped point watchdog_kick watchdog_kick -type PI PI

//output ports
add mapped point wb_dat_o[31] wb_dat_o[31] -type PO PO
add mapped point wb_dat_o[30] wb_dat_o[30] -type PO PO
add mapped point wb_dat_o[29] wb_dat_o[29] -type PO PO
add mapped point wb_dat_o[28] wb_dat_o[28] -type PO PO
add mapped point wb_dat_o[27] wb_dat_o[27] -type PO PO
add mapped point wb_dat_o[26] wb_dat_o[26] -type PO PO
add mapped point wb_dat_o[25] wb_dat_o[25] -type PO PO
add mapped point wb_dat_o[24] wb_dat_o[24] -type PO PO
add mapped point wb_dat_o[23] wb_dat_o[23] -type PO PO
add mapped point wb_dat_o[22] wb_dat_o[22] -type PO PO
add mapped point wb_dat_o[21] wb_dat_o[21] -type PO PO
add mapped point wb_dat_o[20] wb_dat_o[20] -type PO PO
add mapped point wb_dat_o[19] wb_dat_o[19] -type PO PO
add mapped point wb_dat_o[18] wb_dat_o[18] -type PO PO
add mapped point wb_dat_o[17] wb_dat_o[17] -type PO PO
add mapped point wb_dat_o[16] wb_dat_o[16] -type PO PO
add mapped point wb_dat_o[15] wb_dat_o[15] -type PO PO
add mapped point wb_dat_o[14] wb_dat_o[14] -type PO PO
add mapped point wb_dat_o[13] wb_dat_o[13] -type PO PO
add mapped point wb_dat_o[12] wb_dat_o[12] -type PO PO
add mapped point wb_dat_o[11] wb_dat_o[11] -type PO PO
add mapped point wb_dat_o[10] wb_dat_o[10] -type PO PO
add mapped point wb_dat_o[9] wb_dat_o[9] -type PO PO
add mapped point wb_dat_o[8] wb_dat_o[8] -type PO PO
add mapped point wb_dat_o[7] wb_dat_o[7] -type PO PO
add mapped point wb_dat_o[6] wb_dat_o[6] -type PO PO
add mapped point wb_dat_o[5] wb_dat_o[5] -type PO PO
add mapped point wb_dat_o[4] wb_dat_o[4] -type PO PO
add mapped point wb_dat_o[3] wb_dat_o[3] -type PO PO
add mapped point wb_dat_o[2] wb_dat_o[2] -type PO PO
add mapped point wb_dat_o[1] wb_dat_o[1] -type PO PO
add mapped point wb_dat_o[0] wb_dat_o[0] -type PO PO
add mapped point wb_ack_o wb_ack_o -type PO PO
add mapped point wb_err_o wb_err_o -type PO PO
add mapped point emergency_stop emergency_stop -type PO PO
add mapped point channel_disable[3] channel_disable[3] -type PO PO
add mapped point channel_disable[2] channel_disable[2] -type PO PO
add mapped point channel_disable[1] channel_disable[1] -type PO PO
add mapped point channel_disable[0] channel_disable[0] -type PO PO
add mapped point system_reset system_reset -type PO PO
add mapped point watchdog_timeout watchdog_timeout -type PO PO
add mapped point irq irq -type PO PO
add mapped point protection_status[31] protection_status[31] -type PO PO
add mapped point protection_status[30] protection_status[30] -type PO PO
add mapped point protection_status[29] protection_status[29] -type PO PO
add mapped point protection_status[28] protection_status[28] -type PO PO
add mapped point protection_status[27] protection_status[27] -type PO PO
add mapped point protection_status[26] protection_status[26] -type PO PO
add mapped point protection_status[25] protection_status[25] -type PO PO
add mapped point protection_status[24] protection_status[24] -type PO PO
add mapped point protection_status[23] protection_status[23] -type PO PO
add mapped point protection_status[22] protection_status[22] -type PO PO
add mapped point protection_status[21] protection_status[21] -type PO PO
add mapped point protection_status[20] protection_status[20] -type PO PO
add mapped point protection_status[19] protection_status[19] -type PO PO
add mapped point protection_status[18] protection_status[18] -type PO PO
add mapped point protection_status[17] protection_status[17] -type PO PO
add mapped point protection_status[16] protection_status[16] -type PO PO
add mapped point protection_status[15] protection_status[15] -type PO PO
add mapped point protection_status[14] protection_status[14] -type PO PO
add mapped point protection_status[13] protection_status[13] -type PO PO
add mapped point protection_status[12] protection_status[12] -type PO PO
add mapped point protection_status[11] protection_status[11] -type PO PO
add mapped point protection_status[10] protection_status[10] -type PO PO
add mapped point protection_status[9] protection_status[9] -type PO PO
add mapped point protection_status[8] protection_status[8] -type PO PO
add mapped point protection_status[7] protection_status[7] -type PO PO
add mapped point protection_status[6] protection_status[6] -type PO PO
add mapped point protection_status[5] protection_status[5] -type PO PO
add mapped point protection_status[4] protection_status[4] -type PO PO
add mapped point protection_status[3] protection_status[3] -type PO PO
add mapped point protection_status[2] protection_status[2] -type PO PO
add mapped point protection_status[1] protection_status[1] -type PO PO
add mapped point protection_status[0] protection_status[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point kick_sync[2]/q kick_sync_reg[2]/Q -type DFF DFF
add mapped point wb_ack_reg/q wb_ack_reg_reg/Q -type DFF DFF
add mapped point kick_sync[1]/q kick_sync_reg[1]/Q -type DFF DFF
add mapped point current_protection[0].current_digital[3]/q current_protection[0].current_digital_reg[3]/Q -type DFF DFF
add mapped point voltage_protection[3].voltage_digital[3]/q voltage_protection[3].voltage_digital_reg[3]/Q -type DFF DFF
add mapped point voltage_protection[2].voltage_digital[3]/q voltage_protection[2].voltage_digital_reg[3]/Q -type DFF DFF
add mapped point voltage_protection[1].voltage_digital[3]/q voltage_protection[1].voltage_digital_reg[3]/Q -type DFF DFF
add mapped point voltage_protection[0].voltage_digital[3]/q voltage_protection[0].voltage_digital_reg[3]/Q -type DFF DFF
add mapped point current_protection[3].current_digital[3]/q current_protection[3].current_digital_reg[3]/Q -type DFF DFF
add mapped point current_protection[2].current_digital[3]/q current_protection[2].current_digital_reg[3]/Q -type DFF DFF
add mapped point current_protection[1].current_digital[3]/q current_protection[1].current_digital_reg[3]/Q -type DFF DFF
add mapped point kick_sync[0]/q kick_sync_reg[0]/Q -type DFF DFF
add mapped point control_reg[0]/q control_reg_reg[0]/Q -type DFF DFF
add mapped point control_reg[1]/q control_reg_reg[1]/Q -type DFF DFF
add mapped point control_reg[2]/q control_reg_reg[2]/Q -type DFF DFF
add mapped point control_reg[3]/q control_reg_reg[3]/Q -type DFF DFF
add mapped point control_reg[4]/q control_reg_reg[4]/Q -type DFF DFF
add mapped point control_reg[5]/q control_reg_reg[5]/Q -type DFF DFF
add mapped point control_reg[6]/q control_reg_reg[6]/Q -type DFF DFF
add mapped point control_reg[7]/q control_reg_reg[7]/Q -type DFF DFF
add mapped point control_reg[8]/q control_reg_reg[8]/Q -type DFF DFF
add mapped point control_reg[9]/q control_reg_reg[9]/Q -type DFF DFF
add mapped point control_reg[10]/q control_reg_reg[10]/Q -type DFF DFF
add mapped point control_reg[11]/q control_reg_reg[11]/Q -type DFF DFF
add mapped point control_reg[12]/q control_reg_reg[12]/Q -type DFF DFF
add mapped point control_reg[13]/q control_reg_reg[13]/Q -type DFF DFF
add mapped point control_reg[14]/q control_reg_reg[14]/Q -type DFF DFF
add mapped point control_reg[15]/q control_reg_reg[15]/Q -type DFF DFF
add mapped point control_reg[16]/q control_reg_reg[16]/Q -type DFF DFF
add mapped point control_reg[17]/q control_reg_reg[17]/Q -type DFF DFF
add mapped point control_reg[18]/q control_reg_reg[18]/Q -type DFF DFF
add mapped point control_reg[19]/q control_reg_reg[19]/Q -type DFF DFF
add mapped point control_reg[20]/q control_reg_reg[20]/Q -type DFF DFF
add mapped point control_reg[21]/q control_reg_reg[21]/Q -type DFF DFF
add mapped point control_reg[22]/q control_reg_reg[22]/Q -type DFF DFF
add mapped point control_reg[23]/q control_reg_reg[23]/Q -type DFF DFF
add mapped point control_reg[24]/q control_reg_reg[24]/Q -type DFF DFF
add mapped point control_reg[25]/q control_reg_reg[25]/Q -type DFF DFF
add mapped point control_reg[26]/q control_reg_reg[26]/Q -type DFF DFF
add mapped point control_reg[27]/q control_reg_reg[27]/Q -type DFF DFF
add mapped point control_reg[28]/q control_reg_reg[28]/Q -type DFF DFF
add mapped point control_reg[29]/q control_reg_reg[29]/Q -type DFF DFF
add mapped point control_reg[30]/q control_reg_reg[30]/Q -type DFF DFF
add mapped point control_reg[31]/q control_reg_reg[31]/Q -type DFF DFF
add mapped point current_fault[0]/q current_fault_reg[0]/Q -type DFF DFF
add mapped point current_fault[1]/q current_fault_reg[1]/Q -type DFF DFF
add mapped point current_fault[2]/q current_fault_reg[2]/Q -type DFF DFF
add mapped point current_fault[3]/q current_fault_reg[3]/Q -type DFF DFF
add mapped point current_threshold[0]/q current_threshold_reg[0]/Q -type DFF DFF
add mapped point current_threshold[1]/q current_threshold_reg[1]/Q -type DFF DFF
add mapped point current_threshold[2]/q current_threshold_reg[2]/Q -type DFF DFF
add mapped point current_threshold[3]/q current_threshold_reg[3]/Q -type DFF DFF
add mapped point current_threshold[4]/q current_threshold_reg[4]/Q -type DFF DFF
add mapped point current_threshold[5]/q current_threshold_reg[5]/Q -type DFF DFF
add mapped point current_threshold[6]/q current_threshold_reg[6]/Q -type DFF DFF
add mapped point current_threshold[7]/q current_threshold_reg[7]/Q -type DFF DFF
add mapped point current_threshold[8]/q current_threshold_reg[8]/Q -type DFF DFF
add mapped point current_threshold[9]/q current_threshold_reg[9]/Q -type DFF DFF
add mapped point current_threshold[10]/q current_threshold_reg[10]/Q -type DFF DFF
add mapped point current_threshold[11]/q current_threshold_reg[11]/Q -type DFF DFF
add mapped point current_threshold[12]/q current_threshold_reg[12]/Q -type DFF DFF
add mapped point current_threshold[13]/q current_threshold_reg[13]/Q -type DFF DFF
add mapped point current_threshold[14]/q current_threshold_reg[14]/Q -type DFF DFF
add mapped point current_threshold[15]/q current_threshold_reg[15]/Q -type DFF DFF
add mapped point current_threshold[16]/q current_threshold_reg[16]/Q -type DFF DFF
add mapped point current_threshold[17]/q current_threshold_reg[17]/Q -type DFF DFF
add mapped point current_threshold[18]/q current_threshold_reg[18]/Q -type DFF DFF
add mapped point current_threshold[19]/q current_threshold_reg[19]/Q -type DFF DFF
add mapped point current_threshold[20]/q current_threshold_reg[20]/Q -type DFF DFF
add mapped point current_threshold[21]/q current_threshold_reg[21]/Q -type DFF DFF
add mapped point current_threshold[22]/q current_threshold_reg[22]/Q -type DFF DFF
add mapped point current_threshold[23]/q current_threshold_reg[23]/Q -type DFF DFF
add mapped point current_threshold[24]/q current_threshold_reg[24]/Q -type DFF DFF
add mapped point current_threshold[25]/q current_threshold_reg[25]/Q -type DFF DFF
add mapped point current_threshold[26]/q current_threshold_reg[26]/Q -type DFF DFF
add mapped point current_threshold[27]/q current_threshold_reg[27]/Q -type DFF DFF
add mapped point current_threshold[28]/q current_threshold_reg[28]/Q -type DFF DFF
add mapped point current_threshold[29]/q current_threshold_reg[29]/Q -type DFF DFF
add mapped point current_threshold[30]/q current_threshold_reg[30]/Q -type DFF DFF
add mapped point current_threshold[31]/q current_threshold_reg[31]/Q -type DFF DFF
add mapped point int_enable[0]/q int_enable_reg[0]/Q -type DFF DFF
add mapped point int_enable[1]/q int_enable_reg[1]/Q -type DFF DFF
add mapped point int_enable[2]/q int_enable_reg[2]/Q -type DFF DFF
add mapped point int_enable[3]/q int_enable_reg[3]/Q -type DFF DFF
add mapped point int_enable[4]/q int_enable_reg[4]/Q -type DFF DFF
add mapped point int_enable[5]/q int_enable_reg[5]/Q -type DFF DFF
add mapped point int_enable[6]/q int_enable_reg[6]/Q -type DFF DFF
add mapped point int_enable[7]/q int_enable_reg[7]/Q -type DFF DFF
add mapped point int_enable[8]/q int_enable_reg[8]/Q -type DFF DFF
add mapped point int_enable[9]/q int_enable_reg[9]/Q -type DFF DFF
add mapped point int_enable[10]/q int_enable_reg[10]/Q -type DFF DFF
add mapped point int_enable[11]/q int_enable_reg[11]/Q -type DFF DFF
add mapped point int_enable[12]/q int_enable_reg[12]/Q -type DFF DFF
add mapped point int_enable[13]/q int_enable_reg[13]/Q -type DFF DFF
add mapped point int_enable[14]/q int_enable_reg[14]/Q -type DFF DFF
add mapped point int_enable[15]/q int_enable_reg[15]/Q -type DFF DFF
add mapped point int_enable[16]/q int_enable_reg[16]/Q -type DFF DFF
add mapped point int_enable[17]/q int_enable_reg[17]/Q -type DFF DFF
add mapped point int_enable[18]/q int_enable_reg[18]/Q -type DFF DFF
add mapped point int_enable[19]/q int_enable_reg[19]/Q -type DFF DFF
add mapped point int_enable[20]/q int_enable_reg[20]/Q -type DFF DFF
add mapped point int_enable[21]/q int_enable_reg[21]/Q -type DFF DFF
add mapped point int_enable[22]/q int_enable_reg[22]/Q -type DFF DFF
add mapped point int_enable[23]/q int_enable_reg[23]/Q -type DFF DFF
add mapped point int_enable[24]/q int_enable_reg[24]/Q -type DFF DFF
add mapped point int_enable[25]/q int_enable_reg[25]/Q -type DFF DFF
add mapped point int_enable[26]/q int_enable_reg[26]/Q -type DFF DFF
add mapped point int_enable[27]/q int_enable_reg[27]/Q -type DFF DFF
add mapped point int_enable[28]/q int_enable_reg[28]/Q -type DFF DFF
add mapped point int_enable[29]/q int_enable_reg[29]/Q -type DFF DFF
add mapped point int_enable[30]/q int_enable_reg[30]/Q -type DFF DFF
add mapped point int_enable[31]/q int_enable_reg[31]/Q -type DFF DFF
add mapped point int_status[0]/q int_status_reg[0]/Q -type DFF DFF
add mapped point int_status[1]/q int_status_reg[1]/Q -type DFF DFF
add mapped point int_status[2]/q int_status_reg[2]/Q -type DFF DFF
add mapped point int_status[3]/q int_status_reg[3]/Q -type DFF DFF
add mapped point int_status[4]/q int_status_reg[4]/Q -type DFF DFF
add mapped point int_status[5]/q int_status_reg[5]/Q -type DFF DFF
add mapped point int_status[6]/q int_status_reg[6]/Q -type DFF DFF
add mapped point int_status[7]/q int_status_reg[7]/Q -type DFF DFF
add mapped point int_status[8]/q int_status_reg[8]/Q -type DFF DFF
add mapped point int_status[9]/q int_status_reg[9]/Q -type DFF DFF
add mapped point thermal_fault/q thermal_fault_reg/Q -type DFF DFF
add mapped point voltage_fault[0]/q voltage_fault_reg[0]/Q -type DFF DFF
add mapped point voltage_fault[1]/q voltage_fault_reg[1]/Q -type DFF DFF
add mapped point voltage_fault[2]/q voltage_fault_reg[2]/Q -type DFF DFF
add mapped point voltage_fault[3]/q voltage_fault_reg[3]/Q -type DFF DFF
add mapped point voltage_threshold[0]/q voltage_threshold_reg[0]/Q -type DFF DFF
add mapped point voltage_threshold[1]/q voltage_threshold_reg[1]/Q -type DFF DFF
add mapped point voltage_threshold[2]/q voltage_threshold_reg[2]/Q -type DFF DFF
add mapped point voltage_threshold[3]/q voltage_threshold_reg[3]/Q -type DFF DFF
add mapped point voltage_threshold[4]/q voltage_threshold_reg[4]/Q -type DFF DFF
add mapped point voltage_threshold[5]/q voltage_threshold_reg[5]/Q -type DFF DFF
add mapped point voltage_threshold[6]/q voltage_threshold_reg[6]/Q -type DFF DFF
add mapped point voltage_threshold[7]/q voltage_threshold_reg[7]/Q -type DFF DFF
add mapped point voltage_threshold[8]/q voltage_threshold_reg[8]/Q -type DFF DFF
add mapped point voltage_threshold[9]/q voltage_threshold_reg[9]/Q -type DFF DFF
add mapped point voltage_threshold[10]/q voltage_threshold_reg[10]/Q -type DFF DFF
add mapped point voltage_threshold[11]/q voltage_threshold_reg[11]/Q -type DFF DFF
add mapped point voltage_threshold[12]/q voltage_threshold_reg[12]/Q -type DFF DFF
add mapped point voltage_threshold[13]/q voltage_threshold_reg[13]/Q -type DFF DFF
add mapped point voltage_threshold[14]/q voltage_threshold_reg[14]/Q -type DFF DFF
add mapped point voltage_threshold[15]/q voltage_threshold_reg[15]/Q -type DFF DFF
add mapped point voltage_threshold[16]/q voltage_threshold_reg[16]/Q -type DFF DFF
add mapped point voltage_threshold[17]/q voltage_threshold_reg[17]/Q -type DFF DFF
add mapped point voltage_threshold[18]/q voltage_threshold_reg[18]/Q -type DFF DFF
add mapped point voltage_threshold[19]/q voltage_threshold_reg[19]/Q -type DFF DFF
add mapped point voltage_threshold[20]/q voltage_threshold_reg[20]/Q -type DFF DFF
add mapped point voltage_threshold[21]/q voltage_threshold_reg[21]/Q -type DFF DFF
add mapped point voltage_threshold[22]/q voltage_threshold_reg[22]/Q -type DFF DFF
add mapped point voltage_threshold[23]/q voltage_threshold_reg[23]/Q -type DFF DFF
add mapped point voltage_threshold[24]/q voltage_threshold_reg[24]/Q -type DFF DFF
add mapped point voltage_threshold[25]/q voltage_threshold_reg[25]/Q -type DFF DFF
add mapped point voltage_threshold[26]/q voltage_threshold_reg[26]/Q -type DFF DFF
add mapped point voltage_threshold[27]/q voltage_threshold_reg[27]/Q -type DFF DFF
add mapped point voltage_threshold[28]/q voltage_threshold_reg[28]/Q -type DFF DFF
add mapped point voltage_threshold[29]/q voltage_threshold_reg[29]/Q -type DFF DFF
add mapped point voltage_threshold[30]/q voltage_threshold_reg[30]/Q -type DFF DFF
add mapped point voltage_threshold[31]/q voltage_threshold_reg[31]/Q -type DFF DFF
add mapped point watchdog_control[0]/q watchdog_control_reg[0]/Q -type DFF DFF
add mapped point watchdog_control[1]/q watchdog_control_reg[1]/Q -type DFF DFF
add mapped point watchdog_control[2]/q watchdog_control_reg[2]/Q -type DFF DFF
add mapped point watchdog_control[3]/q watchdog_control_reg[3]/Q -type DFF DFF
add mapped point watchdog_control[4]/q watchdog_control_reg[4]/Q -type DFF DFF
add mapped point watchdog_control[5]/q watchdog_control_reg[5]/Q -type DFF DFF
add mapped point watchdog_control[6]/q watchdog_control_reg[6]/Q -type DFF DFF
add mapped point watchdog_control[7]/q watchdog_control_reg[7]/Q -type DFF DFF
add mapped point watchdog_control[8]/q watchdog_control_reg[8]/Q -type DFF DFF
add mapped point watchdog_control[9]/q watchdog_control_reg[9]/Q -type DFF DFF
add mapped point watchdog_control[10]/q watchdog_control_reg[10]/Q -type DFF DFF
add mapped point watchdog_control[11]/q watchdog_control_reg[11]/Q -type DFF DFF
add mapped point watchdog_control[12]/q watchdog_control_reg[12]/Q -type DFF DFF
add mapped point watchdog_control[13]/q watchdog_control_reg[13]/Q -type DFF DFF
add mapped point watchdog_control[14]/q watchdog_control_reg[14]/Q -type DFF DFF
add mapped point watchdog_control[15]/q watchdog_control_reg[15]/Q -type DFF DFF
add mapped point watchdog_control[16]/q watchdog_control_reg[16]/Q -type DFF DFF
add mapped point watchdog_control[17]/q watchdog_control_reg[17]/Q -type DFF DFF
add mapped point watchdog_control[18]/q watchdog_control_reg[18]/Q -type DFF DFF
add mapped point watchdog_control[19]/q watchdog_control_reg[19]/Q -type DFF DFF
add mapped point watchdog_control[20]/q watchdog_control_reg[20]/Q -type DFF DFF
add mapped point watchdog_control[21]/q watchdog_control_reg[21]/Q -type DFF DFF
add mapped point watchdog_control[22]/q watchdog_control_reg[22]/Q -type DFF DFF
add mapped point watchdog_control[23]/q watchdog_control_reg[23]/Q -type DFF DFF
add mapped point watchdog_control[24]/q watchdog_control_reg[24]/Q -type DFF DFF
add mapped point watchdog_control[25]/q watchdog_control_reg[25]/Q -type DFF DFF
add mapped point watchdog_control[26]/q watchdog_control_reg[26]/Q -type DFF DFF
add mapped point watchdog_control[27]/q watchdog_control_reg[27]/Q -type DFF DFF
add mapped point watchdog_control[28]/q watchdog_control_reg[28]/Q -type DFF DFF
add mapped point watchdog_control[29]/q watchdog_control_reg[29]/Q -type DFF DFF
add mapped point watchdog_control[30]/q watchdog_control_reg[30]/Q -type DFF DFF
add mapped point watchdog_control[31]/q watchdog_control_reg[31]/Q -type DFF DFF
add mapped point watchdog_counter[0]/q watchdog_counter_reg[0]/Q -type DFF DFF
add mapped point watchdog_counter[1]/q watchdog_counter_reg[1]/Q -type DFF DFF
add mapped point watchdog_counter[2]/q watchdog_counter_reg[2]/Q -type DFF DFF
add mapped point watchdog_counter[3]/q watchdog_counter_reg[3]/Q -type DFF DFF
add mapped point watchdog_counter[4]/q watchdog_counter_reg[4]/Q -type DFF DFF
add mapped point watchdog_counter[5]/q watchdog_counter_reg[5]/Q -type DFF DFF
add mapped point watchdog_counter[6]/q watchdog_counter_reg[6]/Q -type DFF DFF
add mapped point watchdog_counter[7]/q watchdog_counter_reg[7]/Q -type DFF DFF
add mapped point watchdog_counter[8]/q watchdog_counter_reg[8]/Q -type DFF DFF
add mapped point watchdog_counter[9]/q watchdog_counter_reg[9]/Q -type DFF DFF
add mapped point watchdog_counter[10]/q watchdog_counter_reg[10]/Q -type DFF DFF
add mapped point watchdog_counter[11]/q watchdog_counter_reg[11]/Q -type DFF DFF
add mapped point watchdog_counter[12]/q watchdog_counter_reg[12]/Q -type DFF DFF
add mapped point watchdog_counter[13]/q watchdog_counter_reg[13]/Q -type DFF DFF
add mapped point watchdog_counter[14]/q watchdog_counter_reg[14]/Q -type DFF DFF
add mapped point watchdog_counter[15]/q watchdog_counter_reg[15]/Q -type DFF DFF
add mapped point watchdog_counter[16]/q watchdog_counter_reg[16]/Q -type DFF DFF
add mapped point watchdog_fault/q watchdog_fault_reg/Q -type DFF DFF
add mapped point wb_dat_reg[0]/q wb_dat_reg_reg[0]/Q -type DFF DFF
add mapped point wb_dat_reg[1]/q wb_dat_reg_reg[1]/Q -type DFF DFF
add mapped point wb_dat_reg[2]/q wb_dat_reg_reg[2]/Q -type DFF DFF
add mapped point wb_dat_reg[3]/q wb_dat_reg_reg[3]/Q -type DFF DFF
add mapped point wb_dat_reg[4]/q wb_dat_reg_reg[4]/Q -type DFF DFF
add mapped point wb_dat_reg[5]/q wb_dat_reg_reg[5]/Q -type DFF DFF
add mapped point wb_dat_reg[6]/q wb_dat_reg_reg[6]/Q -type DFF DFF
add mapped point wb_dat_reg[7]/q wb_dat_reg_reg[7]/Q -type DFF DFF
add mapped point wb_dat_reg[8]/q wb_dat_reg_reg[8]/Q -type DFF DFF
add mapped point wb_dat_reg[9]/q wb_dat_reg_reg[9]/Q -type DFF DFF
add mapped point wb_dat_reg[10]/q wb_dat_reg_reg[10]/Q -type DFF DFF
add mapped point wb_dat_reg[11]/q wb_dat_reg_reg[11]/Q -type DFF DFF
add mapped point wb_dat_reg[12]/q wb_dat_reg_reg[12]/Q -type DFF DFF
add mapped point wb_dat_reg[13]/q wb_dat_reg_reg[13]/Q -type DFF DFF
add mapped point wb_dat_reg[14]/q wb_dat_reg_reg[14]/Q -type DFF DFF
add mapped point wb_dat_reg[15]/q wb_dat_reg_reg[15]/Q -type DFF DFF
add mapped point wb_dat_reg[16]/q wb_dat_reg_reg[16]/Q -type DFF DFF
add mapped point wb_dat_reg[17]/q wb_dat_reg_reg[17]/Q -type DFF DFF
add mapped point wb_dat_reg[18]/q wb_dat_reg_reg[18]/Q -type DFF DFF
add mapped point wb_dat_reg[19]/q wb_dat_reg_reg[19]/Q -type DFF DFF
add mapped point wb_dat_reg[20]/q wb_dat_reg_reg[20]/Q -type DFF DFF
add mapped point wb_dat_reg[21]/q wb_dat_reg_reg[21]/Q -type DFF DFF
add mapped point wb_dat_reg[22]/q wb_dat_reg_reg[22]/Q -type DFF DFF
add mapped point wb_dat_reg[23]/q wb_dat_reg_reg[23]/Q -type DFF DFF
add mapped point wb_dat_reg[24]/q wb_dat_reg_reg[24]/Q -type DFF DFF
add mapped point wb_dat_reg[25]/q wb_dat_reg_reg[25]/Q -type DFF DFF
add mapped point wb_dat_reg[26]/q wb_dat_reg_reg[26]/Q -type DFF DFF
add mapped point wb_dat_reg[27]/q wb_dat_reg_reg[27]/Q -type DFF DFF
add mapped point wb_dat_reg[28]/q wb_dat_reg_reg[28]/Q -type DFF DFF
add mapped point wb_dat_reg[29]/q wb_dat_reg_reg[29]/Q -type DFF DFF
add mapped point wb_dat_reg[30]/q wb_dat_reg_reg[30]/Q -type DFF DFF
add mapped point wb_dat_reg[31]/q wb_dat_reg_reg[31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
