
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Dec 24 2025 12:05:20 +03 (Dec 24 2025 09:05:20 UTC)

// Verification Directory fv/memory_macro 

module memory_macro(clk, rst_n, iwb_adr_i, iwb_dat_o, iwb_dat_i,
     iwb_we_i, iwb_sel_i, iwb_cyc_i, iwb_stb_i, iwb_ack_o, iwb_err_o,
     dwb_adr_i, dwb_dat_o, dwb_dat_i, dwb_we_i, dwb_sel_i, dwb_cyc_i,
     dwb_stb_i, dwb_ack_o, dwb_err_o, ext_mem_adr_o, ext_mem_dat_o,
     ext_mem_dat_i, ext_mem_we_o, ext_mem_sel_o, ext_mem_cyc_o,
     ext_mem_stb_o, ext_mem_ack_i, ext_mem_err_i, rom_ready, ram_ready,
     memory_status);
  input clk, rst_n, iwb_we_i, iwb_cyc_i, iwb_stb_i, dwb_we_i,
       dwb_cyc_i, dwb_stb_i, ext_mem_ack_i, ext_mem_err_i;
  input [31:0] iwb_adr_i, iwb_dat_i, dwb_adr_i, dwb_dat_i,
       ext_mem_dat_i;
  input [3:0] iwb_sel_i, dwb_sel_i;
  output [31:0] iwb_dat_o, dwb_dat_o, ext_mem_adr_o, ext_mem_dat_o,
       memory_status;
  output iwb_ack_o, iwb_err_o, dwb_ack_o, dwb_err_o, ext_mem_we_o,
       ext_mem_cyc_o, ext_mem_stb_o, rom_ready, ram_ready;
  output [3:0] ext_mem_sel_o;
  wire clk, rst_n, iwb_we_i, iwb_cyc_i, iwb_stb_i, dwb_we_i, dwb_cyc_i,
       dwb_stb_i, ext_mem_ack_i, ext_mem_err_i;
  wire [31:0] iwb_adr_i, iwb_dat_i, dwb_adr_i, dwb_dat_i, ext_mem_dat_i;
  wire [3:0] iwb_sel_i, dwb_sel_i;
  wire [31:0] iwb_dat_o, dwb_dat_o, ext_mem_adr_o, ext_mem_dat_o,
       memory_status;
  wire iwb_ack_o, iwb_err_o, dwb_ack_o, dwb_err_o, ext_mem_we_o,
       ext_mem_cyc_o, ext_mem_stb_o, rom_ready, ram_ready;
  wire [3:0] ext_mem_sel_o;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, ext_ack, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_173, n_174, n_181, n_182, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_223, n_253, n_259, n_447, n_448, ram_ack, rom_ack;
  assign memory_status[0] = 1'b0;
  assign memory_status[1] = 1'b1;
  assign memory_status[2] = 1'b1;
  assign memory_status[3] = 1'b0;
  assign memory_status[4] = 1'b1;
  assign memory_status[5] = 1'b0;
  assign memory_status[6] = 1'b0;
  assign memory_status[7] = 1'b1;
  assign memory_status[8] = 1'b0;
  assign memory_status[9] = 1'b0;
  assign memory_status[10] = 1'b0;
  assign memory_status[11] = 1'b0;
  assign memory_status[12] = ext_mem_ack_i;
  assign memory_status[13] = 1'b0;
  assign memory_status[14] = 1'b1;
  assign memory_status[15] = 1'b1;
  assign memory_status[16] = 1'b0;
  assign memory_status[17] = 1'b0;
  assign memory_status[18] = 1'b0;
  assign memory_status[19] = 1'b0;
  assign memory_status[20] = 1'b0;
  assign memory_status[21] = 1'b0;
  assign memory_status[22] = 1'b0;
  assign memory_status[23] = 1'b0;
  assign memory_status[24] = 1'b0;
  assign memory_status[25] = 1'b0;
  assign memory_status[26] = 1'b0;
  assign memory_status[27] = 1'b0;
  assign memory_status[28] = 1'b0;
  assign memory_status[29] = 1'b0;
  assign memory_status[30] = 1'b0;
  assign memory_status[31] = 1'b0;
  assign ram_ready = 1'b1;
  assign rom_ready = 1'b1;
  assign ext_mem_stb_o = ext_mem_cyc_o;
  assign dwb_err_o = iwb_err_o;
  sky130_osu_sc_18T_ms__oai22_l g7453__2398(.A0 (ram_ack), .A1 (n_192),
       .B0 (n_195), .B1 (ext_ack), .Y (dwb_ack_o));
  sky130_osu_sc_18T_ms__oai22_l g7454__5107(.A0 (rom_ack), .A1 (n_188),
       .B0 (n_194), .B1 (ext_ack), .Y (iwb_ack_o));
  sky130_osu_sc_18T_ms__nand2_l g7518__6260(.A (n_186), .B (n_253), .Y
       (iwb_dat_o[0]));
  sky130_osu_sc_18T_ms__and2_l g7485__4319(.A (n_259), .B
       (ext_mem_dat_i[0]), .Y (dwb_dat_o[0]));
  sky130_osu_sc_18T_ms__and2_l g7486__8428(.A (n_259), .B
       (ext_mem_dat_i[31]), .Y (dwb_dat_o[31]));
  sky130_osu_sc_18T_ms__and2_l g7456__5526(.A (n_259), .B
       (ext_mem_dat_i[30]), .Y (dwb_dat_o[30]));
  sky130_osu_sc_18T_ms__and2_l g7484__6783(.A (n_259), .B
       (ext_mem_dat_i[4]), .Y (dwb_dat_o[4]));
  sky130_osu_sc_18T_ms__and2_l g7471__3680(.A (n_259), .B
       (ext_mem_dat_i[29]), .Y (dwb_dat_o[29]));
  sky130_osu_sc_18T_ms__and2_l g7472__1617(.A (n_259), .B
       (ext_mem_dat_i[28]), .Y (dwb_dat_o[28]));
  sky130_osu_sc_18T_ms__nand2_l g7516__2802(.A (n_189), .B (n_253), .Y
       (iwb_dat_o[4]));
  sky130_osu_sc_18T_ms__nand2_l g7517__1705(.A (n_187), .B (n_253), .Y
       (iwb_dat_o[1]));
  sky130_osu_sc_18T_ms__and2_l g7459__5122(.A (n_259), .B
       (ext_mem_dat_i[25]), .Y (dwb_dat_o[25]));
  sky130_osu_sc_18T_ms__and2_l g7460__8246(.A (n_259), .B
       (ext_mem_dat_i[24]), .Y (dwb_dat_o[24]));
  sky130_osu_sc_18T_ms__and2_l g7461__7098(.A (n_259), .B
       (ext_mem_dat_i[23]), .Y (dwb_dat_o[23]));
  sky130_osu_sc_18T_ms__and2_l g7480__6131(.A (n_259), .B
       (ext_mem_dat_i[12]), .Y (dwb_dat_o[12]));
  sky130_osu_sc_18T_ms__and2_l g7462__1881(.A (n_259), .B
       (ext_mem_dat_i[22]), .Y (dwb_dat_o[22]));
  sky130_osu_sc_18T_ms__and2_l g7463__5115(.A (n_259), .B
       (ext_mem_dat_i[21]), .Y (dwb_dat_o[21]));
  sky130_osu_sc_18T_ms__and2_l g7464__7482(.A (n_259), .B
       (ext_mem_dat_i[20]), .Y (dwb_dat_o[20]));
  sky130_osu_sc_18T_ms__and2_l g7465__4733(.A (n_259), .B
       (ext_mem_dat_i[19]), .Y (dwb_dat_o[19]));
  sky130_osu_sc_18T_ms__and2_l g7476__6161(.A (n_259), .B
       (ext_mem_dat_i[8]), .Y (dwb_dat_o[8]));
  sky130_osu_sc_18T_ms__and2_l g7467__9315(.A (n_259), .B
       (ext_mem_dat_i[17]), .Y (dwb_dat_o[17]));
  sky130_osu_sc_18T_ms__and2_l g7468__9945(.A (n_259), .B
       (ext_mem_dat_i[16]), .Y (dwb_dat_o[16]));
  sky130_osu_sc_18T_ms__and2_l g7469__2883(.A (n_259), .B
       (ext_mem_dat_i[15]), .Y (dwb_dat_o[15]));
  sky130_osu_sc_18T_ms__and2_l g7470__2346(.A (n_259), .B
       (ext_mem_dat_i[14]), .Y (dwb_dat_o[14]));
  sky130_osu_sc_18T_ms__and2_l g7455__1666(.A (n_259), .B
       (ext_mem_dat_i[13]), .Y (dwb_dat_o[13]));
  sky130_osu_sc_18T_ms__and2_l g7457__7410(.A (n_259), .B
       (ext_mem_dat_i[27]), .Y (dwb_dat_o[27]));
  sky130_osu_sc_18T_ms__and2_l g7474__6417(.A (n_259), .B
       (ext_mem_dat_i[10]), .Y (dwb_dat_o[10]));
  sky130_osu_sc_18T_ms__and2_l g7475__5477(.A (n_259), .B
       (ext_mem_dat_i[9]), .Y (dwb_dat_o[9]));
  sky130_osu_sc_18T_ms__and2_l g7466__2398(.A (n_259), .B
       (ext_mem_dat_i[18]), .Y (dwb_dat_o[18]));
  sky130_osu_sc_18T_ms__and2_l g7477__5107(.A (n_259), .B
       (ext_mem_dat_i[7]), .Y (dwb_dat_o[7]));
  sky130_osu_sc_18T_ms__and2_l g7478__6260(.A (n_259), .B
       (ext_mem_dat_i[6]), .Y (dwb_dat_o[6]));
  sky130_osu_sc_18T_ms__and2_l g7479__4319(.A (n_259), .B
       (ext_mem_dat_i[5]), .Y (dwb_dat_o[5]));
  sky130_osu_sc_18T_ms__and2_l g7458__8428(.A (n_259), .B
       (ext_mem_dat_i[26]), .Y (dwb_dat_o[26]));
  sky130_osu_sc_18T_ms__and2_l g7482__5526(.A (n_259), .B
       (ext_mem_dat_i[2]), .Y (dwb_dat_o[2]));
  sky130_osu_sc_18T_ms__and2_l g7483__6783(.A (n_259), .B
       (ext_mem_dat_i[1]), .Y (dwb_dat_o[1]));
  sky130_osu_sc_18T_ms__and2_l g7473__3680(.A (n_259), .B
       (ext_mem_dat_i[11]), .Y (dwb_dat_o[11]));
  sky130_osu_sc_18T_ms__and2_l g7481__1617(.A (n_259), .B
       (ext_mem_dat_i[3]), .Y (dwb_dat_o[3]));
  sky130_osu_sc_18T_ms__and2_l g7511__2802(.A (n_223), .B
       (ext_mem_dat_i[25]), .Y (iwb_dat_o[25]));
  sky130_osu_sc_18T_ms__and2_l g7510__1705(.A (n_223), .B
       (ext_mem_dat_i[31]), .Y (iwb_dat_o[31]));
  sky130_osu_sc_18T_ms__and2_l g7490__5122(.A (n_223), .B
       (ext_mem_dat_i[30]), .Y (iwb_dat_o[30]));
  sky130_osu_sc_18T_ms__and2_l g7513__8246(.A (n_223), .B
       (ext_mem_dat_i[29]), .Y (iwb_dat_o[29]));
  sky130_osu_sc_18T_ms__and2_l g7504__7098(.A (n_223), .B
       (ext_mem_dat_i[28]), .Y (iwb_dat_o[28]));
  sky130_osu_sc_18T_ms__and2_l g7506__6131(.A (n_223), .B
       (ext_mem_dat_i[27]), .Y (iwb_dat_o[27]));
  sky130_osu_sc_18T_ms__and2_l g7508__1881(.A (n_223), .B
       (ext_mem_dat_i[26]), .Y (iwb_dat_o[26]));
  sky130_osu_sc_18T_ms__and2_l g7507__5115(.A (n_223), .B
       (ext_mem_dat_i[3]), .Y (iwb_dat_o[3]));
  sky130_osu_sc_18T_ms__and2_l g7500__7482(.A (n_223), .B
       (ext_mem_dat_i[8]), .Y (iwb_dat_o[8]));
  sky130_osu_sc_18T_ms__and2_l g7512__4733(.A (n_223), .B
       (ext_mem_dat_i[24]), .Y (iwb_dat_o[24]));
  sky130_osu_sc_18T_ms__and2_l g7514__6161(.A (n_223), .B
       (ext_mem_dat_i[23]), .Y (iwb_dat_o[23]));
  sky130_osu_sc_18T_ms__and2_l g7515__9315(.A (n_223), .B
       (ext_mem_dat_i[22]), .Y (iwb_dat_o[22]));
  sky130_osu_sc_18T_ms__and2_l g7497__9945(.A (n_223), .B
       (ext_mem_dat_i[12]), .Y (iwb_dat_o[12]));
  sky130_osu_sc_18T_ms__and2_l g7492__2883(.A (n_223), .B
       (ext_mem_dat_i[21]), .Y (iwb_dat_o[21]));
  sky130_osu_sc_18T_ms__and2_l g7503__2346(.A (n_223), .B
       (ext_mem_dat_i[20]), .Y (iwb_dat_o[20]));
  sky130_osu_sc_18T_ms__and2_l g7498__1666(.A (n_223), .B
       (ext_mem_dat_i[11]), .Y (iwb_dat_o[11]));
  sky130_osu_sc_18T_ms__and2_l g7489__7410(.A (n_223), .B
       (ext_mem_dat_i[18]), .Y (iwb_dat_o[18]));
  sky130_osu_sc_18T_ms__and2_l g7493__6417(.A (n_223), .B
       (ext_mem_dat_i[17]), .Y (iwb_dat_o[17]));
  sky130_osu_sc_18T_ms__and2_l g7491__5477(.A (n_223), .B
       (ext_mem_dat_i[16]), .Y (iwb_dat_o[16]));
  sky130_osu_sc_18T_ms__and2_l g7494__2398(.A (n_223), .B
       (ext_mem_dat_i[15]), .Y (iwb_dat_o[15]));
  sky130_osu_sc_18T_ms__and2_l g7495__5107(.A (n_223), .B
       (ext_mem_dat_i[14]), .Y (iwb_dat_o[14]));
  sky130_osu_sc_18T_ms__and2_l g7496__6260(.A (n_223), .B
       (ext_mem_dat_i[13]), .Y (iwb_dat_o[13]));
  sky130_osu_sc_18T_ms__and2_l g7488__4319(.A (n_223), .B
       (ext_mem_dat_i[19]), .Y (iwb_dat_o[19]));
  sky130_osu_sc_18T_ms__and2_l g7499__8428(.A (n_223), .B
       (ext_mem_dat_i[10]), .Y (iwb_dat_o[10]));
  sky130_osu_sc_18T_ms__and2_l g7501__5526(.A (n_223), .B
       (ext_mem_dat_i[9]), .Y (iwb_dat_o[9]));
  sky130_osu_sc_18T_ms__and2_l g7502__6783(.A (n_223), .B
       (ext_mem_dat_i[7]), .Y (iwb_dat_o[7]));
  sky130_osu_sc_18T_ms__and2_l g7487__3680(.A (n_223), .B
       (ext_mem_dat_i[6]), .Y (iwb_dat_o[6]));
  sky130_osu_sc_18T_ms__and2_l g7505__1617(.A (n_223), .B
       (ext_mem_dat_i[5]), .Y (iwb_dat_o[5]));
  sky130_osu_sc_18T_ms__and2_l g7509__2802(.A (n_223), .B
       (ext_mem_dat_i[2]), .Y (iwb_dat_o[2]));
  sky130_osu_sc_18T_ms__inv_1 g7522(.A (n_259), .Y (n_195));
  sky130_osu_sc_18T_ms__inv_1 g7519(.A (n_223), .Y (n_194));
  sky130_osu_sc_18T_ms__oai21_l g7523__1705(.A0 (n_173), .A1 (n_182),
       .B0 (n_193), .Y (n_253));
  sky130_osu_sc_18T_ms__dffr_1 rom_ack_reg(.RN (rst_n), .CK (clk), .D
       (n_185), .Q (UNCONNECTED), .QN (rom_ack));
  sky130_osu_sc_18T_ms__dffr_1 ram_ack_reg(.RN (rst_n), .CK (clk), .D
       (n_191), .Q (UNCONNECTED0), .QN (ram_ack));
  sky130_osu_sc_18T_ms__oai21_l g7524__5122(.A0 (n_190), .A1 (n_184),
       .B0 (n_193), .Y (n_259));
  sky130_osu_sc_18T_ms__inv_1 g7525(.A (n_191), .Y (n_192));
  sky130_osu_sc_18T_ms__oai21_l g7521__8246(.A0 (n_193), .A1 (n_174),
       .B0 (n_190), .Y (n_223));
  sky130_osu_sc_18T_ms__nand2_l g7528__7098(.A (n_188), .B
       (ext_mem_dat_i[4]), .Y (n_189));
  sky130_osu_sc_18T_ms__nand2_l g7529__6131(.A (n_188), .B
       (ext_mem_dat_i[1]), .Y (n_187));
  sky130_osu_sc_18T_ms__nand2_l g7530__1881(.A (n_188), .B
       (ext_mem_dat_i[0]), .Y (n_186));
  sky130_osu_sc_18T_ms__nor2_1 g7527__5115(.A (dwb_adr_i[31]), .B
       (n_448), .Y (n_191));
  sky130_osu_sc_18T_ms__inv_1 g7564(.A (n_188), .Y (n_185));
  sky130_osu_sc_18T_ms__nand2_1 g7600__7482(.A (n_19), .B (n_181), .Y
       (n_188));
  sky130_osu_sc_18T_ms__inv_1 g7563(.A (n_448), .Y (n_184));
  sky130_osu_sc_18T_ms__nor2_l g7583__4733(.A (iwb_adr_i[31]), .B
       (n_181), .Y (n_182));
  sky130_osu_sc_18T_ms__inv_l g7636(.A (n_77), .Y (ext_mem_adr_o[13]));
  sky130_osu_sc_18T_ms__inv_l g7617(.A (n_56), .Y (ext_mem_adr_o[21]));
  sky130_osu_sc_18T_ms__inv_l g7618(.A (n_75), .Y (ext_mem_dat_o[5]));
  sky130_osu_sc_18T_ms__inv_l g7533(.A (n_41), .Y (ext_mem_adr_o[29]));
  sky130_osu_sc_18T_ms__inv_l g7619(.A (n_109), .Y (ext_mem_dat_o[14]));
  sky130_osu_sc_18T_ms__inv_l g7549(.A (n_110), .Y (ext_mem_dat_o[28]));
  sky130_osu_sc_18T_ms__nor2_l g7568__6161(.A (n_173), .B (n_39), .Y
       (n_174));
  sky130_osu_sc_18T_ms__inv_l g7620(.A (n_104), .Y (ext_mem_adr_o[20]));
  sky130_osu_sc_18T_ms__inv_l g7621(.A (n_106), .Y (ext_mem_adr_o[19]));
  sky130_osu_sc_18T_ms__inv_l g7550(.A (n_105), .Y (ext_mem_dat_o[27]));
  sky130_osu_sc_18T_ms__inv_l g7622(.A (n_102), .Y (ext_mem_dat_o[3]));
  sky130_osu_sc_18T_ms__inv_l g7623(.A (n_101), .Y (ext_mem_dat_o[2]));
  sky130_osu_sc_18T_ms__inv_l g7551(.A (n_100), .Y (ext_mem_dat_o[26]));
  sky130_osu_sc_18T_ms__inv_l g7624(.A (n_98), .Y (ext_mem_adr_o[18]));
  sky130_osu_sc_18T_ms__inv_l g7534(.A (n_99), .Y (ext_mem_adr_o[12]));
  sky130_osu_sc_18T_ms__inv_l g7625(.A (n_96), .Y (ext_mem_dat_o[1]));
  sky130_osu_sc_18T_ms__inv_l g7552(.A (n_97), .Y (ext_mem_dat_o[25]));
  sky130_osu_sc_18T_ms__inv_l g7626(.A (n_94), .Y (ext_mem_adr_o[17]));
  sky130_osu_sc_18T_ms__inv_l g7627(.A (n_92), .Y (ext_mem_dat_o[0]));
  sky130_osu_sc_18T_ms__inv_l g7553(.A (n_93), .Y (ext_mem_dat_o[24]));
  sky130_osu_sc_18T_ms__inv_l g7628(.A (n_91), .Y (ext_mem_adr_o[16]));
  sky130_osu_sc_18T_ms__inv_l g7535(.A (n_95), .Y (ext_mem_adr_o[11]));
  sky130_osu_sc_18T_ms__inv_l g7629(.A (n_89), .Y (ext_mem_we_o));
  sky130_osu_sc_18T_ms__inv_l g7554(.A (n_90), .Y (ext_mem_dat_o[23]));
  sky130_osu_sc_18T_ms__inv_l g7630(.A (n_87), .Y (ext_mem_adr_o[15]));
  sky130_osu_sc_18T_ms__inv_l g7631(.A (n_85), .Y (ext_mem_sel_o[3]));
  sky130_osu_sc_18T_ms__inv_l g7555(.A (n_86), .Y (ext_mem_dat_o[22]));
  sky130_osu_sc_18T_ms__inv_l g7632(.A (n_84), .Y (ext_mem_sel_o[2]));
  sky130_osu_sc_18T_ms__inv_l g7536(.A (n_88), .Y (ext_mem_adr_o[10]));
  sky130_osu_sc_18T_ms__inv_l g7633(.A (n_82), .Y (ext_mem_adr_o[14]));
  sky130_osu_sc_18T_ms__inv_l g7556(.A (n_83), .Y (ext_mem_dat_o[21]));
  sky130_osu_sc_18T_ms__inv_l g7634(.A (n_80), .Y (ext_mem_sel_o[1]));
  sky130_osu_sc_18T_ms__inv_l g7635(.A (n_78), .Y (ext_mem_sel_o[0]));
  sky130_osu_sc_18T_ms__inv_l g7557(.A (n_79), .Y (ext_mem_dat_o[20]));
  sky130_osu_sc_18T_ms__inv_l g7548(.A (n_40), .Y (ext_mem_dat_o[29]));
  sky130_osu_sc_18T_ms__inv_l g7616(.A (n_42), .Y (ext_mem_dat_o[6]));
  sky130_osu_sc_18T_ms__inv_l g7558(.A (n_76), .Y (ext_mem_dat_o[19]));
  sky130_osu_sc_18T_ms__inv_l g7559(.A (n_72), .Y (ext_mem_dat_o[18]));
  sky130_osu_sc_18T_ms__inv_l g7538(.A (n_73), .Y (ext_mem_adr_o[8]));
  sky130_osu_sc_18T_ms__inv_l g7560(.A (n_71), .Y (ext_mem_dat_o[17]));
  sky130_osu_sc_18T_ms__inv_l g7561(.A (n_69), .Y (ext_mem_adr_o[30]));
  sky130_osu_sc_18T_ms__inv_l g7539(.A (n_70), .Y (ext_mem_adr_o[7]));
  sky130_osu_sc_18T_ms__inv_l g7562(.A (n_68), .Y (ext_mem_dat_o[16]));
  sky130_osu_sc_18T_ms__inv_l g7537(.A (n_81), .Y (ext_mem_adr_o[9]));
  sky130_osu_sc_18T_ms__inv_l g7540(.A (n_67), .Y (ext_mem_adr_o[6]));
  sky130_osu_sc_18T_ms__inv_l g7601(.A (n_66), .Y (ext_mem_dat_o[4]));
  sky130_osu_sc_18T_ms__inv_l g7602(.A (n_64), .Y (ext_mem_adr_o[28]));
  sky130_osu_sc_18T_ms__inv_l g7541(.A (n_65), .Y (ext_mem_adr_o[5]));
  sky130_osu_sc_18T_ms__inv_l g7603(.A (n_63), .Y (ext_mem_dat_o[13]));
  sky130_osu_sc_18T_ms__inv_l g7604(.A (n_61), .Y (ext_mem_adr_o[27]));
  sky130_osu_sc_18T_ms__inv_l g7542(.A (n_62), .Y (ext_mem_adr_o[4]));
  sky130_osu_sc_18T_ms__inv_l g7605(.A (n_60), .Y (ext_mem_dat_o[12]));
  sky130_osu_sc_18T_ms__inv_l g7606(.A (n_58), .Y (ext_mem_adr_o[26]));
  sky130_osu_sc_18T_ms__inv_l g7543(.A (n_59), .Y (ext_mem_adr_o[3]));
  sky130_osu_sc_18T_ms__inv_l g7607(.A (n_57), .Y (ext_mem_dat_o[11]));
  sky130_osu_sc_18T_ms__inv_l g7608(.A (n_55), .Y (ext_mem_dat_o[10]));
  sky130_osu_sc_18T_ms__inv_l g7544(.A (n_74), .Y (ext_mem_adr_o[2]));
  sky130_osu_sc_18T_ms__inv_l g7609(.A (n_53), .Y (ext_mem_adr_o[25]));
  sky130_osu_sc_18T_ms__inv_l g7610(.A (n_51), .Y (ext_mem_dat_o[9]));
  sky130_osu_sc_18T_ms__inv_l g7545(.A (n_52), .Y (ext_mem_adr_o[1]));
  sky130_osu_sc_18T_ms__inv_l g7531(.A (n_54), .Y (ext_mem_dat_o[30]));
  sky130_osu_sc_18T_ms__inv_l g7611(.A (n_50), .Y (ext_mem_adr_o[24]));
  sky130_osu_sc_18T_ms__inv_l g7612(.A (n_48), .Y (ext_mem_dat_o[8]));
  sky130_osu_sc_18T_ms__inv_l g7546(.A (n_49), .Y (ext_mem_adr_o[0]));
  sky130_osu_sc_18T_ms__inv_l g7613(.A (n_46), .Y (ext_mem_adr_o[23]));
  sky130_osu_sc_18T_ms__inv_l g7614(.A (n_44), .Y (ext_mem_dat_o[7]));
  sky130_osu_sc_18T_ms__inv_l g7547(.A (n_45), .Y (ext_mem_dat_o[31]));
  sky130_osu_sc_18T_ms__inv_l g7532(.A (n_47), .Y (ext_mem_dat_o[15]));
  sky130_osu_sc_18T_ms__inv_l g7615(.A (n_43), .Y (ext_mem_adr_o[22]));
  sky130_osu_sc_18T_ms__aoi22_l g7585__9945(.A0 (iwb_dat_i[28]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[28]), .Y (n_110));
  sky130_osu_sc_18T_ms__aoi22_l g7655__2883(.A0 (iwb_dat_i[14]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[14]), .Y (n_109));
  sky130_osu_sc_18T_ms__aoi22_l g7657__2346(.A0 (iwb_adr_i[19]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[19]), .Y (n_106));
  sky130_osu_sc_18T_ms__aoi22_l g7586__1666(.A0 (iwb_dat_i[27]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[27]), .Y (n_105));
  sky130_osu_sc_18T_ms__aoi22_l g7656__7410(.A0 (iwb_adr_i[20]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[20]), .Y (n_104));
  sky130_osu_sc_18T_ms__nand2_l g7673__6417(.A (n_33), .B (n_36), .Y
       (ext_mem_adr_o[31]));
  sky130_osu_sc_18T_ms__aoi22_l g7658__5477(.A0 (iwb_dat_i[3]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[3]), .Y (n_102));
  sky130_osu_sc_18T_ms__aoi22_l g7659__2398(.A0 (iwb_dat_i[2]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[2]), .Y (n_101));
  sky130_osu_sc_18T_ms__aoi22_l g7587__5107(.A0 (iwb_dat_i[26]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[26]), .Y (n_100));
  sky130_osu_sc_18T_ms__aoi22_l g7569__6260(.A0 (iwb_adr_i[12]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[12]), .Y (n_99));
  sky130_osu_sc_18T_ms__aoi22_l g7660__4319(.A0 (iwb_adr_i[18]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[18]), .Y (n_98));
  sky130_osu_sc_18T_ms__aoi22_l g7588__8428(.A0 (iwb_dat_i[25]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[25]), .Y (n_97));
  sky130_osu_sc_18T_ms__aoi22_l g7661__5526(.A0 (iwb_dat_i[1]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[1]), .Y (n_96));
  sky130_osu_sc_18T_ms__aoi22_l g7570__6783(.A0 (iwb_adr_i[11]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[11]), .Y (n_95));
  sky130_osu_sc_18T_ms__aoi22_l g7662__3680(.A0 (iwb_adr_i[17]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[17]), .Y (n_94));
  sky130_osu_sc_18T_ms__aoi22_l g7589__1617(.A0 (iwb_dat_i[24]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[24]), .Y (n_93));
  sky130_osu_sc_18T_ms__aoi22_l g7663__2802(.A0 (iwb_dat_i[0]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[0]), .Y (n_92));
  sky130_osu_sc_18T_ms__aoi22_l g7664__1705(.A0 (iwb_adr_i[16]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[16]), .Y (n_91));
  sky130_osu_sc_18T_ms__aoi22_l g7590__5122(.A0 (iwb_dat_i[23]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[23]), .Y (n_90));
  sky130_osu_sc_18T_ms__aoi22_l g7665__8246(.A0 (iwb_we_i), .A1
       (n_108), .B0 (n_107), .B1 (dwb_we_i), .Y (n_89));
  sky130_osu_sc_18T_ms__aoi22_l g7571__7098(.A0 (iwb_adr_i[10]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[10]), .Y (n_88));
  sky130_osu_sc_18T_ms__aoi22_l g7666__6131(.A0 (iwb_adr_i[15]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[15]), .Y (n_87));
  sky130_osu_sc_18T_ms__aoi22_l g7591__1881(.A0 (iwb_dat_i[22]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[22]), .Y (n_86));
  sky130_osu_sc_18T_ms__aoi22_l g7667__5115(.A0 (iwb_sel_i[3]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_sel_i[3]), .Y (n_85));
  sky130_osu_sc_18T_ms__aoi22_l g7668__7482(.A0 (iwb_sel_i[2]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_sel_i[2]), .Y (n_84));
  sky130_osu_sc_18T_ms__aoi22_l g7592__4733(.A0 (iwb_dat_i[21]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[21]), .Y (n_83));
  sky130_osu_sc_18T_ms__aoi22_l g7669__6161(.A0 (iwb_adr_i[14]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[14]), .Y (n_82));
  sky130_osu_sc_18T_ms__aoi22_l g7572__9315(.A0 (iwb_adr_i[9]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[9]), .Y (n_81));
  sky130_osu_sc_18T_ms__aoi22_l g7670__9945(.A0 (iwb_sel_i[1]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_sel_i[1]), .Y (n_80));
  sky130_osu_sc_18T_ms__aoi22_l g7593__2883(.A0 (iwb_dat_i[20]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[20]), .Y (n_79));
  sky130_osu_sc_18T_ms__aoi22_l g7671__2346(.A0 (iwb_sel_i[0]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_sel_i[0]), .Y (n_78));
  sky130_osu_sc_18T_ms__aoi22_l g7672__1666(.A0 (iwb_adr_i[13]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[13]), .Y (n_77));
  sky130_osu_sc_18T_ms__aoi22_l g7594__7410(.A0 (iwb_dat_i[19]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[19]), .Y (n_76));
  sky130_osu_sc_18T_ms__aoi22_l g7654__6417(.A0 (iwb_dat_i[5]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[5]), .Y (n_75));
  sky130_osu_sc_18T_ms__dffr_1 ext_ack_reg(.RN (rst_n), .CK (clk), .D
       (n_37), .Q (UNCONNECTED1), .QN (ext_ack));
  sky130_osu_sc_18T_ms__aoi22_l g7579__5477(.A0 (iwb_adr_i[2]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[2]), .Y (n_74));
  sky130_osu_sc_18T_ms__aoi22_l g7573__2398(.A0 (iwb_adr_i[8]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[8]), .Y (n_73));
  sky130_osu_sc_18T_ms__aoi22_l g7595__5107(.A0 (iwb_dat_i[18]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[18]), .Y (n_72));
  sky130_osu_sc_18T_ms__aoi22_l g7596__6260(.A0 (iwb_dat_i[17]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[17]), .Y (n_71));
  sky130_osu_sc_18T_ms__aoi22_l g7574__4319(.A0 (iwb_adr_i[7]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[7]), .Y (n_70));
  sky130_osu_sc_18T_ms__aoi22_l g7597__8428(.A0 (iwb_adr_i[30]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[30]), .Y (n_69));
  sky130_osu_sc_18T_ms__aoi22_l g7598__5526(.A0 (iwb_dat_i[16]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[16]), .Y (n_68));
  sky130_osu_sc_18T_ms__aoi22_l g7575__6783(.A0 (iwb_adr_i[6]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[6]), .Y (n_67));
  sky130_osu_sc_18T_ms__aoi22_l g7637__3680(.A0 (iwb_dat_i[4]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[4]), .Y (n_66));
  sky130_osu_sc_18T_ms__aoi22_l g7576__1617(.A0 (iwb_adr_i[5]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[5]), .Y (n_65));
  sky130_osu_sc_18T_ms__aoi22_l g7638__2802(.A0 (iwb_adr_i[28]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[28]), .Y (n_64));
  sky130_osu_sc_18T_ms__aoi22_l g7639__1705(.A0 (iwb_dat_i[13]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[13]), .Y (n_63));
  sky130_osu_sc_18T_ms__aoi22_l g7577__5122(.A0 (iwb_adr_i[4]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[4]), .Y (n_62));
  sky130_osu_sc_18T_ms__aoi22_l g7640__8246(.A0 (iwb_adr_i[27]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[27]), .Y (n_61));
  sky130_osu_sc_18T_ms__aoi22_l g7641__7098(.A0 (iwb_dat_i[12]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[12]), .Y (n_60));
  sky130_osu_sc_18T_ms__aoi22_l g7578__6131(.A0 (iwb_adr_i[3]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[3]), .Y (n_59));
  sky130_osu_sc_18T_ms__aoi22_l g7642__1881(.A0 (iwb_adr_i[26]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[26]), .Y (n_58));
  sky130_osu_sc_18T_ms__aoi22_l g7643__5115(.A0 (iwb_dat_i[11]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[11]), .Y (n_57));
  sky130_osu_sc_18T_ms__aoi22_l g7653__7482(.A0 (iwb_adr_i[21]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[21]), .Y (n_56));
  sky130_osu_sc_18T_ms__aoi22_l g7644__4733(.A0 (iwb_dat_i[10]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[10]), .Y (n_55));
  sky130_osu_sc_18T_ms__aoi22_l g7565__6161(.A0 (iwb_dat_i[30]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[30]), .Y (n_54));
  sky130_osu_sc_18T_ms__aoi22_l g7645__9315(.A0 (iwb_adr_i[25]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[25]), .Y (n_53));
  sky130_osu_sc_18T_ms__aoi22_l g7580__9945(.A0 (iwb_adr_i[1]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[1]), .Y (n_52));
  sky130_osu_sc_18T_ms__aoi22_l g7646__2883(.A0 (iwb_dat_i[9]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[9]), .Y (n_51));
  sky130_osu_sc_18T_ms__aoi22_l g7647__2346(.A0 (iwb_adr_i[24]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[24]), .Y (n_50));
  sky130_osu_sc_18T_ms__aoi22_l g7581__1666(.A0 (iwb_adr_i[0]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[0]), .Y (n_49));
  sky130_osu_sc_18T_ms__aoi22_l g7648__7410(.A0 (iwb_dat_i[8]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[8]), .Y (n_48));
  sky130_osu_sc_18T_ms__aoi22_l g7566__6417(.A0 (iwb_dat_i[15]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[15]), .Y (n_47));
  sky130_osu_sc_18T_ms__aoi22_l g7649__5477(.A0 (iwb_adr_i[23]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[23]), .Y (n_46));
  sky130_osu_sc_18T_ms__aoi22_l g7582__2398(.A0 (iwb_dat_i[31]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[31]), .Y (n_45));
  sky130_osu_sc_18T_ms__aoi22_l g7650__5107(.A0 (iwb_dat_i[7]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[7]), .Y (n_44));
  sky130_osu_sc_18T_ms__aoi22_l g7651__6260(.A0 (iwb_adr_i[22]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[22]), .Y (n_43));
  sky130_osu_sc_18T_ms__aoi22_l g7652__4319(.A0 (iwb_dat_i[6]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[6]), .Y (n_42));
  sky130_osu_sc_18T_ms__aoi22_l g7567__8428(.A0 (iwb_adr_i[29]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_adr_i[29]), .Y (n_41));
  sky130_osu_sc_18T_ms__aoi22_l g7584__5526(.A0 (iwb_dat_i[29]), .A1
       (n_108), .B0 (n_107), .B1 (dwb_dat_i[29]), .Y (n_40));
  sky130_osu_sc_18T_ms__inv_1 g7675(.A (n_39), .Y (n_181));
  sky130_osu_sc_18T_ms__nor2_1 g7676__6783(.A (n_30), .B (n_34), .Y
       (n_38));
  sky130_osu_sc_18T_ms__nand2_1 g7677__3680(.A (n_31), .B (n_35), .Y
       (n_39));
  sky130_osu_sc_18T_ms__and2_l g7682__1617(.A (ext_mem_cyc_o), .B
       (ext_mem_err_i), .Y (iwb_err_o));
  sky130_osu_sc_18T_ms__and2_1 g7678__2802(.A (ext_mem_cyc_o), .B
       (ext_mem_ack_i), .Y (n_37));
  sky130_osu_sc_18T_ms__aoi21_l g7681__1705(.A0 (iwb_adr_i[31]), .A1
       (n_32), .B0 (n_27), .Y (n_36));
  sky130_osu_sc_18T_ms__nor2_1 g7680__5122(.A (n_21), .B (n_28), .Y
       (n_35));
  sky130_osu_sc_18T_ms__nand2_1 g7679__8246(.A (n_10), .B (n_29), .Y
       (n_34));
  sky130_osu_sc_18T_ms__inv_l g7687(.A (n_107), .Y (n_33));
  sky130_osu_sc_18T_ms__oai21_l g7683__7098(.A0 (n_1), .A1 (n_193), .B0
       (n_190), .Y (n_108));
  sky130_osu_sc_18T_ms__nor2_1 g7690__6131(.A (iwb_cyc_i), .B (n_193),
       .Y (n_107));
  sky130_osu_sc_18T_ms__nand2_1 g7689__1881(.A (n_193), .B (n_190), .Y
       (ext_mem_cyc_o));
  sky130_osu_sc_18T_ms__inv_1 g7692(.A (n_193), .Y (n_32));
  sky130_osu_sc_18T_ms__nor2_1 g7684__5115(.A (n_25), .B (n_22), .Y
       (n_31));
  sky130_osu_sc_18T_ms__nand2_1 g7685__7482(.A (n_26), .B (n_20), .Y
       (n_30));
  sky130_osu_sc_18T_ms__nor2_1 g7686__4733(.A (n_9), .B (n_23), .Y
       (n_29));
  sky130_osu_sc_18T_ms__nand2_1 g7688__6161(.A (n_5), .B (n_24), .Y
       (n_28));
  sky130_osu_sc_18T_ms__inv_1 g7691(.A (n_190), .Y (n_27));
  sky130_osu_sc_18T_ms__nand2_1 g7696__9315(.A (iwb_adr_i[31]), .B
       (n_15), .Y (n_190));
  sky130_osu_sc_18T_ms__nand2_1 g7697__9945(.A (dwb_adr_i[31]), .B
       (n_17), .Y (n_193));
  sky130_osu_sc_18T_ms__nor2_l g7695__2883(.A (dwb_adr_i[17]), .B
       (n_16), .Y (n_26));
  sky130_osu_sc_18T_ms__or2_1 g7694__2346(.A (iwb_adr_i[16]), .B (n_4),
       .Y (n_25));
  sky130_osu_sc_18T_ms__nor2_1 g7693__1666(.A (iwb_adr_i[23]), .B
       (n_3), .Y (n_24));
  sky130_osu_sc_18T_ms__nand2_1 g7699__7410(.A (n_7), .B (n_14), .Y
       (n_23));
  sky130_osu_sc_18T_ms__nand2_1 g7702__6417(.A (n_6), .B (n_2), .Y
       (n_22));
  sky130_osu_sc_18T_ms__nand2_1 g7701__5477(.A (n_8), .B (n_13), .Y
       (n_21));
  sky130_osu_sc_18T_ms__and2_1 g7700__2398(.A (n_11), .B (n_12), .Y
       (n_20));
  sky130_osu_sc_18T_ms__nor2_1 g7698__5107(.A (iwb_adr_i[31]), .B
       (n_173), .Y (n_19));
  sky130_osu_sc_18T_ms__inv_1 g7711(.A (n_16), .Y (n_17));
  sky130_osu_sc_18T_ms__inv_1 g7712(.A (n_173), .Y (n_15));
  sky130_osu_sc_18T_ms__nor2_1 g7710__4319(.A (dwb_adr_i[24]), .B
       (dwb_adr_i[25]), .Y (n_14));
  sky130_osu_sc_18T_ms__nor2_1 g7704__8428(.A (iwb_adr_i[20]), .B
       (iwb_adr_i[27]), .Y (n_13));
  sky130_osu_sc_18T_ms__nor2_1 g7705__5526(.A (dwb_adr_i[27]), .B
       (dwb_adr_i[30]), .Y (n_12));
  sky130_osu_sc_18T_ms__nor2_1 g7706__6783(.A (dwb_adr_i[21]), .B
       (dwb_adr_i[22]), .Y (n_11));
  sky130_osu_sc_18T_ms__nor2_1 g7708__3680(.A (dwb_adr_i[23]), .B
       (dwb_adr_i[26]), .Y (n_10));
  sky130_osu_sc_18T_ms__or2_1 g7709__1617(.A (dwb_adr_i[16]), .B
       (dwb_adr_i[19]), .Y (n_9));
  sky130_osu_sc_18T_ms__nor2_1 g7703__2802(.A (iwb_adr_i[17]), .B
       (iwb_adr_i[28]), .Y (n_8));
  sky130_osu_sc_18T_ms__nor2_1 g7717__1705(.A (dwb_adr_i[18]), .B
       (dwb_adr_i[20]), .Y (n_7));
  sky130_osu_sc_18T_ms__nor2_1 g7714__5122(.A (iwb_adr_i[18]), .B
       (iwb_adr_i[26]), .Y (n_6));
  sky130_osu_sc_18T_ms__nor2_1 g7715__8246(.A (iwb_adr_i[21]), .B
       (iwb_adr_i[29]), .Y (n_5));
  sky130_osu_sc_18T_ms__or2_1 g7716__7098(.A (iwb_adr_i[19]), .B
       (iwb_adr_i[30]), .Y (n_4));
  sky130_osu_sc_18T_ms__or2_1 g7713__6131(.A (iwb_adr_i[15]), .B
       (iwb_adr_i[24]), .Y (n_3));
  sky130_osu_sc_18T_ms__nor2_1 g7718__1881(.A (iwb_adr_i[22]), .B
       (iwb_adr_i[25]), .Y (n_2));
  sky130_osu_sc_18T_ms__nand2_1 g7719__5115(.A (dwb_stb_i), .B
       (dwb_cyc_i), .Y (n_16));
  sky130_osu_sc_18T_ms__nand2_1 g7720__7482(.A (iwb_stb_i), .B
       (iwb_cyc_i), .Y (n_173));
  sky130_osu_sc_18T_ms__inv_1 g7722(.A (iwb_cyc_i), .Y (n_1));
  sky130_osu_sc_18T_ms__or2_1 g2(.A (n_447), .B (dwb_adr_i[28]), .Y
       (n_448));
  sky130_osu_sc_18T_ms__nand2_1 g3(.A (dwb_adr_i[29]), .B (n_38), .Y
       (n_447));
endmodule

